### ISSUE TITLE
update fails for jails without /usr/src

### ISSUE THREAD

**Issue by fliiiix** [iocage/iocage#1004]
`iocage update` fails for jails with out `/usr/src`

```
$ iocage --version
Version	1.2 RC
```

the output looks something like this:
```
usr/share/zoneinfo/zone.tab
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/ntp/libntp/xsbprintf.c: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/hostapd/README-MULTI-AP: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/ap/dpp_hostapd.c: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/ap/dpp_hostapd.h: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/ap/eth_p_oui.c: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/ap/eth_p_oui.h: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/ap/fils_hlp.c: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/ap/fils_hlp.h: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/ap/gas_query_ap.c: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/ap/gas_query_ap.h: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/ap/ieee802_11_he.c: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/common/dhcp.h: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/common/dpp.c: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/common/dpp.h: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/common/gas_server.c: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/common/gas_server.h: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/common/ocv.c: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/common/ocv.h: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/crypto/crypto_linux.c: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/crypto/crypto_nettle.c: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/crypto/crypto_wolfssl.c: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/crypto/fips_prf_wolfssl.c: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/crypto/sha384-kdf.c: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/crypto/sha384.c: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/crypto/sha512-kdf.c: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/crypto/sha512-prf.c: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/crypto/sha512.c: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/crypto/sha512.h: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/crypto/tls_wolfssl.c: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/drivers/driver_macsec_linux.c: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/drivers/driver_wired_common.c: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/drivers/driver_wired_common.h: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/utils/const_time.h: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/utils/crc32.c: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/utils/crc32.h: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/utils/json.c: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/utils/json.h: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/wpa_supplicant/README-DPP: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/wpa_supplicant/dpp_supplicant.c: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/wpa_supplicant/dpp_supplicant.h: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/wpa_supplicant/examples/dpp-qrcode.py: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/wpa_supplicant/op_classes.c: No such file or directory
install: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/wpa_supplicant/rrm.c: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/ntp/libntp/xsbprintf.c: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/hostapd/README-MULTI-AP: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/ap/dpp_hostapd.c: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/ap/dpp_hostapd.h: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/ap/eth_p_oui.c: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/ap/eth_p_oui.h: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/ap/fils_hlp.c: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/ap/fils_hlp.h: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/ap/gas_query_ap.c: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/ap/gas_query_ap.h: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/ap/ieee802_11_he.c: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/common/dhcp.h: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/common/dpp.c: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/common/dpp.h: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/common/gas_server.c: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/common/gas_server.h: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/common/ocv.c: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/common/ocv.h: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/crypto/crypto_linux.c: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/crypto/crypto_nettle.c: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/crypto/crypto_wolfssl.c: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/crypto/fips_prf_wolfssl.c: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/crypto/sha384-kdf.c: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/crypto/sha384.c: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/crypto/sha512-kdf.c: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/crypto/sha512-prf.c: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/crypto/sha512.c: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/crypto/sha512.h: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/crypto/tls_wolfssl.c: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/drivers/driver_macsec_linux.c: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/drivers/driver_wired_common.c: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/drivers/driver_wired_common.h: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/utils/const_time.h: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/utils/crc32.c: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/utils/crc32.h: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/utils/json.c: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/utils/json.h: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/wpa_supplicant/README-DPP: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/wpa_supplicant/dpp_supplicant.c: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/wpa_supplicant/dpp_supplicant.h: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/wpa_supplicant/examples/dpp-qrcode.py: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/wpa_supplicant/op_classes.c: No such file or directory
chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/wpa_supplicant/rrm.c: No such file or directory
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_fetch.py", line 941, in fetch_update
    _exec, callback=self.callback)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_common.py", line 893, in consume_and_log
    for output in filter(lambda o: any(v for v in o), exec_gen):
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_exec.py", line 260, in exec_jail
    list(stderr_queue)
iocage_lib.ioc_exceptions.CommandFailed: [b'chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/crypto/sha384.c: No such file or directory\n', b'chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/crypto/sha512-kdf.c: No such file or directory\n', b'chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/crypto/sha512-prf.c: No such file or directory\n', b'chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/crypto/sha512.c: No such file or directory\n', b'chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/crypto/sha512.h: No such file or directory\n', b'chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/crypto/tls_wolfssl.c: No such file or directory\n', b'chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/drivers/driver_macsec_linux.c: No such file or directory\n', b'chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/drivers/driver_wired_common.c: No such file or directory\n', b'chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/drivers/driver_wired_common.h: No such file or directory\n', b'chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/utils/const_time.h: No such file or directory\n', b'chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/utils/crc32.c: No such file or directory\n', b'chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/utils/crc32.h: No such file or directory\n', b'chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/utils/json.c: No such file or directory\n', b'chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/src/utils/json.h: No such file or directory\n', b'chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/wpa_supplicant/README-DPP: No such file or directory\n', b'chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/wpa_supplicant/dpp_supplicant.c: No such file or directory\n', b'chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/wpa_supplicant/dpp_supplicant.h: No such file or directory\n', b'chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/wpa_supplicant/examples/dpp-qrcode.py: No such file or directory\n', b'chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/wpa_supplicant/op_classes.c: No such file or directory\n', b'chflags: /zroot/iocage/jails/aegir/root//usr/src/contrib/wpa/wpa_supplicant/rrm.c: No such file or directory\n', b'', b'', b'', b'', b'', b'', b'', b'', b'', b'']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/update.py", line 45, in cli
    ioc.IOCage(jail=jail, skip_jails=skip_jails).update(pkgs=pkgs)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 2093, in update
    ).fetch_update(*params)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_fetch.py", line 949, in fetch_update
    silent=self.silent
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_common.py", line 100, in logit
    callback(content, exception)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_common.py", line 79, in callback
    message = '\n'.join(message)
TypeError: sequence item 0: expected str instance, int found
```
I guess the jail is still updated but the upgrade didn't run clean so before the next update I need to cleanup `rm -r /var/db/freebsd-update/*` myself

**Comment by sonicaj** [comment]
This is similar to #892

**Comment by sonicaj** [comment]
Please refer to the above issue @fliiiix for this. Thank you!

**Comment by fliiiix** [comment]
Overlooked that issue but you are right this seems like the same problem!
