### ISSUE TITLE
activate fails on hbsd

### ISSUE THREAD

**Issue by shivno** [iocage/iocage#102]
installed from git master, as it touches py-libzfs, a sidenote:
would it be needed to do `git pull --recurse-submodules` to get updated?

its hbsd 11-stable, the zpool in question was "vanilla", no iocage on there yet.
```
root@awary: # iocage activate hd204ui  
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/iocage/main.py", line 90, in main
    cli(obj=MODULES)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/activate.py", line 23, in activate_cmd
    ds.properties[prop].value = "yes"
  File "libzfs.pyx", line 1969, in libzfs.ZFSPropertyDict.__getitem__ (libzfs.c:44587)
KeyError: 'org.freebsd.ioc:active'
```

**Comment by skarekrow** [comment]
Interesting, will investigate this. As for your question, yes.

**Comment by shivno** [comment]
can confirm, works, thanks!

**Comment by skarekrow** [comment]
That's great to hear!
