### ISSUE TITLE
exec_poststart/exec_poststop -> unable to reset it to "empty" value -> causing start/stop problem

### ISSUE THREAD

**Issue by atomicbeecz** [iocage/iocage#1022]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [ ] Supply `iocage --version`
Version 1.1 RELEASE 2019/01

- [ ] Supply the commands used, along with any steps to recreate it.
Basically problem began, when i wanted to remove exec_post* values (which pointed to some shell script) to empty value. Seems that this is not possible.

iocage start/stop when exec_poststart/exec_poststop was defined, but you set it to empty value like:
iocage set exec_poststart= <jail_name>
iocage set exec_poststop= <jail_name>
Then you get below traceback

- [ ] Provide the output from the command you issued.
root@vaio_clone:~ # iocage start sftp
\* Starting sftp
  sftp is not using the devfs_ruleset of 4, not generating a ruleset for the jail, DHCP may not work.
  + Started OK
  + Using devfs_ruleset: 5
^R
  + Configuring VNET OK
  + Starting services OK
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/start.py", line 60, in cli
    ioc.IOCage(jail=jail, rc=rc).start(ignore_exception=ignore)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 1788, in start
    suppress_exception=ignore_exception
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_start.py", line 76, in __init__
    raise e
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_start.py", line 73, in __init__
    self.__start_jail__()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_start.py", line 576, in __start_jail__
    exec_poststart
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_common.py", line 825, in runscript
    elif os.access(script[0], os.X_OK):
IndexError: list index out of range

- [ ] Supply what you expected the result or output to be
iocage set exec_poststart= <jail_name>
iocage set exec_poststop= <jail_name>
Not sure how to "reset" the exec_post* values to empty/null values if they were used for some script before.
When i set "dummy script" in exec_post then all works as expected.
Example of dummy script:
/iocage/scripts/<jail_name>/test.sh
#!/bin/sh
exit 0

- [ ] Checked that the problem has not already been fixed on `master` if using
 a stable release.
not really as i have no idea how to check easily from the code

**Comment by sonicaj** [comment]
You can use the defaults in this case which are `/usr/bin/true`

**Comment by sonicaj** [comment]
I'm closing this, if you think it still doesn't work for you, please feel free to leave a comment here. Thank you
