### ISSUE TITLE
iocage stop results in UnicodeDecodeError

### ISSUE THREAD

**Issue by mateuszkwiatkowski** [iocage/iocage#1032]
Hello,
I'm playing with toy I made: it wraps some iocage commands:
https://gitlab.com/kwiat/jailer/tree/master

Steps to reproduce:
1) clone jailer repository to your home directory
2) configure nat (pf example: `nat on igb0 from 172.16.4.0/24 to any -> (igb0)`)
3) launch: `sudo ./jailer build`

It'll crash with UnicodeDecodeError exception:
```
[CUT]
WORKDIR /usr/home/webapp/
ADD . /usr/home/webapp/
RUN md5 Jailfile
MD5 (Jailfile) = 8ae3dbb5f32b56170692c303eaed05f6
[*] Removing temporary jail (jailer-build.98360)
* Stopping jailer-build_98360
  + Executing prestop OK
  + Stopping services OK
  + Removing devfs_ruleset: 8 OK
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/stop.py", line 68, in cli
    force=force, ignore_exception=ignore
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 1815, in stop
    force=force, suppress_exception=ignore_exception
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_stop.py", line 61, in __init__
    raise e
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_stop.py", line 58, in __init__
    self.__stop_jail__()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_stop.py", line 320, in __stop_jail__
    msg = f'  + Removing jail process FAILED:\n' \
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xde in position 45: invalid continuation byte
```

I get the same error when trying to remove the jail manually.
My env:
```
$ env
OLDPWD=/home/kwiat/iocage
PWD=/home/kwiat/jailer
PATH=/usr/local/opt/vim/bin/:/usr/local/opt/terraform@0.11/bin:/usr/local/opt/unzip/bin:/snap/bin:/home/kwiat/.gem/ruby/2.4.0/bin:/usr/local/opt/vim/bin/:/usr/local/opt/terraform@0.11/bin:/usr/local/opt/unzip/bin:/snap/bin:/home/kwiat/.gem/ruby/2.4.0/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/home/kwiat/bin:/home/kwiat/.rvm/bin:/home/kwiat/.rvm/bin
TERM=xterm-256color
TMUX_PANE=%5
TMUX=/tmp/tmux-1001/default,61412,1
_=/usr/bin/env
SSH_AGENT_PID=46763
SSH_AUTH_SOCK=/tmp/ssh-zWSz6HozinMc/agent.44640
EDITOR=vim
LANG=en_US.UTF-8
LSCOLORS=Gxfxcxdxbxegedabagacad
LESS=-R
PAGER=less
ZSH=/home/kwiat/.oh-my-zsh
SHLVL=2
USER=kwiat
LOGNAME=kwiat
HOME=/home/kwiat
MAIL=/var/mail/kwiat
BLOCKSIZE=K
SHELL=/usr/local/bin/zsh
SSH_CLIENT=192.168.0.180 36898 22
SSH_CONNECTION=192.168.0.180 38340 192.168.0.11 22
SSH_TTY=/dev/pts/0
```

Iocage version: latest master (Version 1.2 RC)

**Comment by mateuszkwiatkowski** [comment]
I couldn't reproduce this on other hosts so I assume that this is local problem.
