### ISSUE TITLE
libzfs.ZFSException: Dataset with path  not found

### ISSUE THREAD

**Issue by cjemorton** [iocage/iocage#1045]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`

> Version 1.1 RELEASE 2019/01

- [x] Supply the commands used, along with any steps to recreate it.

> iocage list

- [x] Provide the output from the command you issued.

> Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/list.py", line 58, in cli
    iocage = ioc.IOCage(skip_jails=True)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 115, in __init__
    self.pool = PoolAndDataset().get_pool()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 55, in __init__
    self.pool = ioc_json.IOCJson().json_get_value("pool")
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 1151, in __init__
    super().__init__(location, checking_datasets, silent, callback)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 446, in __init__
    self.default_config = self.check_default_config()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 1127, in check_default_config
    defaults=True)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 616, in json_write
    if template else None
  File "libzfs.pyx", line 664, in libzfs.ZFS.get_dataset_by_path
libzfs.ZFSException: Dataset with path  not found

- [x] Supply what you expected the result or output to be

- I expected to get a list of jails.

- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.
- Looked around for others with this issue and haven't been able to find anything. 
- I might just be missing something. 
- My jails were up and running and then one of them suddenly became unresponsive so I went in to restart it, and this error came up. 
- I did a pkg update && pkg upgrade recently. That might have broken something. 
- I've restarted the whole server several times and still nothing.
- when I perform a `service iocage stop` or `service iocage start` i get the same error.
 `service iocage stop`
> * [I|O|C] stopping jails...
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/stop.py", line 62, in cli
    ioc.IOCage(rc=rc, silent=True).stop(
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 115, in __init__
    self.pool = PoolAndDataset().get_pool()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 55, in __init__
    self.pool = ioc_json.IOCJson().json_get_value("pool")
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 1151, in __init__
    super().__init__(location, checking_datasets, silent, callback)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 446, in __init__
    self.default_config = self.check_default_config()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 1127, in check_default_config
    defaults=True)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 616, in json_write
    if template else None
  File "libzfs.pyx", line 664, in libzfs.ZFS.get_dataset_by_path
libzfs.ZFSException: Dataset with path  not found

`service iocage start`

> * [I|O|C] starting jails...
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/start.py", line 57, in cli
    ioc.IOCage(rc=rc, silent=True).start(ignore_exception=ignore)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 115, in __init__
    self.pool = PoolAndDataset().get_pool()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 55, in __init__
    self.pool = ioc_json.IOCJson().json_get_value("pool")
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 1151, in __init__
    super().__init__(location, checking_datasets, silent, callback)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 446, in __init__
    self.default_config = self.check_default_config()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 1127, in check_default_config
    defaults=True)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 616, in json_write
    if template else None
  File "libzfs.pyx", line 664, in libzfs.ZFS.get_dataset_by_path
libzfs.ZFSException: Dataset with path  not found

- I'm probably overlooking something simple. Any help would be much appreciated.

**Comment by cjemorton** [comment]
Just a quick update.
- The version I was running above was from ports.
- I pulled down the version from github `Version 1.2 RC` and installed it, now it is working.
- Is the port just not up to date?
- I prefer to keep all my packages managed under the ports tree, makes updating easier. However this will work in my situation for the time being.
- If anyone has anything to add to this please do so.
