### ISSUE TITLE
iocage upgrade fails with DHCP set

### ISSUE THREAD

**Issue by internationils** [iocage/iocage#1052]
I encountered this bug when updating a 9.3 jail to 11.2. The workaround was to set a fixed IP address (instead of DHCP) and that made it work.

$ iocage --version
Version FreeNAS 11.2-U6
$ sudo iocage upgrade backup_jail -r 11.2-RELEASE
ifconfig: illegal option -- f
usage: ifconfig [-L] [-C] [-g groupname] interface address_family [address [dest_address]]
                [parameters]
       ifconfig interface create
       ifconfig -a [-L] [-C] [-g groupname] [-d] [-m] [-u] [-v] [address_family]
       ifconfig -l [-d] [-u] [address_family]
       ifconfig [-L] [-C] [-g groupname] [-d] [-m] [-u] [-v]
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/upgrade.py", line 39, in cli
    ioc.IOCage(jail=jail, skip_jails=True).upgrade(release)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 1819, in upgrade
    ioc_start.IOCStart(uuid, path, conf, silent=True)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_start.py", line 67, in __init__
    self.__start_jail__()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_start.py", line 467, in __start_jail__
    "message": "  + Acquiring DHCP address: FAILED,"
UnboundLocalError: local variable 'addr' referenced before assignment

**Comment by internationils** [comment]
@araujobsd FYI

**Comment by internationils** [comment]
accidental close, wrong button... PEBCAK ; )

**Comment by araujobsd** [comment]
@sonicaj are you aware of it?

**Comment by sonicaj** [comment]
@internationils apart from the traceback, the issue is different. The jail in question failed to acquire dhcp address. It could be for a variety of reasons. I see you are using this on FreeNAS. Can you perhaps make a ticket on Jira and we can track this there ? And please reproduce this issue and attach a debug so i can have more context. Thank you

**Comment by internationils** [comment]
How can I make a debug? I have destroyed the old jails, so I can't really reproduce it easily.

To reproduce, take a warden jail (9.x or 10.x to 11.2 should work), migrate it to iocage with `migrate_warden.py -v -j <WARDEN> -p <POOL>`
then edit it before doing the upgrade to set DHCP and Berkeley Packet Filter, and you should see the error immediately. I assume 10.x jails updating would have the same issue, but I only saw it with the 9.3 one as I only set the DHCP later (after doing the upgrade) in the others.
