### ISSUE TITLE
Fetch old releases from ftp-archive.FreeBSD.org

### ISSUE THREAD

**Issue by asomers** [iocage/iocage#1059]
Jails are an awesome way to explore old FreeBSD releases, and iocage is the easiest way to create a jail.  But the current implementation fetches releases from https://download.freebsd.org, which only serves currently supported releases.  As an enhancement, it would be awesome if iocage could fetch historic releases from ftp-archive.FreeBSD.org .  This recently came up at work, when I needed to install a 9.3 jail.
```
> iocage --version
Version	1.2 RC
> sudo iocage fetch -r 9.3-RELEASE
Password:
9.3-RELEASE was not found!
```

**Comment by jsegaert** [comment]
iocage allows you to specify an alternate download source.  For your use case, try:

```
➜  iocage git:(master) sudo iocage fetch --root-dir /pub/FreeBSD-Archive/old-releases/amd64/ --server ftp-archive.freebsd.org
[0] 5.1-RELEASE
[1] 5.2-RELEASE
[2] 5.3-RELEASE (EOL)
[3] 5.4-RELEASE (EOL)
[4] 5.5-RELEASE (EOL)
[5] 6.0-RELEASE (EOL)
[6] 6.1-RELEASE (EOL)
[7] 6.2-RELEASE (EOL)
[8] 6.3-RELEASE (EOL)
[9] 6.4-RELEASE (EOL)
[10] 7.0-RELEASE (EOL)
[11] 7.1-RELEASE (EOL)
[12] 7.2-RELEASE (EOL)
[13] 7.3-RELEASE (EOL)
[14] 7.4-RELEASE (EOL)
[15] 8.0-RELEASE (EOL)
[16] 8.1-RELEASE (EOL)
[17] 8.2-RELEASE (EOL)
[18] 8.3-RELEASE (EOL)
[19] 8.4-RELEASE (EOL)
[20] 9.0-RELEASE (EOL)
[21] 9.1-RELEASE (EOL)
[22] 9.2-RELEASE (EOL)
[23] 9.3-RELEASE (EOL)
[24] 10.0-RELEASE (EOL)
[25] 10.1-RELEASE (EOL)
[26] 10.2-RELEASE (EOL)
[27] 10.3-RELEASE (EOL)
[28] 10.4-RELEASE (EOL)
[29] 11.0-RELEASE (EOL)
[30] 11.1-RELEASE (EOL)
[31] 11.2-RELEASE
[32] 12.0-RELEASE

Type the number of the desired RELEASE
Press [Enter] to fetch the default selection: (12.0-RELEASE)
Type EXIT to quit: 
```
By default it will attempt to update to the latest patch level, it you do not want this, consider adding the `--noupdate` flag

**Comment by asomers** [comment]
Awesome!  I didn't know about that option.  Still, iocage runs into a different problem when trying to fetch releases older than 9.0:

```
sudo iocage fetch --root-dir /pub/FreeBSD-Archive/old-releases/amd64/ --server ftp-archive.freebsd.org --release 8.4-RELEASE
Fetching: 8.4-RELEASE

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_fetch.py", line 536, in __fetch_check__
    with open("MANIFEST", "r") as _manifest:
FileNotFoundError: [Errno 2] No such file or directory: 'MANIFEST'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/fetch.py", line 129, in cli
    ioc.IOCage().fetch(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 1056, in fetch
    **kwargs).fetch_release()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_fetch.py", line 207, in fetch_release
    rel = self.fetch_http_release(eol, _list=_list)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_fetch.py", line 449, in fetch_http_release
    missing_files = self.__fetch_check__(self.files)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_fetch.py", line 554, in __fetch_check__
    self.fetch_download(['MANIFEST'], missing=True)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_fetch.py", line 698, in fetch_download
    r.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://ftp-archive.freebsd.org//pub/FreeBSD-Archive/old-releases/amd64//8.4-RELEASE/MANIFEST
```
It seems that 9.0-RELEASE changed the release format.  It would be nice if iocage could install older releases, too, but I understand if that would be too much work.  If I get ambitious, I may submit a patch that specializes root_dir and server for old FreeBSD releases in a similar way to how they're specialized for Hardened BSD.

**Comment by sonicaj** [comment]
That would be awesome ; )
> 
> If I get ambitious, I may submit a patch that specializes root_dir and server for old FreeBSD releases in a similar way to how they're specialized for Hardened BSD.
