### ISSUE TITLE
fetch without setting -r fails on hbsd

### ISSUE THREAD

**Issue by shivno** [iocage/iocage#107]
master from now

```
root@awary:~ # iocage fetch
Creating hd204ui/iocage
Creating hd204ui/iocage/download
Creating hd204ui/iocage/images
Creating hd204ui/iocage/jails
Creating hd204ui/iocage/log
Creating hd204ui/iocage/releases
Creating hd204ui/iocage/templates
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/iocage/main.py", line 90, in main
    cli(obj=MODULES)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 105, in fetch_cmd
    eol=eol, files=files).fetch_release()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 141, in fetch_release
    self.fetch_http_release(eol, _list=_list)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 235, in fetch_http_release
    rel = rel.strip("href=").strip("/").split(">")
TypeError: a bytes-like object is required, not 'str'
```
when setting -r 11-STABLE, it works

**Comment by skarekrow** [comment]
Alright, should be nailed. As always, test and report back as well if you can 👍

**Comment by shivno** [comment]
works!

**Comment by skarekrow** [comment]
Yay!
