### ISSUE TITLE
iocage exec exception

### ISSUE THREAD

**Issue by joachimmathes** [iocage/iocage#112]
When I run `iocage exec JAIL 'env ASSUME_ALWAYS_YES=YES pkg install sudo'` on a
new jail an exception is thrown:

```
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/iocage/main.py", line 85, in main
    cli(obj=MODULES)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 726, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 701, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1070, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 899, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/exec.py", line 60, in exec_cmd
    err = indent_lines(msg)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_common.py", line 175, in indent_lines
    indented = message.replace("\n", "\n       ").rstrip()
TypeError: a bytes-like object is required, not 'str'
```

But sudo is installed anyway. A second run confirms:

```
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
Checking integrity... done (0 conflicting)
The most recent version of packages are already installed
```

Tried `iocage pkg JAIL install sudo`, but it did no work.

`iocage --version:` Version 0.9.7 2017/03/08 (commit hash: 'a3ec3c55feda1a0b3b3472ae08c9546e9ae8e635')

**Comment by skarekrow** [comment]
Yeah that was an annoyingly small bug where I was trying to be clever. I am no longer attempting that :D It is nuked. Should all work now 👍

**Comment by joachimmathes** [comment]
Cool! Will try it on Monday. Thank you!

**Comment by joachimmathes** [comment]
It works!

Sorry for my late reply.

**Comment by skarekrow** [comment]
Hahah no worries! Thanks for getting back.
