### ISSUE TITLE
devfs_ruleset 1000 doesn't exist

### ISSUE THREAD

**Issue by dlangille** [iocage/iocage#1130]
$ pkg info -x iocage
py36-iocage-1.2_3

on FreeBSD 12.1

I rebooted the server after updating the host and jails. When completed, no jails were running. I found this in `/var/log/iocage.log`:

```
....
2020/01/29 19:31:19 (INFO) src component not installed, skipped
2020/01/29 19:31:21 (INFO) Installing updates... done.
2020/01/29 19:31:22 (INFO) Updated jail successfully.
2020/01/29 19:31:22 (INFO) 
pkg01 updates have been applied successfully.
```

Let's try this manually:

```
[dan@r720-01:~] $ sudo service iocage start
* [I|O|C] starting jails... 
devfs_ruleset 1000 doesn't exist
```

OK, who has that?

```
$ grep 1000 */config.json
mqtt01/config.json:    "devfs_ruleset": "1000",

```

Let's turn it off:

```
[dan@r720-01:/iocage/jails] $ sudo iocage set boot=off mqtt01
boot: 1 -> 0

```

And try again:

```
[dan@r720-01:/iocage/jails] $ sudo service iocage start
* [I|O|C] starting jails... 
devfs_ruleset 1000 doesn't exist

```

What?

**Comment by dlangille** [comment]
Ahah!

```
[dan@r720-01:/iocage/jails] $ sudo pkg check -s py36-iocage
Checking py36-iocage:   0%
py36-iocage-1.2_3: checksum mismatch for /usr/local/lib/python3.6/site-packages/iocage_lib/__pycache__/ioc_common.cpython-36.pyc
py36-iocage-1.2_3: checksum mismatch for /usr/local/lib/python3.6/site-packages/iocage_lib/ioc_common.py
Checking py36-iocage: 100%
[dan@r720-01:/iocage/jails] $ 

```

I bet this is left over from helping with similar issues.

**Comment by dlangille** [comment]
Ironically, this host also runs the poudriere jail, so I cannot install from there.

Instead, get it from another server:

```
[dan@slocum:/var/cache/pkg] $ scp py36-iocage-1.2_3-3ac1c4457c.txz r720-01:
py36-iocage-1.2_3-3ac1c4457c.txz                                                                                                                                                                        100%  235KB  41.1MB/s   00:00    
[dan@slocum:/var/cache/pkg] $ 
```

To see what might be different, let's delete the `pkg` then inspect:

```
[dan@r720-01:/iocage/jails] $ sudo pkg delete py36-iocage
Checking integrity... done (0 conflicting)
Deinstallation has been requested for the following 1 packages (of 0 packages in the universe):

Installed packages to be REMOVED:
	py36-iocage-1.2_3

Number of packages to be removed: 1

The operation will free 1 MiB.

Proceed with deinstalling packages? [y/N]: y
[1/1] Deinstalling py36-iocage-1.2_3...
[1/1] Deleting files for py36-iocage-1.2_3: 100%
[dan@r720-01:/iocage/jails] $ ls -l /usr/local/lib/python3.6/site-packages/iocage_lib
total 33
-rw-r--r--  1 root  wheel  32064 Sep 26 07:23 ioc_common.py.orig
-rw-r--r--  1 root  wheel  32064 Sep 26 07:23 ioc_common.py.original
[dan@r720-01:/iocage/jails] $ cd /usr/local/lib/python3.6/site-packages/iocage_lib
[dan@r720-01:/usr/local/lib/python3.6/site-packages/iocage_lib] $ diff -ruN ioc_common.py.original ioc_common.py.orig
[dan@r720-01:/usr/local/lib/python3.6/site-packages/iocage_lib] $ 
```

Oh, nothing to see here, please move along.

**Comment by dlangille** [comment]
Let's install:

```
$ sudo pkg install ~/py36-iocage-1.2_3-3ac1c4457c.txz 
Updating local repository catalogue...
^C
```

That won't work. The pkg server is in a jail on this host.

```
[dan@r720-01:~] $ sudo pkg install --no-repo-update -f ./py36-iocage-1.2_3-3ac1c4457c.txz
pkg: Repository local cannot be opened. 'pkg update' required
Checking integrity... done (0 conflicting)
The following 1 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
	py36-iocage: 1.2_3

Number of packages to be installed: 1

The process will require 1 MiB more space.

Proceed with this action? [y/N]: y
[1/1] Installing py36-iocage-1.2_3...
Extracting py36-iocage-1.2_3: 100%
[dan@r720-01:~] $ ': sudo iocage start pkg01
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 6, in <module>
    from iocage_cli import cli
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/__init__.py", line 36, in <module>
    import click
ModuleNotFoundError: No module named 'click'
[dan@r720-01:~] $ pkg info -x click
py36-click-7.0
[dan@r720-01:~] $ 

```

**Comment by dlangille** [comment]
I think I am anticipating a series of installs:

```
[dan@r720-01:/var/cache/pkg] $ sudo pkg install --no-repo-update -f ./py36-click-7.0.txz
pkg: Repository local cannot be opened. 'pkg update' required
Checking integrity... done (0 conflicting)
The following 1 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
	py36-click: 7.0

Number of packages to be installed: 1

Proceed with this action? [y/N]: y
[1/1] Installing py36-click-7.0...
Extracting py36-click-7.0: 100%
[dan@r720-01:/var/cache/pkg] $ sudiocage list
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 6, in <module>
    from iocage_cli import cli
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/__init__.py", line 37, in <module>
    import coloredlogs
ModuleNotFoundError: No module named 'coloredlogs'
[dan@r720-01:/var/cache/pkg] $ 



```

**Comment by dlangille** [comment]
After a bunch of installs:

```
  565  sudo pkg install --no-repo-update -f ./py36-click-7.0.txz
  569  sudo pkg install --no-repo-update -f ./py36-coloredlogs-10.0_1.txz
  572  sudo pkg install --no-repo-update -f ./py36-humanfriendly-4.16.1_1.txz
  575  sudo pkg install --no-repo-update -y -f ./py36-requests-2.22.0.txz
  578  sudo pkg install --no-repo-update -y -f ./py36-urllib3-1.22,1.txz
  581  sudo pkg install --no-repo-update -y -f ./py36-chardet-3.0.4_1.txz
  585  sudo pkg install --no-repo-update -y -f ./py36-certifi-2019.9.11.txz
  588  sudo pkg install --no-repo-update -y -f ./py36-idna-2.8.txz
  591  sudo pkg install --no-repo-update -y -f ./py36-netifaces-0.10.9.txz
  594  sudo pkg install --no-repo-update -y -f py36-libzfs-1.0.20181220.txz
  597  sudo pkg install --no-repo-update -y -f py36-texttable-1.6.2.txz
  602  sudo pkg install --no-repo-update -y -f py36-dnspython-1.16.0.txz

```

We hit this known issue:

```
[dan@r720-01:/var/cache/pkg] $ sudiocage list
Usage: iocage [OPTIONS] COMMAND [ARGS]...
Try "iocage --help" for help.

Error: No such command "list".

```

**Comment by dlangille** [comment]
I changed to using the FreeBSD public repo.  I installed py37-iocage-1.2_4

```
[dan@r720-01:/usr/local/etc/pkg/repos] $ sudo service iocage start
* [I|O|C] starting jails... 
[dan@r720-01:/usr/local/etc/pkg/repos] $ jls
   JID  IP Address      Hostname                      Path
[dan@r720-01:/usr/local/etc/pkg/repos] $
```

**Comment by dlangille** [comment]
```
$ sudo iocage start pkg01
* Starting pkg01
pkg01 devfs_ruleset 1004 does not exist! - Not starting jail

```

**Comment by dlangille** [comment]
```
 $ sudo iocage set devfs_ruleset=4 pkg01
devfs_ruleset: 1004 -> 4


[dan@r720-01:/usr/local/etc/pkg/repos] $ sudo iocage start pkg01
* Starting pkg01
  + Started OK
  + Using devfs_ruleset: 1000 (iocage generated default)
  + Configuring VNET OK
  + Using IP options: vnet
  + Starting services OK
  + Executing poststart OK

[dan@r720-01:/usr/local/etc/pkg/repos] $ jls
   JID  IP Address      Hostname                      Path
     1                  pkg01.int.unixathome.org      /iocage/jails/pkg01/root
[dan@r720-01:/usr/local/etc/pkg/repos] $ 

```

**Comment by dlangille** [comment]
After running `sudo iocage set devfs_ruleset=4` for each jail, I was able to return the host to service.

**Comment by skarekrow** [comment]
Did you originally set those to 1000 on your own? If so, this is pretty expected behavior. But things changed on this side and i haven't been following super close, so @sonicaj would know best.

**Comment by dlangille** [comment]
> Did you originally set those to 1000 on your own?

see #952 where this was done

> If so, this is pretty expected behavior. But things changed on this side and i haven't been following super close, so @sonicaj would know best.

Hmmm. I hope others don't get caught by this. Do folks need to know about this `devfs_rules` numbering issue?

**Comment by sonicaj** [comment]
@dlangille kindly elaborate what the issue is. It seems you had the wrong number selected which iocage was unable to find which means that an exception is expected behaviour.

**Comment by dlangille** [comment]
This was a working host.  I rebooted and encountered this issue.

It took some time & effort to recover.  I have no idea why this happened but I suspect it is related to #952

**Comment by ehartsock** [comment]
I also just hit this. Updated host to FreeBSD 12.1-RELEASE-p2 and then updated two jails via `iocage update jailname` . Trying to start them results in:

```
root@core:~ # iocage start unifi
No default gateway found for ipv6.
* Starting unifi
unifi devfs_ruleset 1001 does not exist! - Not starting jail

root@core:~ # iocage start homebridge
No default gateway found for ipv6.
* Starting homebridge
homebridge devfs_ruleset 1000 does not exist! - Not starting jail
```

I do have vnet enabled for both but no special configurations or modifications.

**Comment by sonicaj** [comment]
@ehartsock please don’t correct the jails configuration and kindly email me a debug of iocage generated via iocage debug command. My email is “waqar at the rate of ixsystems.com”. I would require this information to debug the issue correctly as I am not able to reproduce locally. 

Looking forward to hearing from you, Thank you

**Comment by dlangille** [comment]
@ehartsock How is your jail now? I ask in case you resolved this issue via email and to get the solution into this issue for other users.

**Comment by sonicaj** [comment]
@dlangille the issue was that iocage had a different bug for quite a while which came to front because of recent devfs_ruleset changes. What happened was that iocage completely updated the configuration for each jail which was updated instead of just updating the release property - this caused 2 issues, users expecting a slimmer config would get the full config and the second was that some properties like devfs_ruleset are different when the jail is running. So that different property got saved as well resulting in this issue.

Thank you @ehartsock and @dlangille for your help

**Comment by dlangille** [comment]
@sonicaj I see.

If someone is running an older version of icoage and gets into this situation, how do they fix it?

**Comment by sonicaj** [comment]
Manually setting the `devfs_ruleset` property is the only solution for this - it's possible it might break for some other prop as well - not sure, so that would have to be handled similarly as well

**Comment by ehartsock** [comment]
@dlangille Fixed by setting `devfs_ruleset=4` for each jail. Command pulled from your comment:

https://github.com/iocage/iocage/issues/1130#issuecomment-579968356

**Comment by grembo** [comment]
@skarekrow @sonicaj There is a problem with how the devfs_ruleset property is handled in general, I'll open an issue about that soon (before this would happen as well, but silently ignored - which wasn't a problem for devfs_ruleset 4, but for custom ones it was).
