### ISSUE TITLE
iocage-1.2 - get devfs_ruleset fails for some jails but not all

### ISSUE THREAD

**Issue by dlangille** [iocage/iocage#1155]
I'm using iocage-1.2 on FreeBSD. Some jails don't let me extract devfs_ruleset while the jail is running.

```
[dan@r720-01:/iocage/jails] $ sudo iocage set devfs_ruleset=4 pg02
devfs_ruleset: 4 -> 4
[dan@r720-01:/iocage/jails] $ sudo iocage get devfs_ruleset pg02
4
[dan@r720-01:/iocage/jails] $ sudo iocage start pg02
* Starting pg02_int_unixathome_org
  + Started OK
  + Using devfs_ruleset: 1006 (iocage generated default)
  + Using IP options: ip4.addr=ix0|10.55.0.32 ip4.saddrsel=1 ip4=new ip6.saddrsel=1 ip6=new
  + Starting services OK
  + Executing poststart OK
[dan@r720-01:/iocage/jails] $ sudo iocage get devfs_ruleset pg02
jls: jail "ioc-pg02.int.unixathome.org" not found
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/iocage_cli/get.py", line 128, in cli
    p = ioc.IOCage(jail=jail, skip_jails=True).get(prop)
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/iocage.py", line 1295, in get
    return ioc_json.IOCJson(path).json_get_value(prop)
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_json.py", line 1944, in json_get_value
    'devfs_ruleset'
  File "/usr/local/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/local/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['jls', '-j', 'ioc-pg02.int.unixathome.org', 'devfs_ruleset']' returned non-zero exit status 1.
[dan@r720-01:/iocage/jails] $ 
```

This jail is fine:

```
[dan@r720-01:/iocage/jails] $ sudo iocage get devfs_ruleset mqtt01
1001
```

I see no differences:

```
[dan@r720-01:/iocage/jails] $ grep devfs_ruleset pg02.int.unixathome.org/config.json 
    "devfs_ruleset": "4",
    "min_dyn_devfs_ruleset": "1000",
[dan@r720-01:/iocage/jails] $ gregrep devfs_ruleset mqtt01/config.json 
    "devfs_ruleset": "4",
    "min_dyn_devfs_ruleset": "1000",
[dan@r720-01:/iocage/jails] $ 
```

**Comment by dlangille** [comment]
Perhaps related to #1138?
