### ISSUE TITLE
iocage create throws exception

### ISSUE THREAD

**Issue by joefrancia** [iocage/iocage#120]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x ] Supply `iocage --version`
Version	0.9.7 2017/03/08

- [ x] Supply the commands used, along with any steps to recreate it.
(From here: https://iocage.readthedocs.io/en/latest/basic-use.html)
iocage create -c tag=jira ip4_addr="bce0|10.10.100.27/24"

- [ x] Provide the output from the command you issues.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/create.py", line 22, in validate_count
    return int(count)
ValueError: invalid literal for int() with base 10: 'tag=jira'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/iocage/main.py", line 90, in main
    cli(obj=MODULES)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1064, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 621, in make_context
    self.parse_args(ctx, args)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 880, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1404, in handle_parse_result
    self.callback, ctx, self, value)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 78, in invoke_param_callback
    return callback(ctx, param, value)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/create.py", line 24, in validate_count
    return int(value)
ValueError: invalid literal for int() with base 10: 'tag=jira'

- [x ] Supply what you expected the result or output to be
Create a jail with a tag 'jira'

- [x ] Checked that the problem has not already been fixed on `master` if using
 a stable release.
Checked, found nothing.

**Comment by skarekrow** [comment]
That is because you used `-c` which is for count. Clonejails are the default now so you don't need to supply that.

**Comment by joefrancia** [comment]
Fair enough. I guess the docs are just a bit behind,

**Comment by skarekrow** [comment]
Indeed they are! But this is still a valid bug regardless, so thanks :)

Should be fixed now 👍
