### ISSUE TITLE
`iocage list -h` stopped working in TrueNAS-12.0-RC

### ISSUE THREAD

**Issue by wfrank** [iocage/iocage#1213]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`

Version 1.2

- [x] Supply the commands used, along with any steps to recreate it.

iocage list -h

- [x] Provide the output from the command you issued.

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/iocage_cli/list.py", line 96, in cli
    "message": "\t".join(item)
TypeError: sequence item 0: expected str instance, int found

- [x] Supply what you expected the result or output to be

List of jails for scripting

- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

Seems to be caused by https://github.com/iocage/iocage/commit/170047965e7e5a892bb55cf290c0a0d6b892c98a. The type of jid changed from str to int.

**Comment by william-gr** [comment]
Please create a ticket on TrueNAS tracker

**Comment by GunbleR** [comment]
https://github.com/freenas/iocage/pull/330

**Comment by untouchable** [comment]
I’m sorry to report this *exact same error*  presents itself on FreeBSD 12.2-RELEASE-p6 which makes ansible automation scripts unusable.
