### ISSUE TITLE
When Plugin has a () in description, traceback occurs

### ISSUE THREAD

**Issue by kmoore134** [iocage/iocage#124]
(Note: I've since removed the () from the description and confirmed that fixes the issue)

# iocage fetch --plugins ip4_addr="igb0|192.168.0.91/24"
[0] BitTorrent Sync - Resilient, fast and scalable file sync software for enterprises and individuals. (btsync)
[1] CouchPotato - CouchPotato (CP) is an automatic NZB and torrent downloader. (couchpotato)
[2] Jenkins - Jenkins CI (jenkins)
[3] Plex Media Server - The Plex media server system (plexmediaserver)
[4] Quasselcore - Quassel Core is a daemon/headless IRC client, part of Quassel, that supports 24/7 connectivity. Quassel Client can be attached to it to. (quasselcore)
[5] SubSonic - Open-source web-based media streamer and jukebox. (subsonic)
[6] Syncthing - Personal cloud sync (syncthing)

Which plugin do you want to create? (EXIT) 1
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/iocage/main.py", line 85, in main
    cli(obj=MODULES)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 113, in fetch_cmd
    IOCFetch(release=None).fetch_plugin_index(props)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 980, in fetch_plugin_index
    props, 0)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 743, in fetch_plugin
    with open(_json, "r") as j:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/iocage/.plugin_index/CP is an automatic NZB and torrent downloader. .json'

**Comment by skarekrow** [comment]
While a bug I'd mention that (CP) is odd looking. None of the other plugins do that. Anything in the () is for iocage to parse and name the jail that. So I'd avoid doing that in the description.
