### ISSUE TITLE
after removing post_start or post_stop parameter : IndexError: list index out of range during a stop or start.

### ISSUE THREAD

**Issue by Oxyaxion** [iocage/iocage#1240]
Hello 

- iocage 1.2

Maybe I didn't understood how to clean this parameter but I have a strange problem.

Step to reproduce :

1. Setting a exec_poststop or start in a jail 

`# iocage set exec_poststop='/zroot/iocage/scripts/myjail_umount.sh' myjail`

2. Start and stop the jail without any issue

3. Remove the previous parameter

`# iocage set exec_poststop="" myjail`

4. Retry to stop and start the jail 

Output : 

```
 # iocage start myjail
* Starting myjail
  + Started OK
  + Using devfs_ruleset: 1003 (iocage generated default)
  + Using IP options: ip4.addr=lo1|172.16.0.3 ip4.saddrsel=1 ip4=new ip6.saddrsel=1 ip6=new
  + Starting services OK
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/iocage_cli/start.py", line 60, in cli
    ioc.IOCage(jail=jail, rc=rc).start(ignore_exception=ignore)
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/iocage.py", line 1907, in start
    used_ports=used_ports,
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_start.py", line 87, in __init__
    raise e
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_start.py", line 84, in __init__
    self.__start_jail__()
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_start.py", line 803, in __start_jail__
    exec_poststart
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_common.py", line 836, in runscript
    elif os.access(script[0], os.X_OK):
IndexError: list index out of range

```

Same problem with the exec_poststop or exec_poststart probably same with exec_prestart and stop but I didn't try.

**Comment by squidbreaker** [comment]
I've had the same problem with my iocage jail.
You should be able to find another entry for poststop/poststart in the config file for your jail.
See: /zroot/iocage/<jailname>/config
Delete the exec_poststop/exec_poststart/exec_preststart row and the error should no longer happen :)
