### ISSUE TITLE
creating jail with '-r latest' errors out

### ISSUE THREAD

**Issue by FrostKiwi** [iocage/iocage#1244]
iocage version: 1.2
FreeBSD Version: 12.2-RELEASE-p2

Always created my jails with:
```sudo iocage create -n jail_cloud -r latest vnet=off jail_zfs=on boot=on allow_raw_sockets=1 ip4_addr="lo14|10.0.0.6/32"```
Suddenly this errors out with "could not convert string to float: '12.2</p'"
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/iocage_cli/create.py", line 167, in cli
    ioc_common.check_release_newer(release)
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_common.py", line 722, in check_release_newer
    r_float = float(str(release).rsplit("-")[0])
ValueError: could not convert string to float: '12.2</p'
​
During handling of the above exception, another exception occurred:
​
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/iocage_cli/create.py", line 173, in cli
    _release = ioc_common.get_jail_freebsd_version(path, release)
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_common.py", line 928, in get_jail_freebsd_version
    f'{path}/bin/freebsd-version', mode='r', encoding='utf-8'
FileNotFoundError: [Errno 2] No such file or directory: '/iocage/releases/12.2</p-RELEASE/root/bin/freebsd-version'
```
Specifying the version with -r fixes the problem: "-r 12.2-RELEASE"

**Comment by gamecreature** [comment]
Same here:

```
No such file or directory: '/zroot/iocage/releases/12.2</p-RELEASE/root/bin/freebsd-version'
```

**Comment by apprell** [comment]
Fix `/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_common.py`:

```
<                 rel = rel[1].strip('</td').strip("releng/")
---
>                 rel = rel[1].strip('</td').strip("releng/").strip("</p").strip("</cod")
```

It's a pity that the project looks dead

**Comment by FrostKiwi** [comment]
> 
> 
> Fix `/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_common.py`:
> 
> ```
> <                 rel = rel[1].strip('</td').strip("releng/")
> ---
> >                 rel = rel[1].strip('</td').strip("releng/").strip("</p").strip("</cod")
> ```
> 
> It's a pity that the project looks dead

Ohh, many thanks!

As long as I keep using it daily, it's not dead to me :P

**Comment by dko1905** [comment]
FreeBSD version: 13.0-RELEASE
iocage version: 1.2

I'm having the same issue, I would love to have this fix incorporated into the master branch.
