### ISSUE TITLE
Missing dependency on git in port?

### ISSUE THREAD

**Issue by telser** [iocage/iocage#125]
After following the README for installing via ports I get an error about not finding git trying to list the plugins. To be clear git is not installed on my host machine and I'd prefer to keep it that way, but if it is a dependency then oh well. Hopefully all the relevant information is below. 

> freebsd-version
11.0-RELEASE-p10

- [x] Supply `iocage --version`
> iocage --version
Version 0.9.7 2017/03/08

- [x] Supply the commands used, along with any steps to recreate it.
`# cd /usr/ports/sysutils/py3-iocage/ ; make install clean`
`# iocage list -P`

- [x] Provide the output from the command you issues.

> Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 11, in <module>
    load_entry_point('iocage==0.9.7', 'console_scripts', 'iocage')()
  File "/usr/local/lib/python3.6/site-packages/iocage/main.py", line 93, in main
    cli(obj=MODULES)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/list.py", line 45, in list_cmd
    IOCFetch("").fetch_plugin_index("", _list=True)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 782, in fetch_plugin_index
    stderr=STDOUT)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_common.py", line 191, in checkoutput
    out = check_output(*args, **kwargs).decode("utf-8")
  File "/usr/local/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'git'

- [x] Supply what you expected the result or output to be
Not an error?

- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.
This one is a bit iffy since the problem would obviously not be there if I used git to fetch master..

As a final note, as I switch all of my usage over from legacy iocage to the python based one, I have to say that I'm very excited about the work being done especially around plugins. Not extremely experienced with python (if it was Haskell I'd probably already have a pr or two :) so just wanted to say thank you along with the issue.

**Comment by skarekrow** [comment]
Yeah git is required. I'm gonna let a person on the mailing list send the PR since they found it. But I'll wait a couple days and if he doesn't I can do it too. I'd recommend `git-lite`.

Much less dependencies. 

Thanks for the kind words!

**Comment by skarekrow** [comment]
I completely misinterpreted this question. The port stuff is out of my control. @araujobsd will update the port to have `git` and the other new deps when a new release is tagged. Closing this then :)
