### ISSUE TITLE
iocage : ZFS module is required (but it's already present)

### ISSUE THREAD

**Issue by gllb** [iocage/iocage#1258]
iocage complains about a missing kernel module : zfs. But i'm using zfs since i setup freebsd i actually have jail using it. 
I wanted to migrate to iocage but seem's that iocage do not want my jails.

```
% zpool list
NAME    SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
`zroot`   928G   190G   738G        -         -    14%    20%  1.00x  ONLINE  -
% kldlaod zfs
kldload: can't load zfs: module already loaded or in kernel

```

version from pkg info : py37-iocage-1.2_6.
iocage fails with :
```
% iocage --version
ZFS is required to use iocage.
Try calling 'kldload zfs' as root.
```
expected: output the version number or the normal output for any other iocage cmd.

I'm using a stable release from pkg.

**Comment by gllb** [comment]
Ok i've open an issue too quickly, it seem's related to subprocess python library.
Sorry for the noise.

```
>>> import subprocess as su
>>> su.check_call(["sysctl", "vfs.zfs.version.spa"])
ld-elf.so.1: /usr/local/lib/libpython3.7m.so.1.0: Undefined symbol "close_range@FBSD_1.6"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sysctl', 'vfs.zfs.version.spa']' returned non-zero exit status 1.

```
