### ISSUE TITLE
Fetch on Hardened BSD fails

### ISSUE THREAD

**Issue by gronke** [iocage/iocage#126]
```sh
root@hbsd # /usr/local/bin/iocage fetch
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/iocage/main.py", line 85, in main
    cli(obj=MODULES)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 132, in fetch_cmd
    eol=eol, files=files).fetch_release()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 144, in fetch_release
    self.fetch_http_release(eol, _list=_list)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 242, in fetch_http_release
    req.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://installer.hardenedbsd.org/releases/pub/HardenedBSD/releases/%7Bself.arch%7D/%7Bself.arch%7D
```

```python
# print(os.uname())
posix.uname_result(sysname='FreeBSD', nodename='hbsd', release='11.0-STABLE-HBSD', version='FreeBSD 11.0-STABLE-HBSD #0 [STABLE:HardenedBSD-11-STABLE-v46.16]: Thu Mar 30 13:37:00 UTC 2017     root@nyi-01.build.hardenedbsd.org:/usr/obj/usr/src/sys/HARDENEDBSD', machine='amd64')
```

```sh
root@hbsd # uname -a
FreeBSD hbsd 11.0-STABLE-HBSD FreeBSD 11.0-STABLE-HBSD #0 [STABLE:HardenedBSD-11-STABLE-v46.16]: Thu Mar 30 13:37:00 UTC 2017     root@nyi-01.build.hardenedbsd.org:/usr/obj/usr/src/sys/HARDENEDBSD  amd64
```

**Comment by skarekrow** [comment]
Can you post your `iocage --version` too?

**Comment by skarekrow** [comment]
Doesn't matter, should be fixed now 👍

**Comment by gronke** [comment]
thanks 😍! you were quicker than I could type `iocage --version` 😼 (btw. the version was `master`)

**Comment by skarekrow** [comment]
Hehe I figured that out when I noticed the error. It was a stupid typo on my part :D

Thanks for the report :+1:
