### ISSUE TITLE
Starting basejail on HardenedBSD fails due to missing /iocage/releases/11-STABLE/root/usr/lib32

### ISSUE THREAD

**Issue by utrenkner** [iocage/iocage#127]
Today, I compiled iocage from source (96caea4aaabab35f958d791928897a0920af6a2e) on HardenedBSD-11-STABLE-v46.16.

I created a jail with ``iocage create -b -r 11-STABLE tag=maria1``, then added host_hostname, ip4_addr and ip6_addr.

When I tried to start the jail, I got the following error, because /iocage/releases/11-STABLE/root/usr/lib32 does not exist.

```% sudo iocage start maria1
* Starting 1c4bab5e-96fd-482d-a451-10eb8af15d47 (maria1)
  + Start FAILED
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/start.py", line 32, in cli
    ioc.IOCage(jail, rc=rc).start()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 125, in start
    callback=self.callback, silent=self.silent)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_start.py", line 35, in __init__
    self.__start_jail__()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_start.py", line 256, in __start_jail__
    raise RuntimeError(f"  {stderr_data.decode('utf-8')}")
RuntimeError:   mount_nullfs: /iocage/releases/11-STABLE/root/usr/lib32: No such file or directory
jail: /sbin/mount -t nullfs -o ro /iocage/releases/11-STABLE/root/usr/lib32 /iocage/jails/1c4bab5e-96fd-482d-a451-10eb8af15d47/root/usr/lib32: failed
```
This is the output of ``ls -l /iocage/releases/11-STABLE/root/usr``:
```
drwxr-xr-x   2 root  wheel  498  9 Mai  15:08 bin
drwxr-xr-x  55 root  wheel  330  9 Mai  15:07 include
drwxr-xr-x   7 root  wheel  649  9 Mai  15:08 lib
drwxr-xr-x   6 root  wheel    6  9 Mai  15:03 libdata
drwxr-xr-x   8 root  wheel   68  9 Mai  15:08 libexec
drwxr-xr-x   2 root  wheel    2  9 Mai  15:03 local
drwxr-xr-x   2 root  wheel    2  9 Mai  15:03 obj
drwxr-xr-x   2 root  wheel  295  9 Mai  15:08 sbin
drwxr-xr-x  32 root  wheel   32  9 Mai  15:08 share
drwxr-xr-x   2 root  wheel    2  9 Mai  15:03 src
drwxr-xr-x  15 root  wheel   15  9 Mai  15:03 tests
```
Thanks for your great tool! Locally, I am still using the old shell version.

**Comment by skarekrow** [comment]
Thanks for the kind words, hopefully you switch soon :)

For this error, just remove the offending entry from `/iocage/jails/1c4bab5e-96fd-482d-a451-10eb8af15d47/fstab`, that will fix it 👍

**Comment by utrenkner** [comment]
Thanks, that was easy!

I also asked the HardenedBSD folks and learned that [lib32 does not ship with HardenedBSD by default](https://github.com/HardenedBSD/hardenedBSD/issues/258). So maybe this could be tested when starting a HBSD jail.
