### ISSUE TITLE
iocage activate: 'None/iocage': dataset does not exist

### ISSUE THREAD

**Issue by gronke** [iocage/iocage#129]
```
root@hbsd # iocage activate storage
cannot open 'None/iocage': dataset does not exist
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 365, in json_get_value
    "mountpoint", loc]).strip()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_common.py", line 419, in checkoutput
    out = su.check_output(*args, **kwargs)
  File "/usr/local/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['zfs', 'get', '-H', '-o', 'value', 'mountpoint', 'None/iocage']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "iocage/main.py", line 106, in <module>
    cli()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/activate.py", line 14, in cli
    ioc.IOCage().activate(zpool)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 59, in __init__
    self.iocroot = PoolAndDataset().get_iocroot()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 53, in get_iocroot
    return ioc_json.IOCJson(self.pool).json_get_value("iocroot")
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 372, in json_get_value
    raise RuntimeError(f"{self.location} not found!")
RuntimeError: None not found!
```

### Meta
```
root@hbsd:~ # iocage --version
Version 0.9.8 BETA

root@hbsd:~ # uname -a
FreeBSD hbsd.example.com 11.0-STABLE-HBSD FreeBSD 11.0-STABLE-HBSD #0 [STABLE:HardenedBSD-11-STABLE-v46.16]: Thu Mar 30 13:41:47 UTC 2017     root@nyi-01.build.hardenedbsd.org:/usr/obj/usr/src/sys/HARDENEDBSD  amd64
```

Commit: https://github.com/iocage/iocage/commit/e7d6f2eef54600d3053af945c7144241e915f632

**Comment by gronke** [comment]
### Git Bisect: first bad comit
```
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[3c6ad21b4413894fe0d1a0c25e07637830b1a9f9] Add `activate` to `iocage` API
```
3c6ad21b4413894fe0d1a0c25e07637830b1a9f9

**Comment by skarekrow** [comment]
Yeah something must have happened during that, I swore it worked. But obviously not :D

**Comment by skarekrow** [comment]
Does the `storage` pool exist?

**Comment by gronke** [comment]
Yep! All previous commits worked.

**Comment by skarekrow** [comment]
Interesting, thanks! This needs some more love methinks anyways, it's quite optimistic atm. Look for a commit soon ;)

**Comment by gronke** [comment]
Awesome 💛  Usually I would have created a pull-request, but your response times are faster (again) than I can click the fork button. Thanks!

**Comment by skarekrow** [comment]
Ok @gronke works for me again, please test and let me know how you make out 👍

**Comment by gronke** [comment]
Looks good over here as well.

**Comment by skarekrow** [comment]
Fantastic! Thanks for the report :)
