### ISSUE TITLE
iocage start IOError: [Errno 2] No such file or directory: u'none'

### ISSUE THREAD

**Issue by woodsb02** [iocage/iocage#14]
When I am trying to start an 11.0-RELEASE jail that I create with iocage-legacy, it gives the error below.

Note that the jail still starts and appears to be working.

```
# iocage start emby
* Starting 5dcc061b-985c-11e6-846f-bc5ff4fb5ea1 (emby)
  + Started OK
vnet0
  + Starting services OK
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 11, in <module>
    load_entry_point('iocage==0.9', 'console_scripts', 'iocage')()
  File "/usr/local/lib/python2.7/site-packages/iocage/main.py", line 78, in main
    cli(obj=MODULES)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/iocage/cli/start.py", line 48, in start_cmd
    IOCStart(uuid, path).start_jail(tag, conf)
  File "/usr/local/lib/python2.7/site-packages/iocage/lib/ioc_start.py", line 201, in start_jail
    self.generate_resolv()
  File "/usr/local/lib/python2.7/site-packages/iocage/lib/ioc_start.py", line 278, in generate_resolv
    copy(resolver, "{}/root/etc/resolv.conf".format(self.path))
  File "/usr/local/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/local/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'none'
```

**Comment by skarekrow** [comment]
This is already fixed as far as I know in the master repo. It hasn't been pushed to ports yet it looks like.
