### ISSUE TITLE
Error when setting ipaddr to none when jail running

### ISSUE THREAD

**Issue by No9** [iocage/iocage#140]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
`Version	0.9.8 BETA`
- [x] Supply the commands used, along with any steps to recreate it.
`iocage set ip4_addr=none gw`
- [x] Provide the output from the command you issues.
Property: ip4_addr has been updated to none
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 485, in json_set_value
    stderr=su.STDOUT)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_common.py", line 419, in checkoutput
    out = su.check_output(*args, **kwargs)
  File "/usr/local/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['jail', '-m', 'jid=4', 'ip4.addr=none']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/set.py", line 73, in cli
    iocjson.json_set_value(prop)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 488, in json_set_value
    f"{err.output.decode('utf-8').rstrip()}")
RuntimeError: jail: ip4.addr: not an IPv4 address: none

- [x] Supply what you expected the result or output to be
Probably just a message to say you cannot set the IP to none on a running jail
Works as expected on a stopped jail.
- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.
Ran on https://github.com/iocage/iocage/commit/8cbfe3a8c8b2b6d4ad01ec81a05203eac70e2195 Latest on 2017-05-15

Thanks for this project BTW I am enjoying splunking around it

**Comment by skarekrow** [comment]
Thanks for the kind words! I swore this annoying bug was solved. Must not be. Thanks for the report :+1:

**Comment by skarekrow** [comment]
Alright I forgot a spot, which figures. Should be good to go now, please test and report back 👍

**Comment by No9** [comment]
Property is now set if the jail is up - no error thrown
```
# iocage set ip4_addr=none gw
ip4_addr has been updated to none
```
Thanks for turning this around

**Comment by skarekrow** [comment]
Awesome! Thanks for testing.
