### ISSUE TITLE
iocage create crashes on a system with no zpools

### ISSUE THREAD

**Issue by ghost** [iocage/iocage#146]
Yes, I know iocage won't work without zfs, but it should probably print out a nice error message

Make sure to follow and check these boxes before submitting an issue! Thank you.

- [ ] Supply `iocage --version`
Version 0.9.8 BETA

- [ ] Supply the commands used, along with any steps to recreate it.
On a new VM installed with UFS as root
```
kldload zfs
iocage create
```

- [ ] Provide the output from the command you issued.
```
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/main.py", line 101, in cli
    ioc_check.IOCCheck()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_check.py", line 15, in __init__
    "pool")
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 320, in json_get_value
    zpool = zpools[0]
IndexError: list index out of range

```

**Comment by skarekrow** [comment]
Indeed it should and I thought did. We may have regressed since quite a bits changed. 

Thanks for the report!

**Comment by skarekrow** [comment]
Alright should be fixed, please test as well 👍
