### ISSUE TITLE
jailed zfs datasets aren't able to be mounted

### ISSUE THREAD

**Issue by johnramsden** [iocage/iocage#157]
As mentioned in [the issue](https://github.com/iocage/iocage/issues/151#issuecomment-304599756) on how i'm unable to set systemwide defaults, jailed zfs datasets don't seem to be mounting properly.

I'm trying to mount: vault/data/jails/stratus/db with:

`iocage set jail_zfs_dataset='data/jails/stratus' stratus`

but in the jail it says the following when I try to mount it:

```
zfs set mountpoint=/var/db/mysql vault/data/jails/stratus
cannot open 'vault/data/jails/stratus': dataset does not exist
``` 
---

- [x] iocage version: (Version 0.9.5 2017/02/15)
- [x] Supply the commands used, along with any steps to recreate it.
- [x] Provide the output from the command you issued.
- [x] Supply what you expected the result or output to be
- [ ] Checked that the problem has not already been fixed on `master` if using a stable release.

---

Properties on jail:

```
iocage get all stratus

openfiles:off
resolver:/etc/resolv.conf
nmsgq:off
memoryuse:8G:log
compressratio:readonly
allow_quotas:0
allow_mount_zfs:0
sync_tgt_zpool:none
istemplate:no
gitlocation:https://github.com
interfaces:vnet0:bridge0,vnet1:bridge1
login_flags:-f root
hostid:13757acc-3480-fba2-dc11-a3ab008ab736
ip4_autosubnet:none
bpf:off
notes:none
defaultrouter6:none
release:11.0-RELEASE-p10
nthr:off
coredumpsize:off
ip4_addr:sge0|172.20.0.100/32
allow_raw_sockets:0
allow_mount_tmpfs:0
ip4_autostart:none
exec_start:/bin/sh /etc/rc
allow_mount_procfs:0
mountpoint:readonly
sync_state:none
shmsize:off
dedup:off
jail_zfs_mountpoint:none
template:none
dhcp:off
hack88:0
available:readonly
pcpu:off
vmemoryuse:off
exec_clean:1
exec_prestop:/usr/bin/true
last_started:2017-05-27 06:47:50
exec_fib:0
allow_set_hostname:1
exec_system_jail_user:0
securelevel:2
allow_mount_devfs:0
origin:readonly
mount_fdescfs:1
allow_mount:0
rlimits:off
exec_system_user:root
reservation:none
owner:root
swapuse:off
compression:lz4
exec_poststart:mount lilan.ramsden.network:/mnt/tank/data/stratus/data /iocage/jails/030c5af2-a429-4e0e-b571-8c14c933f1c5/root/mnt/data; mount lilan.ramsden.network:/mnt/tank/data/syncthing/sync /iocage/jails/030c5af2-a429-4e0e-b571-8c14c933f1c5/root/mnt/sync
ip6_addr:none
exec_timeout:60
host_domainname:none
priority:99
maxproc:off
ip4_saddrsel:1
exec_stop:/bin/sh /etc/rc.shutdown
sysvmsg:new
stacksize:off
datasize:off
type:jail
allow_mount_nullfs:0
allow_chflags:0
cpuset:off
ipv6:off
allow_socket_af:0
ip6:new
ip4:new
sysvsem:new
mount_devfs:1
mount_procfs:0
count:1
memorylocked:off
host_hostuuid:030c5af2-a429-4e0e-b571-8c14c933f1c5
tag:stratus
mount_linprocfs:0
ip4_autoend:none
vnet0_mac:none
pseudoterminals:off
allow_sysvipc:0
cloned_release:11.0-RELEASE
vnet3_mac:none
mac_prefix:02ff60
jail_zfs:on
msgqsize:off
stop_timeout:30
nsemop:off
ip6_saddrsel:1
nshm:off
host_hostname:030c5af2-a429-4e0e-b571-8c14c933f1c5
boot:on
wallclock:off
sysvshm:new
exec_jail_user:root
used:readonly
defaultrouter:none
quota:none
exec_prestart:/usr/bin/true
enforce_statfs:2
jail_zfs_dataset:data/jails/stratus
cputime:off
exec_poststop:umount /iocage/jails/030c5af2-a429-4e0e-b571-8c14c933f1c5/root/mnt/data; umount /iocage/jails/030c5af2-a429-4e0e-b571-8c14c933f1c5/root/mnt/sync
CONFIG_VERSION:3
children_max:0
sync_target:none
vnet1_mac:none
msgqqueued:off
vnet2_mac:none
vnet:off
devfs_ruleset:4
```

**Comment by skarekrow** [comment]
Does that dataset you provide exist before starting the jail?

**Comment by johnramsden** [comment]
Yes, and I just tried it with using `vault/iocage/jails/data/stratus` to see if it would make a difference being a child of `iocage/jails` given that the [man page mentions](https://www.freebsd.org/cgi/man.cgi?query=iocage&sektion=8): 

> jail_zfs_dataset="zfs_filesystem	..."
> 
> 	   This	is a space-separated list of datasets to be jailed and fully handed
> 	   over	to a jail.
> 	   Takes a ZFS filesystem name;	if it begins with "iocage/jails", it will be
> 	   created on the ZFS pool that	iocage uses.
> 	   NOTE: only valid if jail_zfs=on. By default the mountpoint is set to	none,
> 	   to mount this dataset set its mountpoint inside the jail i.e. "zfs set
> 	   mountpoint=/data full-dataset-name" and issue "mount	-a".
> 
> 	   Default: iocage/jails/UUID/root/data
> 	   Source: local

And it didn't work. The data set existed beforehand as well.

**Comment by skarekrow** [comment]
Alright thanks. I'll dig into this tomorrow and see what's up!

**Comment by johnramsden** [comment]
From the [man page](https://www.freebsd.org/cgi/man.cgi?query=iocage&sektion=8):

>        jail_zfs=on | off
> 
> 	   Enables automatic ZFS jailing inside	the jail. Assigned ZFS dataset will
> 	   be fully controlled by the jail.
> 	   NOTE: Setting this to "on" automatically enables allow_mount=1
> 	   enforce_statfs=1 and	allow_mount_zfs=1! These are dependent options
> 	   required for	ZFS management inside a	jail.

I just tried setting the properties it mentions need setting by hand, and it didn't help. Should enforce_statfs be set to 2?

**Comment by johnramsden** [comment]
So I just found out it will let me create and mount new datasets under `iocage/jails/UUID/data` within the jail.  I wonder if this is related to the default jailed dataset being  `iocage/jails/UUID/data` as mentioned in the  [jail_zfs_dataset](https://www.freebsd.org/cgi/man.cgi?query=iocage&sektion=8) entry.

**Comment by skarekrow** [comment]
No it shouldn't be related to that, but I do believe that you need `enforce_statfs=0`. Since your dataset is not under the jails chroot. I hardcode it to 1 currently, so I can change that behavior quickly, but I'm going to confirm that's the issue first on my end.

That being said, your version is over 3 months old. I highly recommend upgrading, as I may have touched the jailed dataset behavior and I'm just not remembering, it's been a while ;)

**Comment by skarekrow** [comment]
It all works here, so I would recommend upgrading.

```
╰─ iocage clean -jf ; iocage create tag="test" -r 11.0-RELEASE
Cleaning iocage/jails
All iocage jail datasets have been destroyed.
4df63b8f-c9ef-49e1-98a6-ba0831307bf3 (test) successfully created!                                                                                                                                                                     
╰─ iocage set jail_zfs_dataset=foo test
Property: jail_zfs_dataset has been updated to foo
╰─ iocage set jail_zfs="on" test
Property: jail_zfs has been updated to on
╰─ iocage start test
* Starting 4df63b8f-c9ef-49e1-98a6-ba0831307bf3 (test)
  + Started OK
  + Starting services OK
╰─ iocage console test
FreeBSD 11.0-RELEASE-p9 (VIMAGE_GENERIC) #0 r316823: Fri Apr 14 06:31:28 CDT 2017

Welcome to FreeBSD!

Release Notes, Errata: https://www.FreeBSD.org/releases/
Security Advisories:   https://www.FreeBSD.org/security/
FreeBSD Handbook:      https://www.FreeBSD.org/handbook/
FreeBSD FAQ:           https://www.FreeBSD.org/faq/
Questions List: https://lists.FreeBSD.org/mailman/listinfo/freebsd-questions/
FreeBSD Forums:        https://forums.FreeBSD.org/

Documents installed with the system are in the /usr/local/share/doc/freebsd/
directory, or can be installed later with:  pkg install en-freebsd-doc
For other languages, replace "en" with a language code like de or fr.

Show the version of FreeBSD installed:  freebsd-version ; uname -a
Please include that output and any error messages when posting questions.
Introduction to manual pages:  man man
FreeBSD directory layout:      man hier

Edit /etc/motd to change this login announcement.
root@4df63b8f-c9ef-49e1-98a6-ba0831307bf3:~ # zfs list
NAME        USED  AVAIL  REFER  MOUNTPOINT
zroot      4.58G  24.2G    96K  /zroot
zroot/foo    96K  24.2G    96K  none
root@4df63b8f-c9ef-49e1-98a6-ba0831307bf3:~ # zfs set mountpoint="/foo" zroot/foo
root@4df63b8f-c9ef-49e1-98a6-ba0831307bf3:~ # zfs list
NAME        USED  AVAIL  REFER  MOUNTPOINT
zroot      4.58G  24.2G    96K  /zroot
zroot/foo    96K  24.2G    96K  /foo
root@4df63b8f-c9ef-49e1-98a6-ba0831307bf3:~ # cd /foo
root@4df63b8f-c9ef-49e1-98a6-ba0831307bf3:/foo # ls
```

EDIT: This was with `enforce_statfs=1` I should add. So that's the default behavior. Once you upgrade it should all start working :)

**Comment by johnramsden** [comment]
Still getting this on current version.

```
#  iocage set jail_zfs_dataset='data/jails/stratus/db' stratus
Property: jail_zfs_dataset has been updated to data/jails/stratus/db
```

```
# iocage set jail_zfs_mountpoint='none' stratus
Property: jail_zfs_mountpoint has been updated to none
```

```
# iocage set jail_zfs=on stratus
Property: jail_zfs has been updated to on
```

```

# iocage stop stratus
* Stopping 5e8586e5-c7da-41ee-9abb-744f62d593d0 (stratus)
  + Running prestop OK
  + Stopping services OK
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_stop.py", line 164, in __stop_jail__
    stderr=su.STDOUT)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_common.py", line 421, in checkoutput
    out = su.check_output(*args, **kwargs)
  File "/usr/local/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['zfs', 'unjail', 'ioc-5e8586e5-c7da-41ee-9abb-744f62d593d0', 'vault/data/jails/stratus/db']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/stop.py", line 32, in cli
    ioc.IOCage(jail, rc=rc).stop()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 500, in stop
    ioc_stop.IOCStop(uuid, tag, path, conf, silent=self.silent)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_stop.py", line 27, in __init__
    self.__stop_jail__()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_stop.py", line 168, in __stop_jail__
    err.output.decode("utf-8").rstrip()))
RuntimeError: cannot unjail 'vault/data/jails/stratus/db': dataset does not exist
```

```
# zfs list
NAME                                                           USED  AVAIL  REFER  MOUNTPOINT
...
vault/data/jails/stratus/db                                     96K   834G    96K  none
...
vault/iocage/jails                                            35.5M   834G    96K  /iocage/jails
vault/iocage/jails/5e8586e5-c7da-41ee-9abb-744f62d593d0       35.4M   834G   100K  /iocage/jails/5e8586e5-c7da-41ee-9abb-744f62d593d0
vault/iocage/jails/5e8586e5-c7da-41ee-9abb-744f62d593d0/data    96K   834G    96K  none
vault/iocage/jails/5e8586e5-c7da-41ee-9abb-744f62d593d0/root  35.2M   834G   390M  /iocage/jails/5e8586e5-c7da-41ee-9abb-744f62d593d0/root
```

**Comment by skarekrow** [comment]
You need to create that dataset. That's the error :)

**Comment by johnramsden** [comment]
It exists already.

**Comment by johnramsden** [comment]
So I figured it out. You can't jail datasets while the jail is on. It only works if you stop the jail, jail the dataset, and then start it. I'm not sure if this is intended Behavior but it wasn't clear to me.

**Comment by skarekrow** [comment]
I'll look next week to see what's up. I agree that's not intuitive.

**Comment by marschal** [comment]
@skarekrow Is there a workaround for this issue by now? 
I'm experiencing the same issue like @johnramsden with my jails when `jail_zfs="on"`.

**Comment by johnramsden** [comment]
@marschal Just set `jail_zfs="off"`, stop your jail, set `jail_zfs="on"`, `jail_zfs_dataset`, and `jail_zfs_mountpoint`. Then you can start your jail and everything should work.
