### ISSUE TITLE
iocage fetch - errors are not caught to give a user understandable message

### ISSUE THREAD

**Issue by woodsb02** [iocage/iocage#165]
If iocage fetch is not able to fetch the release, the output to the console is a python traceback which is not very user friendly. It would be better if the fetch error was caught in the code and a helpful message was provided to the console.

iocage --version: Version 0.9.8.1 05/23/2017

EXAMPLE 1 - with outbound FTP blocked by firewall
# iocage fetch
Expected output (something like):
```
Attempting ftp connection to ftp.freebsd.org...
Unable to connect to ftp.freebsd.org
```
Actual output:
<after 80 seconds with no output to the console to let the user know what is happening or if it is attempting a connection>
```
Traceback (most recent call last):                                         
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())                         
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs) 
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main                                                                                        
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)                                   
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)                                                               
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 135, in cli
    eol=eol, files=files).fetch_release()                                                              
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 230, in fetch_release
    self.fetch_ftp_release(eol, _list=_list)                                                                    
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 383, in fetch_ftp_release
    ftp_list = ftp.nlst()           
  File "/usr/local/lib/python3.6/ftplib.py", line 557, in nlst
    self.retrlines(cmd, files.append)                                                                                                                                   
  File "/usr/local/lib/python3.6/ftplib.py", line 466, in retrlines
    with self.transfercmd(cmd) as conn, \
  File "/usr/local/lib/python3.6/ftplib.py", line 397, in transfercmd                                                                                                   
    return self.ntransfercmd(cmd, rest)[0]
  File "/usr/local/lib/python3.6/ftplib.py", line 359, in ntransfercmd                                                                                                  
    source_address=self.source_address)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err                                       
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)                                
TimeoutError: [Errno 60] Operation timed out
```

EXAMPLE 2 - Use of http when file not found
# iocage fetch -h -s ftp.au.freebsd.org
Expected output (something like):
```
Attempting http connection to http://ftp.au.freebsd.org/None...
File note found: http://ftp.au.freebsd.org/None
```
Actual output:
```
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 135, in cli
    eol=eol, files=files).fetch_release()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 169, in fetch_release
    self.fetch_http_release(eol, _list=_list)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 317, in fetch_http_release
    req.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 929, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://ftp.au.freebsd.org/None
```

**Comment by rwestlund** [comment]
You get this on HEAD (ae37026) when you do something like misspell "release":
```sh
root@legion ~# iocage fetch -r 11.0-RELASE
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 447, in fetch_ftp_release
    ftp.cwd(self.release)
  File "/usr/local/lib/python3.6/ftplib.py", line 629, in cwd
    return self.voidcmd(cmd)
  File "/usr/local/lib/python3.6/ftplib.py", line 276, in voidcmd
    return self.voidresp()
  File "/usr/local/lib/python3.6/ftplib.py", line 249, in voidresp
    resp = self.getresp()
  File "/usr/local/lib/python3.6/ftplib.py", line 244, in getresp
    raise error_perm(resp)
ftplib.error_perm: 550 Failed to change directory.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 94, in cli
    ioc.IOCage().fetch(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 632, in fetch
    ioc_fetch.IOCFetch(release, **kwargs).fetch_release()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 256, in fetch_release
    self.fetch_ftp_release(eol, _list=_list)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 449, in fetch_ftp_release
    raise RuntimeError(f"{self.release} was not found!")
RuntimeError: 11.0-RELASE was not found!
```
