### ISSUE TITLE
iocage fetch - root directory defaults to "None" when -h used for http

### ISSUE THREAD

**Issue by woodsb02** [iocage/iocage#166]
Adding the -h option to iocage fetch causes the root directory to default to "None" where I would have expected it to default to "/pub/FreeBSD/releases/{self.arch}".

iocage --version: Version 0.9.8.1 05/23/2017

```
iocage fetch -h -s ftp.au.freebsd.org
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 135, in cli
    eol=eol, files=files).fetch_release()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 169, in fetch_release
    self.fetch_http_release(eol, _list=_list)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 317, in fetch_http_release
    req.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 929, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://ftp.au.freebsd.org/None
```

**Comment by skarekrow** [comment]
It does keep that behavior when you use the default server with it. I could change this behavior, but I'm more likely to make `-h` and `-d` be co-dependent. It makes sense to me if you're using a custom http server, that you likely have your own layout.

**Comment by woodsb02** [comment]
I actually think it still makes sense to default to pub/FreeBSD/releases/{self.arch} because the most likely alternative server you are using is a mirror, and they almost all have this same folder structure.

**Comment by skarekrow** [comment]
Hmm perhaps. I'll adjust it next week then :)

**Comment by skarekrow** [comment]
So I keep the root_dir now, but it seems some mirrors use pub/ and the Official FreeBSD site uses ftp/, so for those nonstandard layouts (IE: This one) you will still have to manually supply root_dir.

**Comment by woodsb02** [comment]
Looks like the official FreeBSD site can use pub/FreeBSD/... if you instead access it through http://ftp.FreeBSD.org?
http://ftp.freebsd.org/pub/FreeBSD/

**Comment by skarekrow** [comment]
Hmm I'll have to look when I get to a computer on why I chose that. If only I could remember! Hehe.

**Comment by woodsb02** [comment]
It looks like the same server is available at http://download.freebsd.org/ or also at http://ftp.freebsd.org/ but the initial part of the subdirectories is different.

**Comment by skarekrow** [comment]
Interesting. Can you send a PR changing t from download then and the root_dir? Should be a simple change.
