### ISSUE TITLE
iocage create -r 11.0-RELEASE test - creates an erroneous jail which cannot be listed or deleted

### ISSUE THREAD

**Issue by woodsb02** [iocage/iocage#170]
If the command for creating a jail is incorrectly formed as shown below, it will create a jail which is not fully configured and cannot be deleted by iocage. Instead, one has to use zfs to destroy the dataset.

iocage --version: Version 0.9.8.1 05/23/2017

```
# iocage create -r 11.0-RELEASE test
test is not a valid property!
# ls -lah /iocage/jails/
total 13                                                                               
drwxr-xr-x  3 root  wheel     3B 10 Jun 17:57 .                          
drwxr-xr-x  9 root  wheel     9B 10 Jun 17:53 ..                                                 
drwxr-xr-x  3 root  wheel     3B 10 Jun 17:57 0f83eaf9-7d7e-4c2f-8f58-6b976a78e854
# iocage list
Traceback (most recent call last):              
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 544, in json_check_config
    release = conf["release"]                                  
KeyError: 'release'                                                               
                                                  
During handling of the above exception, another exception occurred:                                                                                                     

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/list.py", line 44, in cli
    _list = ioc.IOCage().list(dataset_type, header, _long, _sort)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 68, in __init__
    self.jails, self._paths = self.list("uuid")
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 468, in list
    return ioc_list.IOCList(lst_type, header, long, sort).list_datasets()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_list.py", line 53, in list_datasets
    conf = iocage.lib.ioc_json.IOCJson(jail).json_load()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 256, in json_load
    conf = self.json_check_config(conf, version)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 548, in json_check_config
    freebsd_version = f"{iocroot}/releases/{conf['release']}" \
KeyError: 'release'

# iocage destroy 0f83eaf9-7d7e-4c2f-8f58-6b976a78e854
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 544, in json_check_config
    release = conf["release"]
KeyError: 'release'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/destroy.py", line 28, in cli
    jail_list, paths = ioc_list.IOCList("uuid").list_datasets()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_list.py", line 53, in list_datasets
    conf = iocage.lib.ioc_json.IOCJson(jail).json_load()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 256, in json_load
    conf = self.json_check_config(conf, version)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 548, in json_check_config
    freebsd_version = f"{iocroot}/releases/{conf['release']}" \
KeyError: 'release'

# zfs destroy -r zstore/iocage/jails/0f83eaf9-7d7e-4c2f-8f58-6b976a78e854
# iocage list
+-----+------+-------+-----+---------+-----+
| JID | UUID | STATE | TAG | RELEASE | IP4 |
+=====+======+=======+=====+=========+=====+
+-----+------+-------+-----+---------+-----+

```

**Comment by skarekrow** [comment]
Good news and bad.

The good, I can reproduce this, and the behavior has changed from that release to the latest on `master`, and because of some changes I did a little while ago, you can actually destroy this with iocage instead of jumping to zfs.  Should be a fairly easy bug to squash.

The bad, it still happens on `master` ;)

```
root@iocage-vm:~ # iocage create -r 11.0-RELEASE test
test is not a valid property!
root@iocage-vm:~ # ls -lha /iocage/jails
total 4
drwxr-xr-x   3 root  wheel     3B Jun  5 19:14 .
drwxr-xr-x  10 root  wheel    11B Jun  5 19:14 ..
drwxr-xr-x   3 root  wheel     3B Jun  5 19:14 8f20403a-f3b5-4d35-9c22-e455024693cf
root@iocage-vm:~ # iocage list
Traceback (most recent call last):
  File "/usr/home/bschneider/iocage/iocage/lib/ioc_json.py", line 607, in json_check_config
    release = conf["release"]
KeyError: 'release'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/home/bschneider/iocage/iocage/lib/ioc_json.py", line 611, in json_check_config
    freebsd_version = f"{iocroot}/releases/{conf['release']}" \
KeyError: 'release'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/home/bschneider/iocage/iocage/cli/list.py", line 71, in cli
    _list = iocage.list(dataset_type, header, _long, _sort, plugin=plugins)
  File "/usr/home/bschneider/iocage/iocage/lib/iocage.py", line 682, in list
    plugin=plugin).list_datasets()
  File "/usr/home/bschneider/iocage/iocage/lib/ioc_list.py", line 67, in list_datasets
    _all = self.list_all(ds)
  File "/usr/home/bschneider/iocage/iocage/lib/ioc_list.py", line 142, in list_all
    conf = iocage.lib.ioc_json.IOCJson(mountpoint).json_load()
  File "/usr/home/bschneider/iocage/iocage/lib/ioc_json.py", line 279, in json_load
    conf = self.json_check_config(conf)
  File "/usr/home/bschneider/iocage/iocage/lib/ioc_json.py", line 619, in json_check_config
    raise RuntimeError("Configuration is missing!"
RuntimeError: Configuration is missing! Please destroy 8f20403a-f3b5-4d35-9c22-e455024693cf and recreate it.
root@iocage-vm:~ # iocage destroy 8f20403a-f3b5-4d35-9c22-e455024693cf
root@iocage-vm:~ # iocage list
+-----+------+-------+-----+---------+-----+
| JID | UUID | STATE | TAG | RELEASE | IP4 |
+=====+======+=======+=====+=========+=====+
+-----+------+-------+-----+---------+-----+
```
