### ISSUE TITLE
problems with templates

### ISSUE THREAD

**Issue by antxxxx** [iocage/iocage#175]
I may be misunderstanding how templates work, but they seem to be broken in a couple of ways

I created a new jail using this
```
 iocage create tag=template  -r 11.0-RELEASE
```

I then did some stuff on there (eg install some default packages I wanted) and then turned it into a template using
```
iocage set template=yes template
```
I can then create jails from the template using 
```
iocage create -t template
```
If I now want to modify the template, I would expect to use
```
iocage set template=no template
```
but I get the error 
```
template not found
```

If I use the UUID to try and set the property by using
```
iocage set template=no 797fb90e
```
, I get this error
```
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/set.py", line 73, in cli
    iocjson.json_set_value(prop)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 457, in json_set_value
    self.zfs.get_dataset(old_location).rename(new_location)
  File "libzfs.pyx", line 566, in libzfs.ZFS.get_dataset (libzfs.c:18784)
libzfs.ZFSException: Dataset sys/iocage/jails/797fb90e-f691-4b4a-bf74-f2174db5925e not found

```
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [Version	0.9.8.1 05/23/2017 ] Supply `iocage --version`
- [] Supply the commands used, along with any steps to recreate it.
- [ ] Provide the output from the command you issued.
- [ ] Supply what you expected the result or output to be
- [ ] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by skarekrow** [comment]
You're understanding it correctly. This is a side effect of some other changes I did a while back. I can't recall the difference ATM but when I'm at a computer next week I'll circle back. But I believe iocage list -t will show you the "new" name.

**Comment by skarekrow** [comment]
I cannot reproduce this with master:
```
╰─ iocage create tag="test" -r 11.0-RELEASE
56aea669-700c-4804-8d7e-a7c6926edb9f (test) successfully created!
╰─ iocage set template="yes" test
56aea669-700c-4804-8d7e-a7c6926edb9f (test) converted to atemplate.
Property: template has been updated to yes
╰─ iocage create -t test
eaf58c0b-8891-4503-9e6d-1ec4bbed40ce (2017-06-14@20:47:16:503125) successfully created!
╰─ iocage list
+-----+----------+-------+----------------------------+--------------+-----+
| JID |   UUID   | STATE |            TAG             |   RELEASE    | IP4 |
+=====+==========+=======+============================+==============+=====+
| -   | eaf58c0b | down  | 2017-06-14@20:47:16:503125 | 11.0-RELEASE | -   |
+-----+----------+-------+----------------------------+--------------+-----+
╰─ iocage list -t
+-----+----------+-------+------+--------------+-----+
| JID |   UUID   | STATE | TAG  |   RELEASE    | IP4 |
+=====+==========+=======+======+==============+=====+
| -   | 56aea669 | down  | test | 11.0-RELEASE | -   |
+-----+----------+-------+------+--------------+-----+
╰─ zfs list -t snap
--snip--
zroot/iocage/templates/test/root@eaf58c0b-8891-4503-9e6d-1ec4bbed40ce             0      -   281M  -
```
