### ISSUE TITLE
iocage list giving IndexError: list index out of range

### ISSUE THREAD

**Issue by woodsb02** [iocage/iocage#18]
After updating from py-iocage 0.9 in ports to 0.9.2, I started getting the following errors:

```
# iocage list
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 11, in <module>
    load_entry_point('iocage==0.9', 'console_scripts', 'iocage')()
  File "/usr/local/lib/python2.7/site-packages/iocage/main.py", line 78, in main
    cli(obj=MODULES)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/iocage/cli/list.py", line 24, in list_cmd
    IOCList(dataset_type, header, _long).get_datasets()
  File "/usr/local/lib/python2.7/site-packages/iocage/lib/ioc_list.py", line 62, in get_datasets
    self.list_all(datasets)
  File "/usr/local/lib/python2.7/site-packages/iocage/lib/ioc_list.py", line 152, in list_all
    self.pool, uuid)]).split("/")[3]
IndexError: list index out of range
```

**Comment by skarekrow** [comment]
Sigh. I swore this was fixed. I'll look into this next week. Thanks for all the reports!

**Comment by skarekrow** [comment]
Actually I just verified it is fixed:https://github.com/iocage/iocage/blob/master/iocage/lib/ioc_list.py#L152 was the fix for this. I'd verify that pip actually overwrote any of the libs from the port. Since as you can see your line 152 is not the same.

Please retest after you verify the update went well. You will need `pip install -U` for that.
