### ISSUE TITLE
iocage fetch lacks proxy support

### ISSUE THREAD

**Issue by bsdlme** [iocage/iocage#200]
Version 0.9.8.1 05/23/2017

iocage fetch is lacking proxy support. I have set http_proxy and https_proxy to http://proxy:port which works for fetch(1) and other programs. However iocage does not use the proxy:

```
# iocage fetch -r 11.0-RELEASE
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 135, in cli
    eol=eol, files=files).fetch_release()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 230, in fetch_release
    self.fetch_ftp_release(eol, _list=_list)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 382, in fetch_ftp_release
    ftp = self.__fetch_ftp_connect__()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 446, in __fetch_ftp_connect__
    ftp = ftplib.FTP(self.server)
  File "/usr/local/lib/python3.6/ftplib.py", line 117, in __init__
    self.connect(host)
  File "/usr/local/lib/python3.6/ftplib.py", line 152, in connect
    source_address=self.source_address)
  File "/usr/local/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.6/socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] hostname nor servname provided, or not known
```

**Comment by skarekrow** [comment]
I don't personally use proxies, so this would have to be supplied by somebody else, as I won't get to it for some time.

Thanks for the issue :)

**Comment by dgeo** [comment]
@larsengels Did you try with HTTP_PROXY instead of http_proxy (and HTTPS…) ?

http://docs.python-requests.org/en/master/user/advanced/#proxies

If it works, it may be sufficient to export http_proxy content to HTTP_PROXY (or just document this fact ?, or open an issue againt python's requests module ?)

**Comment by bsdlme** [comment]
IIRC I had set both upper and lower case vars. Will check tomorrow

**Comment by bsdlme** [comment]
Yes, both cases are set set.

**Comment by phyber** [comment]
Just been looking at this a little, although obviously testing with 1.0 and `HTTP_PROXY` support seems to work fine in 1.0 as documented in `requests`.

However, looking at the original report, it looks like the download was attempting to take place over FTP (see the mentions of `ftplib` and FTP related functions in the output). Looking at old versions of `iocage` and the Python 3.6 `ftplib`, there doesn't seem to be any mention in either of them about supporting FTP downloads over a HTTP proxy which likely explains why it didn't work back then.

Since this is working now (`iocage` was rewritten to download over HTTP, or at least, defaults to it and uses `requests`), this feature is likely complete 👍

**Comment by skarekrow** [comment]
Agreed! Closing

**Comment by bsdlme** [comment]
Thank you @phyber!
