### ISSUE TITLE
Broken local fetch

### ISSUE THREAD

**Issue by bsdlme** [iocage/iocage#201]
Version 0.9.8.1 05/23/2017

I've set up a new iocage instance for zpool _data_, running

```
iocage activate data
```

As _iocage fetch_ does not support proxies, I downloaded the .txz files and put them into _/tmp/fbsd/ftp/releases/11.0-RELEASE/_.

_iocage fetch -f_ finds them, but the needed datasets cannot be created because of a leading /. I guess the a zpool variable is unset somewhere.

```
 recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 135, in cli
    eol=eol, files=files).fetch_release()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 186, in fetch_release
    "compression": "lz4"
  File "libzfs.pyx", line 1807, in libzfs.ZFSPool.create (libzfs.c:41209)
libzfs.ZFSException: leading slash in name

```

**Comment by skarekrow** [comment]
I can't replicate this, I did find a different bug in the meantime that I've since fixed 3b1d2e0e62f0c324ba4125c8a6be04876a8250af, but I'll need more information from you for this one.

```
╰─ iocage fetch -f -d /home/bschneider/releases -r 10.3-RELEASE
Copying: MANIFEST...
Copying: base.txz...
Extracting: base.txz...
Copying: lib32.txz...
Extracting: lib32.txz...
Copying: doc.txz...
Extracting: doc.txz...
```
Can you post your exact command, and try on `master`?

**Comment by bsdlme** [comment]
Sorry, I switched to iocell on that machine and cannot test iocage again.

**Comment by dpejcha** [comment]
I am running into the same problem. Running TrueOS/FreeBSD 12.0-CURRENT and iocage 0.9.9.1.

What I am trying to do: iocage will not fetch snapshots, so I cannot get 12.0-CURRENT as a base for making a jail, the latest I can grab is 11.1-RELEASE. If I create a jail based on 11.1-RELEASE, then I cannot build ports - the ports are expecting to build on FreeBSD 11 but the fact it is FreeBSD 12 is visible inside the jail. So, I downloaded the .txz files for 12.0-CURRENT from the FreeBSD servers and placed them in a local folder:

# iocage fetch -f -d /iocage/_snap/ -r 12.0-CURRENT
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 95, in cli
    ioc.IOCage().fetch(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 754, in fetch
    ioc_fetch.IOCFetch(release, **kwargs).fetch_release()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 219, in fetch_release
    "compression": "lz4"
  File "libzfs.pyx", line 1807, in libzfs.ZFSPool.create (libzfs.c:41192)
libzfs.ZFSException: leading slash in name

I am prepared to provide any additional information needed.

**Comment by dpejcha** [comment]
More information: I just updated to master, Version 0.9.9.2 09/30/2017 and I am still getting the problem:

[root@athena] ~# iocage --version
Version 0.9.9.2 09/30/2017
[root@athena] ~# iocage fetch -f -d /root/release -r 12.0-TRUEOS
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 158, in cli
    ioc.IOCage(exit_on_error=True).fetch(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 943, in fetch
    **kwargs).fetch_release()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 275, in fetch_release
    self.zpool.create(dataset, {"compression": "lz4"})
  File "libzfs.pyx", line 1807, in libzfs.ZFSPool.create (libzfs.c:41192)
libzfs.ZFSException: leading slash in name
[root@athena] ~# ls -l /root/release
total 1
drwxr-xr-x  2 root  wheel  6 Oct  9 12:06 12.0-TRUEOS
[root@athena] ~# ls -l /root/release/12.0-TRUEOS/
total 123410
-rw-r--r--  1 root  wheel  105483144 Oct  9 12:01 base.txz
-rw-r--r--  1 root  wheel    1403396 Oct  9 12:05 doc.txz
-rw-r--r--  1 root  wheel   19373876 Oct  9 12:05 lib32.txz
-rw-r--r--  1 root  wheel       1054 Oct  9 12:06 MANIFEST

**Comment by skarekrow** [comment]
Well I can reproduce now! Yay. Will fix :)

**Comment by skarekrow** [comment]
Fixed :)
```
root@iocage:~ # iocage fetch -f -d /root/release -r 12.0-TRUEOS
Copying: MANIFEST...
Copying: base.txz...
Extracting: base.txz...
Copying: lib32.txz...
Extracting: lib32.txz...
Copying: doc.txz...
Extracting: doc.txz...
```

**Comment by dpejcha** [comment]
works for me too now, thank you!
