### ISSUE TITLE
Starting a jail fails when /etc/localtime is missing

### ISSUE THREAD

**Issue by rwestlund** [iocage/iocage#208]
Using HEAD (cd94645):

On a system where `/etc/localtime` doesn't exist (e.g. UTC):
```
root@r2d2 /u/h/randy# env ASSUME_ALWAYS_YES=yes iocage pkg test update
test (test) is not running, starting jail
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/pkg.py", line 38, in cli
    ioc.IOCage(jail).exec(cmd)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 558, in exec
    silent=self.silent).exec_jail()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_exec.py", line 75, in exec_jail
    silent=True)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_start.py", line 59, in __init__
    self.__start_jail__()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_start.py", line 351, in __start_jail__
    self.start_copy_localtime()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_start.py", line 554, in start_copy_localtime
    f"{self.path}/root/etc/localtime")
  File "/usr/local/lib/python3.6/shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/localtime'
```

Not having `/etc/localtime` is a valid way to specify UTC on FreeBSD.  This was the case on my system that was installed with 10.x and upgraded to 11.0.  Running `tzsetup(8)` and selecting UTC did install the symlink, however.

iocage should probably just skip copying `/etc/localtime` if it doesn't exist.

**Comment by skarekrow** [comment]
Indeed!

**Comment by skarekrow** [comment]
You can also set the jail property `host_time` to `no`, which had a bug (lol), but now works as well 👍
