### ISSUE TITLE
Can't clone a template

### ISSUE THREAD

**Issue by rwestlund** [iocage/iocage#214]
Using HEAD (cd9464527b3876157461631ea7ac3c89382b4de2):

`iocage clone` doesn't work on template jails:

```
root@r2d2 /u/h/randy# iocage create -n mytempl -r 11.0-RELEASE
mytempl (mytempl) successfully created!

root@r2d2 /u/h/randy# iocage set template=yes mytempl
mytempl (mytempl) converted to a template.
Property: template has been updated to yes

root@r2d2 /u/h/randy# iocage clone mytempl
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 172, in json_load
    with open(self.location + "/config.json", "r") as conf:
FileNotFoundError: [Errno 2] No such file or directory: '/iocage/jails/mytempl/config.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_create.py", line 114, in _create_jail
    cloned_release = clone_config("cloned_release")
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 402, in json_get_value
    conf = self.json_load()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 263, in json_load
    self.json_convert_from_zfs(uuid, skip=skip)
UnboundLocalError: local variable 'uuid' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/clone.py", line 53, in cli
    err, msg = ioc.IOCage(jail=source).create(source, props, count, clone=True)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 491, in create
    silent=self.silent).create_jail()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_create.py", line 82, in create_jail
    return self._create_jail(jail_uuid, location)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_create.py", line 143, in _create_jail
    raise RuntimeError(f"Jail: {self.jail} not found!")
AttributeError: 'IOCCreate' object has no attribute 'jail'
```

**Comment by skarekrow** [comment]
I label this a bug. But more because I won't allow it. Cloning a template is identical to creating from one :)

**Comment by rwestlund** [comment]
Ah, okay.  I wasn't sure it was the same behavior.

So there's no reason to do this
```
iocage create tag=templ -r 11.0-RELEASE
iocage set template=on templ
iocage create -t templ
```
rather than this
```
iocage create tag=templ -r 11.0-RELEASE
iocage clone templ
```

The whole `template=on` and `create -t` thing seems like a roundabout way to run `clone`.  Why have both if they do the same thing?

BTW, sorry for all the issues tonight.  I'm doing some testing before I decide whether to migrate my infrastructure this week or wait for you to tag 1.0.

**Comment by skarekrow** [comment]
I can't remember if I did anything that separates them, but if I did this a bug because yes I intend them to be identical. 

Some people just want to quickly clone a a jail and destroy it and others prefer to have a static template. So both exist. 

The issues are OK I promise haha. It only causes minimal tears on my part now. I was talking with @araujobsd actually and he suggested making you the official triage person for the project. Would you be open to contributing in that fashion? I've noted you've tested iocage in a myriad of odd configurations and it's highlighted a lot of issues.

Would be nice to have somebody to possibly even say "Yes Brandon, this release is OK to tag and you haven't messed things up any worse then they were!" in addition to pulling information from reporting and labeling/closing redundant tickets.

**Comment by rwestlund** [comment]
Hmm, maybe.  I'm willing to discuss it at least.  Let me know where we can chat.

**Comment by skarekrow** [comment]
For the spam bots, I recommend removing that address or changing it to something not spam friendly ;)
