### ISSUE TITLE
Duplicating a tag with clone crashes

### ISSUE THREAD

**Issue by rwestlund** [iocage/iocage#221]
Using HEAD (25727df28a8711d4f8dd413f912f04a1f2a36dc0):
```
root@r2d2 /u/h/randy# iocage create -n test -r 11.0-RELEASE
test (test) successfully created!

root@r2d2 /u/h/randy# iocage clone test tag=test
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/clone.py", line 77, in cli
    uuid=_uuid, clone=True)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 503, in create
    silent=self.silent).create_jail()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_create.py", line 82, in create_jail
    return self._create_jail(jail_uuid, location)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_create.py", line 304, in _create_jail
    _tag = self.create_link(jail_uuid, config["tag"])
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_create.py", line 529, in create_link
    if len(m) == 36 or len(m) == 8][0]
IndexError: list index out of range
```

**Comment by skarekrow** [comment]
I think the root cause in #220 is likely at play here as well.

**Comment by skarekrow** [comment]
As I suspected, fixing #220 fixed this as well 👍 
```
╰─ iocage create -n test -r 11.0-RELEASE
test (test) successfully created!
╰─ iocage clone test tag="test"

  tag: "test" in use by test!
  Renaming 9dfb8890-2334-42d0-88f7-474fa0e39978's tag to 2017-06-28@06:30:28:272926.

9dfb8890-2334-42d0-88f7-474fa0e39978 (2017-06-28@06:30:28:272926) successfully cloned!
```
