### ISSUE TITLE
unable to *automatically* create a jail

### ISSUE THREAD

**Issue by igalic** [iocage/iocage#234]
I'm running `iocage` version `0.9.9-ALPHA`, and trying to integrate it with puppet, that means that commands such as:

```
~ # /usr/local/bin/iocage create --force --release=11.0-RELEASE --pkglist=/tmp/puppet-iocage-pkglist.json20170630-81422-c4l764 ip4_addr='vtnet0|172.16.0.2/12' template=yes tag=f11-apache2
6e78c938-cdf3-4ea7-b335-f632678547a1 (f11-apache2) successfully created!
Testing SRV response to FreeBSD
Testing DNSSEC response to FreeBSD

Installing pkg... 
Installing supplied packages:
  - puppet4... 
===> Creating groups.
…etc…
```

are run via `exec`, resulting in:

```
Error: /Stage[main]/Profile::Jail/Jail[f11-apache24]: Could not evaluate: Execution of '/usr/local/bin/iocage create --force --release=11.0-RELEASE --pkglist=/tmp/puppet-iocage-pkglist.json20170630-81422-c4l764 ip4_addr='vtnet0|172.16.0.2/12' template=yes tag=f11-apache24' returned 1: Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/create.py", line 171, in cli
    empty=empty)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 524, in create
    silent=self.silent).create_jail()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_create.py", line 85, in create_jail
    return self._create_jail(jail_uuid, location)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_create.py", line 132, in _create_jail
    for line in r:
  File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 47: ordinal not in range(128)
```

i have no idea how to properly track that down, so… uhm… help.

**Comment by skarekrow** [comment]
Well I'm not sure what the issue you're having yet is, what's the `pkglist` look like?

**Comment by igalic** [comment]
```json
{"pkgs":[“puppet4","apache24"]}
```

**Comment by igalic** [comment]
oohh
i just realised what might have caused this

puppet, but default, runs things under the `C` locale, and this could be very wrong in our case!

-----
I'm in bed right now, but will track this down tomorrow morning

**Comment by skarekrow** [comment]
That's definitely going to be an issue, UTF-8 is required. I'll wait to see what you report back with before I dig into this any further 👍

**Comment by igalic** [comment]
so, yes, can confirm locale was the cause.
would be cool if we had a global(?) exception catch for Unicode errors, to inform users of this.
but im not sure how possible that is.

**Comment by skarekrow** [comment]
I do have one, if I recall I have two actually. Not sure how this is calling it to avoid it but perhaps a PR or something if you stumble on the solution would be great!
