### ISSUE TITLE
Impossible to retag or destroy a jail if there are duplicate tags

### ISSUE THREAD

**Issue by bravesirrobin81** [iocage/iocage#238]
I've ended up in a situation whereby I have two jails with the same tag. It seems impossible to retag or destroy them. This is with latest master.

To reproduce, create a tagged jail. Then import another jail from an image with the same tag. 

```
+-----+----------+-------+--------------+--------------+-----------+
| JID |   UUID   | STATE |     TAG      |   RELEASE    |    IP4    |
+=====+==========+=======+==============+==============+===========+
| -   | cd33d544 | down  | ansible-base | 11.0-RELEASE | 10.1.1.20 |
+-----+----------+-------+--------------+--------------+-----------+
| 1   | 9215e0f1 | up    | ansible-base | 11.0-RELEASE | 10.1.1.31 |
+-----+----------+-------+--------------+--------------+-----------+

[root@fimbrethil ~/iocage]# iocage set tag=NewTag 921
Duplicate tag (ansible-base) detected!
  9215e0f1-8966-47dc-80db-1528be8ad46e (ansible-base)
  cd33d544-d3b8-4724-95d7-e3b9a7683b4e (ansible-base)

Please run "iocage set tag=NEWTAG UUID" for one of the UUID's.

Please run "iocage set tag=NEWTAG UUID" for one of the UUID's.
[root@fimbrethil ~/iocage]# iocage set tag=NewTag cd3
Duplicate tag (ansible-base) detected!
  9215e0f1-8966-47dc-80db-1528be8ad46e (ansible-base)
  cd33d544-d3b8-4724-95d7-e3b9a7683b4e (ansible-base)

Please run "iocage set tag=NEWTAG UUID" for one of the UUID's.

Please run "iocage set tag=NEWTAG UUID" for one of the UUID's.
[root@fimbrethil ~/iocage]# iocage destroy cd3

This will destroy jail cd3

Are you sure? [y/N]: y
Duplicate tag (ansible-base) detected!
  9215e0f1-8966-47dc-80db-1528be8ad46e (ansible-base)
  cd33d544-d3b8-4724-95d7-e3b9a7683b4e (ansible-base)

Please run "iocage set tag=NEWTAG UUID" for one of the UUID's.
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/destroy.py", line 62, in cli
    ioc.IOCage(jail, skip_jails=True).destroy_jail()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 604, in destroy_jail
    tag, uuid, path = self.__check_jail_existence__()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 198, in __check_jail_existence__
    _jail = {tag: uuid for (tag, uuid) in self.jails.items() if
AttributeError: 'IOCage' object has no attribute 'jails'
[root@fimbrethil ~/iocage]# 
```

Make sure to follow and check these boxes before submitting an issue! Thank you.

- [ x] Supply `iocage --version`
- [ x] Supply the commands used, along with any steps to recreate it.
- [ x] Provide the output from the command you issued.
- [ x] Supply what you expected the result or output to be
- [ x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by skarekrow** [comment]
Heh that's a fun one. In the mean time use the UUID to destroy it.

**Comment by bravesirrobin81** [comment]
That doesn't work either! See the command output.

**Comment by skarekrow** [comment]
Bah you're right I totally missed that wasn't a tag
