### ISSUE TITLE
Error while destroying old jail

### ISSUE THREAD

**Issue by root-ua** [iocage/iocage#251]
iocage: ```Version 0.9.8.1 05/23/2017``` (installed via PKG)
base systme: ```FreeBSD cluster 11.0-RELEASE-p9 FreeBSD 11.0-RELEASE-p9 #0: Tue Apr 11 08:48:40 UTC 2017 root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC amd64```

Trying to delete my old jail using command:
```bash
# iocage list
+-----+----------+-------+------+--------------+----------------+
| JID |   UUID   | STATE | TAG  |   RELEASE    |      IP4       |
+=====+==========+=======+======+==============+================+
| -   | e322ccf4 | down  | voip | 10.3-RELEASE | 10.100.0.11 |
+-----+----------+-------+------+--------------+----------------+

# iocage destroy e322ccf4

This will destroy jail e322ccf4-5fd9-11e6-811c-485b3977a95d (voip)

Are you sure? [y/N]: y
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 149, in json_load
    with open(self.location + "/config.json", "r") as conf:
FileNotFoundError: [Errno 2] No such file or directory: 'none/config.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/destroy.py", line 97, in cli
    ioc_destroy.IOCDestroy().destroy_jail(path)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_destroy.py", line 181, in destroy_jail
    f"{self.pool}/iocage/{dataset_type}/{uuid}")
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_destroy.py", line 153, in __destroy_parse_datasets__
    self.__stop_jails__(datasets, path, root)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_destroy.py", line 40, in __stop_jails__
    conf = iocage.lib.ioc_json.IOCJson(_path).json_load()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 240, in json_load
    self.json_convert_from_zfs(uuid, skip=skip)
UnboundLocalError: local variable 'uuid' referenced before assignment

# ll /iocage/jails/e322ccf4-5fd9-11e6-811c-485b3977a95d/config.json
-rw-r--r--  1 root  wheel   2.7K Jul  6 14:54 /iocage/jails/e322ccf4-5fd9-11e6-811c-485b3977a95d/config.json

# cat /iocage/jails/e322ccf4-5fd9-11e6-811c-485b3977a95d/config.json
{
    "CONFIG_VERSION": "6",
    "allow_chflags": "1",
    "allow_mount": "1",
    "allow_mount_devfs": "1",
    "allow_mount_nullfs": "1",
    "allow_mount_procfs": "1",
    "allow_mount_tmpfs": "1",
    "allow_mount_zfs": "1",
    "allow_quotas": "1",
    "allow_raw_sockets": "1",
    "allow_set_hostname": "1",
    "allow_socket_af": "1",
    "allow_sysvipc": "1",
    "basejail": "no",
    "boot": "off",
    "children_max": "0",
    "cloned_release": "10.3-RELEASE",
    "comment": "none",
    "coredumpsize": "off",
    "cpuset": "off",
    "cputime": "off",
    "datasize": "off",
    "defaultrouter": "none",
    "defaultrouter6": "none",
    "devfs_ruleset": "4",
    "enforce_statfs": "2",
    "exec_clean": "1",
    "exec_fib": "0",
    "exec_jail_user": "root",
    "exec_poststart": "/usr/bin/true",
    "exec_poststop": "/usr/bin/true",
    "exec_prestart": "/usr/bin/true",
    "exec_prestop": "/usr/bin/true",
    "exec_start": "/etc/init.d/rc 3",
    "exec_stop": "/etc/init.d/rc 0",
    "exec_system_jail_user": "0",
    "exec_system_user": "root",
    "exec_timeout": "60",
    "gitlocation": "https://github.com",
    "hack88": "0",
    "host_domainname": "none",
    "host_hostname": "e322ccf4-5fd9-11e6-811c-485b3977a95d",
    "host_hostuuid": "e322ccf4-5fd9-11e6-811c-485b3977a95d",
    "host_time": "yes",
    "hostid": "a10442c0-fedb-11d5-8cb1-7c7d9cb71879",
    "interfaces": "vnet0:bridge0,vnet1:bridge1",
    "ip4": "new",
    "ip4_addr": "msk0|10.100.0.11/27",
    "ip4_autoend": "none",
    "ip4_autostart": "none",
    "ip4_autosubnet": "none",
    "ip4_saddrsel": "1",
    "ip6": "new",
    "ip6_addr": "none",
    "ip6_saddrsel": "1",
    "jail_zfs": "off",
    "jail_zfs_dataset": "iocage/jails/e322ccf4-5fd9-11e6-811c-485b3977a95d/data",
    "last_started": "2016-08-17_21:04:09",
    "login_flags": "-f root",
    "maxproc": "off",
    "memorylocked": "off",
    "memoryuse": "8G:log",
    "mount_devfs": "1",
    "mount_fdescfs": "1",
    "mount_procfs": "1",
    "msgqqueued": "off",
    "msgqsize": "off",
    "nmsgq": "off",
    "notes": "none",
    "nsemop": "off",
    "nshm": "off",
    "nthr": "off",
    "openfiles": "off",
    "owner": "root",
    "pcpu": "off",
    "priority": "99",
    "pseudoterminals": "off",
    "release": "10.3-RELEASE-p6",
    "resolver": "none",
    "rlimits": "off",
    "securelevel": "2",
    "shmsize": "off",
    "stacksize": "off",
    "stop_timeout": "30",
    "swapuse": "off",
    "sync_target": "none",
    "sync_tgt_zpool": "none",
    "sysvmsg": "new",
    "sysvsem": "new",
    "sysvshm": "new",
    "tag": "voip",
    "template": "no",
    "type": "jail",
    "vmemoryuse": "off",
    "vnet": "off",
    "vnet0_mac": "none",
    "vnet1_mac": "none",
    "vnet2_mac": "none",
    "vnet3_mac": "none",
    "wallclock": "off"
}
```

**Comment by skarekrow** [comment]
When you say old, which version do you mean? Can you please try `master` and see if this has been resolved?

**Comment by zachfi** [comment]
I am seeing this issue upgrading from `iocage-1.7.6`.

**Comment by joachimmathes** [comment]
I can confirm this in version `3dfd6b7a93d7c1b727ddd2d124e9c8f0c71fcb24`. As a workaround I

* `cd /iocage/jails/<UUID>`
* run `mkdir legacy`
* run `cp config.json legacy/`
* run `iocage destroy <UUID>`

and it works.

**Comment by stratacast** [comment]
I am having the same problem with iocage version 0.9.8.1 too. FreeBSD 11.0-RELEASE-p11, amd64 and grabbed with pkg

**Comment by stratacast** [comment]
I tried this yet again on the same machine (no updates have been applied or anything to this system since previous testing) and suddenly my problems have gone away. I can iocage destroy and restart, where before I couldn't. But I'm wondering if the error lies in the ioc_destroy.py script "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_destroy.py". Perhaps if one could put in the uuid of the jail they wish to destroy where "uuid" is set as a new variable:

* Line 33
* Line 46
* Line 172

Then run iocage destroy again and see if that works

**Comment by stratacast** [comment]
I have found the error comes in the ioc_destroy.py file in the path "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_destroy.py"

There is a reference to "uuid" before it is assigned (references can be found at lines 33, 46, and 172.

I took the uuid of the jail I wished to destroy and placed it at line 33 and issued "iocage destroy" again and it successfully destroyed the jail. It appears the variable creation of "uuid" works successfully at lines 46 and 172 since I didin't have to mess with those

**Comment by skarekrow** [comment]
Quite a lot has changed, I can't recreate this in `master` so I'm going to close it. Thanks for the additional debug, if it crops up again that should be helpful.

**Comment by zachfi** [comment]
@skarekrow Should we expect a release any time soon for this?  I've got piles of jails, some duplicates, that I can't destroy currently.

**Comment by skarekrow** [comment]
@xaque208 Yeah I've mentioned it in a couple places, but I'm currently shooting for Friday as a release. Got a couple things left to do outside iocage and then a few bugs here I'd like gone for a release. 

But if you're using pkg it will be sometime next week, @araujobsd is ready to go, but the pkgs have to be built :)

**Comment by zachfi** [comment]
@skarekrow No trouble, I build my own packages, so whenever the port is updated, I can upgrade.
