### ISSUE TITLE
iocage clone broken by TAG removal

### ISSUE THREAD

**Issue by rwestlund** [iocage/iocage#261]
Using HEAD (b7093109ce517668480f0091c2177eb61e8eb81d):

```
root@r2d2 /u/h/randy# iocage create -n test -r 11.0-RELEASE
test successfully created!

root@r2d2 /u/h/randy# iocage clone test
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/clone.py", line 62, in cli
    _uuid=_uuid, clone=True)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 482, in create
    _, clone_uuid, _ = self.__check_jail_existence__()
ValueError: not enough values to unpack (expected 3, got 2)

root@r2d2 /u/h/randy# iocage clone -n test2 test
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/clone.py", line 62, in cli
    _uuid=_uuid, clone=True)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 482, in create
    _, clone_uuid, _ = self.__check_jail_existence__()
ValueError: not enough values to unpack (expected 3, got 2)
```

Looks like the number of arguments doesn't match anymore.

**Comment by skarekrow** [comment]
That missed all my searches for mass changes ;)

Nice catch.
