### ISSUE TITLE
child_test() breaks destroying by partial uuid

### ISSUE THREAD

**Issue by rwestlund** [iocage/iocage#271]
Using HEAD (bb3cbf02f8d3b11fb5e4a80769b7818b0e43ff51):

Breakage from 96be5d85bf492f2fb32987b05210e9aba53f5f45.

```
root@r2d2 /u/h/randy# iocage create -r 11.0-RELEASE
ab64b0ba-fb56-47ef-a79c-f69c2394622c successfully created!

root@r2d2 /u/h/randy# iocage destroy ab64

This will destroy jail ab64

Are you sure? [y/N]: y
/iocage/jails/ab64/root: No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/destroy.py", line 108, in cli
    child_test(zfs, iocroot, jail, "jail", force=force)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/destroy.py", line 44, in child_test
    children = zfs.get_dataset_by_path(path).snapshots_recursive
  File "libzfs.pyx", line 614, in libzfs.ZFS.get_dataset_by_path (libzfs.c:19772)
libzfs.ZFSException: Dataset with path /iocage/jails/ab64/root not found
```

**Comment by rwestlund** [comment]
@skarekrow not quite there.  Using HEAD (486b4853993094b71ad74315f966dff9e4ae363f):

```
root@r2d2 /u/h/r/a/s/jails# iocage list
+-----+----------+-------+--------------+-----+
| JID |   NAME   | STATE |   RELEASE    | IP4 |
+=====+==========+=======+==============+=====+
| -   | 52a66565 | down  | 11.0-RELEASE | -   |
+-----+----------+-------+--------------+-----+

root@r2d2 /u/h/r/a/s/jails# iocage destroy 52a

This will destroy jail 52a

Are you sure? [y/N]: y
Partial UUID/NAME supplied, cannot check for dependant jails.

Proceed? [y/N]: y
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/destroy.py", line 124, in cli
    child_test(zfs, iocroot, jail, "jail", force=force)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/destroy.py", line 62, in child_test
    for child in children:
UnboundLocalError: local variable 'children' referenced before assignment

```

**Comment by skarekrow** [comment]
51e4265cf032d7895749dab315607ecfd4b984c5 Fixed this time ;) That last renaming triggered this again.
