### ISSUE TITLE
iocage create fails to create either jails or templates (HEAD)

### ISSUE THREAD

**Issue by igalic** [iocage/iocage#288]
creating a jail or template no longer works (i'm not sure if for the same reason)

```
~ # /usr/local/bin/iocage create --pkglist /tmp/puppet-iocage.pkglist20170716-18198-j7t54n --release 11.0-RELEASE --name php71 template=yes ip4_addr='vtnet0|172.16.0.2/12'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 190, in json_load
    with open(self.location + "/config.json", "r") as conf:
FileNotFoundError: [Errno 2] No such file or directory: '/iocage/jails/php71/config.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/create.py", line 140, in cli
    basejail=basejail, empty=empty)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 521, in create
    silent=self.silent).create_jail()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_create.py", line 84, in create_jail
    return self._create_jail(jail_uuid, location)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_create.py", line 289, in _create_jail
    iocjson.json_set_value("template=yes")
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 439, in json_set_value
    conf = self.json_load()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 278, in json_load
    self.json_convert_from_zfs(uuid, skip=skip)
UnboundLocalError: local variable 'uuid' referenced before assignment
~ #
```

```
~ # /usr/local/bin/iocage create --pkglist /tmp/puppet-iocage.pkglist20170716-18198-j7t54n --release 11.0-RELEASE --name blag  ip4_addr='vtnet0|172.16.1.2/12'
blag successfully created!
Testing SRV response to FreeBSD
Testing DNSSEC response to FreeBSD

Installing pkg... 
jexec: jail_attach(20): Not a directory
Installing supplied packages:
  - puppet4... 
jexec: jail_attach(20): Not a directory
  - apache24... 
jexec: jail_attach(20): Not a directory
  - php71... 
jexec: jail_attach(20): Not a directory
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/create.py", line 140, in cli
    basejail=basejail, empty=empty)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 521, in create
    silent=self.silent).create_jail()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_create.py", line 84, in create_jail
    return self._create_jail(jail_uuid, location)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_create.py", line 382, in _create_jail
    self.create_install_packages(jail_uuid, location, config)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_create.py", line 511, in create_install_packages
    os.remove(f"{location}/root/etc/resolv.conf")
FileNotFoundError: [Errno 2] No such file or directory: '/iocage/jails/blag/root/etc/resolv.conf'
~ #
```

`iocage list -l` gives us the same error as the template create:

```
~ # iocage list -l
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 190, in json_load
    with open(self.location + "/config.json", "r") as conf:
FileNotFoundError: [Errno 2] No such file or directory: '/iocage/jails/php71/config.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/list.py", line 74, in cli
    plugin=plugins, quick=quick)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 889, in list
    plugin=plugin, quick=quick).list_datasets()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_list.py", line 72, in list_datasets
    _all = self.list_all(ds)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_list.py", line 149, in list_all
    conf = iocage.lib.ioc_json.IOCJson(mountpoint).json_load()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 278, in json_load
    self.json_convert_from_zfs(uuid, skip=skip)
UnboundLocalError: local variable 'uuid' referenced before assignment
```

but not `iocage list -lt`:

```
~ # iocage list -lt
+-----+------+------+-------+------+---------+-----+-----+----------+
| JID | NAME | BOOT | STATE | TYPE | RELEASE | IP4 | IP6 | TEMPLATE |
+=====+======+======+=======+======+=========+=====+=====+==========+
+-----+------+------+-------+------+---------+-----+-----+----------+
~ #
```

**Comment by skarekrow** [comment]
I can't reproduce this:
```
╰─iocage create -n test -r 11.0-RELEASE --pkglist pkg.json ip4_addr="vtnet0|192.168.1.70"
test successfully created!
Testing SRV response to FreeBSD
Testing DNSSEC response to FreeBSD

Installing pkg...
Installing supplied packages:
  - nginx...
===> Creating groups.
Using existing group 'www'.
===> Creating users
Using existing user 'www'.
Message from nginx-1.12.1,2:
===================================================================
Recent version of the NGINX introduces dynamic modules support.  In
FreeBSD ports tree this feature was enabled by default with the DSO
knob.  Several vendor's and third-party modules have been converted
to dynamic modules.  Unset the DSO knob builds an NGINX without
dynamic modules support.

To load a module at runtime, include the new `load_module'
directive in the main context, specifying the path to the shared
object file for the module, enclosed in quotation marks.  When you
reload the configuration or restart NGINX, the module is loaded in.
It is possible to specify a path relative to the source directory,
or a full path, please see
https://www.nginx.com/blog/dynamic-modules-nginx-1-9-11/ and
http://nginx.org/en/docs/ngx_core_module.html#load_module for
details.

Default path for the NGINX dynamic modules is

/usr/local/libexec/nginx.
===================================================================


===>   NOTICE:

The nginx port currently does not have a maintainer. As a result, it is
more likely to have unresolved issues, not be up-to-date, or even be removed in
the future. To volunteer to maintain this port, please create an issue at:

https://bugs.freebsd.org/bugzilla

More information about port maintainership is available at:

https://www.freebsd.org/doc/en/articles/contributing/ports-contributing.html#maintain-port
  - tmux...
╰─ cat pkg.json
{
    "pkgs": [
    "nginx",
    "tmux"
    ]
}
```

Which HEAD, and make sure your datasets are mounted with `zfs mount -a`. But something is missing it's configuration, so the more information you can give the better.

**Comment by rwestlund** [comment]
@skarekrow try running that command with `template=yes`.

**Comment by skarekrow** [comment]
Ah I missed that prop. I'll circle back to this later and see

**Comment by skarekrow** [comment]
Yeah more TAG removal fallout. Should be simple to fix. I'll get that done later :) thanks for the issue @igalic

**Comment by igalic** [comment]
\o/

all is well now! thank you so much!!

**Comment by skarekrow** [comment]
Yay!
