### ISSUE TITLE
Jail is created but in the process some error regarding '/etc/localtime' is not found appears. 

### ISSUE THREAD

**Issue by petri8** [iocage/iocage#296]
Version	0.9.8.1 05/23/2017
root@hostname:/home/petri8 # iocage create -b -r 11.0-RELEASE boot=on
729df3ec-81ff-42ed-891b-5f01487cf6a9 (2017-07-20@13:43:34:402429) successfully created!
* Starting 729df3ec-81ff-42ed-891b-5f01487cf6a9 (2017-07-20@13:43:34:402429)
  + Started OK
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/create.py", line 89, in cli
    empty=empty)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 456, in create
    silent=self.silent).create_jail()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_create.py", line 58, in create_jail
    return self._create_jail(jail_uuid, location)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_create.py", line 303, in _create_jail
    silent=self.silent)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_start.py", line 35, in __init__
    self.__start_jail__()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_start.py", line 317, in __start_jail__
    self.start_copy_localtime()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_start.py", line 512, in start_copy_localtime
    f"{self.path}/root/etc/localtime")
  File "/usr/local/lib/python3.6/shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/localtime'

iocage list 
+-----+----------+-------+----------------------------+--------------+-----+
| JID |   UUID   | STATE |            TAG             |   RELEASE    | IP4 |
+=====+==========+=======+============================+==============+=====+
| 5   | 729df3ec | up    | 2017-07-20@13:43:34:402429 | 11.0-RELEASE | -   |
+-----+----------+-------+----------------------------+--------------+-----+

Found the problem: 
 I don't have local time set.
It's how the server image  came from amazon aws.

tzsetup --	set local timezone    puts the time in  /etc/localtime		   current time	zone file

Fixed by running :  "tzsetup"

**Comment by skarekrow** [comment]
Dup of #208
