### ISSUE TITLE
iocage not fetching releases on release candidate versions of the operating system.

### ISSUE THREAD

**Issue by Infiniverse** [iocage/iocage#300]
Version	0.9.8.1 05/23/2017

I'm running iocage on FreeBSD 10.3-RC3.
The shell version worked just fine, but the new python version is stumbling:

    [systems@host ~/.ansible/tmp/ansible-tmp-1501085084.85-102923486802315/debug_dir]$ python2.7 ansible_module_iocage.py < args 
    Traceback (most recent call last):
      File "ansible_module_iocage.py", line 678, in <module>
        main()
      File "ansible_module_iocage.py", line 494, in main
        release = re.match('(\d+\.\d+\-RELEASE).*',out.strip()).group(1)
    AttributeError: 'NoneType' object has no attribute 'group'

**Comment by Infiniverse** [comment]
Sorry -- this is clearly an issue with the ansible iocage module, and not iocage itself!
