### ISSUE TITLE
iocage fetch: regression in --release (tqdm breaks API in minor release)

### ISSUE THREAD

**Issue by igalic** [iocage/iocage#302]
version 0.9.9-ALPHA (7cc997bb2103c64500896bdab9376045b8619e67)

when trying to fetch a release non-interactively, i'm running into the following failure:

```
~ # iocage fetch --release 11.0-RELEASE
Fetching: 11.0-RELEASE

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 95, in cli
    ioc.IOCage().fetch(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 754, in fetch
    ioc_fetch.IOCFetch(release, **kwargs).fetch_release()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 264, in fetch_release
    self.fetch_ftp_release(eol, _list=_list)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 474, in fetch_ftp_release
    self.fetch_download(ftp_list, ftp=True)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 701, in fetch_download
    unit_scale="mega")
  File "/usr/local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 777, in __init__
    self.postfix, unit_divisor))
  File "/usr/local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 293, in format_meter
    frac = n / total
TypeError: unsupported operand type(s) for /: 'str' and 'str'
```

this error also occurs in the interactive mode, so it suggests it's a general one:

```
~ # iocage fetch 
[0] 9.3-RELEASE (EOL)
[1] 10.1-RELEASE (EOL)
[2] 10.2-RELEASE (EOL)
[3] 10.3-RELEASE
[4] 11.0-RELEASE
[5] 11.1-RELEASE

Type the number of the desired RELEASE
Press [Enter] to fetch the default selection: (11.0-RELEASE)
Type EXIT to quit: 5
Fetching: 11.1-RELEASE

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 95, in cli
    ioc.IOCage().fetch(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 754, in fetch
    ioc_fetch.IOCFetch(release, **kwargs).fetch_release()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 264, in fetch_release
    self.fetch_ftp_release(eol, _list=_list)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 474, in fetch_ftp_release
    self.fetch_download(ftp_list, ftp=True)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 701, in fetch_download
    unit_scale="mega")
  File "/usr/local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 777, in __init__
    self.postfix, unit_divisor))
  File "/usr/local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 293, in format_meter
    frac = n / total
TypeError: unsupported operand type(s) for /: 'str' and 'str'
```

**Comment by igalic** [comment]
i;ve extracted the logic (at least in the ftp bit) for readability:
https://gist.github.com/2b399079ab24c0d99ca55e556bf010c4

anyway, a bit more info: that first invocation creates an empty `MANIFEST` file. a second invocation creates an empty `base.txz`, and then fails on the SHA256 validation (unsurprisingly ;)

```
~ # iocage fetch --release 11.0-RELEASE
Fetching: 11.0-RELEASE

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 95, in cli
    ioc.IOCage().fetch(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 754, in fetch
    ioc_fetch.IOCFetch(release, **kwargs).fetch_release()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 264, in fetch_release
    self.fetch_ftp_release(eol, _list=_list)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 475, in fetch_ftp_release
    missing = self.__fetch_check__(ftp_list, ftp=True)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 566, in __fetch_check__
    if hashes[f] != sha256.hexdigest():
KeyError: 'base.txz'
```

**Comment by igalic** [comment]
i should point out that `-h` fails in the same way, which means it's gotta be something higher up the call hierarchy.

**Comment by igalic** [comment]
(guess what's a real fun learning experience? stepping thru a giant program with `pdb`)

****
(i have no idea what i'm doing lol)

**Comment by skarekrow** [comment]
I can't reproduce this:
```
╰─ iocage fetch
[0] 9.3-RELEASE (EOL)
[1] 10.1-RELEASE (EOL)
[2] 10.2-RELEASE (EOL)
[3] 10.3-RELEASE
[4] 11.0-RELEASE
[5] 11.1-RELEASE

Type the number of the desired RELEASE
Press [Enter] to fetch the default selection: (11.1)
Type EXIT to quit: 0
Fetching: 9.3-RELEASE

Downloading: MANIFEST: 100% 4.44Kbit/s Elapsed: 00:00 Remaining: 00:00
Downloading: base.txz: 100% 1.98Mbit/s Elapsed: 00:35 Remaining: 00:00
Downloading: lib32.txz: 100% 1.69Mbit/s Elapsed: 00:07 Remaining: 00:00
Downloading: doc.txz: 100% 1.15Mbit/s Elapsed: 00:01 Remaining: 00:00
Extracting: base.txz...
Extracting: lib32.txz...
Extracting: doc.txz...

* Updating 9.3-RELEASE to the latest patch level...
-- snip --
```

It may be something in your environment, if you can give me exact reproduction steps, I'll reopen.

**Comment by igalic** [comment]
@skarekrow, i cannot ***not*** reproduce this.

please note that by now i've blown away `/usr/local/lib/python3.6` and reinstalled it to be sure.

something **is** wrong here.

****

```cd /usr/local ; find . -type f -name \*.pyc -delete```
result: still the same.

****
potentially cleaner:
```
~ # find /usr/ /lib/ -type d -name __pycache__ | xargs rm -rf                                                                                      
~ # iocage clean -af                
Cleaning iocage/templates                                                                                                                          
Cleaning iocage/releases                                                 
Cleaning iocage/log                                                                                                                                
Cleaning iocage/jails                                                    
Cleaning iocage/images                                                                                                                             
Cleaning iocage/download                                                 
Cleaning iocage                                                                                                                                    
All iocage datasets have been destroyed.                                 
~ # iocage list -lr                                                                                                                                
Creating jails/iocage/download      
Creating jails/iocage/images                                                                                                                       
Creating jails/iocage/jails         
Creating jails/iocage/log                                                
Creating jails/iocage/releases      
Creating jails/iocage/templates     
+---------------+                   
| Bases fetched |                   
+===============+                   
+---------------+                   
~ # iocage fetch -r 11.0-RELEASE    
Fetching: 11.0-RELEASE              

Traceback (most recent call last):  
  File "/usr/local/bin/iocage", line 10, in <module>                     
    sys.exit(cli())                 
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__                                                               
    return self.main(*args, **kwargs)                                    
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main                                                                   
    rv = self.invoke(ctx)           
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke                                                                
    return _process_result(sub_ctx.command.invoke(sub_ctx))              
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke                                                                 
    return ctx.invoke(self.callback, **ctx.params)                       
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke                                                                 
    return callback(*args, **kwargs)                                     
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 95, in cli                                                               
    ioc.IOCage().fetch(**kwargs)    
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 754, in fetch                                                           
    ioc_fetch.IOCFetch(release, **kwargs).fetch_release()                
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 264, in fetch_release                                                
    self.fetch_ftp_release(eol, _list=_list)                             
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 474, in fetch_ftp_release                                            
    self.fetch_download(ftp_list, ftp=True)                              
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 701, in fetch_download                                               
    unit_scale="mega")              
  File "/usr/local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 777, in __init__                                                               
    self.postfix, unit_divisor))    
  File "/usr/local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 293, in format_meter                                                           
    frac = n / total                
TypeError: unsupported operand type(s) for /: 'str' and 'str'            

```

**Comment by skarekrow** [comment]
I'm not sure what's causing the issue for you.

Perhaps you should post a `pip3.6 freeze`? If you notice your errors, you have two different ones in the posts you've made. One would be upstream(tqdm) and the other a KeyError. Which is odd as that file is always apart of the dictionary.

I'm not disputing you have an issue, but until I can reproduce this, I won't be reopening the ticket. As I posted, it works for me, and presumably many others as there aren't a million +1's here ;)

Instead of blowing away that directory, try using virtualenvs and see how you make out. Something is clearly interfering, and my guess is some new version of a dependency.

Here's my list, note that I use this for other things, so somethings aren't necessary:
```
apipkg==1.4
certifi==2017.4.17
cffi==1.9.1
chardet==3.0.3
click==6.7
coloredlogs==7.0
colorlog==2.10.0
coverage==4.3.4
Cython==0.25.2
execnet==1.4.1
flake8==3.3.0
gitdb2==2.0.0
GitPython==2.1.3
hgtools==6.3
humanfriendly==3.2
idna==2.5
libzfs==1.0
mccabe==0.6.1
mock==2.0.0
pbr==2.1.0
pep8==1.7.0
py==1.4.33
pycodestyle==2.3.1
pycparser==2.17
pyflakes==1.5.0
pygit2==0.25.1
pyrapidjson==0.5.1
pytest==3.0.7
pytest-cache==1.0
pytest-cov==2.4.0
pytest-pep8==1.0.6
pytest-runner==2.11.1
requests==2.17.3
six==1.10.0
smmap2==2.0.1
stevedore==1.21.0
texttable==0.9.0
tqdm==4.14.0
urllib3==1.21.1
verboselogs==1.6
virtualenv==15.1.0
virtualenv-clone==0.2.6
virtualenvwrapper==4.7.2
```

**Comment by igalic** [comment]
here's my list, same caveat applies
```
apipkg==1.4
bleach==2.0.0
certifi==2017.7.27.1
cffi==1.10.0
chardet==3.0.4
click==6.7
coloredlogs==7.1
coverage==4.4.1
Cython==0.26
decorator==4.1.2
entrypoints==0.2.3
execnet==1.4.1
html5lib==0.999999999
humanfriendly==4.4
idna==2.5
iocage==0.9.9
ipykernel==4.6.1
ipython==6.1.0
ipython-genutils==0.2.0
ipywidgets==6.0.0
jedi==0.10.2
Jinja2==2.9.6
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.1.0
jupyter-console==5.1.0
jupyter-core==4.3.0
libzfs==1.0
MarkupSafe==1.0
mistune==0.7.4
nbconvert==5.2.1
nbformat==4.3.0
notebook==5.0.0
pandocfilters==1.4.1
pep8==1.7.0
pexpect==4.2.1
pickleshare==0.7.4
prompt-toolkit==1.0.15
ptyprocess==0.5.2
py==1.4.34
pycparser==2.18
pygit2==0.26.0
Pygments==2.2.0
pytest==3.1.3
pytest-cache==1.0
pytest-cov==2.5.1
pytest-pep8==1.0.6
python-dateutil==2.6.1
pyzmq==16.0.2
qtconsole==4.3.0
requests==2.18.2
simplegeneric==0.8.1
six==1.10.0
terminado==0.6
testpath==0.3.1
texttable==0.9.1
tornado==4.5.1
tqdm==4.15.0
traitlets==4.3.2
ucl==0.8
urllib3==1.22
verboselogs==1.6
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==2.0.0
```

**Comment by skarekrow** [comment]
Try downgrading tqdm to 4.14

**Comment by igalic** [comment]
that fixed the issue.

is there a way to work-around this issue by disabling the use tqdm? especially useful for non-interactive use

**Comment by skarekrow** [comment]
I'll think about it. In the meantime please open an issue on his tracker and link to here. He should know there's been a regression.

**Comment by igalic** [comment]
@skarekrow done. https://github.com/tqdm/tqdm/issues/415

**Comment by skarekrow** [comment]
Appreciate it @igalic :+1:

**Comment by casperdcl** [comment]
Thanks for opening the issue with us; as mentioned `unit_scale` has never supported a `str` (see issue discussion tqdm/tqdm#415).

**Comment by skarekrow** [comment]
@casperdcl awesome! I'll look into fixing my end then soon. Sorry for the noise :+1:

**Comment by casperdcl** [comment]
No worries, let me know if this fixes it for you.

> I suppose you need either `unit_scale=True` or `unit="Mb", unit_scale=2**20`

We have 100% coverage for our code so any "regression" issues should (hopefully) only be related to non-standard usage.
