### ISSUE TITLE
Nothing works on FreeBSD 11.1

### ISSUE THREAD

**Issue by Peter2121** [iocage/iocage#303]
Version 0.9.8.1 (from packages) on FreeBSD 11.1.
Problems with fetching the last version of FreeBSD, so cannot create any jail.
Does not work fetching 11.0 neither.

`
# iocage fetch -h
[0] 9.3-RELEASE (EOL)
[1] 10.1-RELEASE (EOL)
[2] 10.2-RELEASE (EOL)
[3] 10.3-RELEASE
[4] 11.0-RELEASE
[5] 11.1-RELEASE

Which release do you want to fetch? (11.1)
Type EXIT to quit: 5
Fetching: 11.1-RELEASE

Extracting: base.txz...
Extracting: lib32.txz...
Extracting: doc.txz...

* Updating 11.1-RELEASE to the latest patch level...
src component not installed, skipped
Looking up update.FreeBSD.org mirrors... 4 mirrors found.
Fetching metadata signature for 11.1-RELEASE from update6.freebsd.org... done.
Fetching metadata index... done.
Inspecting system... done.
Preparing to download files... done.

No updates needed to update system to 11.1-RELEASE-p0.
src component not installed, skipped
No updates are available to install.
Run '/tmp/tmppzmuy9ax fetch' first.

# iocage list -r
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 544, in json_check_config
    release = conf["release"]
KeyError: 'release'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/list.py", line 44, in cli
    _list = ioc.IOCage().list(dataset_type, header, _long, _sort)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 68, in __init__
    self.jails, self._paths = self.list("uuid")
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 468, in list
    return ioc_list.IOCList(lst_type, header, long, sort).list_datasets()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_list.py", line 53, in list_datasets
    conf = iocage.lib.ioc_json.IOCJson(jail).json_load()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 256, in json_load
    conf = self.json_check_config(conf, version)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 548, in json_check_config
    freebsd_version = f"{iocroot}/releases/{conf['release']}" \
KeyError: 'release'
`

**Comment by skarekrow** [comment]
I can't reproduce this on `master`.

```
╰─ iocage list -r
+---------------+
| Bases fetched |
+===============+
| 10.3-RELEASE  |
+---------------+
| 11.0-RELEASE  |
+---------------+
| 11.1-RELEASE  |
+---------------+
╰─ iocage fetch
[0] 9.3-RELEASE (EOL)
[1] 10.1-RELEASE (EOL)
[2] 10.2-RELEASE (EOL)
[3] 10.3-RELEASE
[4] 11.0-RELEASE
[5] 11.1-RELEASE

Type the number of the desired RELEASE
Press [Enter] to fetch the default selection: (11.1)
Type EXIT to quit: 0
Fetching: 9.3-RELEASE

Downloading: MANIFEST: 100% 4.44Kbit/s Elapsed: 00:00 Remaining: 00:00
Downloading: base.txz: 100% 1.98Mbit/s Elapsed: 00:35 Remaining: 00:00
Downloading: lib32.txz: 100% 1.69Mbit/s Elapsed: 00:07 Remaining: 00:00
Downloading: doc.txz: 100% 1.15Mbit/s Elapsed: 00:01 Remaining: 00:00
Extracting: base.txz...
Extracting: lib32.txz...
Extracting: doc.txz...

* Updating 9.3-RELEASE to the latest patch level...
-- snip --
╰─ iocage list -r
+---------------+
| Bases fetched |
+===============+
| 9.3-RELEASE   |
+---------------+
| 10.3-RELEASE  |
+---------------+
| 11.0-RELEASE  |
+---------------+
| 11.1-RELEASE  |
+---------------+
╰─ freebsd-version -ku
11.1-RELEASE
11.1-RELEASE
╰─ uname -a
FreeBSD HOST 11.1-RELEASE FreeBSD 11.1-RELEASE #0 r321309: Fri Jul 21 02:08:28 UTC 2017     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
```
