### ISSUE TITLE
Problem migrating from legacy iocage 1.7.6

### ISSUE THREAD

**Issue by mranner** [iocage/iocage#304]
Version 0.9.8.1 05/23/2017

iocage list

Creating tank/iocage/log
Creating tank/iocage/releases
Creating tank/iocage/templates
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/list.py", line 44, in cli
    _list = ioc.IOCage().list(dataset_type, header, _long, _sort)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 68, in __init__
    self.jails, self._paths = self.list("uuid")
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 468, in list
    return ioc_list.IOCList(lst_type, header, long, sort).list_datasets()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_list.py", line 53, in list_datasets
    conf = iocage.lib.ioc_json.IOCJson(jail).json_load()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 178, in json_load
    self.json_convert_from_zfs(full_uuid)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 70, in json_convert_from_zfs
    props = self.zfs.get_dataset(dataset).properties
  File "libzfs.pyx", line 566, in libzfs.ZFS.get_dataset (libzfs.c:18784)
libzfs.ZFSException: Dataset tank/iocage/jails/- not found

**Comment by skarekrow** [comment]
Sorry I can't reproduce this on `master`. Try it when `0.9.9` comes out.
