### ISSUE TITLE
`iocage list` broken for ordinary users if DHCP-enabled VNET jails are running

### ISSUE THREAD

**Issue by rexpo** [iocage/iocage#328]
If any DHCP-enabled VNET jails are running, then `iocage list` (and `iocage list --long`) now crap out when running them as an ordinary user. (Makes sense, as an ordinary user can't `jexec` an `ifconfig`)

- [x] Supply `iocage --version`
0.9.9.2 ALPHA updated to 97c3329
- [x] Supply the commands used, along with any steps to recreate it.
```
% sudo iocage create --name listjail --release 10.3-RELEASE vnet=on dhcp=on bpf=yes interfaces='vnet0:bridge0' host_hostname=listjail
listjail successfully created!
% iocage list
+-----+----------+-------+--------------+------+
| JID |   NAME   | STATE |   RELEASE    | IP4  |
+=====+==========+=======+==============+======+
| -   | listjail | down  | 10.3-RELEASE | DHCP |
+-----+----------+-------+--------------+------+
% iocage list --long
+-----+----------+------+-------+------+------------------+--------------------+-----+----------+
| JID |   NAME   | BOOT | STATE | TYPE |     RELEASE      |        IP4         | IP6 | TEMPLATE |
+=====+==========+======+=======+======+==================+====================+=====+==========+
| -   | listjail | off  | down  | jail | 10.3-RELEASE-p20 | DHCP (not running) | -   | -        |
+-----+----------+------+-------+------+------------------+--------------------+-----+----------+
% sudo iocage start listjail
* Starting listjail
  + Started OK
  + Starting services OK
% iocage list
```
- [x] Provide the output from the command you issued.
```
jexec: jail_attach(33): Operation not permitted
Traceback (most recent call last):
...
  File "/home/jamie/iocage/iocage/lib/ioc_list.py", line 219, in list_all
    out = su.check_output(full_ip4_cmd)
  File "/usr/local/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['jexec', 'ioc-listjail', 'ifconfig', 'vnet0', 'inet']' returned non-zero exit status 1
```
- [x] Supply what you expected the result or output to be

If we're not running as root, then we could have, for example:
```
% iocage list
+-----+----------+-------+--------------+------+
| JID |   NAME   | STATE |   RELEASE    | IP4  |
+=====+==========+=======+==============+======+
| -   | listjail | up    | 10.3-RELEASE | DHCP |
+-----+----------+-------+--------------+------+
```
and simply show `DHCP (running)` for the `--long` listing:
```
% iocage list --long
+-----+----------+------+-------+------+------------------+----------------+-----+----------+
| JID |   NAME   | BOOT | STATE | TYPE |     RELEASE      |      IP4       | IP6 | TEMPLATE |
+=====+==========+======+=======+======+==================+================+=====+==========+
| -   | listjail | off  | up    | jail | 10.3-RELEASE-p20 | DHCP (running) | -   | -        |
+-----+----------+------+-------+------+------------------+----------------+-----+----------+
```

**Comment by rexpo** [comment]
Forgot to add my suggestion for a possible solution to this:

How about simply check before trying to `jexec` the `ifconfig`, to see if we're running as root or ordinary user?  If we're not running as root, then:

```
% iocage list
+-----+----------+-------+--------------+------+
| JID |   NAME   | STATE |   RELEASE    | IP4  |
+=====+==========+=======+==============+======+
| -   | listjail | down  | 10.3-RELEASE | DHCP |
+-----+----------+-------+--------------+------+
```
and the `--long` list when the jail is running, for example:
```
% iocage list --long
+-----+----------+-------+--------------+----------------+
| JID |   NAME   | STATE |   RELEASE    |      IP4       |
+=====+==========+=======+==============+================+
| -   | listjail | down  | 10.3-RELEASE | DHCP (running) |
+-----+----------+-------+--------------+----------------+

**Comment by skarekrow** [comment]
D'oh! I normally test normal users, but only did root this time...lol thanks for the ticket.

**Comment by rexpo** [comment]
You're welcome ;) and nice touch with the "address requires root" bit!
