### ISSUE TITLE
Log Directory not created on hbsd

### ISSUE THREAD

**Issue by shivno** [iocage/iocage#348]
0.9.9.1 08/01/2017

on hbsd 11-STABLE, when doing some commands:

```
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/stop.py", line 55, in cli
    ioc.IOCage(jail, rc=rc).stop()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 1129, in stop
    ioc_stop.IOCStop(uuid, path, conf, silent=self.silent)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_stop.py", line 50, in __init__
    self.__stop_jail__()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_stop.py", line 137, in __stop_jail__
    with open(f"{self.iocroot}/log/{self.uuid}-console.log", "a") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/iocage/log/2c6bb29e-ffc0-4408-8870-2dcb9c3962b7-console.log'
```

when creating /iocage/log its ok

**Comment by skarekrow** [comment]
Are you running as root?

**Comment by shivno** [comment]
Yes

**Comment by shivno** [comment]
i will deploy an identical machine with ansible in a few days and will report then

**Comment by skarekrow** [comment]
I cannot reproduce @shivno :(

```
─ iocage list
Creating zroot/iocage/download
Creating zroot/iocage/images
Creating zroot/iocage/jails
Creating zroot/iocage/log
Creating zroot/iocage/releases
Creating zroot/iocage/templates
+-----+------+-------+---------+-----+
| JID | NAME | STATE | RELEASE | IP4 |
+=====+======+=======+=========+=====+
+-----+------+-------+---------+-----+
╰─ iocage --version
Version	0.9.9.2 ALPHA
╰─ iocage create -n testy -r 11-STABLE
Fetching: 11-STABLE

Downloading: MANIFEST: 100% 5.01Mbit/s Elapsed: 00:00 Remaining: 00:00
Downloading: base.txz: 100% 827Kbit/s Elapsed: 02:21 Remaining: 00:00
Downloading: doc.txz: 100% 710Kbit/s Elapsed: 00:02 Remaining: 00:00
Extracting: base.txz...
Extracting: doc.txz...
testy successfully created!
╰─ iocage start testy
* Starting testy
  + Started OK
  + Starting services OK
╰─ iocage stop testy
* Stopping testy
  + Running prestop OK
  + Stopping services OK
  + Removing jail process OK
  + Running poststop OK
╰─ cd /iocage/log
╰─ ls
testy-console.log
╰─ zfs list -r zroot/iocage
NAME                                   USED  AVAIL  REFER  MOUNTPOINT
zroot/iocage                           451M  26.8G   100K  /iocage
zroot/iocage/download                  113M  26.8G    88K  /iocage/download
zroot/iocage/download/11-STABLE        113M  26.8G   113M  /iocage/download/11-STABLE
zroot/iocage/images                     88K  26.8G    88K  /iocage/images
zroot/iocage/jails                     392K  26.8G    88K  /iocage/jails
zroot/iocage/jails/testy               304K  26.8G    92K  /iocage/jails/testy
zroot/iocage/jails/testy/root          212K  26.8G   337M  /iocage/jails/testy/root
zroot/iocage/log                        88K  26.8G    88K  /iocage/log
zroot/iocage/releases                  337M  26.8G    88K  /iocage/releases
zroot/iocage/releases/11-STABLE        337M  26.8G    88K  /iocage/releases/11-STABLE
zroot/iocage/releases/11-STABLE/root   337M  26.8G   337M  /iocage/releases/11-STABLE/root
zroot/iocage/templates                  88K  26.8G    88K  /iocage/templates
╰─ zfs destroy zroot/iocage/log
╰─ ls
defaults.json	images		releases
download	jails		templates
╰─ iocage start testy
Creating zroot/iocage/log
* Starting testy
  + Started OK
  + Starting services OK
╰─ ls
defaults.json	images		log		templates
download	jails		releases
╰─ ls log/
testy-console.log
```

**Comment by skarekrow** [comment]
I suggest removing your log directory, and letting iocage create the dataset it wants. If you find a reproducable pattern, I will reopen this and investigate 👍
