### ISSUE TITLE
'iocage start' does not like if /etc/localtime is a soft link

### ISSUE THREAD

**Issue by MarkMartinec** [iocage/iocage#349]
If /etc/localtime in the jail is a soft link to an actual time zone file (instead of a copy or a hard link), the _iocage start_ does start the jail, but then it complains that these are _the same file_ .

```
# iocage --version
0.9.9.1 08/01/2017

# iocage start gitlab-r
* Starting gitlab-runner
  + Started OK
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/start.py", line 55, in cli
    ioc.IOCage(jail, rc=rc).start()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 1111, in start
    callback=self.callback)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_start.py", line 58, in __init__
    self.__start_jail__()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_start.py", line 335, in __start_jail__
    self.start_copy_localtime()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_start.py", line 543, in start_copy_localtime
    shutil.copy("/etc/localtime", f"{self.path}/root/etc/localtime")
  File "/usr/local/lib/python3.6/shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.6/shutil.py", line 104, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: '/etc/localtime' and '/iocage/jails/gitlab-runner/root/etc/localtime' are the same file

# ls -i -l /etc/localtime /iocage/jails/gitlab-runner/root/etc/localtime
53451 lrwxr-xr-x  1 root  wheel  36 Oct 21  2016 /etc/localtime -> /usr/share/zoneinfo/Europe/Ljubljana
20579 lrwxr-xr-x  1 root  wheel  36 Aug 24 17:37 /iocage/jails/gitlab-runner/root/etc/localtime -> /usr/share/zoneinfo/Europe/Ljubljana
```

**Comment by MarkMartinec** [comment]
As a sidetrack: why would _iocage start_ want to muck about with /etc/localtime ???  An _iocage create_ probably yes, but not the  _iocage start_, IMO.

**Comment by skarekrow** [comment]
It's to keep time in sync with the host. If you don't like it you can set that property to `no`

**Comment by randomnonsense** [comment]
Still running 0.9.8.1 and host_time=no doesn't have any effect. On jail start jail-local tzsetup is reset to host time. Host is CEST, jail is supposed to be UTC, but as said, on stop/start timezone is reset to CEST (host time).

Has this been fixed in a more recent version? Changelogs don't mention it.

**Comment by skarekrow** [comment]
@randomnonsense Yes @igalic submitted a PR that actually did the right check a month or so ago. So this issue is actually solved.

@MarkMartinec the reason being that the user could move the iocage dataset and jails elsewhere, and still want the local time in the jail to reflect it. I used to do it only during creation, this was a feature request.

**Comment by skarekrow** [comment]
And then that sidetracked sidetracked me lol, reopening for actual bug
