### ISSUE TITLE
'iocage fetch' fails in format_meter() - calculating frac from strings

### ISSUE THREAD

**Issue by MarkMartinec** [iocage/iocage#359]
A freshly installed iocage fails performing an 'iocage fetch'. The function format_meter() tries to do arithmetic on strings (`frac = n / total`). I had to clobber the format_meter() to always and immediately return some fixed string in order to be able to fetch a release.

```
# freebsd-version
11.1-RELEASE

# iocage --version
0.9.9.1 08/01/2017

# iocage activate zroot

# iocage list
Creating zroot/iocage
Creating zroot/iocage/download
Creating zroot/iocage/images
Creating zroot/iocage/jails
Creating zroot/iocage/log
Creating zroot/iocage/releases
Creating zroot/iocage/templates
+-----+------+-------+---------+-----+
| JID | NAME | STATE | RELEASE | IP4 |
+=====+======+=======+=========+=====+
+-----+------+-------+---------+-----+

# iocage fetch
[0] 9.3-RELEASE (EOL)
[1] 10.1-RELEASE (EOL)
[2] 10.2-RELEASE (EOL)
[3] 10.3-RELEASE
[4] 11.0-RELEASE
[5] 11.1-RELEASE

Type the number of the desired RELEASE
Press [Enter] to fetch the default selection: (11.1)
Type EXIT to quit: 5
Fetching: 11.1-RELEASE

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 95, in cli
    ioc.IOCage().fetch(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 754, in fetch
    ioc_fetch.IOCFetch(release, **kwargs).fetch_release()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 264, in fetch_release
    self.fetch_ftp_release(eol, _list=_list)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 474, in fetch_ftp_release
    self.fetch_download(ftp_list, ftp=True)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 701, in fetch_download
    unit_scale="mega")
  File "/usr/local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 777, in __init__
    self.postfix, unit_divisor))
  File "/usr/local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 293, in format_meter
    frac = n / total
TypeError: unsupported operand type(s) for /: 'str' and 'str'
```

/usr/local/lib/python3.6/site-packages/tqdm/_tqdm.py:
```
    def format_meter(n, total, elapsed, ncols=None, prefix='',
                     ascii=False, unit='it', unit_scale=False, rate=None,
                     bar_format=None, postfix=None, unit_divisor=1000):
      [...]
        if total:
            # fractional and percentage progress
            frac = n / total
```

**Comment by skarekrow** [comment]
This is a dup :)
https://github.com/iocage/iocage/issues/302 closed with https://github.com/iocage/iocage/commit/d55c9387c5dbc220bded2125d5167ef426eb09ea
