### ISSUE TITLE
'iocage fetch -r 11.1-RELEASE' error

### ISSUE THREAD

**Issue by ghost** [iocage/iocage#365]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
`0.9.9.1 08/01/2017`
- [x] Supply the commands used, along with any steps to recreate it.
`iocage fetch -r 11.1-RELEASE` on a fresh install with `pkg install py36-iocage`
- [x] Provide the output from the command you issued.
```
Fetching: 11.1-RELEASE

base.txz missing, will try to redownload!
lib32.txz missing, will try to redownload!
doc.txz missing, will try to redownload!
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 95, in cli
    ioc.IOCage().fetch(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 754, in fetch
    ioc_fetch.IOCFetch(release, **kwargs).fetch_release()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 264, in fetch_release
    self.fetch_ftp_release(eol, _list=_list)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 478, in fetch_ftp_release
    self.fetch_download(missing, ftp=True, missing=True)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 701, in fetch_download
    unit_scale="mega")
  File "/usr/local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 777, in __init__
    self.postfix, unit_divisor))
  File "/usr/local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 293, in format_meter
    frac = n / total
TypeError: unsupported operand type(s) for /: 'str' and 'str'
```
- [x] Supply what you expected the result or output to be
Succesful download of `11.1-RELEASE`
- [ ] Checked that the problem has not already been fixed on `master` if using
 a stable release.
Do not have resources to compile from source.

**Comment by skarekrow** [comment]
Appreciate the report but this has been fixed already in `master` :)

**Comment by ghost** [comment]
Thanks.

Just a note for anyone else who finds this: the `Makefile` doesn't seem to contain valid shell code if trying to compile as root (didn't work for me anyways). I moved the code for updating from git to a separate file, set it to use `zsh`, then ran `make install` again - without errors.

If anyone sees an error like the following when trying to fetch:
```
Fetching: 11.1-RELEASE

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 156, in cli
    ioc.IOCage(exit_on_error=True).fetch(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 943, in fetch
    **kwargs).fetch_release()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 288, in fetch_release
    self.fetch_ftp_release(eol, _list=_list)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 503, in fetch_ftp_release
    missing = self.__fetch_check__(ftp_list, ftp=True)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 602, in __fetch_check__
    if hashes[f] != sha256.hexdigest():
KeyError: 'base.txz'
```
Use `zfs destroy ...` to remove the data in the `$IOCAGE/download` directory and try again.
