### ISSUE TITLE
IOcage segfaults after iocage fetch

### ISSUE THREAD

**Issue by symgryph** [iocage/iocage#368]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [ ] Supply `iocage --version` = 0.9.9.1
- [ ] Supply the commands used, along with any steps to recreate it. iocage fetch

I was using HardenedFREEBSD 11.1-STABLE-HBSD 

Exact commands to reduplicate:
pkg install py36-iocage

iocage activate zroot
iocage fetch

I get Creating ....
Then 
Segmentation Fault (core dumped)

-- Running under HYPERV windows server 2016 type I hypervisor

Thomas

**Comment by skarekrow** [comment]
Can you paste the output? I haven’t seen this. I’d make sure you have enough space and memory as well.

**Comment by symgryph** [comment]
Its the normal output hard to do since no ssh access yet. I could ScreenCap . 8gb memory. 

2 fresh installs hbsd running on azure

Thomas J Munn

**Comment by skarekrow** [comment]
A screen cap would help :) I don’t use hyper V so I’m shooting in the dark really.

**Comment by symgryph** [comment]
I will check. I think it was the Hardened BSD folks (they had a huge regression because they were in the middle of an openssl-libressl conversion).

Thomas

**Comment by rterbush** [comment]
Seeing same thing on fresh install.

```
$ uname -ro
FreeBSD 11.1-STABLE`
$ iocage --version
Version	0.9.9.2 RC
```

```
$ sudo iocage fetch
[0] 9.3-RELEASE (EOL)
[1] 10.1-RELEASE (EOL)
[2] 10.2-RELEASE (EOL)
[3] 10.3-RELEASE
[4] 11.0-RELEASE
[5] 11.1-RELEASE

Type the number of the desired RELEASE
Press [Enter] to fetch the default selection: (11.1-RELEASE)
Type EXIT to quit: 5
Fetching: 11.1-RELEASE

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 158, in cli
    ioc.IOCage(exit_on_error=True).fetch(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 943, in fetch
    **kwargs).fetch_release()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 288, in fetch_release
    self.fetch_ftp_release(eol, _list=_list)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 503, in fetch_ftp_release
    missing = self.__fetch_check__(ftp_list, ftp=True)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 602, in __fetch_check__
    if hashes[f] != sha256.hexdigest():
KeyError: 'base.txz'
```

**Comment by rterbush** [comment]
Note that I first installed this from ports and after running into this problem, built and installed from github master.

**Comment by skarekrow** [comment]
@rterbush You're using HBSD also?

**Comment by rterbush** [comment]
@skarekrow negative. Standard 11.1-Stable

**Comment by symgryph** [comment]
root@jumphost:~ # iocage fetch
********************************************************************************
fdescfs(5) is not mounted, performance  may suffer. Please run:
mount -t fdescfs fdesc /dev/fd
You can also permanently mount it in /etc/fstab with the following entry:
fdesc /dev/fd  fdescfs  rw  0  0
********************************************************************************

Creating zroot/iocage
Creating zroot/iocage/download
Creating zroot/iocage/images
Creating zroot/iocage/jails
Creating zroot/iocage/log
Creating zroot/iocage/releases
Creating zroot/iocage/templates
Segmentation fault (core dumped)
root@jumphost:~ #

**Comment by symgryph** [comment]
uname -a
FreeBSD jumphost 11.1-STABLE-HBSD FreeBSD 11.1-STABLE-HBSD #0 : Sun Sep 17 05:06:33 UTC 2017     root@updater-01:/usr/obj/usr/src/sys/HARDENEDBSD  amd64

**Comment by symgryph** [comment]
I did full update

**Comment by skarekrow** [comment]
@rterbush Hmm. I wonder if it’s something in STABLE. I’ve only tested release. I’ll circle back next week and see. 

@symgryph Interesting. You are able to use zfs and everything just fine on that host? Seems like something else is going on. Anything in `dmesg`?

**Comment by symgryph** [comment]
root@jumphost:~ # ifconfig
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
        inet6 ::1 prefixlen 128
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1
        inet 127.0.0.1 netmask 0xff000000
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        groups: lo
hn0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=8051b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,TSO4,LRO,LINKSTATE>
        ether 00:15:5d:06:04:08
        hwaddr 00:15:5d:06:04:08
        inet 192.168.101.29 netmask 0xffffff00 broadcast 192.168.101.255
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
        media: Ethernet autoselect (10Gbase-T <full-duplex>)
        status: active
lo1: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
        inet 127.0.1.3 netmask 0xffffffff
        inet 127.0.1.4 netmask 0xffffffff
        inet 127.0.1.5 netmask 0xffffffff
        inet 127.0.1.6 netmask 0xffffffff
        inet 127.0.1.7 netmask 0xffffffff
        inet 127.0.1.8 netmask 0xffffffff
        inet 127.0.1.9 netmask 0xffffffff
        inet 127.0.1.2 netmask 0xffffff00
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
        groups: lo
root@jumphost:~ # dmesg
[10136] Waiting (max 60 seconds) for system process `vnlru' to stop... done
[10136] Waiting (max 60 seconds) for system process `bufdaemon' to stop... done
[10137] Waiting (max 60 seconds) for system process `syncer' to stop...
[10137] Syncing disks, vnodes remaining... 0 0 0 0 0 0 0 done
[10143] All buffers synced.
[10143] Uptime: 2h49m3s
[10143] Rebooting...
[10144] cpu_reset: Stopping other CPUs
Copyright (c) 2013-2017 The HardenedBSD Project.
[1] Copyright (c) 1992-2017 The FreeBSD Project.
[1] Copyright (c) 1979, 1980, 1983, 1986, 1988, 1989, 1991, 1992, 1993, 1994
[1]     The Regents of the University of California. All rights reserved.
[1] FreeBSD is a registered trademark of The FreeBSD Foundation.
[1] FreeBSD 11.1-STABLE-HBSD #0 : Sun Sep 17 05:06:33 UTC 2017
[1]     root@updater-01:/usr/obj/usr/src/sys/HARDENEDBSD amd64
[1] FreeBSD clang version 4.0.0 (tags/RELEASE_400/final 297347) (based on LLVM 4.0.0)
[1] SRAT: Ignoring memory at addr 0x208200000
[1] SRAT: Ignoring memory at addr 0x1000000000
[1] VT(vga): text 80x25
[1] Hyper-V Version: 10.0.14393 [SP1]
[1]   Features=0x2e7f<VPRUNTIME,TMREFCNT,SYNIC,SYNTM,APIC,HYPERCALL,VPINDEX,REFTSC,IDLE,TMFREQ>
[1]   PM Features=0x0 [C2]
[1]   Features3=0xed7b2<DEBUG,XMMHC,IDLE,NUMA,TMFREQ,SYNCMC,CRASH,NPIEP>
[1] Timecounter "Hyper-V" frequency 10000000 Hz quality 2000
[1] HardenedBSD: initialize and check features (__HardenedBSD_version 1100049 __FreeBSD_version 1101503).
[1] CPU: Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (2294.69-MHz K8-class CPU)
[1]   Origin="GenuineIntel"  Id=0x406f1  Family=0x6  Model=0x4f  Stepping=1
[1]   Features=0x1f83fbff<FPU,VME,DE,PSE,TSC,MSR,PAE,MCE,CX8,APIC,SEP,MTRR,PGE,MCA,CMOV,PAT,PSE36,MMX,FXSR,SSE,SSE2,SS,HTT>
[1]   Features2=0xfed83203<SSE3,PCLMULQDQ,SSSE3,FMA,CX16,SSE4.1,SSE4.2,MOVBE,POPCNT,AESNI,XSAVE,OSXSAVE,AVX,F16C,RDRAND,HV>
[1]   AMD Features=0x2c100800<SYSCALL,NX,Page1GB,RDTSCP,LM>
[1]   AMD Features2=0x121<LAHF,ABM,Prefetch>
[1]   Structured Extended Features=0x1c2bb9<FSGSBASE,BMI1,HLE,AVX2,SMEP,BMI2,ERMS,RTM,NFPUSG,RDSEED,ADX,SMAP>
[1]   XSAVE Features=0x1<XSAVEOPT>
[1] Hypervisor: Origin = "Microsoft Hv"
[1] real memory  = 8589934592 (8192 MB)
[1] avail memory = 8277622784 (7894 MB)
[1] Event timer "LAPIC" quality 100
[1] ACPI APIC Table: <VRTUAL MICROSFT>
[1] FreeBSD/SMP: Multiprocessor System Detected: 4 CPUs
[1] FreeBSD/SMP: 1 package(s) x 4 core(s)
[1] random: unblocking device.
[1] ioapic0: Changing APIC ID to 0
[1] ioapic0 <Version 1.1> irqs 0-23 on motherboard
[1] Timecounter "Hyper-V-TSC" frequency 10000000 Hz quality 3000
[1] random: entropy device external interface
[1] kbd1 at kbdmux0
[1] netmap: loaded module
[1] module_register_init: MOD_LOAD (vesa, 0xffffffff80f35f50, 0) error 19
[1] random: registering fast source Intel Secure Key RNG
[1] random: fast provider: "Intel Secure Key RNG"
[1] nexus0
[1] vtvga0: <VT VGA driver> on motherboard
[1] cryptosoft0: <software crypto> on motherboard
[1] aesni0: <AES-CBC,AES-XTS,AES-GCM,AES-ICM> on motherboard
[1] acpi0: <VRTUAL MICROSFT> on motherboard
[1] acpi0: Power Button (fixed)
[1] cpu0: <ACPI CPU> on acpi0
[1] cpu1: <ACPI CPU> on acpi0
[1] cpu2: <ACPI CPU> on acpi0
[1] cpu3: <ACPI CPU> on acpi0
[1] attimer0: <AT timer> port 0x40-0x43 irq 0 on acpi0
[1] Timecounter "i8254" frequency 1193182 Hz quality 0
[1] Event timer "i8254" frequency 1193182 Hz quality 100
[1] atrtc0: <AT realtime clock> port 0x70-0x71 irq 8 on acpi0
[1] atrtc0: registered as a time-of-day clock, resolution 1.000000s
[1] Event timer "RTC" frequency 32768 Hz quality 0
[1] Timecounter "ACPI-fast" frequency 3579545 Hz quality 900
[1] acpi_timer0: <32-bit timer at 3.579545MHz> port 0x408-0x40b on acpi0
[1] pcib0: <ACPI Host-PCI bridge> port 0xcf8-0xcff on acpi0
[1] pcib0: Length mismatch for 3 range: 20000000 vs 1fffffff
[1] vmbus0: <Hyper-V Vmbus> on pcib0
[1] pci0: <ACPI PCI bus> on pcib0
[1] isab0: <PCI-ISA bridge> at device 7.0 on pci0
[1] isa0: <ISA bus> on isab0
[1] atapci0: <Intel PIIX4 UDMA33 controller> port 0x1f0-0x1f7,0x3f6,0x170-0x177,0x376,0xffa0-0xffaf at device 7.1 on pci0
[1] ata0: <ATA channel> at channel 0 on atapci0
[1] ata1: <ATA channel> at channel 1 on atapci0
[1] pci0: <bridge> at device 7.3 (no driver attached)
[1] vgapci0: <VGA-compatible display> mem 0xf8000000-0xfbffffff irq 11 at device 8.0 on pci0
[1] vgapci0: Boot video device
[1] atkbdc0: <Keyboard controller (i8042)> port 0x60,0x64 irq 1 on acpi0
[1] atkbd0: <AT Keyboard> irq 1 on atkbdc0
[1] kbd0 at atkbd0
[1] atkbd0: [GIANT-LOCKED]
[1] psm0: <PS/2 Mouse> irq 12 on atkbdc0
[1] psm0: [GIANT-LOCKED]
[1] psm0: model IntelliMouse Explorer, device ID 4
[1] uart0: <16550 or compatible> port 0x3f8-0x3ff irq 4 flags 0x10 on acpi0
[1] uart1: <16550 or compatible> port 0x2f8-0x2ff irq 3 on acpi0
[1] fdc0: <floppy drive controller (FDE)> port 0x3f0-0x3f5,0x3f7 irq 6 drq 2 on acpi0
[1] fd0: <1440-KB 3.5" drive> on fdc0 drive 0
[1] vmbus_res0: <Hyper-V Vmbus Resource> irq 5,7 on acpi0
[1] orm0: <ISA Option ROM> at iomem 0xc0000-0xcbfff on isa0
[1] vga0: <Generic ISA VGA> at port 0x3c0-0x3df iomem 0xa0000-0xbffff on isa0
[1] ppc0: cannot reserve I/O port range
[1] ZFS filesystem version: 5
[1] ZFS storage pool version: features support (5000)
[1] Timecounters tick every 10.000 msec
[1] usb_needs_explore_all: no devclass
[1] nvme cam probe device init
[5] cd0 at ata1 bus 0 scbus1 target 0 lun 0
[5] cd0: <Msft Virtual CD/ROM 1.0> Removable CD-ROM SPC-3 SCSI device
[5] cd0: 16.700MB/s transfers (WDMA2, ATAPI 12bytes, PIO 65534bytes)
[5] cd0: Attempt to query device size failed: NOT READY, Medium not present
[5] SMP: AP CPU #1 Launched!
[5] SMP: AP CPU #2 Launched!
[5] SMP: AP CPU #3 Launched!
[5] Trying to mount root from zfs:zroot/ROOT/default []...
[5] vmbus0: version 3.0
[5] hvet0: <Hyper-V event timer> on vmbus0
[5] Event timer "Hyper-V" frequency 10000000 Hz quality 1000
[5] storvsc0: <Hyper-V IDE> on vmbus0
[5] hvkbd0: <Hyper-V KBD> on vmbus0
[5] da0 at blkvsc0 bus 0 scbus2 target 0 lun 0
[5] da0: <Msft Virtual Disk 1.0> Fixed Direct Access SPC-3 SCSI device
[5] da0: 300.000MB/s transfers
[5] da0: Command Queueing enabled
[5] da0: 130048MB (266338304 512 byte sectors)
[5] hvheartbeat0: <Hyper-V Heartbeat> on vmbus0
[5] hvkvp0: <Hyper-V KVP> on vmbus0
[5] hvshutdown0: <Hyper-V Shutdown> on vmbus0
[5] hvtimesync0: <Hyper-V Timesync> on vmbus0
[5] hvtimesync0: RTT
[5] hvvss0: <Hyper-V VSS> on vmbus0
[5] storvsc1: <Hyper-V SCSI> on vmbus0
[5] hn0: <Hyper-V Network Interface> on vmbus0
[5] hn0: Ethernet address: 00:15:5d:06:04:08
[5] hn0: link state changed to UP
[342] Waiting (max 60 seconds) for system process `vnlru' to stop... done
[342] Waiting (max 60 seconds) for system process `bufdaemon' to stop... done
[342] Waiting (max 60 seconds) for system process `syncer' to stop...
[342] Syncing disks, vnodes remaining... 0 0 0 0 0 0 done
[348] All buffers synced.
[348] Uptime: 5m48s
[348] Rebooting...
[349] cpu_reset: Stopping other CPUs
Copyright (c) 2013-2017 The HardenedBSD Project.
[1] Copyright (c) 1992-2017 The FreeBSD Project.
[1] Copyright (c) 1979, 1980, 1983, 1986, 1988, 1989, 1991, 1992, 1993, 1994
[1]     The Regents of the University of California. All rights reserved.
[1] FreeBSD is a registered trademark of The FreeBSD Foundation.
[1] FreeBSD 11.1-STABLE-HBSD #0 : Sun Sep 17 05:06:33 UTC 2017
[1]     root@updater-01:/usr/obj/usr/src/sys/HARDENEDBSD amd64
[1] FreeBSD clang version 4.0.0 (tags/RELEASE_400/final 297347) (based on LLVM 4.0.0)
[1] SRAT: Ignoring memory at addr 0x208200000
[1] SRAT: Ignoring memory at addr 0x1000000000
[1] VT(vga): text 80x25
[1] Hyper-V Version: 10.0.14393 [SP1]
[1]   Features=0x2e7f<VPRUNTIME,TMREFCNT,SYNIC,SYNTM,APIC,HYPERCALL,VPINDEX,REFTSC,IDLE,TMFREQ>
[1]   PM Features=0x0 [C2]
[1]   Features3=0xed7b2<DEBUG,XMMHC,IDLE,NUMA,TMFREQ,SYNCMC,CRASH,NPIEP>
[1] Timecounter "Hyper-V" frequency 10000000 Hz quality 2000
[1] HardenedBSD: initialize and check features (__HardenedBSD_version 1100049 __FreeBSD_version 1101503).
[1] CPU: Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (2294.74-MHz K8-class CPU)
[1]   Origin="GenuineIntel"  Id=0x406f1  Family=0x6  Model=0x4f  Stepping=1
[1]   Features=0x1f83fbff<FPU,VME,DE,PSE,TSC,MSR,PAE,MCE,CX8,APIC,SEP,MTRR,PGE,MCA,CMOV,PAT,PSE36,MMX,FXSR,SSE,SSE2,SS,HTT>
[1]   Features2=0xfed83203<SSE3,PCLMULQDQ,SSSE3,FMA,CX16,SSE4.1,SSE4.2,MOVBE,POPCNT,AESNI,XSAVE,OSXSAVE,AVX,F16C,RDRAND,HV>
[1]   AMD Features=0x2c100800<SYSCALL,NX,Page1GB,RDTSCP,LM>
[1]   AMD Features2=0x121<LAHF,ABM,Prefetch>
[1]   Structured Extended Features=0x1c2bb9<FSGSBASE,BMI1,HLE,AVX2,SMEP,BMI2,ERMS,RTM,NFPUSG,RDSEED,ADX,SMAP>
[1]   XSAVE Features=0x1<XSAVEOPT>
[1] Hypervisor: Origin = "Microsoft Hv"
[1] real memory  = 8589934592 (8192 MB)
[1] avail memory = 8277622784 (7894 MB)
[1] Event timer "LAPIC" quality 100
[1] ACPI APIC Table: <VRTUAL MICROSFT>
[1] FreeBSD/SMP: Multiprocessor System Detected: 4 CPUs
[1] FreeBSD/SMP: 1 package(s) x 4 core(s)
[1] random: unblocking device.
[1] ioapic0: Changing APIC ID to 0
[1] ioapic0 <Version 1.1> irqs 0-23 on motherboard
[1] Timecounter "Hyper-V-TSC" frequency 10000000 Hz quality 3000
[1] random: entropy device external interface
[1] kbd1 at kbdmux0
[1] netmap: loaded module
[1] module_register_init: MOD_LOAD (vesa, 0xffffffff80f35f50, 0) error 19
[1] random: registering fast source Intel Secure Key RNG
[1] random: fast provider: "Intel Secure Key RNG"
[1] nexus0
[1] vtvga0: <VT VGA driver> on motherboard
[1] cryptosoft0: <software crypto> on motherboard
[1] aesni0: <AES-CBC,AES-XTS,AES-GCM,AES-ICM> on motherboard
[1] acpi0: <VRTUAL MICROSFT> on motherboard
[1] acpi0: Power Button (fixed)
[1] cpu0: <ACPI CPU> on acpi0
[1] cpu1: <ACPI CPU> on acpi0
[1] cpu2: <ACPI CPU> on acpi0
[1] cpu3: <ACPI CPU> on acpi0
[1] attimer0: <AT timer> port 0x40-0x43 irq 0 on acpi0
[1] Timecounter "i8254" frequency 1193182 Hz quality 0
[1] Event timer "i8254" frequency 1193182 Hz quality 100
[1] atrtc0: <AT realtime clock> port 0x70-0x71 irq 8 on acpi0
[1] atrtc0: registered as a time-of-day clock, resolution 1.000000s
[1] Event timer "RTC" frequency 32768 Hz quality 0
[1] Timecounter "ACPI-fast" frequency 3579545 Hz quality 900
[1] acpi_timer0: <32-bit timer at 3.579545MHz> port 0x408-0x40b on acpi0
[1] pcib0: <ACPI Host-PCI bridge> port 0xcf8-0xcff on acpi0
[1] pcib0: Length mismatch for 3 range: 20000000 vs 1fffffff
[1] vmbus0: <Hyper-V Vmbus> on pcib0
[1] pci0: <ACPI PCI bus> on pcib0
[1] isab0: <PCI-ISA bridge> at device 7.0 on pci0
[1] isa0: <ISA bus> on isab0
[1] atapci0: <Intel PIIX4 UDMA33 controller> port 0x1f0-0x1f7,0x3f6,0x170-0x177,0x376,0xffa0-0xffaf at device 7.1 on pci0
[1] ata0: <ATA channel> at channel 0 on atapci0
[1] ata1: <ATA channel> at channel 1 on atapci0
[1] pci0: <bridge> at device 7.3 (no driver attached)
[1] vgapci0: <VGA-compatible display> mem 0xf8000000-0xfbffffff irq 11 at device 8.0 on pci0
[1] vgapci0: Boot video device
[1] atkbdc0: <Keyboard controller (i8042)> port 0x60,0x64 irq 1 on acpi0
[1] atkbd0: <AT Keyboard> irq 1 on atkbdc0
[1] kbd0 at atkbd0
[1] atkbd0: [GIANT-LOCKED]
[1] psm0: <PS/2 Mouse> irq 12 on atkbdc0
[1] psm0: [GIANT-LOCKED]
[1] psm0: model IntelliMouse Explorer, device ID 4
[1] uart0: <16550 or compatible> port 0x3f8-0x3ff irq 4 flags 0x10 on acpi0
[1] uart1: <16550 or compatible> port 0x2f8-0x2ff irq 3 on acpi0
[1] fdc0: <floppy drive controller (FDE)> port 0x3f0-0x3f5,0x3f7 irq 6 drq 2 on acpi0
[1] fd0: <1440-KB 3.5" drive> on fdc0 drive 0
[1] vmbus_res0: <Hyper-V Vmbus Resource> irq 5,7 on acpi0
[1] orm0: <ISA Option ROM> at iomem 0xc0000-0xcbfff on isa0
[1] vga0: <Generic ISA VGA> at port 0x3c0-0x3df iomem 0xa0000-0xbffff on isa0
[1] ppc0: cannot reserve I/O port range
[1] ZFS filesystem version: 5
[1] ZFS storage pool version: features support (5000)
[1] Timecounters tick every 10.000 msec
[1] usb_needs_explore_all: no devclass
[1] nvme cam probe device init
[5] cd0 at ata1 bus 0 scbus1 target 0 lun 0
[5] cd0: <Msft Virtual CD/ROM 1.0> Removable CD-ROM SPC-3 SCSI device
[5] cd0: 16.700MB/s transfers (WDMA2, ATAPI 12bytes, PIO 65534bytes)
[5] cd0: Attempt to query device size failed: NOT READY, Medium not present
[5] SMP: AP CPU #3 Launched!
[5] SMP: AP CPU #2 Launched!
[5] SMP: AP CPU #1 Launched!
[5] Trying to mount root from zfs:zroot/ROOT/default []...
[5] vmbus0: version 3.0
[5] hvet0: <Hyper-V event timer> on vmbus0
[5] Event timer "Hyper-V" frequency 10000000 Hz quality 1000
[5] storvsc0: <Hyper-V IDE> on vmbus0
[5] hvkbd0: <Hyper-V KBD> on vmbus0
[5] da0 at blkvsc0 bus 0 scbus2 target 0 lun 0
[5] da0: <Msft Virtual Disk 1.0> Fixed Direct Access SPC-3 SCSI device
[5] da0: 300.000MB/s transfers
[5] da0: Command Queueing enabled
[5] da0: 130048MB (266338304 512 byte sectors)
[5] hvheartbeat0: <Hyper-V Heartbeat> on vmbus0
[5] hvkvp0: <Hyper-V KVP> on vmbus0
[5] hvshutdown0: <Hyper-V Shutdown> on vmbus0
[5] hvtimesync0: <Hyper-V Timesync> on vmbus0
[5] hvtimesync0: RTT
[5] hvvss0: <Hyper-V VSS> on vmbus0
[5] storvsc1: <Hyper-V SCSI> on vmbus0
[5] hn0: <Hyper-V Network Interface> on vmbus0
[5] hn0: Ethernet address: 00:15:5d:06:04:08
[5] hn0: link state changed to UP
[1349] pid 55041 (python3.6), uid 0: exited on signal 11 (core dumped)
root@jumphost:~ #

**Comment by symgryph** [comment]
I also get same result when on normal freebsd 11.1

Type the number of the desired RELEASE
Press [Enter] to fetch the default selection: (11.1)
Type EXIT to quit: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 167, in __fetch_validate_release__
    self.release = releases[int(self.release)]
ValueError: invalid literal for int() with base 10: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 181, in __fetch_validate_release__
    releases.index(self.release)
ValueError: '11.1' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 95, in cli
    ioc.IOCage().fetch(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 754, in fetch
    ioc_fetch.IOCFetch(release, **kwargs).fetch_release()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 264, in fetch_release
    self.fetch_ftp_release(eol, _list=_list)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 455, in fetch_ftp_release
    self.release = self.__fetch_validate_release__(releases)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 183, in __fetch_validate_release__
    raise RuntimeError("Please select an item!")
RuntimeError: Please select an item!

**Comment by rterbush** [comment]
This appears to be something specific to the `11.1-RELEASE` option. I gave this another try and it works fine if I select `11.0-RELEASE`.

Might be something as simple as permissions or something on the latest release. I've not looked beyond this.

**Comment by rterbush** [comment]
BTW, I also get the following message after completing the fetch on `11.0-RELEASE`. I think it is a bit premature to EOL 11.0. :smile: 

```
WARNING: FreeBSD 11.0-RELEASE is approaching its End-of-Life date.
It is strongly recommended that you upgrade to a newer
release within the next 1 month.
```

**Comment by skarekrow** [comment]
Interesting. @symgryph that’s actually an error message from me to you ;) it’s telling you to select an item 

@rterbush this comes from FreeBSD itself actually. They publish the EOL notice :D

**Comment by skarekrow** [comment]
Hey guys, still trying to reproduce on my end:
```
root@iocage:~ # iocage clean -af ; iocage fetch -r 11.1-RELEASE
Cleaning iocage/templates
Cleaning iocage/releases
Cleaning iocage/log
Cleaning iocage/jails
Cleaning iocage/images
Cleaning iocage/download
Cleaning iocage
All iocage datasets have been destroyed.
Creating zroot/iocage/download
Creating zroot/iocage/images
Creating zroot/iocage/jails
Creating zroot/iocage/log
Creating zroot/iocage/releases
Creating zroot/iocage/templates
Fetching: 11.1-RELEASE

Downloading: MANIFEST: 100% 1.76Kbit/s Elapsed: 00:00 Remaining: 00:00
Downloading: base.txz: 100% 1.28Mbit/s Elapsed: 01:21 Remaining: 00:00
Downloading: lib32.txz: 100% 908Kbit/s Elapsed: 00:20 Remaining: 00:00
Downloading: doc.txz: 100% 395Kbit/s Elapsed: 00:03 Remaining: 00:00
Extracting: base.txz...
Extracting: lib32.txz...
Extracting: doc.txz...

* Updating 11.1-RELEASE to the latest patch level...
Looking up update.FreeBSD.org mirrors... 4 mirrors found.
Fetching public key from update6.freebsd.org... done.
Fetching metadata signature for 11.1-RELEASE from update6.freebsd.org... done.
Fetching metadata index... done.
Fetching 2 metadata files... done.
Inspecting system... done.
Preparing to download files... done.
Fetching 2 patches.. done.
Applying patches... done.

The following files will be updated as part of updating to 11.1-RELEASE-p1:
/bin/freebsd-version
/usr/sbin/sshd
Installing updates... done.
```
So far everything is working for me™ so this may be a bit.

**Comment by skarekrow** [comment]
Can both of you send me the contents of your `/iocage/download/11.1-RELEASE` dataset please?

**Comment by rterbush** [comment]
@skarekrow after running a clean per your example and trying this again, I cannot recreate it. Closed for me.

**Comment by rsdy** [comment]
I'm still having this issue.

```
# iocage clean -af ; iocage fetch -r 11.1-RELEASE
Cleaning iocage/templates
Cleaning iocage/releases
Cleaning iocage/log
Cleaning iocage/jails
Cleaning iocage/images
Cleaning iocage/download
Cleaning iocage
All iocage datasets have been destroyed.
Creating fairy/iocage
Creating fairy/iocage/download
Creating fairy/iocage/images
Creating fairy/iocage/jails
Creating fairy/iocage/log
Creating fairy/iocage/releases
Creating fairy/iocage/templates
Segmentation fault (core dumped)

# iocage --version
Version 0.9.10 2017/12/22

# uname -a
FreeBSD localhost 11.1-STABLE-HBSD FreeBSD 11.1-STABLE-HBSD #0 [STABLE:HardenedBSD-11-STABLE-v1100055]: Wed Mar  7 11:30:18 UTC 2018     root@nyi-01.build.hardenedbsd.org:/usr/obj/usr/src/sys/HARDENEDBSD  amd64

# dmesg |tail
[97793] pid 75641 (python3.6), uid 0: exited on signal 11 (core dumped)
[99091] pid 88864 (python3.6), uid 0: exited on signal 11 (core dumped)
[99149] pid 24994 (python3.6), uid 0: exited on signal 11 (core dumped)
[99266] pid 80229 (python3.6), uid 0: exited on signal 11 (core dumped)
[100130] pid 95571 (python3.6), uid 0: exited on signal 11 (core dumped)
```

I tried a few things, and every try results in a segfault. This is a fresh install on actual HW, all ZFS things working well.
Let me know what additional information you need. Maybe @lattera would have any ideas?
