### ISSUE TITLE
iocage fetch is broken

### ISSUE THREAD

**Issue by bsdlme** [iocage/iocage#379]
# pkg info -x iocage
py36-iocage-0.9.9.1_1 

 # iocage activate zroot
ZFS pool 'zroot' successfully activated.
 # iocage fetch
Creating zroot/iocage
Creating zroot/iocage/download
Creating zroot/iocage/images
Creating zroot/iocage/jails
Creating zroot/iocage/log
Creating zroot/iocage/releases
Creating zroot/iocage/templates
[0] 9.3-RELEASE (EOL)
[1] 10.1-RELEASE (EOL)
[2] 10.2-RELEASE (EOL)
[3] 10.3-RELEASE
[4] 10.4-RELEASE
[5] 11.0-RELEASE
[6] 11.1-RELEASE

Type the number of the desired RELEASE
Press [Enter] to fetch the default selection: (11.1-RELEASE)
Type EXIT to quit: 6
Fetching: 11.1-RELEASE

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 95, in cli
    ioc.IOCage().fetch(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 754, in fetch
    ioc_fetch.IOCFetch(release, **kwargs).fetch_release()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 264, in fetch_release
    self.fetch_ftp_release(eol, _list=_list)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 474, in fetch_ftp_release
    self.fetch_download(ftp_list, ftp=True)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 701, in fetch_download
    unit_scale="mega")
  File "/usr/local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 867, in __init__
    self.postfix, unit_divisor))
  File "/usr/local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 339, in format_meter
    frac = n / total
TypeError: unsupported operand type(s) for /: 'str' and 'str'

**Comment by unti1x** [comment]
Just reinstall iocage (sysutils/iocage) and tqdm (misc/py3-tqdm) from ports. This will help.

**Comment by skarekrow** [comment]
Hey Lars, just do what @unti1x said :) this bug was fixed in 0.9.9.2
