### ISSUE TITLE
iocage df command results in Traceback

### ISSUE THREAD

**Issue by cedwards** [iocage/iocage#383]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [X] Supply `iocage --version`
- [X] Supply the commands used, along with any steps to recreate it.
- [X] Provide the output from the command you issued.
- [X] Supply what you expected the result or output to be
- [X] Checked that the problem has not already been fixed on `master` if using
 a stable release.

```
arya ~ # iocage --version
Version	0.9.9.2 09/30/2017
arya ~ # iocage df
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/df.py", line 43, in cli
    jail_list = ioc.IOCage(exit_on_error=True).df(long=_long)
TypeError: df() got an unexpected keyword argument 'long'
arya ~ # pkg info py36-iocage
py36-iocage-0.9.9.2
Name           : py36-iocage
Version        : 0.9.9.2
Installed on   : Tue Oct  3 18:19:30 2017 MDT
Origin         : sysutils/iocage
Architecture   : FreeBSD:11:*
Prefix         : /usr/local
Categories     : sysutils python
Licenses       : BSD2CLAUSE
Maintainer     : araujo@FreeBSD.org
WWW            : https://github.com/iocage/iocage
Comment        : FreeBSD jail manager written in Python3
Annotations    :
	repo_type      : binary
	repository     : poudriere
Flat size      : 836KiB
Description    :
iocage is a jail/container manager amalgamating some of the best
features and technologies the FreeBSD operating system has
to offer. It is geared for ease of use with a simple and easy
to understand command syntax.

WWW: https://github.com/iocage/iocage
```

**Comment by dlangille** [comment]
I came here to report this issue.
