### ISSUE TITLE
Create template error

### ISSUE THREAD

**Issue by tehfink** [iocage/iocage#39]
Error when trying to create a jail template, on a fresh install of FreeBSD 11 & iocage from github today:
```
# pkg install python35
# python3.5 -m ensurepip; pip3 install --upgrade pip
# mkdir -p /opt/iocage; cd /opt/iocage
# fetch https://github.com/iocage/iocage/archive/master.zip
# unzip *.zip; rm *.zip
# mv iocage-master iocage-master_github-`date +%Y-%m-%d`
# ln -s iocage-master_github* iocage-master
# cd iocage-master/
# pip3 install .
# setenv LANG en_US.UTF-8
# iocage activate zjail
# iocage fetch
Creating zjail/iocage/images
Creating zjail/iocage/log
Creating zjail/iocage/templates
[0] 9.3-RELEASE (EOL)
[1] 10.1-RELEASE (EOL)
[2] 10.2-RELEASE (EOL)
[3] 10.3-RELEASE
[4] 11.0-RELEASE
# iocage create --help
Usage: iocage create [OPTIONS] [PROPS]...

  Create a jail.

Options:
  -c, --count TEXT
  -r, --release TEXT
  -t, --template TEXT
  -p, --pkglist TEXT
  -s, --short          Use a short UUID of 8 characters instead of the default
                       36
  --help               Show this message and exit.
# iocage create -t template_01
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 9, in <module>
    load_entry_point('iocage==0.9.6', 'console_scripts', 'iocage')()
  File "/usr/local/lib/python3.5/site-packages/iocage/main.py", line 92, in main
    cli(obj=MODULES)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/iocage/cli/create.py", line 66, in create_cmd
    IOCFetch(release).fetch_release()
  File "/usr/local/lib/python3.5/site-packages/iocage/lib/ioc_fetch.py", line 173, in fetch_release
    self.fetch_ftp_release(eol, _list=list)
  File "/usr/local/lib/python3.5/site-packages/iocage/lib/ioc_fetch.py", line 333, in fetch_ftp_release
    ftp.cwd(self.release)
  File "/usr/local/lib/python3.5/ftplib.py", line 630, in cwd
    return self.voidcmd(cmd)
  File "/usr/local/lib/python3.5/ftplib.py", line 277, in voidcmd
    return self.voidresp()
  File "/usr/local/lib/python3.5/ftplib.py", line 250, in voidresp
    resp = self.getresp()
  File "/usr/local/lib/python3.5/ftplib.py", line 245, in getresp
    raise error_perm(resp)
ftplib.error_perm: 550 Failed to change directory.
```

Software versions:
```
# iocage --version
Version 0.9.5 2017/02/15
# uname -a
FreeBSD changeme.local 11.0-RELEASE-p2 FreeBSD 11.0-RELEASE-p2 #0: Mon Oct 24 06:55:27 UTC 2016     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
# freebsd-version 
11.0-RELEASE-p7
```

**Comment by skarekrow** [comment]
Bah, what an oversight. Thanks for reporting!
