### ISSUE TITLE
Error when trying to start all jails (omitting 'ALL')

### ISSUE THREAD

**Issue by tehfink** [iocage/iocage#40]
Error when trying to start all jails, on a fresh install of FreeBSD 11 & iocage from github today:
```
# pkg install python35
# python3.5 -m ensurepip; pip3 install --upgrade pip
# mkdir -p /opt/iocage; cd /opt/iocage
# fetch https://github.com/iocage/iocage/archive/master.zip
# unzip *.zip; rm *.zip
# mv iocage-master iocage-master_github-`date +%Y-%m-%d`
# ln -s iocage-master_github* iocage-master
# cd iocage-master/
# pip3 install .
# setenv LANG en_US.UTF-8
# iocage activate zjail
# iocage fetch
Creating zjail/iocage/images
Creating zjail/iocage/log
Creating zjail/iocage/templates
[0] 9.3-RELEASE (EOL)
[1] 10.1-RELEASE (EOL)
[2] 10.2-RELEASE (EOL)
[3] 10.3-RELEASE
[4] 11.0-RELEASE
#iocage create tag=www ip4_addr="lo1|172.16.10.1/28" -r 11.0-RELEASE
Fetching: 11.0-RELEASE
…
* Updating 11.0-RELEASE to the latest patch level... 
…
Installing updates... done.
118d4f9a-8ffb-4559-851a-a4994cb8fd14 (www) successfully created!
# iocage start --help
Usage: iocage start [OPTIONS] [JAILS]...

  Starts the specified jails or ALL.

Options:
  --rc    Will start all jails with boot=on, in the specified order with
          smaller value for priority starting first.
  --help  Show this message and exit.
# iocage start
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 9, in <module>
    load_entry_point('iocage==0.9.6', 'console_scripts', 'iocage')()
  File "/usr/local/lib/python3.5/site-packages/iocage/main.py", line 92, in main
    cli(obj=MODULES)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/iocage/cli/start.py", line 55, in start_cmd
    if jails[0] == "ALL":
IndexError: tuple index out of range
root@changeme:~ # iocage start www
* Starting 118d4f9a-8ffb-4559-851a-a4994cb8fd14 (www)
  + Started OK
  + Starting services OK
```

Software versions:
```
# iocage --version
Version 0.9.5 2017/02/15
# uname -a
FreeBSD changeme.local 11.0-RELEASE-p2 FreeBSD 11.0-RELEASE-p2 #0: Mon Oct 24 06:55:27 UTC 2016     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
# freebsd-version 
11.0-RELEASE-p7
```

Expected to see an error message or the help message, perhaps?

**Comment by skarekrow** [comment]
I can't believe I haven't tried just supplying `start` without ALL this entire time...lol. Thanks! Should be fixed.
