### ISSUE TITLE
ValueError with RELEASE validation

### ISSUE THREAD

**Issue by baznikin** [iocage/iocage#411]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
Version 0.9.9.2 09/30/2017

- [x] Supply the commands used, along with any steps to recreate it.
- [x] Provide the output from the command you issued.
- [x] Supply what you expected the result or output to be
- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

```
 # iocage fetch
[0] 9.3-RELEASE (EOL)
[1] 10.1-RELEASE (EOL)
[2] 10.2-RELEASE (EOL)
[3] 10.3-RELEASE
[4] 10.4-RELEASE
[5] 11.0-RELEASE
[6] 11.1-RELEASE

Type the number of the desired RELEASE
Press [Enter] to fetch the default selection: (11.1-RELEASE)
Type EXIT to quit: 0
Fetching: 9.3-RELEASE

Downloading: MANIFEST: 100% 5.28Kbit/s Elapsed: 00:00 Remaining: 00:00
Downloading: base.txz: 100% 28.4Mbit/s Elapsed: 00:02 Remaining: 00:00
Downloading: lib32.txz: 100% 9.72Mbit/s Elapsed: 00:01 Remaining: 00:00
Downloading: doc.txz: 100% 1.05Mbit/s Elapsed: 00:01 Remaining: 00:00
Extracting: base.txz...
```

```
# iocage create -r 9.3-RELEASE --name 93test
93test successfully created!
```

```
# iocage start 93test

Host: 11.1 is not greater than jail: 9.3
This is unsupported.
```

Same for empty type jails:
```
# iocage start botnet

Host: 11.1 is not greater than jail: EMPTY
This is unsupported.
```

**Comment by baznikin** [comment]
Installed master from github, not it can run older releases, but not EMPTY.
(Actually I don't care about empty type jails, all I need is to run ancient 7.0 jail)

```
root@node2:~/iocage-master # iocage --version
Version 0.9.10 RC
root@node2:~/iocage-master #
root@node2:~/iocage-master #
root@node2:~/iocage-master # iocage list
+-----+---------+-------+--------------+-------------+
| JID |  NAME   | STATE |   RELEASE    |     IP4     |
+=====+=========+=======+==============+=============+
| -   | 70test  | down  | 7.0-RELEASE  | 192.168.1.2 |
+-----+---------+-------+--------------+-------------+
| -   | 93test  | down  | 9.3-RELEASE  | -           |
+-----+---------+-------+--------------+-------------+
| -   | botnet  | down  | EMPTY        | 192.168.1.1 |
+-----+---------+-------+--------------+-------------+
| 2   | mysql   | up    | 11.1-RELEASE | 10.1.2.2    |
+-----+---------+-------+--------------+-------------+
| 1   | unbound | up    | 11.1-RELEASE | 10.1.2.1    |
+-----+---------+-------+--------------+-------------+
root@node2:~/iocage-master # iocage start botnet
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/start.py", line 54, in cli
    ioc.IOCage(exit_on_error=True, jail=jail, rc=rc).start()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 1571, in start
    1)[0])
ValueError: could not convert string to float: 'EMPTY'
root@node2:~/iocage-master # iocage start 93test
* Starting 93test
  + Started OK
  + Starting services OK
root@node2:~/iocage-master # iocage start 70test
* Starting 70test
  + Started OK
  + Starting services OK
```
