### ISSUE TITLE
Unhandled exceptions when fetching bogus releases

### ISSUE THREAD

**Issue by rexpo** [iocage/iocage#415]
A typo tipped me off to this one the other day. Tried to fetch `9.2-RELEASE` by accident. `iocage` barfed. Using other fun phrases results in different barves.

- [x] Supply `iocage --version`

Version 0.9.10 RC (08c0ca9)

- [x] Supply the commands used, along with any steps to recreate it.

An honest mistake:

```
iocage fetch --release 9.2-RELEASE
```

Pure malice:

```
iocage fetch --release LINN-NUCKS
```

- [x] Provide the output from the command you issued.

`iocage` tries to do the right thing when `9.2-RELEASE` is requested, but doesn't react well to the remote server's `404` error:

```
iocage fetch --release 9.2-RELEASE
Fetching: 9.2-RELEASE

base.txz missing, will try to redownload!
lib32.txz missing, will try to redownload!
doc.txz missing, will try to redownload!
Traceback (most recent call last):
  File "/usr/home/jamie/iocage/iocage/main.py", line 136, in <module>
    cli(prog_name="iocage")
  File "/usr/home/jamie/iocage-env/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/home/jamie/iocage-env/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/home/jamie/iocage-env/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/home/jamie/iocage-env/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/home/jamie/iocage-env/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/jamie/iocage/iocage/cli/fetch.py", line 157, in cli
    ioc.IOCage(exit_on_error=True).fetch(**kwargs)
  File "/home/jamie/iocage/iocage/lib/iocage.py", line 974, in fetch
    **kwargs).fetch_release()
  File "/home/jamie/iocage/iocage/lib/ioc_fetch.py", line 233, in fetch_release
    rel = self.fetch_http_release(eol, _list=_list)
  File "/home/jamie/iocage/iocage/lib/ioc_fetch.py", line 516, in fetch_http_release
    self.fetch_download(missing, missing=True)
  File "/home/jamie/iocage/iocage/lib/ioc_fetch.py", line 686, in fetch_download
    r.raise_for_status()
  File "/usr/home/jamie/iocage-env/lib/python3.6/site-packages/requests/models.py", line 929, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://download.freebsd.org/ftp/releases/amd64/9.2-RELEASE/MANIFEST
```

The Lye-knocks test case suggests the need for some input filtering:

```
iocage fetch --release LINN-NUCKS
Traceback (most recent call last):

...

  File "/home/jamie/iocage/iocage/cli/fetch.py", line 145, in cli
    release = float(release.rsplit("-", 1)[0].rsplit("-", 1)[0])
ValueError: could not convert string to float: 'LINN'
```

- [x] Supply what you expected the result or output to be

When attempting to fetch `9.2-RELEASE`, I'd expect either a "not found on remote server" or "must be at least 9.3-RELEASE" type of error.

When attempting to fetch silly nonsense, I'd expect "must be of format X.X-RELEASE" (or perhaps one of the other variants of this notation that `iocage` supports). By the way can `iocage` fetch anything other than X.X-RELEASE? If it should be able to fetch UNSTABLE or CURRENT stuff, then would need to be careful with the filtering here.

**Comment by skarekrow** [comment]
Yes this was one of those "I'll get around to it later things" that I forgot about :D Thanks for the issue!
