### ISSUE TITLE
iocage set ip4_addr="None" LocalGimp

### ISSUE THREAD

**Issue by kitten77** [iocage/iocage#420]
Property: ip4_addr has been updated to None
Traceback (most recent call last):
  File "/usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 653, in json_set_value
    stderr=su.STDOUT)
  File "/usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages/iocage/lib/ioc_common.py", line 451, in checkoutput
    out = su.check_output(*args, **kwargs)
  File "/usr/local/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['jail', '-m', 'jid=23', 'ip4.addr=None']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/home/muad/virtualenv/webhotell/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages/iocage/cli/set.py", line 45, in cli
    plugin)
  File "/usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages/iocage/lib/iocage.py", line 1399, in set
    iocjson.json_set_value(prop)
  File "/usr/home/muad/virtualenv/webhotell/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 656, in json_set_value
    f"{err.output.decode('utf-8').rstrip()}")
RuntimeError: jail: ip4.addr: not an IPv4 address: None

[webhotell] root@gaia:/home/muad/python/webhotell/webhotell_keys # iocage -v
Version 0.9.10 RC
Too reproduce have a running jail and set ipv4_addr="None" 
Seems like there is a missing  string to lower

**Comment by skarekrow** [comment]
Heh, great catch!
