### ISSUE TITLE
fetch failure

### ISSUE THREAD

**Issue by denningsrogue** [iocage/iocage#429]
My attempts to fetch have failed.  Here is the output.  

Freebsd =  11.1-RELEASE-p4
iocage = 0.9.9.1 08/01/2017
Python = 3.6.2

user@LabNUC1: ~ » sudo iocage fetch                                               [08:45:26]
[0] 9.3-RELEASE (EOL)
[1] 10.1-RELEASE (EOL)
[2] 10.2-RELEASE (EOL)
[3] 10.3-RELEASE
[4] 10.4-RELEASE
[5] 11.0-RELEASE
[6] 11.1-RELEASE

Type the number of the desired RELEASE
Press [Enter] to fetch the default selection: (11.1-RELEASE)
Type EXIT to quit: 6
Fetching: 11.1-RELEASE

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 95, in cli
    ioc.IOCage().fetch(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 754, in fetch
    ioc_fetch.IOCFetch(release, **kwargs).fetch_release()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 264, in fetch_release
    self.fetch_ftp_release(eol, _list=_list)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 475, in fetch_ftp_release
    missing = self.__fetch_check__(ftp_list, ftp=True)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 566, in __fetch_check__
    if hashes[f] != sha256.hexdigest():
KeyError: 'base.txz'

I get the same error regardless of the RELEASE I attempt to fetch.

**Comment by denningsrogue** [comment]
Python 3.6.2

**Comment by reelsense** [comment]
Yep, looks like the issue I posted and closed: https://github.com/iocage/iocage/issues/376

It's broken. You have to wait for the `9.9.2` _quarterly_ patch to even use _iocage_, or change from `quarterly` to `latest`.

Relevant instructions: https://forums.freebsd.org/threads/52843/

Since you encountered that bug, after you update to `9.9.2` you will encounter this bug: https://github.com/iocage/iocage/issues/381

`9.9.2` fixes the broken initialization but not the side-effect of encountering it.

I updated to `9.9.2` to solve it and encountered bug #381 and, after solving that everything works like normal.

---
x-post: https://github.com/iocage/iocage/issues/421

**Comment by skarekrow** [comment]
Thanks for helping @reelsense! 

Closing as dup of all the tickets listed.

**Comment by denningsrogue** [comment]
Thanks for your help.  Problem solved.
