### ISSUE TITLE
iocage rename fails on migrated jail

### ISSUE THREAD

**Issue by vendion** [iocage/iocage#431]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
   `Version	0.9.9.2 09/30/2017`
- [x] Supply the commands used, along with any steps to recreate it.
    `iocage rename tag new_tag`
- [x] Provide the output from the command you issued.
```
sudo iocage rename http wiki
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/rename.py", line 39, in cli
    ioc.IOCage(exit_on_error=True, jail=jail).rename(new_name)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 1179, in rename
    self.zfs.get_dataset(path).rename(new_path)
  File "libzfs.pyx", line 2126, in libzfs.ZFSObject.rename
libzfs.ZFSException: child dataset with inherited mountpoint is used in a non-global zone
```
- [x] Supply what you expected the result or output to be
    Expected the named jail to be renamed
- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.
    Don't see any commits that might address this since 0.9.9.2 release.

## Full output and debug notes
```
freebsd@Snortra:~ % sudo iocage stop http
* Stopping http
  + Running prestop OK
  + Stopping services OK
  + Removing jail process OK
  + Running poststop OK
freebsd@Snortra:~ % sudo iocage rename http wiki
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/rename.py", line 39, in cli
    ioc.IOCage(exit_on_error=True, jail=jail).rename(new_name)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 1179, in rename
    self.zfs.get_dataset(path).rename(new_path)
  File "libzfs.pyx", line 2126, in libzfs.ZFSObject.rename
libzfs.ZFSException: child dataset with inherited mountpoint is used in a non-global zone
freebsd@Snortra:~ % sudo iocage start http
* Starting http
  + Started OK
  + Starting services OK
freebsd@Snortra:~ % sudo iocage list
+-----+------------+-------+--------------+------------+
| JID |    NAME    | STATE |   RELEASE    |    IP4     |
+=====+============+=======+==============+============+
| 2   | licensesrv | up    | 11.1-RELEASE | 172.16.1.3 |
+-----+------------+-------+--------------+------------+
| -   | wiki       | down  | 11.1-RELEASE | 172.16.1.2 |
+-----+------------+-------+--------------+------------+
freebsd@Snortra:~ % ls /iocage/jails/
http		licensesrv
freebsd@Snortra:~ % ls /iocage/jails/http/
config.json	fstab		root
freebsd@Snortra:~ % cat /iocage/jails/http/config.json 
{
    "CONFIG_VERSION": "9",
    "allow_chflags": "0",
    "allow_mount": "0",
    "allow_mount_devfs": "0",
    "allow_mount_nullfs": "0",
    "allow_mount_procfs": "0",
    "allow_mount_tmpfs": "0",
    "allow_mount_zfs": "0",
    "allow_quotas": "0",
    "allow_raw_sockets": "0",
    "allow_set_hostname": "0",
    "allow_socket_af": "0",
    "allow_sysvipc": "0",
    "basejail": "no",
    "boot": "on",
    "bpf": "no",
    "children_max": "0",
    "cloned_release": "11.1-RELEASE",
    "comment": "none",
    "coredumpsize": "off",
    "cpuset": "off",
    "cputime": "off",
    "datasize": "off",
    "defaultrouter": "192.241.151.1",
    "defaultrouter6": "none",
    "depends": "none",
    "devfs_ruleset": "4",
    "dhcp": "off",
    "enforce_statfs": "2",
    "exec_clean": "1",
    "exec_fib": "0",
    "exec_jail_user": "root",
    "exec_poststart": "/usr/bin/true",
    "exec_poststop": "/usr/bin/true",
    "exec_prestart": "/usr/bin/true",
    "exec_prestop": "/usr/bin/true",
    "exec_start": "/bin/sh /etc/rc",
    "exec_stop": "/bin/sh /etc/rc.shutdown",
    "exec_system_jail_user": "0",
    "exec_system_user": "root",
    "exec_timeout": "60",
    "gitlocation": "https://github.com",
    "hack88": "0",
    "host_domainname": "none",
    "host_hostname": "http",
    "host_hostuuid": "wiki",
    "host_time": "yes",
    "hostid": "d009188b-8f03-11e6-b47c-75f0d773008d",
    "interfaces": "vnet0:bridge0,vnet1:bridge1",
    "ip4": "new",
    "ip4_addr": "bridge0|172.16.1.2/24",
    "ip4_autoend": "none",
    "ip4_autostart": "none",
    "ip4_autosubnet": "none",
    "ip4_saddrsel": "1",
    "ip6": "new",
    "ip6_addr": "none",
    "ip6_saddrsel": "1",
    "jail_zfs": "off",
    "jail_zfs_dataset": "iocage/jails/c2e61eaa-cb95-11e6-a495-2d02a455a856/data",
    "last_started": "2017-11-28 20:54:36",
    "login_flags": "-f root",
    "maxproc": "off",
    "memorylocked": "off",
    "memoryuse": "8G:log",
    "mount_devfs": "1",
    "mount_fdescfs": "1",
    "mount_procfs": "0",
    "msgqqueued": "off",
    "msgqsize": "off",
    "nmsgq": "off",
    "notes": "none",
    "nsemop": "off",
    "nshm": "off",
    "nthr": "off",
    "openfiles": "off",
    "owner": "root",
    "pcpu": "off",
    "priority": "99",
    "pseudoterminals": "off",
    "release": "11.1-RELEASE",
    "resolver": "none",
    "rlimits": "off",
    "securelevel": "2",
    "shmsize": "off",
    "stacksize": "off",
    "stop_timeout": "30",
    "swapuse": "off",
    "sync_target": "none",
    "sync_tgt_zpool": "none",
    "sysvmsg": "new",
    "sysvsem": "new",
    "sysvshm": "new",
    "tag": "http",
    "template": "no",
    "type": "jail",
    "vmemoryuse": "off",
    "vnet": "off",
    "vnet0_mac": "none",
    "vnet1_mac": "none",
    "vnet2_mac": "none",
    "vnet3_mac": "none",
    "wallclock": "off"
}freebsd@Snortra:~ % iocage --version
Version	0.9.9.2 09/30/2017
```
I'm not sure what `iocage rename` even attempted when it choked as I don't see any changes. I do see that the `jail_zfs_dataset` property is out of date as this jail was migrated from `iocage_legacy`.

The correct entries from `zfs list` for this jail should be:
```
zroot/iocage/jails/http                          4.73G  19.6G  21.5K  /iocage/jails/http
zroot/iocage/jails/http/data                       19K  19.6G    19K  /iocage/jails/http/data
zroot/iocage/jails/http/root                     4.73G  19.6G  2.26G  /iocage/jails/http/root
```
Could this be the cause of the issue?

**Comment by skarekrow** [comment]
That is likely part of the problem, which was recently fixed. I haven't been able to reproduce this for the upcoming release this weekend, are you able to provide a set of steps that trigger it for you?

**Comment by vendion** [comment]
For steps on what I did that triggered it:
1. I followed the [upgrade from iocage_legacy](https://github.com/iocage/iocage#upgrading-from-iocage_legacy) guide in the README
2. After my jails where migrated and confirmed running, I tried running `iocage rename` on one of my running jails which produced the above python traceback.
3. When that failed I tried stopping the jail that I wanted to rename and tried it again, which failed in the same manor as it did while running.

I have not tested creating a new jail with the last release of iocage and renaming that, but I suspect that might work correctly.

**Comment by geoffgarside** [comment]
I recently had this issue with some migrated jails which were still using the UUID path style and was able to fix my jails by doing the following

``` shell
$ jail -r $JID
$ zfs unmount -f tank/iocage/jails/$UUID
$ zfs set jailed=off tank/iocage/jails/$UUID/root/data
$ zfs rename tank/iocage/jails/$UUID tank/iocage/jails/$TAG
$ zfs set jailed=on tank/iocage/jails/$TAG/root/data
$ iocage set jail_zfs_dataset=iocage/jails/$TAG/root/data $TAG
$ iocage start $TAG
```

this was after I'd done the initial list, migrate and attempted to manually rename UUID -> TAG as well. This only affected some of the jails, a bunch of other jails migrated just fine without toggling the `jailed` flag.

Theres probably a better way to shutdown the jail, which negates the need to `zfs unmount`, but I was in a bit of a hurry.

**Comment by vendion** [comment]
@geoffgarside Question did manually renaming the zfs dataset work for you in migrating your jails? If so it may be a decent work around while waiting for the newest version of `iocage` to hit the package repos.

**Comment by geoffgarside** [comment]
@vendion yes, the start/stop/get/set/console commands all appear to be working, and `iocage list` shows the jails as running and `jls` confirms. I already had the config.json created from a migration attempt, so if you've already got that there then it should be ok. It certainly seems alright at the moment anyway :)

**Comment by vendion** [comment]
@geoffgarside Thanks for confirming, I do have a config.json for the jail I already attempted to migrate and the start/stop/get/set/console/etc commands work using the old tag name but `iocage list` shows the new jail tag and reports the jail as not running.

I'll do some snapshots and give that a try on my jail later today to see if that corrects the failed migration.

**Comment by geoffgarside** [comment]
@vendion yeah thats the same behaviour I was seeing, the ZFS paths were still the UUID style, `iocage list` showed them as down, and `start $TAG` would report the jail was unknown.

**Comment by vendion** [comment]
Using the workaround @geoffgarside posted worked for me as well although my dataset paths differed slightly so if anyone else runs into this YMMV. The dataset I had to rename was `zroot/iocage/jails/$OLD_TAG/data` (notice the lack of the root in the path).

**Comment by vendion** [comment]
With iocage v0.9.10 on a stopped jail this is what I get when trying to rename the jail through iocage

```
freebsd@Snortra:~ % sudo iocage rename licensesrv ops
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/rename.py", line 39, in cli
    ioc.IOCage(exit_on_error=True, jail=jail).rename(new_name)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 1238, in rename
    self.zfs.get_dataset(path).rename(new_path)
  File "libzfs.pyx", line 2134, in libzfs.ZFSObject.rename
libzfs.ZFSException: child dataset with inherited mountpoint is used in a non-global zone
```

**Comment by denigmus** [comment]
#iocage rename baseTest baseTest2

```
# iocage rename baseTest baseTest2
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/rename.py", line 39, in cli
    ioc.IOCage(exit_on_error=True, jail=jail).rename(new_name)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 1238, in rename
    self.zfs.get_dataset(path).rename(new_path)
  File "libzfs.pyx", line 2134, in libzfs.ZFSObject.rename
libzfs.ZFSException: Device busy
```

I forced unmount of these two:

```
zroot/iocage/jails/baseTest on /iocage/jails/baseTest (zfs, local, noatime, nfsv4acls)
zroot/iocage/jails/baseTest/root on /iocage/jails/baseTest/root (zfs, local, noatime, nfsv4acls)
```

And have tried rename again - result is the same.

Moreover, it mounted these datasets again during renaming attempt.

FreeBSD 11.1-RELEASE-p8
iocage -v
Version 0.9.10 2017/12/22

**Comment by skarekrow** [comment]
@jsegaert closed this :)
