### ISSUE TITLE
Nested ZFS datasets are mounted incorrectly

### ISSUE THREAD

**Issue by jhujhiti** [iocage/iocage#441]
Hi,

I'm attempting to use nested ZFS datasets inside my jails, but things are behaving rather strangely, with filesystems appearing mounted (mounted property "on", and shows up in `mount`), but their contents not appearing. Here is what happens with iocage "Version 0.9.9.2 09/30/2017", although judging from the code this is still an issue on master.

```
host# iocage create -r 11.1-RELEASE -n test jail_zfs=on
host# iocage start test
jail# zfs set mountpoint=/data zroot/iocage/jails/test/data
jail# zfs create zroot/iocage/jails/test/data/a
jail# zfs create zroot/iocage/jails/test/data/a/b
jail# zfs create zroot/iocage/jails/test/data/a/b/c
jail# touch /data/a/on-zfs
jail# touch /data/a/b/on-zfs
jail# touch /data/a/b/c/on-zfs
jail# ls -R /data/
a

/data/a:
b       on-zfs

/data/a/b:
c       on-zfs

/data/a/b/c:
on-zfs

host# iocage stop test
host# iocage start test
jail# ls -R /data
a

/data/a:
jail# zfs get mounted
NAME                                PROPERTY  VALUE    SOURCE
zroot                               mounted   no       -
zroot/iocage                        mounted   no       -
zroot/iocage/jails                  mounted   no       -
zroot/iocage/jails/test             mounted   no       -
zroot/iocage/jails/test/data        mounted   yes      -
zroot/iocage/jails/test/data/a      mounted   yes      -
zroot/iocage/jails/test/data/a/b    mounted   yes      -
zroot/iocage/jails/test/data/a/b/c  mounted   yes      -
host# iocage stop test   
* Stopping test
  + Running prestop OK
  + Stopping services OK
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_stop.py", line 173, in __stop_jail__
    "zfs", "umount", child], stderr=su.STDOUT)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_common.py", line 451, in checkoutput
    out = su.check_output(*args, **kwargs)
  File "/usr/local/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['setfib', '0', 'jexec', 'ioc-test', 'zfs', 'umount', 'zroot/iocage/jails/test/data/a/b/c']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/stop.py", line 54, in cli
    ioc.IOCage(exit_on_error=True, jail=jail, rc=rc).stop()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 1589, in stop
    exit_on_error=self.exit_on_error)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_stop.py", line 52, in __init__
    self.__stop_jail__()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_stop.py", line 183, in __stop_jail__
    err.output.decode("utf-8").rstrip()))
RuntimeError: cannot unmount '/data/a/b/c': Invalid argument
```

As you can see, the start does not mount the filesystems correctly, causing the stop to fail entirely. I believe this is because the start action calls something like the following, with filesystems sorted in descending order. It then attempts to mount them in that order.
```
host# zfs list -Hro name -S name zroot/iocage/jails/test/data
zroot/iocage/jails/test/data/a/b/c
zroot/iocage/jails/test/data/a/b
zroot/iocage/jails/test/data/a
zroot/iocage/jails/test/data
```
It looks like using a lowercase `-s` here would fix this, but I'm wondering why not just call `zfs mount -a` at start and `zfs umount -a` at stop instead?

**Comment by skarekrow** [comment]
Interesting, I'll have to test this some more. As for the not using `zfs mount -a` and such, I didn't want to mount potentially unmounted filesystems that the user didn't want to be mounted. Trying to be as minimally invasive as I can in this case ;) But at the cost of issues like this from the complexity.

Thanks for the issue!

**Comment by jhujhiti** [comment]
I probably should have mentioned this, but I did confirm that changing `-S` to `-s` does indeed fix the issue I was having.

For what it's worth, the `/etc/rc.d/zfs` script does just call `zfs mount -a` inside a jail.
