### ISSUE TITLE
"iocage fetch" does not work

### ISSUE THREAD

**Issue by samob** [iocage/iocage#451]
Running  FreeBSD 11.1-RELEASE-p4 in bhyve on TrueOS (FreeBSD 12.0-CURRENT #10 d26791952(trueos-stable-17.12)) 
```
# iocage --version
0.9.9.1 08/01/2017
```

Host has this network set up:
```
% ifconfig
em0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=852099<RXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,WOL_MAGIC,VLAN_HWFILTER,VLAN_HWTSO>
        ether 74:d4:35:ec:ae:0c
        inet 192.168.0.10 netmask 0xffffff00 broadcast 192.168.0.255
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
        media: Ethernet autoselect (100baseTX <full-duplex>)
        status: active
alc0: flags=8802<BROADCAST,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=c319a<TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,TSO4,WOL_MCAST,WOL_MAGIC,VLAN_HWTSO,LINKSTATE>
        ether 74:d4:35:ec:ae:0e
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
        media: Ethernet autoselect
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
        inet6 ::1 prefixlen 128
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x3
        inet 127.0.0.1 netmask 0xff000000
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        groups: lo
bridge0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        description: iohyve-bridge-em0
        ether 02:ff:8b:cb:a3:00
        nd6 options=9<PERFORMNUD,IFDISABLED>
        groups: bridge
        id 00:00:00:00:00:00 priority 32768 hellotime 2 fwddelay 15
        maxage 20 holdcnt 6 proto rstp maxaddr 2000 timeout 1200
        root id 00:00:00:00:00:00 priority 32768 ifcost 0 port 0
        member: tap0 flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
                ifmaxaddr 0 port 5 priority 128 path cost 2000000
        member: em0 flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
                ifmaxaddr 0 port 1 priority 128 path cost 200000
tap0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
        description: iohyve-FreeBSD-11-1--
        options=80000<LINKSTATE>
        ether 00:bd:18:0f:76:00
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
        media: Ethernet autoselect
        status: active
        groups: tap
        Opened by PID 72769

```
Network in bhyve guet gets ip via DHCP:
```
samob@dev:~ % ifconfig
vtnet0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=80028<VLAN_MTU,JUMBO_MTU,LINKSTATE>
        ether 00:a0:98:d2:e0:6e
        hwaddr 00:a0:98:d2:e0:6e
        inet 192.168.0.131 netmask 0xffffff00 broadcast 192.168.0.255
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
        media: Ethernet 10Gbase-T <full-duplex>
        status: active
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
        inet6 ::1 prefixlen 128
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x2
        inet 127.0.0.1 netmask 0xff000000
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        groups: lo
samob@dev:~ % ping www.arnes.si
PING lajnar.arnes.si (193.2.1.67): 56 data bytes
64 bytes from 193.2.1.67: icmp_seq=0 ttl=247 time=42.573 ms
64 bytes from 193.2.1.67: icmp_seq=1 ttl=247 time=37.984 ms
64 bytes from 193.2.1.67: icmp_seq=2 ttl=247 time=34.163 ms
^C
--- lajnar.arnes.si ping statistics ---
4 packets transmitted, 3 packets received, 25.0% packet loss
round-trip min/avg/max/stddev = 34.163/38.240/42.573/3.438 ms
```

When I try to fetch release with "fetch release" command, I get this error:
```
root@dev:~ # iocage fetch
[0] 9.3-RELEASE (EOL)
[1] 10.1-RELEASE (EOL)
[2] 10.2-RELEASE (EOL)
[3] 10.3-RELEASE
[4] 10.4-RELEASE
[5] 11.0-RELEASE (EOL)
[6] 11.1-RELEASE

Type the number of the desired RELEASE
Press [Enter] to fetch the default selection: (11.1-RELEASE)
Type EXIT to quit:
Fetching: 11.1-RELEASE

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 95, in cli
    ioc.IOCage().fetch(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 754, in fetch
    ioc_fetch.IOCFetch(release, **kwargs).fetch_release()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 264, in fetch_release
    self.fetch_ftp_release(eol, _list=_list)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 475, in fetch_ftp_release
    missing = self.__fetch_check__(ftp_list, ftp=True)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 566, in __fetch_check__
    if hashes[f] != sha256.hexdigest():
KeyError: 'base.txz'
```

Internet in bhyve guest is working ok:
```
root@dev:~ # pkg install lynx
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
The following 2 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
        lynx: 2.8.8.2_6,1
        libidn: 1.33_1

Number of packages to be installed: 2

The process will require 6 MiB more space.
2 MiB to be downloaded.

Proceed with this action? [y/N]: y
[1/2] Fetching lynx-2.8.8.2_6,1.txz: 100%    2 MiB 396.3kB/s    00:04
[2/2] Fetching libidn-1.33_1.txz: 100%  203 KiB 207.6kB/s    00:01
Checking integrity... done (0 conflicting)
[1/2] Installing libidn-1.33_1...
[1/2] Extracting libidn-1.33_1: 100%
[2/2] Installing lynx-2.8.8.2_6,1...
Extracting lynx-2.8.8.2_6,1: 100%
Message from lynx-2.8.8.2_6,1:
To enable certificate handling for SSL connnections, set
SSL_CERT_DIR and SSL_CERT_FILE in your environment to the
proper values (depending upon which SSL library
/usr/local/bin/lynx uses), as described in:

/usr/local/share/doc/lynx/docs/README.sslcerts

and:

/usr/local/share/doc/lynx/docs/README.rootcerts.

You may also need to generate keys and certificates as
described in the latter document and your SSL documentation.

```

**Comment by reelsense** [comment]
Yep, looks like the issue I posted and closed: https://github.com/iocage/iocage/issues/376

It's broken. You have to wait for the `9.9.2` _quarterly_ patch to even use _iocage_, or change from `quarterly` to `latest`.

Relevant instructions: https://forums.freebsd.org/threads/52843/

Since you encountered that bug, after you update to `9.9.2` you will encounter this bug: https://github.com/iocage/iocage/issues/381

`9.9.2` fixes the broken initialization but not the side-effect of encountering it.

I updated to `9.9.2` to solve it and encountered bug #381 and, after solving that everything works like normal.

---
x-post: https://github.com/iocage/iocage/issues/421
