### ISSUE TITLE
iocage snaplist doesn't seem to work with all available parameters.

### ISSUE THREAD

**Issue by gerritche** [iocage/iocage#466]
First things first: Used to use ezjail but growing on iocage as well. Thanks a lot for that software.

Make sure to follow and check these boxes before submitting an issue! Thank you.

- [X] Supply `iocage --version`
Version 0.9.10 2017/12/22

- [X] Supply the commands used, along with any steps to recreate it.

`iocage snaplist <jailname>`

- [X] Provide the output from the command you issued.

```
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/snaplist.py", line 44, in cli
    _sort)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 1474, in snap_list
    name, snap_name = parent[0].split("@")
ValueError: not enough values to unpack (expected 2, got 1)

```
- [X] Supply what you expected the result or output to be

List of snapshots for that jail like in iocage snaplist -l <jailname> which works.

- [ ] Checked that the problem has not already been fixed on `master` if using
 a stable release.

no, just checked on open issues list

**Comment by skarekrow** [comment]
Thanks for the kind words! I'm assuming you saw https://github.com/iocage/iocage/commit/16bca530be94d1850831673a65d52cfe6c5ecb10 and closed this?

**Comment by gerritche** [comment]
Correct! ;-) When is the new version available for pkg install?

**Comment by gerritche** [comment]
Yes, exactly. Is it not fixed yet?
