### ISSUE TITLE
The snaplist subcommand segfaults if there are snapshots with different name scheme

### ISSUE THREAD

**Issue by vendion** [iocage/iocage#474]
After upgrading to iocage v0.9.10 I wanted to check if this resolved the issue of `iocage update <jail>` not actually installing FreeBSD patches and being use to the behavior of the legacy version of iocage where it would automatically create a snapshot before doing the update, I went to check after my jail was successfully updated to FreeBSD 11.1-p6 when iocage segfaulted.

```
[vendion@Heimdall][~]% iocage --version
Version	0.9.10 2017/12/22
[vendion@Heimdall][~]% sudo iocage snaplist hugo
********************************************************************************
fdescfs(5) is not mounted, performance may suffer. Please run:
mount -t fdescfs null /dev/fd
You can also permanently mount it in /etc/fstab with the following entry:
fdescfs /dev/fd  fdescfs  rw  0  0
********************************************************************************

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/snaplist.py", line 44, in cli
    _sort)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 1474, in snap_list
    name, snap_name = parent[0].split("@")
ValueError: not enough values to unpack (expected 2, got 1)
```

Looking at the snapshots manually with ZFS I don't see any that was created with the naming scheme iocage_legacy used, but I do have several manual snapshots:

```
[vendion@Heimdall][~]% zfs list -t snapshot | grep iocage
tank/iocage@2017-12-30_04.00.00--2m                               64K      -    96K  -
tank/iocage@2018-01-07_00.00.00--2m                               56K      -   100K  -
tank/iocage@2018-01-14_21.46.00--1w                                 0      -   100K  -
tank/iocage@2018-01-14_21.47.00--2m                                 0      -   100K  -
tank/iocage@2018-01-15_00.00.00--1w                                 0      -   100K  -
tank/iocage@2018-01-16_00.00.00--1w                               56K      -   100K  -
tank/iocage@2018-01-17_00.00.00--1w                               56K      -   100K  -
tank/iocage@2018-01-18_00.00.00--1w                               56K      -   100K  -
tank/iocage@2018-01-19_00.00.00--1w                               56K      -   100K  -
tank/iocage@2018-01-20_00.00.00--1w                               56K      -   100K  -
tank/iocage@2018-01-21_00.00.00--1w                                 0      -   100K  -
tank/iocage@2018-01-21_00.00.00--2m                                 0      -   100K  -
tank/iocage/download@2017-12-30_04.00.00--2m                      56K      -    88K  -
tank/iocage/download@2018-01-07_00.00.00--2m                      56K      -    88K  -
tank/iocage/download@2018-01-14_21.46.00--1w                        0      -    88K  -
tank/iocage/download@2018-01-14_21.47.00--2m                        0      -    88K  -
tank/iocage/download@2018-01-15_00.00.00--1w                        0      -    88K  -
tank/iocage/download@2018-01-16_00.00.00--1w                      56K      -    88K  -
tank/iocage/download@2018-01-17_00.00.00--1w                      56K      -    88K  -
tank/iocage/download@2018-01-18_00.00.00--1w                      56K      -    88K  -
tank/iocage/download@2018-01-19_00.00.00--1w                      56K      -    88K  -
tank/iocage/download@2018-01-20_00.00.00--1w                      56K      -    88K  -
tank/iocage/download@2018-01-21_00.00.00--1w                        0      -    88K  -
tank/iocage/download@2018-01-21_00.00.00--2m                        0      -    88K  -
tank/iocage/download/11.1-RELEASE@2017-12-30_04.00.00--2m         56K      -   119M  -
tank/iocage/download/11.1-RELEASE@2018-01-07_00.00.00--2m         56K      -   119M  -
tank/iocage/download/11.1-RELEASE@2018-01-14_21.46.00--1w           0      -   119M  -
tank/iocage/download/11.1-RELEASE@2018-01-14_21.47.00--2m           0      -   119M  -
tank/iocage/download/11.1-RELEASE@2018-01-15_00.00.00--1w           0      -   119M  -
tank/iocage/download/11.1-RELEASE@2018-01-16_00.00.00--1w         56K      -   119M  -
tank/iocage/download/11.1-RELEASE@2018-01-17_00.00.00--1w         56K      -   119M  -
tank/iocage/download/11.1-RELEASE@2018-01-18_00.00.00--1w         56K      -   119M  -
tank/iocage/download/11.1-RELEASE@2018-01-19_00.00.00--1w         56K      -   119M  -
tank/iocage/download/11.1-RELEASE@2018-01-20_00.00.00--1w         56K      -   119M  -
tank/iocage/download/11.1-RELEASE@2018-01-21_00.00.00--1w           0      -   119M  -
tank/iocage/download/11.1-RELEASE@2018-01-21_00.00.00--2m           0      -   119M  -
tank/iocage/images@2017-12-30_04.00.00--2m                        56K      -    88K  -
tank/iocage/images@2018-01-07_00.00.00--2m                        56K      -    88K  -
tank/iocage/images@2018-01-14_21.46.00--1w                          0      -    88K  -
tank/iocage/images@2018-01-14_21.47.00--2m                          0      -    88K  -
tank/iocage/images@2018-01-15_00.00.00--1w                          0      -    88K  -
tank/iocage/images@2018-01-16_00.00.00--1w                        56K      -    88K  -
tank/iocage/images@2018-01-17_00.00.00--1w                        56K      -    88K  -
tank/iocage/images@2018-01-18_00.00.00--1w                        56K      -    88K  -
tank/iocage/images@2018-01-19_00.00.00--1w                        56K      -    88K  -
tank/iocage/images@2018-01-20_00.00.00--1w                        56K      -    88K  -
tank/iocage/images@2018-01-21_00.00.00--1w                          0      -    88K  -
tank/iocage/images@2018-01-21_00.00.00--2m                          0      -    88K  -
tank/iocage/jails@2017-12-30_04.00.00--2m                         56K      -    88K  -
tank/iocage/jails@2018-01-07_00.00.00--2m                         56K      -    88K  -
tank/iocage/jails@2018-01-14_21.46.00--1w                           0      -    88K  -
tank/iocage/jails@2018-01-14_21.47.00--2m                           0      -    88K  -
tank/iocage/jails@2018-01-15_00.00.00--1w                           0      -    88K  -
tank/iocage/jails@2018-01-16_00.00.00--1w                         56K      -    88K  -
tank/iocage/jails@2018-01-17_00.00.00--1w                         56K      -    88K  -
tank/iocage/jails@2018-01-18_00.00.00--1w                         56K      -    88K  -
tank/iocage/jails@2018-01-19_00.00.00--1w                         56K      -    88K  -
tank/iocage/jails@2018-01-20_00.00.00--1w                         56K      -    88K  -
tank/iocage/jails@2018-01-21_00.00.00--1w                           0      -    88K  -
tank/iocage/jails@2018-01-21_00.00.00--2m                           0      -    88K  -
tank/iocage/jails/hugo@2018-01-07_00.00.00--2m                    56K      -    92K  -
tank/iocage/jails/hugo@2018-01-14_21.46.00--1w                      0      -    92K  -
tank/iocage/jails/hugo@2018-01-14_21.47.00--2m                      0      -    92K  -
tank/iocage/jails/hugo@2018-01-15_00.00.00--1w                      0      -    92K  -
tank/iocage/jails/hugo@2018-01-16_00.00.00--1w                    56K      -    92K  -
tank/iocage/jails/hugo@2018-01-17_00.00.00--1w                    56K      -    92K  -
tank/iocage/jails/hugo@2018-01-18_00.00.00--1w                    56K      -    92K  -
tank/iocage/jails/hugo@2018-01-19_00.00.00--1w                    56K      -    92K  -
tank/iocage/jails/hugo@2018-01-20_00.00.00--1w                    56K      -    92K  -
tank/iocage/jails/hugo@2018-01-21_00.00.00--1w                      0      -    92K  -
tank/iocage/jails/hugo@2018-01-21_00.00.00--2m                      0      -    92K  -
tank/iocage/jails/hugo/root@2018-01-07_00.00.00--2m             4.65M      -   744M  -
tank/iocage/jails/hugo/root@2018-01-14_21.46.00--1w                 0      -   749M  -
tank/iocage/jails/hugo/root@2018-01-14_21.47.00--2m                 0      -   749M  -
tank/iocage/jails/hugo/root@2018-01-15_00.00.00--1w                 0      -   749M  -
tank/iocage/jails/hugo/root@2018-01-16_00.00.00--1w             4.41M      -   749M  -
tank/iocage/jails/hugo/root@2018-01-17_00.00.00--1w             4.58M      -   749M  -
tank/iocage/jails/hugo/root@2018-01-18_00.00.00--1w             4.70M      -   750M  -
tank/iocage/jails/hugo/root@2018-01-19_00.00.00--1w             4.72M      -   750M  -
tank/iocage/jails/hugo/root@2018-01-20_00.00.00--1w             4.73M      -   751M  -
tank/iocage/jails/hugo/root@2018-01-21_00.00.00--1w                 0      -   751M  -
tank/iocage/jails/hugo/root@2018-01-21_00.00.00--2m                 0      -   751M  -
tank/iocage/log@2017-12-30_04.00.00--2m                           56K      -    88K  -
tank/iocage/log@2018-01-07_00.00.00--2m                           56K      -    92K  -
tank/iocage/log@2018-01-14_21.46.00--1w                             0      -    92K  -
tank/iocage/log@2018-01-14_21.47.00--2m                             0      -    92K  -
tank/iocage/log@2018-01-15_00.00.00--1w                             0      -    92K  -
tank/iocage/log@2018-01-16_00.00.00--1w                           56K      -    92K  -
tank/iocage/log@2018-01-17_00.00.00--1w                           56K      -    92K  -
tank/iocage/log@2018-01-18_00.00.00--1w                           56K      -    92K  -
tank/iocage/log@2018-01-19_00.00.00--1w                           56K      -    92K  -
tank/iocage/log@2018-01-20_00.00.00--1w                           56K      -    92K  -
tank/iocage/log@2018-01-21_00.00.00--1w                             0      -    92K  -
tank/iocage/log@2018-01-21_00.00.00--2m                             0      -    92K  -
tank/iocage/releases@2017-12-30_04.00.00--2m                      56K      -    88K  -
tank/iocage/releases@2018-01-07_00.00.00--2m                      56K      -    88K  -
tank/iocage/releases@2018-01-14_21.46.00--1w                        0      -    88K  -
tank/iocage/releases@2018-01-14_21.47.00--2m                        0      -    88K  -
tank/iocage/releases@2018-01-15_00.00.00--1w                        0      -    88K  -
tank/iocage/releases@2018-01-16_00.00.00--1w                      56K      -    88K  -
tank/iocage/releases@2018-01-17_00.00.00--1w                      56K      -    88K  -
tank/iocage/releases@2018-01-18_00.00.00--1w                      56K      -    88K  -
tank/iocage/releases@2018-01-19_00.00.00--1w                      56K      -    88K  -
tank/iocage/releases@2018-01-20_00.00.00--1w                      56K      -    88K  -
tank/iocage/releases@2018-01-21_00.00.00--1w                        0      -    88K  -
tank/iocage/releases@2018-01-21_00.00.00--2m                        0      -    88K  -
tank/iocage/releases/11.1-RELEASE@2017-12-30_04.00.00--2m         56K      -    88K  -
tank/iocage/releases/11.1-RELEASE@2018-01-07_00.00.00--2m         56K      -    88K  -
tank/iocage/releases/11.1-RELEASE@2018-01-14_21.46.00--1w           0      -    88K  -
tank/iocage/releases/11.1-RELEASE@2018-01-14_21.47.00--2m           0      -    88K  -
tank/iocage/releases/11.1-RELEASE@2018-01-15_00.00.00--1w           0      -    88K  -
tank/iocage/releases/11.1-RELEASE@2018-01-16_00.00.00--1w         56K      -    88K  -
tank/iocage/releases/11.1-RELEASE@2018-01-17_00.00.00--1w         56K      -    88K  -
tank/iocage/releases/11.1-RELEASE@2018-01-18_00.00.00--1w         56K      -    88K  -
tank/iocage/releases/11.1-RELEASE@2018-01-19_00.00.00--1w         56K      -    88K  -
tank/iocage/releases/11.1-RELEASE@2018-01-20_00.00.00--1w         56K      -    88K  -
tank/iocage/releases/11.1-RELEASE@2018-01-21_00.00.00--1w           0      -    88K  -
tank/iocage/releases/11.1-RELEASE@2018-01-21_00.00.00--2m           0      -    88K  -
tank/iocage/releases/11.1-RELEASE/root@2017-12-30_04.00.00--2m  1.23M      -   328M  -
tank/iocage/releases/11.1-RELEASE/root@hugo                     1.23M      -   328M  -
tank/iocage/releases/11.1-RELEASE/root@2018-01-07_00.00.00--2m  1.23M      -   328M  -
tank/iocage/releases/11.1-RELEASE/root@2018-01-14_21.46.00--1w      0      -   328M  -
tank/iocage/releases/11.1-RELEASE/root@2018-01-14_21.47.00--2m      0      -   328M  -
tank/iocage/releases/11.1-RELEASE/root@2018-01-15_00.00.00--1w      0      -   328M  -
tank/iocage/releases/11.1-RELEASE/root@2018-01-16_00.00.00--1w  1.23M      -   328M  -
tank/iocage/releases/11.1-RELEASE/root@2018-01-17_00.00.00--1w  1.23M      -   328M  -
tank/iocage/releases/11.1-RELEASE/root@2018-01-18_00.00.00--1w  1.23M      -   328M  -
tank/iocage/releases/11.1-RELEASE/root@2018-01-19_00.00.00--1w  1.23M      -   328M  -
tank/iocage/releases/11.1-RELEASE/root@2018-01-20_00.00.00--1w  1.23M      -   328M  -
tank/iocage/releases/11.1-RELEASE/root@2018-01-21_00.00.00--1w      0      -   328M  -
tank/iocage/releases/11.1-RELEASE/root@2018-01-21_00.00.00--2m      0      -   328M  -
tank/iocage/templates@2017-12-30_04.00.00--2m                     56K      -    88K  -
tank/iocage/templates@2018-01-07_00.00.00--2m                     56K      -    88K  -
tank/iocage/templates@2018-01-14_21.46.00--1w                       0      -    88K  -
tank/iocage/templates@2018-01-14_21.47.00--2m                       0      -    88K  -
tank/iocage/templates@2018-01-15_00.00.00--1w                       0      -    88K  -
tank/iocage/templates@2018-01-16_00.00.00--1w                     56K      -    88K  -
tank/iocage/templates@2018-01-17_00.00.00--1w                     56K      -    88K  -
tank/iocage/templates@2018-01-18_00.00.00--1w                     56K      -    88K  -
tank/iocage/templates@2018-01-19_00.00.00--1w                     56K      -    88K  -
tank/iocage/templates@2018-01-20_00.00.00--1w                     56K      -    88K  -
tank/iocage/templates@2018-01-21_00.00.00--1w                       0      -    88K  -
tank/iocage/templates@2018-01-21_00.00.00--2m                       0      -    88K  -
```
To check if those are the problem or not, I created a snapshot with `iocage snapshot <jail>` followed up by `iocage snaplist <jail>` and got the same thing:

```
[vendion@Heimdall][~]% sudo iocage snapshot hugo
********************************************************************************
fdescfs(5) is not mounted, performance may suffer. Please run:
mount -t fdescfs null /dev/fd
You can also permanently mount it in /etc/fstab with the following entry:
fdescfs /dev/fd  fdescfs  rw  0  0
********************************************************************************

Snapshot: tank/iocage/jails/hugo@2018-01-22_03:39:22 created.
[vendion@Heimdall][~]% sudo iocage snaplist hugo
********************************************************************************
fdescfs(5) is not mounted, performance may suffer. Please run:
mount -t fdescfs null /dev/fd
You can also permanently mount it in /etc/fstab with the following entry:
fdescfs /dev/fd  fdescfs  rw  0  0
********************************************************************************

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/snaplist.py", line 44, in cli
    _sort)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 1474, in snap_list
    name, snap_name = parent[0].split("@")
ValueError: not enough values to unpack (expected 2, got 1)
```
Checking ZFS again I do see that iocage did create a snapshot even though it can't list it

```
[vendion@Heimdall][~]% zfs list -t snapshot | grep iocage
tank/iocage@2017-12-30_04.00.00--2m                               64K      -    96K  -
tank/iocage@2018-01-07_00.00.00--2m                               56K      -   100K  -
tank/iocage@2018-01-14_21.46.00--1w                                 0      -   100K  -
tank/iocage@2018-01-14_21.47.00--2m                                 0      -   100K  -
tank/iocage@2018-01-15_00.00.00--1w                                 0      -   100K  -
tank/iocage@2018-01-16_00.00.00--1w                               56K      -   100K  -
tank/iocage@2018-01-17_00.00.00--1w                               56K      -   100K  -
tank/iocage@2018-01-18_00.00.00--1w                               56K      -   100K  -
tank/iocage@2018-01-19_00.00.00--1w                               56K      -   100K  -
tank/iocage@2018-01-20_00.00.00--1w                               56K      -   100K  -
tank/iocage@2018-01-21_00.00.00--1w                                 0      -   100K  -
tank/iocage@2018-01-21_00.00.00--2m                                 0      -   100K  -
tank/iocage/download@2017-12-30_04.00.00--2m                      56K      -    88K  -
tank/iocage/download@2018-01-07_00.00.00--2m                      56K      -    88K  -
tank/iocage/download@2018-01-14_21.46.00--1w                        0      -    88K  -
tank/iocage/download@2018-01-14_21.47.00--2m                        0      -    88K  -
tank/iocage/download@2018-01-15_00.00.00--1w                        0      -    88K  -
tank/iocage/download@2018-01-16_00.00.00--1w                      56K      -    88K  -
tank/iocage/download@2018-01-17_00.00.00--1w                      56K      -    88K  -
tank/iocage/download@2018-01-18_00.00.00--1w                      56K      -    88K  -
tank/iocage/download@2018-01-19_00.00.00--1w                      56K      -    88K  -
tank/iocage/download@2018-01-20_00.00.00--1w                      56K      -    88K  -
tank/iocage/download@2018-01-21_00.00.00--1w                        0      -    88K  -
tank/iocage/download@2018-01-21_00.00.00--2m                        0      -    88K  -
tank/iocage/download/11.1-RELEASE@2017-12-30_04.00.00--2m         56K      -   119M  -
tank/iocage/download/11.1-RELEASE@2018-01-07_00.00.00--2m         56K      -   119M  -
tank/iocage/download/11.1-RELEASE@2018-01-14_21.46.00--1w           0      -   119M  -
tank/iocage/download/11.1-RELEASE@2018-01-14_21.47.00--2m           0      -   119M  -
tank/iocage/download/11.1-RELEASE@2018-01-15_00.00.00--1w           0      -   119M  -
tank/iocage/download/11.1-RELEASE@2018-01-16_00.00.00--1w         56K      -   119M  -
tank/iocage/download/11.1-RELEASE@2018-01-17_00.00.00--1w         56K      -   119M  -
tank/iocage/download/11.1-RELEASE@2018-01-18_00.00.00--1w         56K      -   119M  -
tank/iocage/download/11.1-RELEASE@2018-01-19_00.00.00--1w         56K      -   119M  -
tank/iocage/download/11.1-RELEASE@2018-01-20_00.00.00--1w         56K      -   119M  -
tank/iocage/download/11.1-RELEASE@2018-01-21_00.00.00--1w           0      -   119M  -
tank/iocage/download/11.1-RELEASE@2018-01-21_00.00.00--2m           0      -   119M  -
tank/iocage/images@2017-12-30_04.00.00--2m                        56K      -    88K  -
tank/iocage/images@2018-01-07_00.00.00--2m                        56K      -    88K  -
tank/iocage/images@2018-01-14_21.46.00--1w                          0      -    88K  -
tank/iocage/images@2018-01-14_21.47.00--2m                          0      -    88K  -
tank/iocage/images@2018-01-15_00.00.00--1w                          0      -    88K  -
tank/iocage/images@2018-01-16_00.00.00--1w                        56K      -    88K  -
tank/iocage/images@2018-01-17_00.00.00--1w                        56K      -    88K  -
tank/iocage/images@2018-01-18_00.00.00--1w                        56K      -    88K  -
tank/iocage/images@2018-01-19_00.00.00--1w                        56K      -    88K  -
tank/iocage/images@2018-01-20_00.00.00--1w                        56K      -    88K  -
tank/iocage/images@2018-01-21_00.00.00--1w                          0      -    88K  -
tank/iocage/images@2018-01-21_00.00.00--2m                          0      -    88K  -
tank/iocage/jails@2017-12-30_04.00.00--2m                         56K      -    88K  -
tank/iocage/jails@2018-01-07_00.00.00--2m                         56K      -    88K  -
tank/iocage/jails@2018-01-14_21.46.00--1w                           0      -    88K  -
tank/iocage/jails@2018-01-14_21.47.00--2m                           0      -    88K  -
tank/iocage/jails@2018-01-15_00.00.00--1w                           0      -    88K  -
tank/iocage/jails@2018-01-16_00.00.00--1w                         56K      -    88K  -
tank/iocage/jails@2018-01-17_00.00.00--1w                         56K      -    88K  -
tank/iocage/jails@2018-01-18_00.00.00--1w                         56K      -    88K  -
tank/iocage/jails@2018-01-19_00.00.00--1w                         56K      -    88K  -
tank/iocage/jails@2018-01-20_00.00.00--1w                         56K      -    88K  -
tank/iocage/jails@2018-01-21_00.00.00--1w                           0      -    88K  -
tank/iocage/jails@2018-01-21_00.00.00--2m                           0      -    88K  -
tank/iocage/jails/hugo@2018-01-07_00.00.00--2m                    56K      -    92K  -
tank/iocage/jails/hugo@2018-01-14_21.46.00--1w                      0      -    92K  -
tank/iocage/jails/hugo@2018-01-14_21.47.00--2m                      0      -    92K  -
tank/iocage/jails/hugo@2018-01-15_00.00.00--1w                      0      -    92K  -
tank/iocage/jails/hugo@2018-01-16_00.00.00--1w                    56K      -    92K  -
tank/iocage/jails/hugo@2018-01-17_00.00.00--1w                    56K      -    92K  -
tank/iocage/jails/hugo@2018-01-18_00.00.00--1w                    56K      -    92K  -
tank/iocage/jails/hugo@2018-01-19_00.00.00--1w                    56K      -    92K  -
tank/iocage/jails/hugo@2018-01-20_00.00.00--1w                    56K      -    92K  -
tank/iocage/jails/hugo@2018-01-21_00.00.00--1w                      0      -    92K  -
tank/iocage/jails/hugo@2018-01-21_00.00.00--2m                      0      -    92K  -
tank/iocage/jails/hugo@2018-01-22_03:39:22                        56K      -    92K  -
tank/iocage/jails/hugo/root@2018-01-07_00.00.00--2m             4.65M      -   744M  -
tank/iocage/jails/hugo/root@2018-01-14_21.46.00--1w                 0      -   749M  -
tank/iocage/jails/hugo/root@2018-01-14_21.47.00--2m                 0      -   749M  -
tank/iocage/jails/hugo/root@2018-01-15_00.00.00--1w                 0      -   749M  -
tank/iocage/jails/hugo/root@2018-01-16_00.00.00--1w             4.41M      -   749M  -
tank/iocage/jails/hugo/root@2018-01-17_00.00.00--1w             4.58M      -   749M  -
tank/iocage/jails/hugo/root@2018-01-18_00.00.00--1w             4.70M      -   750M  -
tank/iocage/jails/hugo/root@2018-01-19_00.00.00--1w             4.72M      -   750M  -
tank/iocage/jails/hugo/root@2018-01-20_00.00.00--1w             4.73M      -   751M  -
tank/iocage/jails/hugo/root@2018-01-21_00.00.00--1w                 0      -   751M  -
tank/iocage/jails/hugo/root@2018-01-21_00.00.00--2m                 0      -   751M  -
tank/iocage/jails/hugo/root@2018-01-22_03:39:22                     0      -   751M  -
tank/iocage/log@2017-12-30_04.00.00--2m                           56K      -    88K  -
tank/iocage/log@2018-01-07_00.00.00--2m                           56K      -    92K  -
tank/iocage/log@2018-01-14_21.46.00--1w                             0      -    92K  -
tank/iocage/log@2018-01-14_21.47.00--2m                             0      -    92K  -
tank/iocage/log@2018-01-15_00.00.00--1w                             0      -    92K  -
tank/iocage/log@2018-01-16_00.00.00--1w                           56K      -    92K  -
tank/iocage/log@2018-01-17_00.00.00--1w                           56K      -    92K  -
tank/iocage/log@2018-01-18_00.00.00--1w                           56K      -    92K  -
tank/iocage/log@2018-01-19_00.00.00--1w                           56K      -    92K  -
tank/iocage/log@2018-01-20_00.00.00--1w                           56K      -    92K  -
tank/iocage/log@2018-01-21_00.00.00--1w                             0      -    92K  -
tank/iocage/log@2018-01-21_00.00.00--2m                             0      -    92K  -
tank/iocage/releases@2017-12-30_04.00.00--2m                      56K      -    88K  -
tank/iocage/releases@2018-01-07_00.00.00--2m                      56K      -    88K  -
tank/iocage/releases@2018-01-14_21.46.00--1w                        0      -    88K  -
tank/iocage/releases@2018-01-14_21.47.00--2m                        0      -    88K  -
tank/iocage/releases@2018-01-15_00.00.00--1w                        0      -    88K  -
tank/iocage/releases@2018-01-16_00.00.00--1w                      56K      -    88K  -
tank/iocage/releases@2018-01-17_00.00.00--1w                      56K      -    88K  -
tank/iocage/releases@2018-01-18_00.00.00--1w                      56K      -    88K  -
tank/iocage/releases@2018-01-19_00.00.00--1w                      56K      -    88K  -
tank/iocage/releases@2018-01-20_00.00.00--1w                      56K      -    88K  -
tank/iocage/releases@2018-01-21_00.00.00--1w                        0      -    88K  -
tank/iocage/releases@2018-01-21_00.00.00--2m                        0      -    88K  -
tank/iocage/releases/11.1-RELEASE@2017-12-30_04.00.00--2m         56K      -    88K  -
tank/iocage/releases/11.1-RELEASE@2018-01-07_00.00.00--2m         56K      -    88K  -
tank/iocage/releases/11.1-RELEASE@2018-01-14_21.46.00--1w           0      -    88K  -
tank/iocage/releases/11.1-RELEASE@2018-01-14_21.47.00--2m           0      -    88K  -
tank/iocage/releases/11.1-RELEASE@2018-01-15_00.00.00--1w           0      -    88K  -
tank/iocage/releases/11.1-RELEASE@2018-01-16_00.00.00--1w         56K      -    88K  -
tank/iocage/releases/11.1-RELEASE@2018-01-17_00.00.00--1w         56K      -    88K  -
tank/iocage/releases/11.1-RELEASE@2018-01-18_00.00.00--1w         56K      -    88K  -
tank/iocage/releases/11.1-RELEASE@2018-01-19_00.00.00--1w         56K      -    88K  -
tank/iocage/releases/11.1-RELEASE@2018-01-20_00.00.00--1w         56K      -    88K  -
tank/iocage/releases/11.1-RELEASE@2018-01-21_00.00.00--1w           0      -    88K  -
tank/iocage/releases/11.1-RELEASE@2018-01-21_00.00.00--2m           0      -    88K  -
tank/iocage/releases/11.1-RELEASE/root@2017-12-30_04.00.00--2m  1.23M      -   328M  -
tank/iocage/releases/11.1-RELEASE/root@hugo                     1.23M      -   328M  -
tank/iocage/releases/11.1-RELEASE/root@2018-01-07_00.00.00--2m  1.23M      -   328M  -
tank/iocage/releases/11.1-RELEASE/root@2018-01-14_21.46.00--1w      0      -   328M  -
tank/iocage/releases/11.1-RELEASE/root@2018-01-14_21.47.00--2m      0      -   328M  -
tank/iocage/releases/11.1-RELEASE/root@2018-01-15_00.00.00--1w      0      -   328M  -
tank/iocage/releases/11.1-RELEASE/root@2018-01-16_00.00.00--1w  1.23M      -   328M  -
tank/iocage/releases/11.1-RELEASE/root@2018-01-17_00.00.00--1w  1.23M      -   328M  -
tank/iocage/releases/11.1-RELEASE/root@2018-01-18_00.00.00--1w  1.23M      -   328M  -
tank/iocage/releases/11.1-RELEASE/root@2018-01-19_00.00.00--1w  1.23M      -   328M  -
tank/iocage/releases/11.1-RELEASE/root@2018-01-20_00.00.00--1w  1.23M      -   328M  -
tank/iocage/releases/11.1-RELEASE/root@2018-01-21_00.00.00--1w      0      -   328M  -
tank/iocage/releases/11.1-RELEASE/root@2018-01-21_00.00.00--2m      0      -   328M  -
tank/iocage/templates@2017-12-30_04.00.00--2m                     56K      -    88K  -
tank/iocage/templates@2018-01-07_00.00.00--2m                     56K      -    88K  -
tank/iocage/templates@2018-01-14_21.46.00--1w                       0      -    88K  -
tank/iocage/templates@2018-01-14_21.47.00--2m                       0      -    88K  -
tank/iocage/templates@2018-01-15_00.00.00--1w                       0      -    88K  -
tank/iocage/templates@2018-01-16_00.00.00--1w                     56K      -    88K  -
tank/iocage/templates@2018-01-17_00.00.00--1w                     56K      -    88K  -
tank/iocage/templates@2018-01-18_00.00.00--1w                     56K      -    88K  -
tank/iocage/templates@2018-01-19_00.00.00--1w                     56K      -    88K  -
tank/iocage/templates@2018-01-20_00.00.00--1w                     56K      -    88K  -
tank/iocage/templates@2018-01-21_00.00.00--1w                       0      -    88K  -
tank/iocage/templates@2018-01-21_00.00.00--2m                       0      -    88K  -
```

As an aside are is the datetime stamp from the iocage created snapshot (the one without the `--2m` or `--1w`) in UTC as that date is technically in the future at current time.

**Comment by vendion** [comment]
I probably should add that the snapshot naming scheme for the other snapshots is from [zfsnap](https://github.com/zfsnap/zfsnap) to do rolling snapshots.

**Comment by skarekrow** [comment]
Duplicate of #449.

Fixed in https://github.com/iocage/iocage/commit/16bca530be94d1850831673a65d52cfe6c5ecb10 :)

You can manually use GitHub to grab that version, or wait for the release to get this fixed. As far as UTC timestamps go, I do that to keep consistency, but I could look into using different timezones based on the users system. If that's important, file a ticket and I'll mark it as an enhancement :)

**Comment by vendion** [comment]
Sorry for the duplicate, I saw that issue but it seems to be slightly different to me as I all my snapshots were created by something other than iocage and this was failing where as in that issue they didn't mention that the had other snapshots than the only they created.

In a case like this one those how would `iocage snaplist` work as:

```
...
tank/iocage/jails/hugo@2018-01-21_00.00.00--2m                      0      -    92K  -  <- Not created by iocage
tank/iocage/jails/hugo@2018-01-22_03:39:22                        56K      -    92K  -  <- Created by iocage
```
Would it ignore the snapshots that have a ``--XX`` suffix and only display one entry or display all of them?

As for the timestamps being in UTC, it's not a big issue just seems odd for something that doesn't have to deal with datetime math, timezone conversions, or other datetime issues.
