### ISSUE TITLE
Listing templates doesn't work

### ISSUE THREAD

**Issue by erikagnvall** [iocage/iocage#5]
Installed iocage from source with `pip install .` and tried to create and list a template with the following result:

```
$ iocage list -t
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 11, in <module>
    load_entry_point('iocage==0.9', 'console_scripts', 'iocage')()
  File "/usr/local/lib/python2.7/site-packages/iocage/main.py", line 78, in main
    cli(obj=MODULES)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/iocage/cli/list.py", line 24, in list_cmd
    IOCList(dataset_type, header, _long).get_datasets()
  File "/usr/local/lib/python2.7/site-packages/iocage/lib/ioc_list.py", line 52, in get_datasets
    zfs_list = Popen(cmd, stdout=PIPE).communicate()[0].split()
UnboundLocalError: local variable 'cmd' referenced before assignment
```

Other info:
```sh
$ uname -ro
FreeBSD 11.0-RELEASE-p1
```
```sh
$ iocage --version
Version 0.9 2017/01/16
```
(Installed from bc5a0a5cc44b18ba6bfa622d89dfedbd37133222)

**Comment by skarekrow** [comment]
Creating templates doesn't work yet, and consequently neither will listing. Though this error is unrelated to either, I must have missed it when I was changing things around. Thanks for the report!

**Comment by skarekrow** [comment]
To create a template:
```
iocage set template="yes" JAIL
iocage create PROPS -t TEMPLATE
```

Let me know how this works 👍

**Comment by erikagnvall** [comment]
I was able to convert a jail to a template and create a new one from the template:

```
$ sudo iocage set template="yes" hello
fb78831a-1bc8-4193-b1c8-ae9e247a57b5 (hello) converted to a template.
$ sudo iocage create -t hello tag=wat
wat (8c053ca9-88c6-49a2-9275-4eec7796e78d) successfully created!

```
But running `iocage list -t` now results in:

```
$ iocage list -t
cannot open 'iocage/iocage/jails/fb78831a-1bc8-4193-b1c8-ae9e247a57b5/root': dataset does not exist
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 11, in <module>
    load_entry_point('iocage==0.9', 'console_scripts', 'iocage')()
  File "/usr/local/lib/python2.7/site-packages/iocage/main.py", line 78, in main
    cli(obj=MODULES)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/iocage/cli/list.py", line 24, in list_cmd
    IOCList(dataset_type, header, _long).get_datasets()
  File "/usr/local/lib/python2.7/site-packages/iocage/lib/ioc_list.py", line 111, in get_datasets
    templates = self.list_all(datasets)
  File "/usr/local/lib/python2.7/site-packages/iocage/lib/ioc_list.py", line 148, in list_all
    self.pool, uuid)]).split("/")[3]
  File "/usr/local/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['zfs', 'get', '-H', '-o', 'value', 'origin', 'iocage/iocage/jails/fb78831a-1bc8-4193-b1c8-ae9e247a57b5/root']' returned non-zero exit status 1
```

Listing the datasets in the iocage zpool indeed shows that the dataset doesn't exist:
```
$ zfs list -r iocage
NAME                                                            USED  AVAIL  REFER  MOUNTPOINT
iocage                                                          399M   561M    19K  /usr/iocage
iocage/iocage                                                   399M   561M    23K  /iocage
iocage/iocage/download                                          111M   561M    19K  /iocage/download
iocage/iocage/download/11.0-RELEASE                             111M   561M   111M  /iocage/download/11.0-RELEASE
iocage/iocage/images                                             19K   561M    19K  /iocage/images
iocage/iocage/jails                                            2.35M   561M    20K  /iocage/jails
iocage/iocage/jails/1fbfa602-45b4-4dea-8e99-5da73637d156       1.27M   561M  21.5K  /iocage/jails/1fbfa602-45b4-4dea-8e99-5da73637d156
iocage/iocage/jails/1fbfa602-45b4-4dea-8e99-5da73637d156/root  1.25M   561M   284M  /iocage/jails/1fbfa602-45b4-4dea-8e99-5da73637d156/root
iocage/iocage/jails/2d8ba309-67b6-43bd-a455-91b967f798f8         60K   561M  21.5K  /iocage/jails/2d8ba309-67b6-43bd-a455-91b967f798f8
iocage/iocage/jails/2d8ba309-67b6-43bd-a455-91b967f798f8/root  38.5K   561M   284M  /iocage/jails/2d8ba309-67b6-43bd-a455-91b967f798f8/root
iocage/iocage/jails/3a4a7ef4-0fea-419a-ab75-702790165c0d         36K   561M  21.5K  /iocage/jails/3a4a7ef4-0fea-419a-ab75-702790165c0d
iocage/iocage/jails/3a4a7ef4-0fea-419a-ab75-702790165c0d/root  14.5K   561M   284M  /iocage/jails/3a4a7ef4-0fea-419a-ab75-702790165c0d/root
iocage/iocage/jails/8ce54480-138d-4e39-8f12-204c64c4dac2        991K   561M  21.5K  /iocage/jails/8ce54480-138d-4e39-8f12-204c64c4dac2
iocage/iocage/jails/8ce54480-138d-4e39-8f12-204c64c4dac2/root   970K   561M   284M  /iocage/jails/8ce54480-138d-4e39-8f12-204c64c4dac2/root
iocage/iocage/log                                                22K   561M    22K  /iocage/log
iocage/iocage/releases                                          285M   561M    19K  /iocage/releases
iocage/iocage/releases/11.0-RELEASE                             285M   561M    19K  /iocage/releases/11.0-RELEASE
iocage/iocage/releases/11.0-RELEASE/root                        285M   561M   284M  /iocage/releases/11.0-RELEASE/root
iocage/iocage/templates                                          79K   561M    19K  /iocage/templates
iocage/iocage/templates/hello                                    60K   561M  21.5K  /iocage/templates/hello
iocage/iocage/templates/hello/root                             38.5K   561M   284M  /iocage/templates/hello/root
```

**Comment by skarekrow** [comment]
Fixed in https://github.com/iocage/iocage/commit/34108034fddcaab2530aaf3e5c49c7e5c8d18985.

Thanks for the report!
