### ISSUE TITLE
Errors, problems with creating new basejail on HardenedBSD

### ISSUE THREAD

**Issue by utrenkner** [iocage/iocage#502]
In May of last year, I created 4 basejails on HardenedBSD 11-STABLE. I now want to create a 5th basejail but this goes (partially) wrong. Especially, the newly created jail has the basejail property set to `no`.

-  `iocage --version`: Version 0.9.10 2017/12/22
- Supply the commands used, along with any steps to recreate it: `sudo iocage create -b -r 11-STABLE -n gitea1`
- Output from the command issued 
``` rm: /iocage/jails/gitea1/root/lib/libthr.so.3: Operation not permitted
rm: /iocage/jails/gitea1/root/lib/libc.so.7: Operation not permitted
rm: /iocage/jails/gitea1/root/lib/libcrypt.so.5: Operation not permitted
rm: /iocage/jails/gitea1/root/lib/librt.so.1: Operation not permitted
rm: /iocage/jails/gitea1/root/lib: Directory not empty
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/create.py", line 143, in cli
    basejail=basejail, empty=empty)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 643, in create
    exit_on_error=self.exit_on_error).create_jail()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_create.py", line 85, in create_jail
    return self._create_jail(jail_uuid, location)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_create.py", line 357, in _create_jail
    os.mkdir(destination)
FileExistsError: [Errno 17] File exists: '/iocage/jails/gitea1/root/lib'
```
- Supply what you expected the result or output to be: A new basejail named "gitea1", no error messages.

Further info:
```
zfs list -r zroot/iocage/releases
NAME                                   USED  AVAIL  REFER  MOUNTPOINT
zroot/iocage/releases                 1,91G   137G  9,56M  /iocage/releases
zroot/iocage/releases/11-STABLE       1,90G   137G  9,56M  /iocage/releases/11-STABLE
zroot/iocage/releases/11-STABLE/root  1,89G   137G   321M  /iocage/releases/11-STABLE/root
```

Excerpt from `iocage get -a gitea1`:
```
basejail:no
...
cloned_release:11-STABLE
...
jail_zfs_dataset:iocage/jails/gitea1/data
```

Output of `zfs get origin zroot/iocage/jails/gitea1/root`:
```
NAME                            PROPERTY  VALUE                                        SOURCE
zroot/iocage/jails/gitea1/root  origin    zroot/iocage/releases/11-STABLE/root@gitea1
```

Any idea, of why this fails? As everything else looks rather good: Could I somehow force setting `basejail=yes` (the command fails, saying the user cannot change the property basejail).

**Comment by utrenkner** [comment]
Stupid me!!! These are the files with the immutable flag set. Because I had (manually) updated the release using `hbsd-update -r /iocage/releases/11-STABLE/root`, the flags are set just like in a normal base system.

```
find /iocage/releases/11-STABLE/root -flags +schg -exec chflags noschg {} \;
```
solved the issue for me and I now have my gitea1 basejail!

**Comment by skarekrow** [comment]
Heh, great :+1:
