### ISSUE TITLE
Migrating jails fails if one is running a release that has not been fetched

### ISSUE THREAD

**Issue by asomers** [iocage/iocage#503]
- [x] Supply `iocage --version`
- [x] Supply the commands used, along with any steps to recreate it.
- [x] Provide the output from the command you issued.
- [x] Supply what you expected the result or output to be
- [ ] Checked that the problem has not already been fixed on `master` if using
 a stable release.

I previously installed some 11.0-RELEASE clone jails, and later upgraded one of them to 11.1-RELEASE with "iocage upgrade".  Today I upgraded iocage to a new version with pkg.  It told me I had to convert the jails to a new format.  When I tried, iocage crashed.  Apparently it was looking for a 11.1-RELEASE directory that isn't there.  Migrating the jails failed.

```
> iocage list
You need to be root to convert the configurations to the new format!
> sudo iocage list
Password:
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/list.py", line 114, in cli
    dataset_type, header, _long, _sort, plugin=plugins, quick=quick)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 1200, in list
    exit_on_error=self.exit_on_error).list_datasets()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_list.py", line 76, in list_datasets
    _all = self.list_all(ds)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_list.py", line 154, in list_all
    conf = iocage.lib.ioc_json.IOCJson(mountpoint).json_load()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 404, in json_load
    conf = self.json_check_config(conf)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 866, in json_check_config
    with open(freebsd_version, "r") as r:
FileNotFoundError: [Errno 2] No such file or directory: '/iocage/releases/11.1-RELEASE/root/bin/freebsd-version'
> iocage --version
Version 0.9.10 2017/12/22
```

**Comment by manfredu** [comment]
Maybe my problem with FreeNAS is related where iocage jails are no longer working after updating FreeNAS from 11.1-U2 to 11.1-U4. The error I get is [_"FileNotFoundError:] [Errno 2] No such file or directory: '/mnt/iocage/releases/11.1-RC3/root/bin/freebsd-version'"_: 

https://redmine.ixsystems.com/issues/31056

https://forums.freenas.org/index.php?threads/iocage-jails-no-longer-working-after-update-from-11-1-u2-to-11-1-u4.62818/#post-448869

What can I do to get my jails running again?

**Comment by skarekrow** [comment]
I replied to the ticket, but that's unrelated to this. This is for previous implementations, yours is fresh :)

**Comment by manfredu** [comment]
OK, thanks. Did you see my latest reply in the ticket?

**Comment by skarekrow** [comment]
Addressed by: https://github.com/iocage/iocage/commit/531a5cfc9906d9876dd7a969df30360b0e93596d, you could argue that we may wish to fetch for the user, but I think the user manually doing it in this case is the most fool proof.

**Comment by asomers** [comment]
It's not clear what that revision does.  And why does "iocage migrate" even need to have the release?  The jail in question was a clone jail that had been upgraded.  It shouldn't have any relationship to iocage's 11.1-RELEASE dataset.

**Comment by skarekrow** [comment]
That revision will throw a nicer error on a missing freebsd-version (this exception). Though reading your reply makes me think I misunderstood. Does this behavior still occur for you if you migrate again using the iocage-devel port? There have been a lot of commits to that area, I believe this is solved.

**Comment by asomers** [comment]
I long since had to destroy and recreate that jail.  But I could try again in a VM, if you'd like.  What version of iocage should I use to create the jail?

**Comment by skarekrow** [comment]
Oh I feared that. If you can somehow recall what version you used above to create those jails, that would be most useful. But I think 0.9.10 -> iocage-devel would be very helpful to find out.

*knock on wood* I think it's good.

**Comment by skarekrow** [comment]
Closing due to inactivity, this should be fixed at this point
