### ISSUE TITLE
'iocage create' causes Traceback when no release is specified

### ISSUE THREAD

**Issue by jsegaert** [iocage/iocage#507]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [X] Supply `iocage --version`
Latest / MASTER

- [X] Supply the commands used, along with any steps to recreate it.
**iocage create -n foo ip4_addr="em0|192.168.0.180"**

- [X] Provide the output from the command you issued.
```/home/jurgen jurgen@trinity%  sudo iocage create ip4_adr="em0|192.168.0.210"
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/create.py", line 103, in cli
    elif release.lower() == "latest":
AttributeError: 'NoneType' object has no attribute 'lower'
```
- [X] Supply what you expected the result or output to be
This was broken in one of the more recent commits.
Older versions handle this case by issuing a proper message: 
**Must supply either --template (-t) or --release (-r)!**

- [X] Checked that the problem has not already been fixed on `master` if using a stable release.
On the contrary, this still works in e.g. FreeNAS-11.1-U1, which also lists _Version 1.0 ALPHA_

**Comment by skarekrow** [comment]
Closed in #508
