### ISSUE TITLE
Iocage can't list snapshots 

### ISSUE THREAD

**Issue by brunoschwartz** [iocage/iocage#510]
Hello,-
I am having problems to see and revert to snapshots on an up-to-date 11.1 release. This is what I am getting
`$ sudo iocage snaplist backup
Password:
********************************************************************************
fdescfs(5) is not mounted, performance may suffer. Please run:
mount -t fdescfs null /dev/fd
You can also permanently mount it in /etc/fstab with the following entry:
fdescfs /dev/fd  fdescfs  rw  0  0
********************************************************************************

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/snaplist.py", line 44, in cli
    _sort)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 1474, in snap_list
    name, snap_name = parent[0].split("@")
ValueError: not enough values to unpack (expected 2, got 1)
`

Interestingly the snapshots are getting created correctly with iocage snapshot and they can be listed with zfs list -t.

- [ ] Supply `iocage --version`
...
Version 0.9.10 2017/12/22
...
- [ ] Supply the commands used, along with any steps to recreate it.
- [ ] Provide the output from the command you issued.
- [ ] Supply what you expected the result or output to be
- [ ] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by skarekrow** [comment]
`zfs list -t snap | grep backup` please

**Comment by brunoschwartz** [comment]
Hello,
Thanks for your response. Here is the output

$ zfs list -t snap | grep backup
zroot/iocage/jails/backup@auto-2017-12-31-23-55-00                    0      -   147K  -
zroot/iocage/jails/backup@12Jan18update                               0      -   147K  -
zroot/iocage/jails/backup@auto-2018-01-17-23-55-00                95.9K      -   147K  -
zroot/iocage/jails/backup@auto-2018-01-31-23-55-00                    0      -   147K  -
zroot/iocage/jails/backup@auto-2018-02-16-14-00-00                95.9K      -   147K  -
zroot/iocage/jails/backup@auto-2018-03-20-23-35-00                    0      -   147K  -
zroot/iocage/jails/backup/root@auto-2017-12-31-23-55-00            343M      -   379G  -
zroot/iocage/jails/backup/root@12Jan18update                       488M      -   444G  -
zroot/iocage/jails/backup/root@auto-2018-01-17-23-55-00            346M      -   499G  -
zroot/iocage/jails/backup/root@auto-2018-01-31-23-55-00           27.2G      -   489G  -
zroot/iocage/jails/backup/root@auto-2018-02-16-14-00-00           1.89G      -   454G  -
zroot/iocage/jails/backup/root@auto-2018-03-20-23-35-00               0      -   470G  -
zroot/iocage/releases/11.1-RELEASE/root@backup                        0      -   377M  -

There is an automated script which makes those auto snapshots through zfs snapshot. @12Jan18update is a manually created snapshot using "iocage snapshot" command.

Best regards,

B

**Comment by hxw** [comment]
I have same problem (with snaplist), I think 0.9.10 is just parsing the snapshot names incorrectly as the previous version woks ok.  I think this might be ok on master but I only looked through the code and have not tried to put master on yet.

--- edited:

I attempted to try master and snaplist does work, but there is more breakage:
`iocage list` is now broken reports: 
~~~
A renaming operation is required to continue.
Please run iocage -f -l as root.
~~~

When I ran `man iocage` the man page is broken - it appears that the the `/usr/local/man/man8/iocage.8.gz` installed was a tar containing `usr/home/tmoore/Projects/iocage/iocage/iocage.8` rather than the expected gzipped text.  If this file is extracted and the resulting `iocage.8` is gzipped and written over the installed `/usr/local/man/man8/iocage.8.gz` it does format correctly.  However the `-f` option seems not to be documented, so I will not run this rename until I have time to test this properly.

**Comment by hxw** [comment]
Just a follow up on the renaming: I did not run this, but determined by inspection the source code that the error is related to `tag` field in config.json.  Not all jails had a tag in config.jsone, so I removed it from the older jails (possible they were left in from earlier migration from uuid to name).
Aft tag field removed from all config.json files that hadthem the list commandworks perfectly.

Only remaining problem is man page: I used:
~~~
gzip < work-py36/iocage-2593d90e828ec13481da55958bf8b6fa96c9357a/iocage/iocage.8 > /usr/local/man/man8/iocage.8.gz
~~~
to install a working one. Since the iocage.8.gz in the same directory is invalid as mentioned previously; maybe you could just overwrite it using: `gzip < iocage.8 > iocage.8.gz` and commit.

Hopefully this will enable you to make a 0.9.11 version.

--- edit:
I ran snapshot, snaplist, and snapremove all ran successfully

**Comment by hxw** [comment]
@skarekrow any chance of tagging 0.9.11 ?

**Comment by skarekrow** [comment]
@hxw Nope. The next version will be 1.0 whenever time permits

**Comment by brunoschwartz** [comment]
Helllo both,

I checked and there is no tag field in the config.json of that jail.
The error still remains.
Why is it?

**Comment by hxw** [comment]
my jails originally came from a much older version, some were perhaps from the original shell iocage.  I did go through and make sure that all jails configs were aligned to the directory structure.  I had rename old uuid dirs to names and edited everything to line up.  The last cha I did was to remove all tags and the tags dir symlinks were also removed.  Then I patched the iocage port to build from master and make install that. It seems to be ok.  Only did this to one machine; I will wait for 1.0 befor touching any of the others.

**Comment by serge-vk** [comment]
Just ran into this problem today. the `snaplist` runs fine on any jails created with py-iocage, but fails as reported on any jails created with legacy iocage 1.7.6, even after the `tag` field is removed from `config.json`.

**Comment by skarekrow** [comment]
I don't believe this should affect 1.0 RELEASE anymore, closing due to inactivity. Please reopen if that's the case.

**Comment by hxw** [comment]
I have updated to py36-iocage-1.0 and snaplist command works for me, thanks for fixing this.

**Comment by skarekrow** [comment]
Great to hear @hxw, make sure to catch 1.1, lots of good fixes there too

**Comment by brunoschwartz** [comment]
Yes, it is working for me as well now. Many thanks.
