### ISSUE TITLE
JSONDecodeError while creating a basejail/template

### ISSUE THREAD

**Issue by tehfink** [iocage/iocage#52]
Error while creating a basejail template, on a fresh install of FreeBSD 11 & iocage from github today:

```bash
# iocage create allow_sysvipc=1 allow_raw_sockets=1 --pkglist=/iocage/pkgs.txt tag=template-01 --basejail ip4_addr="lo1|172.16.10.1/28" -r 11.0-RELEASE
080f59d7-565c-42c7-b8ba-fb8ae61ea32d (template-01) successfully created!
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 11, in <module>
    load_entry_point('iocage==0.9.6', 'console_scripts', 'iocage')()
  File "/usr/local/lib/python3.6/site-packages/iocage/main.py", line 92, in main
    cli(obj=MODULES)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/create.py", line 73, in create_cmd
    basejail=basejail).create_jail()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_create.py", line 171, in create_jail
    self.create_install_packages(jail_uuid, location, _tag, config)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_create.py", line 328, in create_install_packages
    self.pkglist = json.load(j)["pkgs"]
  File "/usr/local/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

The jail was created, but packages listed in `pkgs.txt` were not installed. Ping was enabled, however.

```bash
# iocage --version
Version 0.9.5 2017/02/15
# uname -a
FreeBSD changeme.local 11.0-RELEASE-p2 FreeBSD 11.0-RELEASE-p2 #0: Mon Oct 24 06:55:27 UTC 2016     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
# freebsd-version 
11.0-RELEASE-p7
```

**Comment by tehfink** [comment]
Apparently the `pkglist` argument only accepts JSON files now?
https://github.com/iocage/iocage/blob/f61aab7aa010c56be8c42eb0b6b59abe8a70a07a/iocage/cli/create.py#L53
vs.:
https://github.com/iocage/iocage/blob/3f441b72430c1cb9e1fa993f70ea14d6cf9629e2/doc/build/html/_sources/advanced-use.txt#L238

By the way, the JSON provided as an example in the link above does not validate:
```
Error: Parse error on line 4:
...		"foo",		"bar",	]}
--------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got ']'
```
(Just remove the the comma after "bar")

**Comment by skarekrow** [comment]
Yeah we actually check for that in newer versions, so make sure you update. Will fix that example.

**Comment by skarekrow** [comment]
So I thought I checked for that, turns out I didn't. Pushing a fix now :)
