### ISSUE TITLE
"exception" (multiple problem with iocage on FreeBSD 11.1)

### ISSUE THREAD

**Issue by denigmus** [iocage/iocage#523]
Version 0.9.10 2017/12/22
FreeBSD 11.1-RELEASE-p9

```
[root@home1 /iocage/jails/base]# iocage clone iotf --name base
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_create.py", line 203, in _create_jail
    f"@{jail_uuid}"], stderr=su.PIPE)
  File "/usr/local/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['zfs', 'snapshot', '-r', 'zroot1/iocage/jails/iotf@base']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/clone.py", line 64, in cli
    clone=True)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 643, in create
    exit_on_error=self.exit_on_error).create_jail()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_create.py", line 85, in create_jail
    return self._create_jail(jail_uuid, location)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_create.py", line 205, in _create_jail
    raise RuntimeError(f"Jail: {jail_uuid} not found!")
RuntimeError: Jail: base not found!
[root@home1 /iocage/jails/base]# iocage snaplist iotf
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/snaplist.py", line 44, in cli
    _sort)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 1474, in snap_list
    name, snap_name = parent[0].split("@")
ValueError: not enough values to unpack (expected 2, got 1)
[root@home1 /iocage/jails/base]#
```

I have similar problems with renaming/clonning/snapshoting

Only create/start/stop/destroy/set go smooth.

Is this project still alive?

**Comment by denigmus** [comment]
```
[root@home1 /iocage/jails]# iocage snaplist iotf
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/snaplist.py", line 44, in cli
    _sort)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 1474, in snap_list
    name, snap_name = parent[0].split("@")
ValueError: not enough values to unpack (expected 2, got 1)

```

These are jails:

```
[root@home1 /iocage/jails]# iocage list
+-----+------+-------+--------------+------------+
| JID | NAME | STATE |   RELEASE    |    IP4     |
+=====+======+=======+==============+============+
| -   | iotf | down  | 11.1-RELEASE | 10.1.1.123 |
+-----+------+-------+--------------+------------+
| -   | ns   | down  | 11.1-RELEASE | 10.1.1.11  |
+-----+------+-------+--------------+------------+
```

**Comment by skarekrow** [comment]
Why would this project not still be alive? I have a commit from not even a week ago. Please use the latest Github release until a proper release is tagged for ports.

**Comment by denigmus** [comment]
Well... provided your quick responses I would say it's definitely alive, but as for usability for production it's 3 from 5. :)
I would use iocell if not long uids that hurt my eyes.
