### ISSUE TITLE
Jails created from template won't start and be destroyed

### ISSUE THREAD

**Issue by denigmus** [iocage/iocage#524]
Do I understand correctly that this project is dead?

Could you help at least to clean the system from this non-destroyable jail pls? 

```
[root@home1 /iocage]# iocage clone iotf -n cleaninstall
chroot: /bin/sh: No such file or directory
cleaninstall successfully cloned!


[root@home1 /iocage]# iocage list
+-----+--------------+-------+--------------+------------+
| JID |     NAME     | STATE |   RELEASE    |    IP4     |
+=====+==============+=======+==============+============+
| -   | cleaninstall | down  | 11.1-RELEASE | 10.1.1.123 |
+-----+--------------+-------+--------------+------------+
| -   | iotf         | down  | 11.1-RELEASE | 10.1.1.123 |
+-----+--------------+-------+--------------+------------+
| -   | ns           | down  | 11.1-RELEASE | 10.1.1.11  |
+-----+--------------+-------+--------------+------------+


[root@home1 /iocage]# iocage set ip4_addr="lo1|10.1.1.254/24" cleaninstall
Property: ip4_addr has been updated to lo1|10.1.1.254/24


[root@home1 /iocage]# iocage list
+-----+--------------+-------+--------------+------------+
| JID |     NAME     | STATE |   RELEASE    |    IP4     |
+=====+==============+=======+==============+============+
| -   | cleaninstall | down  | 11.1-RELEASE | 10.1.1.254 |
+-----+--------------+-------+--------------+------------+
| -   | iotf         | down  | 11.1-RELEASE | 10.1.1.123 |
+-----+--------------+-------+--------------+------------+
| -   | ns           | down  | 11.1-RELEASE | 10.1.1.11  |
+-----+--------------+-------+--------------+------------+


[root@home1 /iocage]# iocage export cleaninstall
Exporting dataset: zroot1/iocage/jails/cleaninstall
Exporting dataset: zroot1/iocage/jails/cleaninstall/root

Preparing zip file: /iocage/images/cleaninstall_2018-04-17.zip.

Exported: /iocage/images/cleaninstall_2018-04-17.zip

[root@home1 /iocage]# iocage set template=yes cleaninstall
cleaninstall converted to a template.
Property: template has been updated to yes

[root@home1 /iocage/images]# iocage create -t cleaninstall --name redmine
chroot: /bin/sh: No such file or directory
redmine successfully created!

[root@home1 /iocage/jails/redmine]# iocage list
+-----+---------+-------+--------------+------------+
| JID |  NAME   | STATE |   RELEASE    |    IP4     |
+=====+=========+=======+==============+============+
| -   | iotf    | down  | 11.1-RELEASE | 10.1.1.123 |
+-----+---------+-------+--------------+------------+
| -   | ns      | down  | 11.1-RELEASE | 10.1.1.11  |
+-----+---------+-------+--------------+------------+
| -   | redmine | down  | 11.1-RELEASE | -          |
+-----+---------+-------+--------------+------------+

[root@home1 /iocage/jails/redmine]# iocage start redmine
* Starting redmine
  + Started OK
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/start.py", line 54, in cli
    ioc.IOCage(exit_on_error=True, jail=jail, rc=rc).start()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 1627, in start
    exit_on_error=self.exit_on_error)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_start.py", line 63, in __init__
    self.__start_jail__()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_start.py", line 410, in __start_jail__
    stdout=f, stderr=su.PIPE)
  File "/usr/local/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['setfib', '0', 'jexec', 'ioc-redmine', '/bin/sh', '/etc/rc']' returned non-zero exit status 1.

[root@home1 /iocage/jails/redmine]# iocage list
+-----+---------+-------+--------------+------------+
| JID |  NAME   | STATE |   RELEASE    |    IP4     |
+=====+=========+=======+==============+============+
| -   | iotf    | down  | 11.1-RELEASE | 10.1.1.123 |
+-----+---------+-------+--------------+------------+
| -   | ns      | down  | 11.1-RELEASE | 10.1.1.11  |
+-----+---------+-------+--------------+------------+
| 12  | redmine | up    | 11.1-RELEASE | -          |
+-----+---------+-------+--------------+------------+


[root@home1 /iocage/jails/redmine]# iocage console redmine
jexec: execvp: login: No such file or directory

[root@home1 /iocage/jails/redmine]# iocage stop redmine
* Stopping redmine
  + Running prestop OK
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/stop.py", line 54, in cli
    ioc.IOCage(exit_on_error=True, jail=jail, rc=rc).stop()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 1655, in stop
    exit_on_error=self.exit_on_error)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_stop.py", line 52, in __init__
    self.__stop_jail__()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_stop.py", line 142, in __stop_jail__
    stdout=f, stderr=su.PIPE)
  File "/usr/local/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['setfib', '0', 'jexec', 'ioc-redmine', '/bin/sh', '/etc/rc.shutdown']' returned non-zero exit status 1.

 
[root@home1 /iocage/jails/redmine]# iocage destroy redmine

This will destroy jail redmine

Are you sure? [y/N]: y
Stopping redmine
Destroying redmine
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/destroy.py", line 128, in cli
    skip_jails=True).destroy_jail()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 758, in destroy_jail
    exit_on_error=self.exit_on_error).destroy_jail(path)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_destroy.py", line 210, in destroy_jail
    iocage.lib.ioc_stop.IOCStop(uuid, path, conf, silent=True)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_stop.py", line 52, in __init__
    self.__stop_jail__()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_stop.py", line 142, in __stop_jail__
    stdout=f, stderr=su.PIPE)
  File "/usr/local/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['setfib', '0', 'jexec', 'ioc-redmine', '/bin/sh', '/etc/rc.shutdown']' returned non-zero exit status 1.

[root@home1 /iocage/jails/redmine]# iocage list
+-----+---------+-------+--------------+------------+
| JID |  NAME   | STATE |   RELEASE    |    IP4     |
+=====+=========+=======+==============+============+
| -   | iotf    | down  | 11.1-RELEASE | 10.1.1.123 |
+-----+---------+-------+--------------+------------+
| -   | ns      | down  | 11.1-RELEASE | 10.1.1.11  |
+-----+---------+-------+--------------+------------+
| 12  | redmine | up    | 11.1-RELEASE | -          |
+-----+---------+-------+--------------+------------+


```

**Comment by skarekrow** [comment]
I'd recommend you check your disks, it seems something isn't being mounted or is missing from your machine.

As for destroying the jail `iocage destroy -f redmine` should do it.

**Comment by denigmus** [comment]
Nothing is missed or not mounted. Fresh FreeBSD 11.1 zfs-root install where I only test iocage to see if it can be used in production.

The bug is still there after update to 1.0a

```
[root@home1 /iocage/jails]# iocage clone iotf -ntesttemplate
chroot: /bin/sh: No such file or directory
testtemplate successfully cloned!
[root@home1 /iocage/jails]# mount|grep testtemp
zroot1/iocage/jails/testtemplate on /iocage/jails/testtemplate (zfs, local, noatime, nfsv4acls)
zroot1/iocage/jails/testtemplate/root on /iocage/jails/testtemplate/root (zfs, local, noatime, nfsv4acls)
[root@home1 /iocage/jails]# iocage set template="yes" testtemplate
testtemplate converted to a template.
Property: template has been updated to yes
[root@home1 /iocage/jails]# iocage create -t testtemplate -n fromtemplate
chroot: /bin/sh: No such file or directory
fromtemplate successfully created!
[root@home1 /iocage/jails]# mount|grep testtempl
zroot1/iocage/templates/testtemplate on /iocage/templates/testtemplate (zfs, local, noatime, read-only, nfsv4acls)
zroot1/iocage/templates/testtemplate/root on /iocage/templates/testtemplate/root (zfs, local, noatime, read-only, nfsv4acls)
[root@home1 /iocage/jails]# mount|grep fromtempl
zroot1/iocage/jails/fromtemplate on /iocage/jails/fromtemplate (zfs, local, noatime, nfsv4acls)
zroot1/iocage/jails/fromtemplate/root on /iocage/jails/fromtemplate/root (zfs, local, noatime, nfsv4acls)
[root@home1 /iocage/jails]# iocage list
+-----+--------------+-------+--------------+------------+
| JID |     NAME     | STATE |   RELEASE    |    IP4     |
+=====+==============+=======+==============+============+
| -   | fromtemplate | down  | 11.1-RELEASE | -          |
+-----+--------------+-------+--------------+------------+
| -   | iotf         | down  | 11.1-RELEASE | 10.1.1.123 |
+-----+--------------+-------+--------------+------------+
| -   | ns           | down  | 11.1-RELEASE | 10.1.1.11  |
+-----+--------------+-------+--------------+------------+
| -   | something4   | down  | 11.1-RELEASE | 10.1.1.123 |
+-----+--------------+-------+--------------+------------+
[root@home1 /iocage/jails]# iocage start fromtemplate
* Starting fromtemplate
  + Started OK
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/start.py", line 54, in cli
    ioc.IOCage(exit_on_error=True, jail=jail, rc=rc).start()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 1638, in start
    exit_on_error=self.exit_on_error)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_start.py", line 64, in __init__
    self.__start_jail__()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_start.py", line 452, in __start_jail__
    stdout=f, stderr=su.PIPE)
  File "/usr/local/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['setfib', '0', 'jexec', 'ioc-fromtemplate', '/bin/sh', '/etc/rc']' returned non-zero exit status 1.
[root@home1 /iocage/jails]# iocage -v
Version 1.0 ALPHA
[root@home1 /iocage/jails]# mount
zroot1/ROOT/default on / (zfs, local, noatime, nfsv4acls)
devfs on /dev (devfs, local, multilabel)
fdescfs on /dev/fd (fdescfs)
procfs on /proc (procfs, local)
zroot1/iocage on /iocage (zfs, local, noatime, nfsv4acls)
zroot1/iocage/download on /iocage/download (zfs, local, noatime, nfsv4acls)
zroot1/iocage/download/11.1-RELEASE on /iocage/download/11.1-RELEASE (zfs, local, noatime, nfsv4acls)
zroot1/iocage/images on /iocage/images (zfs, local, noatime, nfsv4acls)
zroot1/iocage/jails on /iocage/jails (zfs, local, noatime, nfsv4acls)
zroot1/iocage/jails/iotf on /iocage/jails/iotf (zfs, local, noatime, nfsv4acls)
zroot1/iocage/jails/iotf/root on /iocage/jails/iotf/root (zfs, local, noatime, nfsv4acls)
zroot1/iocage/jails/ns on /iocage/jails/ns (zfs, local, noatime, nfsv4acls)
zroot1/iocage/jails/ns/root on /iocage/jails/ns/root (zfs, local, noatime, nfsv4acls)
zroot1/iocage/log on /iocage/log (zfs, local, noatime, nfsv4acls)
zroot1/iocage/releases on /iocage/releases (zfs, local, noatime, nfsv4acls)
zroot1/iocage/releases/11.1-RELEASE on /iocage/releases/11.1-RELEASE (zfs, local, noatime, nfsv4acls)
zroot1/iocage/releases/11.1-RELEASE/root on /iocage/releases/11.1-RELEASE/root (zfs, local, noatime, nfsv4acls)
zroot1/iocage/templates on /iocage/templates (zfs, local, noatime, nfsv4acls)
zroot1/mysqlfs on /mysqlfs (zfs, local, noatime, noexec, nosuid, nfsv4acls)
zroot1/tmp on /tmp (zfs, local, noatime, nosuid, nfsv4acls)
zroot1/usr/home on /usr/home (zfs, local, noatime, nfsv4acls)
zroot1/usr/ports on /usr/ports (zfs, local, noatime, nosuid, nfsv4acls)
zroot1/usr/src on /usr/src (zfs, local, noatime, nfsv4acls)
zroot1/var/audit on /var/audit (zfs, local, noatime, noexec, nosuid, nfsv4acls)
zroot1/var/crash on /var/crash (zfs, local, noatime, noexec, nosuid, nfsv4acls)
zroot1/var/log on /var/log (zfs, local, noatime, noexec, nosuid, nfsv4acls)
zroot1/var/mail on /var/mail (zfs, local, nfsv4acls)
zroot1/var/tmp on /var/tmp (zfs, local, noatime, nosuid, nfsv4acls)
zroot1/iocage/jails/something4 on /iocage/jails/something4 (zfs, local, noatime, nfsv4acls)
zroot1/iocage/templates/testtemplate on /iocage/templates/testtemplate (zfs, local, noatime, read-only, nfsv4acls)
zroot1/iocage/templates/testtemplate/root on /iocage/templates/testtemplate/root (zfs, local, noatime, read-only, nfsv4acls)
zroot1/iocage/jails/fromtemplate on /iocage/jails/fromtemplate (zfs, local, noatime, nfsv4acls)
zroot1/iocage/jails/fromtemplate/root on /iocage/jails/fromtemplate/root (zfs, local, noatime, nfsv4acls)
devfs on /iocage/jails/fromtemplate/root/dev (devfs, local, multilabel)
fdescfs on /iocage/jails/fromtemplate/root/dev/fd (fdescfs)

```

**Comment by skarekrow** [comment]
Can you paste the fstab of the jail? I'm pretty sure this is related to the same problem.

**Comment by denigmus** [comment]
fstab is actually empty, so it's a bug, not a question ;)

**Comment by denigmus** [comment]
>As for destroying the jail iocage destroy -f redmine should do it.

It's not. But 'jail -r ID' will do

**Comment by ghost** [comment]
I have noticed this too. I created a basejail, did some configuration and installed some packages. I then set that jail to be a template and attempted to create a new jail based on that template. The `iocage create -t templatejail -n testjail` command shows a
```shell
chroot: /bin/sh: No such file or directory
```
message before exiting. The resulting testjail can not be properly started or stopped.
