### ISSUE TITLE
TypeError while trying to create a jail

### ISSUE THREAD

**Issue by tehfink** [iocage/iocage#55]
```bash
# cat /iocage/pkgs.json 
{
    "pkgs": [
    "nano",
    "screen"
    ]
}
# iocage create --pkglist=/iocage/pkgs.json -r 11.0-RELEASE tag=www host_hostname=www allow_sysvipc=1 allow_raw_sockets=1 ip4_addr="lo1|172.16.10.3/28"
b6af38cd-4352-4016-8146-72ea05c259c4 (www) successfully created!
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 11, in <module>
    load_entry_point('iocage==0.9.6', 'console_scripts', 'iocage')()
  File "/usr/local/lib/python3.6/site-packages/iocage/main.py", line 92, in main
    cli(obj=MODULES)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/create.py", line 81, in create_cmd
    basejail=basejail).create_jail()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_create.py", line 171, in create_jail
    self.create_install_packages(jail_uuid, location, _tag, config)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_create.py", line 327, in create_install_packages
    with open(self.pkglist, "r") as j:
TypeError: expected str, bytes or os.PathLike object, not list
```
Versions:
```bash
# iocage --version
Version 0.9.6 2017/02/26
# uname -a
FreeBSD changeme.local 11.0-RELEASE-p8 FreeBSD 11.0-RELEASE-p8 #0: Wed Feb 22 06:12:04 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
# freebsd-version
11.0-RELEASE-p8
```

**Comment by skarekrow** [comment]
D'oh! Thanks for the report, should be fixed 👍
