### ISSUE TITLE
iocage export/import, for archiving and sending to remote hosts

### ISSUE THREAD

**Issue by vin047** [iocage/iocage#554]
Version 0.9.10 2017/12/22

```
iocage export app0001
iocage destroy app0001
iocage import app0001
```

```python
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/import.py", line 36, in cli
    ioc.IOCage(exit_on_error=True, jail=jail).import_()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 1178, in import_
    exit_on_error=self.exit_on_error).import_jail(self.jail)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_image.py", line 210, in import_jail
    date = matches[0].rsplit("_")[1].strip(".zip")
IndexError: list index out of range
```

My actual goal is to be able to archive a jail into a file for backup and for deploying remotely. I tried doing this by sending the ZFS dataset directly but couldn't get it to work (my understanding of ZFS datasets is limited). Thought the export/import commands iocage provides would make things simpler but no idea whats causing this issue. Any help?

**Comment by vin047** [comment]
Had a chance to try this again recently - and it seems to be working now. Pretty sure I didn't change anything, was still running 11.1-RELEASE at the time, no software updates since I reported the issue, using iocage 0.9.10 still...

The issue does occur when you remove the `_DATE` portion, which is what the traceback complains about. Pretty sure that I tried it without renaming too, i.e. quite literally:
```
iocage export app0001
iocage destroy app0001
iocage import app0001
```

But anyways, it seems to be working now as long as I don't remove the `_DATE`. Would be nice if it didn't need the date in the filename but I guess thats more of an enhancement then a bug 🙂
