### ISSUE TITLE
Feature suggestion: Prevent changing jail_zfs and jail_zfs_dataset while jail is running

### ISSUE THREAD

**Issue by jsegaert** [iocage/iocage#556]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [X] Supply `iocage --version`
latest master
- [X] Supply the commands used, along with any steps to recreate it.
```
/root root@trinity#  iocage create -n foo -r latest 
foo successfully created!

/root root@trinity#  iocage start foo
* Starting foo
  + Started OK
  + Starting services OK

/root root@trinity#  iocage set jail_zfs=on foo
Property: jail_zfs has been updated to on
```
- [X] Provide the output from the command you issued.
Now if you attempt to stop the jail, it crashes.  
```
/root root@trinity#  iocage stop foo
* Stopping foo
  + Running prestop OK
  + Stopping services OK
cannot open 'tank/iocage/jails/foo/data': dataset does not exist
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/stop.py", line 54, in cli
    ioc.IOCage(exit_on_error=True, jail=jail, rc=rc).stop()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 1623, in stop
    exit_on_error=self.exit_on_error)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_stop.py", line 52, in __init__
    self.__stop_jail__()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_stop.py", line 168, in __stop_jail__
    f"{self.pool}/{jdataset}"])
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_common.py", line 450, in checkoutput
    out = su.check_output(*args, **kwargs)
  File "/usr/local/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['zfs', 'list', '-H', '-r', '-o', 'name', '-S', 'name', 'tank/iocage/jails/foo/data']' returned non-zero exit status 1.
```
Same result when changing the default dataset e.g.
`iocage set jail_zfs_dataset="iocage/jails/foo/media" foo`.  Even when you create the new dataset manually, it's no longer aware of the original jail_zfs_dataset and it will only unmount and unjail the new dataset.  The old dataset stays as is, causing ZFSExceptions when renaming etc... 

- [X] Supply what you expected the result or output to be

Would you accept a PR to improve exception handing and prevent changes to jail_zfs and jail_zfs_dataset while jail is running, similar to what happens when attempting to set template=yes|no
```
/root root@trinity#  iocage set jail_zfs_dataset="iocage/jails/foo/media" foo
foo is running.
Please stop it first!
```
- [ ] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by skarekrow** [comment]
I agree, this should not be allowed to be changed while the jail is running

**Comment by jsegaert** [comment]
This was successfully merged in master
