### ISSUE TITLE
Destroy Jail gives traceback errors

### ISSUE THREAD

**Issue by NasKar2** [iocage/iocage#560]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [ ] Supply `iocage --version` Version	1.0 ALPHA

- [ ] Supply the commands used, along with any steps to recreate it. iocage destroy nextcloudMan2

- [ ] Provide the output from the command you issued.
Stopping nextcloudMan2
Destroying nextcloudMan2
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/destroy.py", line 128, in cli
    skip_jails=True).destroy_jail()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 703, in destroy_jail
    exit_on_error=self.exit_on_error).destroy_jail(path)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_destroy.py", line 250, in destroy_jail
    iocage.lib.ioc_stop.IOCStop(uuid, path, conf, silent=True)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_stop.py", line 52, in __init__
    self.__stop_jail__()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_stop.py", line 144, in __stop_jail__
    stdout=f, stderr=su.PIPE)
  File "/usr/local/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['setfib', '0', 'jexec', 'ioc-nextcloudMan2', '/bin/sh', '/etc/rc.shutdown']' returned non-zero exit status 1.

- [ ] Supply what you expected the result or output to be Destroying nextcloudMan2

- [ ] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by skarekrow** [comment]
Closed by #571
