### ISSUE TITLE
python error when running iocage via ssh

### ISSUE THREAD

**Issue by joachimmathes** [iocage/iocage#58]
I use ansible for configuration management. When running iocage via the `shell` module a python error occurs. This can be reproduced with a simple `ssh` command, since this is what ansible uses:

```
$ ssh <VAGRANTBOX> iocage
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 11, in <module>
    load_entry_point('iocage==0.9.6', 'console_scripts', 'iocage')()
  File "/usr/local/lib/python3.6/site-packages/iocage/main.py", line 74, in main
    format='%(message)s')
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1776, in basicConfig
    h = FileHandler(filename, mode)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1025, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1054, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 29] Illegal seek
```

Running `ssh` with the `-t` to force pseudo-tty allocation works:

```
$ ssh -t <VAGRANTBOX> iocage
Usage: iocage [OPTIONS] COMMAND [ARGS]...

  A jail manager.

Options:
  -v, --version  Display iocage's version and exit.
  --help         Show this message and exit.
...
```

I don't know if it's actually an iocage issue, or a fundamental problem with python3: https://bugs.python.org/issue27805 

I tried the current master release of iocage (https://github.com/iocage/iocage/commit/fa2dbc74281c1daee8d069d27c74c6780bcddefd)

**Comment by joachimmathes** [comment]
Running `iocage get all <JAIL> | grep hostname` in my FreeBSD 11.0-RELEASE-p7 vagrant box aborts with:
```
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 11, in <module>
    load_entry_point('iocage==0.9.6', 'console_scripts', 'iocage')()
  File "/usr/local/lib/python3.6/site-packages/iocage/main.py", line 74, in main
    format='%(message)s')
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1776, in basicConfig
    h = FileHandler(filename, mode)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1025, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1054, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 29] Illegal seek
```

**Comment by skarekrow** [comment]
Ah, got bit with this moving to Python 3. I'd say this is a Python bug, but since we clearly weren't handling it well, it's probably an iocage one too in that case. Either way, that link was very helpful, thanks!
