### ISSUE TITLE
iocage fetch options --server and --file options fail to work on TrueOS-18.03

### ISSUE THREAD

**Issue by mrT55** [iocage/iocage#594]
The following two issues seems to make iocage unusable on TrueOS:
```
1. iocage fetch --- fails to allow overiding the --server --root-dir (URL path)
   for the TrueOS system files at http://download.trueos.org/master/amd64/dist

2. iocage fetch --- fails to allow fetching from a local directory.
```
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x ] Supply `iocage --version`
iocage --version
Version 0.9.10 2017/12/22

```
uname -a
   FreeBSD trueos-8503 12.0-CURRENT FreeBSD 12.0-CURRENT #26 fa797a5a3(trueos-stable-18.03):
           Mon Mar 26 00:24:47 UTC 2018     root@chimera:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64

OS git branch ……………………………………………………………………………………… trueos-stable-18.03
OS git revision ………………………………………………………………………………… fa797a5a3
OS kernel identity …………………………………………… (uname -i) GENERIC
OS platform (architecture) ……………………… (uname -m) amd64
OS release level ………………………………………………… (uname -r) 12.0-CURRENT
OS version and patch level …… (freebsd-version) 12.0-CURRENT
TrueOS package set ………………… STABLE
TrueOS version …………………………… TrueOS-Desktop-201803131015
```
- [X] Supply the commands used, along with any steps to recreate it.

This fails to overide the default server URL (and '--root-dir' does not help):
```
iocage fetch --noupdate --noeol --server download.trueos.org
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 166, in cli
    ioc.IOCage(exit_on_error=True).fetch(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 993, in fetch
    silent=self.silent, **kwargs).fetch_release()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 234, in fetch_release
    rel = self.fetch_http_release(eol, _list=_list)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 440, in fetch_http_release
    req.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 937, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://download.trueos.org/ftp/releases/amd64



iocage fetch --noupdate --noeol --server download.trueos.org/master/amd64/dist
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 166, in cli
    ioc.IOCage(exit_on_error=True).fetch(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 993, in fetch
    silent=self.silent, **kwargs).fetch_release()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 234, in fetch_release
    rel = self.fetch_http_release(eol, _list=_list)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 440, in fetch_http_release
    req.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 937, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://download.trueos.org/master/amd64/dist/ftp/releases/amd64


iocage fetch --noupdate --noeol --server download.trueos.org  --root-dir /master/amd64/dist
    No RELEASEs were found at http://download.trueos.org//master/amd64/dist!
    Please ensure the server is correct and the root-dir is
    pointing to a top-level directory with the format:
        - XX.X-RELEASE
        - XX.X-RELEASE
        - XX.X_RELEASE
```
This failed to allow fetching of my current host version: 12.0-CURRENT or trueos-stable-18.03:
```
fetch http://download.trueos.org/master/amd64/dist/
I downloaded all eleven files an saved them to:

cd /home/mark/TrueOS/unstable.dist_20180418/ftp/releases/amd64/12.0-CURRENT
ls -l
-rw-r--r--  1 mark  mark  156404056 Apr 18 14:40 base-dbg.txz
-rw-r--r--  1 mark  mark  158403264 Apr 18 14:40 base.txz
-rw-r--r--  1 mark  mark     413776 Apr 18 14:40 distrib.txz
-rw-r--r--  1 mark  mark        180 Apr 18 14:40 doc.txz
-rw-r--r--  1 mark  mark   76610912 Apr 18 14:40 kernel-dbg.txz
-rw-r--r--  1 mark  mark   40378888 Apr 18 14:40 kernel.txz
-rw-r--r--  1 mark  mark   15399788 Apr 18 14:40 lib32-dbg.txz
-rw-r--r--  1 mark  mark   58512040 Apr 18 14:40 lib32.txz
-rw-r--r--  1 mark  mark       1146 Apr 18 14:40 MANIFEST
-rw-r--r--  1 mark  mark  685231348 Apr 18 14:40 src.txz
-rw-r--r--  1 mark  mark    7818168 Apr 18 14:40 tests.txz

iocage fetch --noupdate --noeol -f --file /home/mark/TrueOS/unstable.dist_20180418
[0] 9.3-RELEASE
[1] 10.1-RELEASE
[2] 10.2-RELEASE
[3] 10.3-RELEASE
[4] 10.4-RELEASE
[5] 11.0-RELEASE
[6] 11.1-RELEASE
[7] 11.2-RELEASE

Type the number of the desired RELEASE
Press [Enter] to fetch the default selection: (Not a RELEASE)
Type EXIT to quit:



----

iocage fetch --noupdate --noeol -f --file /home/mark/TrueOS/unstable.dist_20180418/ftp/releases/amd64/12.0-CURRENT
[0] 9.3-RELEASE
[1] 10.1-RELEASE
[2] 10.2-RELEASE
[3] 10.3-RELEASE
[4] 10.4-RELEASE
[5] 11.0-RELEASE
[6] 11.1-RELEASE
[7] 11.2-RELEASE

Type the number of the desired RELEASE
Press [Enter] to fetch the default selection: (Not a RELEASE)
Type EXIT to quit:


iocage fetch --noupdate --noeol -f --file /home/mark/TrueOS/unstable.dist_20180418/ftp/releases/amd64
[0] 9.3-RELEASE
[1] 10.1-RELEASE
[2] 10.2-RELEASE
[3] 10.3-RELEASE
[4] 10.4-RELEASE
[5] 11.0-RELEASE
[6] 11.1-RELEASE
[7] 11.2-RELEASE

Type the number of the desired RELEASE
Press [Enter] to fetch the default selection: (Not a RELEASE)
Type EXIT to quit:


iocage fetch --noupdate --noeol -f --file /home/mark/TrueOS/unstable.dist_20180418  --root-dir /ftp/releases/amd64/12.0-CURRENT
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 166, in cli
    ioc.IOCage(exit_on_error=True).fetch(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 993, in fetch
    silent=self.silent, **kwargs).fetch_release()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 234, in fetch_release
    rel = self.fetch_http_release(eol, _list=_list)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 440, in fetch_http_release
    req.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 937, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://download.freebsd.org/ftp/releases/amd64/12.0-CURRENT

```
- [x ] Provide the output from the command you issued.
- [x] Supply what you expected the result or output to be
I expect to be able to override the the default URL and fetch from: download.trueos.org/master/amd64/dist
and not impose specific restrictions on the URL address/path.

I also expect to be able to override the fetch from a URL and fetch from a local directory
such as '/home/mark/TrueOS/unstable.dist_20180418/ftp/releases/amd64/12.0-CURRENT'
and not impose specific restrictions on the directory naming. (Or at least minimal restrictions.)

- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by skarekrow** [comment]
Currently iocage only supports RELEASE fetching, not CURRENT. In addition the structure is specific and pointed out in the error that was returned. File simple points to a directory hierarchy that has the same layout as a server:
```
    No RELEASEs were found at http://download.trueos.org//master/amd64/dist!
    Please ensure the server is correct and the root-dir is
    pointing to a top-level directory with the format:
        - XX.X-RELEASE
        - XX.X-RELEASE
        - XX.X_RELEASE
```

In this case they're working as intended. If you want what you're doing to function, create a dataset at `iocage/download/12-CURRENT` and put those dists there. Then do `iocage fetch` and type in manually `12-CURRENT`. That should let you bypass this restriction.

**Comment by mrT55** [comment]
iocage fetch --- '-f --file' options fail to overide the search for distribution files to
a local path-directory.

I tried the following several different ways that I could think of and they all failed.
```
zfs list -r tank/iocage
    NAME                    USED  AVAIL  REFER  MOUNTPOINT
    tank/iocage             163K  94.0G    25K  /iocage
    tank/iocage/download     23K  94.0G    23K  /iocage/download
    tank/iocage/images       23K  94.0G    23K  /iocage/images
    tank/iocage/jails        23K  94.0G    23K  /iocage/jails
    tank/iocage/log          23K  94.0G    23K  /iocage/log
    tank/iocage/releases     23K  94.0G    23K  /iocage/releases
    tank/iocage/templates    23K  94.0G    23K  /iocage/templates

I moved the dist files to:
    /home/mark/TrueOS/dist/iocage/download/12-CURRENT
.
ls -l
    -rw-r--r--  1 mark  mark  156404056 Apr 18 14:40 base-dbg.txz
    -rw-r--r--  1 mark  mark  158403264 Apr 18 14:40 base.txz
    -rw-r--r--  1 mark  mark     413776 Apr 18 14:40 distrib.txz
    -rw-r--r--  1 mark  mark        180 Apr 18 14:40 doc.txz
    -rw-r--r--  1 mark  mark   76610912 Apr 18 14:40 kernel-dbg.txz
    -rw-r--r--  1 mark  mark   40378888 Apr 18 14:40 kernel.txz
    -rw-r--r--  1 mark  mark   15399788 Apr 18 14:40 lib32-dbg.txz
    -rw-r--r--  1 mark  mark   58512040 Apr 18 14:40 lib32.txz
    -rw-r--r--  1 mark  mark       1146 Apr 18 14:40 MANIFEST
    -rw-r--r--  1 mark  mark  685231348 Apr 18 14:40 src.txz
    -rw-r--r--  1 mark  mark    7818168 Apr 18 14:40 tests.txz

iocage fetch --noupdate --noeol -f --file /home/mark/TrueOS/dist/iocage/download
     [0] 9.3-RELEASE
     [1] 10.1-RELEASE
     [2] 10.2-RELEASE
     [3] 10.3-RELEASE
     [4] 10.4-RELEASE
     [5] 11.0-RELEASE
     [6] 11.1-RELEASE
     [7] 11.2-RELEASE

     Type the number of the desired RELEASE
     Press [Enter] to fetch the default selection: (Not a RELEASE)
     Type EXIT to quit: 12-CURRENT
     '12-CURRENT' is not in list

iocage fetch --noupdate --noeol -f --file /home/mark/TrueOS/dist/iocage/download/12-CURRENT
    [0] 9.3-RELEASE
    [1] 10.1-RELEASE
    [2] 10.2-RELEASE
    [3] 10.3-RELEASE
    [4] 10.4-RELEASE
    [5] 11.0-RELEASE
    [6] 11.1-RELEASE
    [7] 11.2-RELEASE

    Type the number of the desired RELEASE
    Press [Enter] to fetch the default selection: (Not a RELEASE)
    Type EXIT to quit:


moved the dist files to:
    /iocage/download/12-CURRENT

zfs list -r tank/iocage
    NAME                    USED  AVAIL  REFER  MOUNTPOINT
    tank/iocage            1.12G  92.9G    25K  /iocage
    tank/iocage/download   1.12G  92.9G  1.12G  /iocage/download
    tank/iocage/images       23K  92.9G    23K  /iocage/images
    tank/iocage/jails        23K  92.9G    23K  /iocage/jails
    tank/iocage/log          23K  92.9G    23K  /iocage/log
    tank/iocage/releases     23K  92.9G    23K  /iocage/releases
    tank/iocage/templates    23K  92.9G    23K  /iocage/templates


iocage fetch --noupdate --noeol -f --file /iocage/download
    [0] 9.3-RELEASE
    [1] 10.1-RELEASE
    [2] 10.2-RELEASE
    [3] 10.3-RELEASE
    [4] 10.4-RELEASE
    [5] 11.0-RELEASE
    [6] 11.1-RELEASE
    [7] 11.2-RELEASE

    Type the number of the desired RELEASE
    Press [Enter] to fetch the default selection: (Not a RELEASE)
    Type EXIT to quit:


iocage fetch --noupdate --noeol -f --file /iocage/download/12-CURRENT
        [0] 9.3-RELEASE
        [1] 10.1-RELEASE
        [2] 10.2-RELEASE
        [3] 10.3-RELEASE
        [4] 10.4-RELEASE
        [5] 11.0-RELEASE
        [6] 11.1-RELEASE
        [7] 11.2-RELEASE

        Type the number of the desired RELEASE
        Press [Enter] to fetch the default selection: (Not a RELEASE)
        Type EXIT to quit:

iocage fetch --noupdate --noeol
    [0] 9.3-RELEASE
    [1] 10.1-RELEASE
    [2] 10.2-RELEASE
    [3] 10.3-RELEASE
    [4] 10.4-RELEASE
    [5] 11.0-RELEASE
    [6] 11.1-RELEASE
    [7] 11.2-RELEASE

    Type the number of the desired RELEASE
    Press [Enter] to fetch the default selection: (Not a RELEASE)
    Type EXIT to quit:
```
