### ISSUE TITLE
iocage list -r with non-standard name of the release fails

### ISSUE THREAD

**Issue by netchild** [iocage/iocage#596]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [ ] Supply `iocage --version`

0.9.10

- [ ] Supply the commands used, along with any steps to recreate it.

iocage list -r

- [ ] Provide the output from the command you issued.

```python-traceback
# iocage list -r
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/list.py", line 114, in cli
    dataset_type, header, _long, _sort, plugin=plugins, quick=quick)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 1200, in list
    exit_on_error=self.exit_on_error).list_datasets()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_list.py", line 96, in list_datasets
    bases = self.list_bases(ds)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_list.py", line 305, in list_bases
    exit_on_error=self.exit_on_error)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_common.py", line 140, in ioc_sort
    return sort_release(data, split=True)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_common.py", line 298, in sort_release
    rel = float(rel)
ValueError: could not convert string to float: 'r323637M'
```

- [ ] Supply what you expected the result or output to be

```sh-session
# ioc list -r
+------------------+
|    FULL_NAME     |
+==================+
| r323637M-RELEASE |
+------------------+
| r326049M-RELEASE |
+------------------+
| 11.2-RELEASE     |
+------------------+
| r332871M-RELEASE |
+------------------+
```

- [ ] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by skarekrow** [comment]
This is likely to remain not fixed until libiocage becomes merged, as the expectation is the RELEASEs conform to FreeBSD naming standards.

Good bug though ;)

**Comment by bartekrutkowski** [comment]
@skarekrow isn't libiocage merged now? Is it still a bug?

**Comment by skarekrow** [comment]
@bartekrutkowski No, that has not been merged.
