### ISSUE TITLE
"iocage list" fails with error if interface details change

### ISSUE THREAD

**Issue by ConsciousUniverse** [iocage/iocage#599]
- Iocage version: 1.0 ALPHA
- Commands: `iocage list`
- Output:
```

ifconfig: interface epair0b does not exist
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/list.py", line 81, in cli
    dataset_type, header, _long, _sort, plugin=plugins, quick=quick)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 1144, in list
    exit_on_error=self.exit_on_error).list_datasets()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_list.py", line 76, in list_datasets
    _all = self.list_all(ds)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_list.py", line 228, in list_all
    out = su.check_output(full_ip4_cmd)
  File "/usr/local/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['jexec', 'ioc-MyJail', 'ifconfig', 'epair0b', 'inet']' returned non-zero exit status 1.
```
- Expected output: List of iocage jails.
- Description: This error was caused as a result of deleting the vnet interface from the FreeNAS GUI. However, it would appear the issue is not FreeNAS specific, as it seems to be caused by failure to catch and handle the stderr returned following the subprocess call.

**Comment by ole-db** [comment]
`iocage list` also fails if the config.json does not exist or is not valid.
I would expect, that the list command gives a warning "jail with <uuid> has broken config", but lists the valid jails.

This would be important if you have scripts (eg. backup scripts) that parse the output and run periodically.
