### ISSUE TITLE
iocage destroy broken

### ISSUE THREAD

**Issue by erikagnvall** [iocage/iocage#6]
```
$ sudo iocage create -r 11.0-RELEASE tag=hello
hello (fb78831a-1bc8-4193-b1c8-ae9e247a57b5) successfully created!
```

```
$ sudo iocage destroy hello

WARNING: This will destroy jail fb78831a-1bc8-4193-b1c8-ae9e247a57b5 (hello)
Dataset: /iocage/jails/fb78831a-1bc8-4193-b1c8-ae9e247a57b5

Are you sure? y[N]: y
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 11, in <module>
    load_entry_point('iocage==0.9', 'console_scripts', 'iocage')()
  File "/usr/local/lib/python2.7/site-packages/iocage/main.py", line 78, in main
    cli(obj=MODULES)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/iocage/cli/destroy.py", line 66, in destroy_cmd
    IOCDestroy(uuid, tag, path).destroy_jail()
TypeError: __init__() takes exactly 5 arguments (4 given)
```

**Comment by skarekrow** [comment]
A mild brainfart :(

Thanks for the report!
