### ISSUE TITLE
libzfs.pyx line 2311 error with 12.0-ALPHA2 jails

### ISSUE THREAD

**Issue by agshekeloh** [iocage/iocage#602]
looks like jails running 12.0-ALPHA2 choke iocage in libzfs. Updated from git right now, -current as of today.

```
storm~;iocage --version
Version 1.0 ALPHA 1
storm~;uname -a
FreeBSD storm 12.0-ALPHA3 FreeBSD 12.0-ALPHA3 #9 r338296: Fri Aug 24 15:08:35 EDT 2018     root@storm:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64
storm~;iocage list -r
+---------------+
| Bases fetched |
+===============+
| 11.2-RELEASE  |
+---------------+
| 12.0-ALPHA2   |
+---------------+
storm~;iocage list
+-----+------+-------+--------------+---------------+
| JID | NAME | STATE |   RELEASE    |      IP4      |
+=====+======+=======+==============+===============+
| 4   | wdb1 | up    | 11.2-RELEASE | 203.0.113.236 |
+-----+------+-------+--------------+---------------+
| -   | wdb2 | down  | 12.0-ALPHA2  | 203.0.113.237 |
+-----+------+-------+--------------+---------------+
| 1   | www1 | up    | 11.2-RELEASE | 203.0.113.234 |
+-----+------+-------+--------------+---------------+
| -   | www2 | down  | 12.0-ALPHA2  | 203.0.113.235 |
+-----+------+-------+--------------+---------------+
```

- [ ] Supply the commands used, along with any steps to recreate it.

```python-backtrace
# iocage start wdb2
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/start.py", line 54, in cli
    ioc.IOCage(jail=jail, rc=rc).start()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 1582, in start
    conf = ioc_json.IOCJson(path, silent=self.silent).json_load()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 224, in json_load
    if jail_dataset.mountpoint is None:
  File "libzfs.pyx", line 2311, in libzfs.ZFSDataset.mountpoint.__get__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xee in position 148: ordinal not in range(128)

storm~;iocage get -r boot
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/get.py", line 122, in cli
    jails = ioc.IOCage().get(prop, recursive=True)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 1102, in get
    ioc_json.IOCJson(path).json_get_value(prop)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 565, in json_get_value
    conf = self.json_load()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 224, in json_load
    if jail_dataset.mountpoint is None:
  File "libzfs.pyx", line 2311, in libzfs.ZFSDataset.mountpoint.__get__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf4 in position 135: ordinal not in range(128)
```

```python-backtrace
# iocage restart www1
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/restart.py", line 41, in cli
    ioc.IOCage(jail=jail).restart(soft)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 1268, in restart
    self.stop()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 1641, in stop
    conf = ioc_json.IOCJson(path, silent=self.silent, stop=True
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 224, in json_load
    if jail_dataset.mountpoint is None:
  File "libzfs.pyx", line 2311, in libzfs.ZFSDataset.mountpoint.__get__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xee in position 148: ordinal not in range(128)
```

I destroy the 12.0-ALPHA2 jails, and I can restart www1.

```
storm~;iocage restart www1
* Stopping www1
  + Running prestop OK
  + Stopping services OK
ioc-www1: removed
  + Removing jail process OK
  + Running poststop OK
* Starting www1
  + Started OK
  + Starting services OK
```

I still can't do a get:

```python-backtrace 
# storm~;iocage get -r boot
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/get.py", line 122, in cli
    jails = ioc.IOCage().get(prop, recursive=True)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 1102, in get
    ioc_json.IOCJson(path).json_get_value(prop)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 565, in json_get_value
    conf = self.json_load()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 224, in json_load
    if jail_dataset.mountpoint is None:
  File "libzfs.pyx", line 2311, in libzfs.ZFSDataset.mountpoint.__get__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf4 in position 135: ordinal not in range(128)
```

Iocage is assigned the zpool "iocage."

**Comment by skarekrow** [comment]
Yet (another) :( variant of #153

**Comment by agshekeloh** [comment]
Whelp, I guess I fall back to the 0.9.whatever from the ports tree for now.

I'm available for patch testing.

**Comment by gronke** [comment]
I suspect this is also the cause of https://github.com/freenas/py-libzfs/issues/14. Probably @william-gr can help ☝️

**Comment by agshekeloh** [comment]
pulled py-libzfs master, and everything seems to work now...

**Comment by gronke** [comment]
Yes, but that only works if `/usr/src` is available on the host.

**Comment by skarekrow** [comment]
Which is required to use iocage from GitHub currently, so that's a fair
requirement.

> --
- Brandon

**Comment by agshekeloh** [comment]
Brandon, could you update the makefile or the docs on this one to save others pain?

**Comment by skarekrow** [comment]
Alright Michael, https://github.com/iocage/iocage/commit/8d2cd72bcd52c3fd985713ee1e4ff738fb03d86c *should* fix this, lemme know.
