### ISSUE TITLE
iocage list -PR results in a Python exception

### ISSUE THREAD

**Issue by danielBreitlauch** [iocage/iocage#616]
Version: Version	0.9.10 2017/12/22
cmd: iocage list -PR
Trace:
```python-traceback
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/list.py", line 111, in cli
    plugin_file=True)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 941, in fetch
    icon=True)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 1447, in fetch_plugin_index
    table.add_rows(plugin_list)
  File "/usr/local/lib/python3.6/site-packages/texttable.py", line 382, in add_rows
    self.add_row(row)
  File "/usr/local/lib/python3.6/site-packages/texttable.py", line 354, in add_row
    self._check_row_size(array)
  File "/usr/local/lib/python3.6/site-packages/texttable.py", line 502, in _check_row_size
    % self._row_size)
texttable.ArraySizeError: array should contain 3 elements
```

**Comment by skarekrow** [comment]
This was fixed a while back, thanks for the report though :)
