### ISSUE TITLE
iocage list -t gives error

### ISSUE THREAD

**Issue by agshekeloh** [iocage/iocage#625]
Hi,

storm~;iocage --version
Version 1.0 ALPHA 1

Updated twenty minutes ago.

storm~;uname -a
FreeBSD storm 12.0-ALPHA6 FreeBSD 12.0-ALPHA6  r338724  amd64

storm~;iocage list -t
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/list.py", line 81, in cli
    dataset_type, header, _long, _sort, plugin=plugins, quick=quick)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 1145, in list
    quick=quick
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_list.py", line 99, in list_datasets
    templates = self.list_all(ds)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_list.py", line 153, in list_all
    conf = iocage_lib.ioc_json.IOCJson(mountpoint).json_load()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 407, in json_load
    conf = self.json_check_config(conf)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 1046, in json_check_config
    self.json_write(conf)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 416, in json_write
    'w') as out:
  File "/usr/local/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_common.py", line 503, in open_atomic
    with tempfile(dir=os.path.dirname(os.path.abspath(filepath))) as tmppath:
  File "/usr/local/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_common.py", line 466, in tempfile
    tf = tmp.NamedTemporaryFile(delete=False, suffix=suffix, dir=dir)
  File "/usr/local/lib/python3.6/tempfile.py", line 551, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/local/lib/python3.6/tempfile.py", line 262, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 30] Read-only file system: '/iocage/templates/dnsbase/tmpmei6lw_5'
storm~;

storm/iocage/templates/dnsbase;head -2 config.json
{
    "CONFIG_VERSION": "12",

Wants to update config version, can't.

**Comment by skarekrow** [comment]
Note to self: This is related to wanting to set properties on templates in general, to avoid annoying workarounds like setting ip4_addr to something else *before* setting a jail as a template. As you can't change it afterwards if a jail was created from it.

**Comment by agshekeloh** [comment]
This looks related to me. Might not be, what do I know. Yesterday's -current and yesterday's iocage.

storm~;iocage get -rh template

/usr/local/lib/python3.6/site-packages/requests/__init__.py:80: RequestsDependencyWarning:        urllib3 (1.24.1) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/get.py", line 122, in cli
    jails = ioc.IOCage().get(prop, recursive=True)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 1186, in get
    ioc_json.IOCJson(path).json_get_value(prop)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 577, in json_g       et_value
    conf = self.json_load()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 407, in json_l       oad
    conf = self.json_check_config(conf)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 1023, in json_       check_config
    self.json_write(conf)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 416, in json_w       rite
    'w') as out:
  File "/usr/local/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_common.py", line 514, in open       _atomic
    with tempfile(dir=os.path.dirname(os.path.abspath(filepath))) as tmppath:
  File "/usr/local/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_common.py", line 477, in temp       file
    tf = tmp.NamedTemporaryFile(delete=False, suffix=suffix, dir=dir)
  File "/usr/local/lib/python3.6/tempfile.py", line 551, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/local/lib/python3.6/tempfile.py", line 262, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 30] Read-only file system: '/iocage/templates/dnsbase/tmpdw4glceb'
