### ISSUE TITLE
iocage fetch,list,create,upgrade should work if version is unsupported

### ISSUE THREAD

**Issue by ole-db** [iocage/iocage#656]
```
iocage fetch
/usr/local/lib/python3.6/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.23) or chardet (3.0.4) doesn't match a supported version!
```
```
iocage list
/usr/local/lib/python3.6/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.23) or chardet (3.0.4) doesn't match a supported version!
```

I don't see a reason why ' fetch', 'list', 'create' or 'upgrade' shouldn't work.
Maybe you think this is a stupid request, but here is an use case:

If you are running multiple Instances of iocage on different hosts you may want to keep them in sync. And may be, you already updated a few hosts to 11.2 but some are still on 11.1. 

And you created 11.2 Jails on the 11.2-Hosts. Which got automatic synced to the outdated Hosts.
In this case you want to use commands like 'iocage list' on the outdated hosts.

**Comment by skarekrow** [comment]
That's not what this error is, you have unsupported dependencies for the `requests` module, how did you install this?

**Comment by ole-db** [comment]
` git clone https://github.com/iocage/iocage.git ; cd iocage ; make install`
But this it's been a while since that. But you are right. I copyed the wrong message.

```
# iocage fetch
/usr/local/lib/python3.6/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.23) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
[0] 9.3-RELEASE (EOL)
[1] 10.1-RELEASE (EOL)
[2] 10.2-RELEASE (EOL)
[3] 10.3-RELEASE (EOL)
[4] 10.4-RELEASE
[5] 11.0-RELEASE (EOL)
[6] 11.1-RELEASE (EOL)
[7] 11.2-RELEASE

Type the number of the desired RELEASE
Press [Enter] to fetch the default selection: (11.1)
Type EXIT to quit: 7

Host: 11.1 is not greater than target: 11.2-RELEASE
This is unsupported.
```

And if you copy a 11.2 jail to a 11.1 Host, the `iocage list` command will also fail.
In my opinion, only `iocage start` should fail.

**Comment by ole-db** [comment]
```python-traceback
# iocage list
/usr/local/lib/python3.6/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.23) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/list.py", line 81, in cli
    dataset_type, header, _long, _sort, plugin=plugins, quick=quick)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 1138, in list
    quick=quick
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_list.py", line 75, in list_datasets
    _all = self.list_all(ds)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_list.py", line 153, in list_all
    conf = iocage_lib.ioc_json.IOCJson(mountpoint).json_load()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 406, in json_load
    conf = self.json_check_config(conf)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 900, in json_check_config
    with open(freebsd_version, "r") as r:
FileNotFoundError: [Errno 2] No such file or directory: '/iocage/releases/11.2-RELEASE/root/bin/freebsd-version'
```

**Comment by ole-db** [comment]
Thanks to @skarekrow 
I think https://github.com/iocage/iocage/commit/d0b358ae440044d0adc3a5c9b9c2d26115d9f1d9 fixes the list command. This works for me on 11.1 with 11.2 Jails

**Comment by ghost** [comment]
Reinstalling the requests module fixed this issue for me (updated requests from 2.18.4 to 2.20.0)
sudo pip uninstall requests
sudo pip install requests

**Comment by skarekrow** [comment]
I can't repro any longer, so I'm going to close this @ole-db unless we run into it again, we can reopen it in that case :+1: 

Thanks for the additional information @constrict!
