### ISSUE TITLE
iocage snaplist failed to run

### ISSUE THREAD

**Issue by amutu** [iocage/iocage#660]
```sh-session
# iocage -v
Version	0.9.10 2017/12/22 
# iocage list
+-----+---------+-------+--------------+-------------+
| JID |  NAME   | STATE |   RELEASE    |     IP4     |
+=====+=========+=======+==============+=============+
| -   | r112    | down  | 11.2-RELEASE | 192.168.0.1 |
+-----+---------+-------+--------------+-------------+
| 4   | rss_svr | up    | 11.2-RELEASE | 192.168.0.2 |
+-----+---------+-------+--------------+-------------+
```
```python-traceback
# iocage snaplist rss_svr
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/snaplist.py", line 44, in cli
    _sort)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 1474, in snap_list
    name, snap_name = parent[0].split("@")
ValueError: not enough values to unpack (expected 2, got 1)
```
```sh-session
# zfs list -t snap zroot/iocage/jails/rss_svr@ioc-export-2018-09-12
NAME                                               USED  AVAIL  REFER  MOUNTPOINT
zroot/iocage/jails/rss_svr@ioc-export-2018-09-12    14K      -  25.5K  -
```

**Comment by skarekrow** [comment]
Please check with the git version before filing bugs, but for future reference, the implementation changed some time ago:
```
root@freenas[~]# iocage create -n foobar -r latest ; zfs snapshot foo/iocage/jails/foobar@ioc-export-2018-09-12
foobar successfully created!
root@freenas[~]# iocage snaplist foobar
+------+---------+-------+------+
| NAME | CREATED | RSIZE | USED |
+======+=========+=======+======+
+------+---------+-------+------+
root@freenas[~]# zfs list -t snap foo/iocage/jails/foobar@ioc-export-2018-09-12
NAME                                            USED  AVAIL  REFER  MOUNTPOINT
foo/iocage/jails/foobar@ioc-export-2018-09-12    56K      -    92K  -
root@freenas[~]# zfs snapshot foo/iocage/jails/foobar/root@ioc-export-2018-09-12
root@freenas[~]# iocage snaplist foobar                                        
+----------------------------+-----------------------+-------+------+
|            NAME            |        CREATED        | RSIZE | USED |
+============================+=======================+=======+======+
| ioc-export-2018-09-12      | Tue Oct 16 21:17 2018 | 92K   | 56K  |
+----------------------------+-----------------------+-------+------+
| ioc-export-2018-09-12/root | Tue Oct 16 21:17 2018 | 971M  | 0    |
+----------------------------+-----------------------+-------+------+
root@freenas[~]# zfs list -rt snap foo/iocage/jails/foobar                     
NAME                                                 USED  AVAIL  REFER  MOUNTPOINT
foo/iocage/jails/foobar@ioc-export-2018-09-12         56K      -    92K  -
foo/iocage/jails/foobar/root@ioc-export-2018-09-12      0      -   971M  -
```
It will only show something if the jail's root has a snapshot.
