### ISSUE TITLE
How can I destroy unused releases?

### ISSUE THREAD

**Issue by denigmus** [iocage/iocage#662]
I don't need these:

zroot/iocage/releases/11.1-RELEASE on /iocage/releases/11.1-RELEASE (zfs, local, noatime, nfsv4acls)
zroot/iocage/releases/11.1-RELEASE/root on /iocage/releases/11.1-RELEASE/root (zfs, local, noatime, nfsv4acls)

I don't see any option to destroy them by iocage.

If I try zfs destroy I get "busy".
umount -F will not unmount too.

How?

Version 1.0 ALPHA

**Comment by skarekrow** [comment]
@denigmus You can use `iocage destroy -rd 11.1-RELEASE`

**Comment by denigmus** [comment]
The same "busy" but in another form:

```
# iocage destroy -rdf 11.1-RELEASE
Destroying RELEASE dataset: 11.1-RELEASE
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/destroy.py", line 144, in cli
    skip_jails=True).destroy_release(download)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 608, in destroy_release
    path, stop=False)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_destroy.py", line 225, in __destroy_parse_datasets__
    self.__destroy_dataset__(dataset)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_destroy.py", line 183, in __destroy_dataset__
    dataset.umount(force=True)
  File "libzfs.pyx", line 2361, in libzfs.ZFSDataset.umount
libzfs.ZFSException: Device busy

```

**Comment by skarekrow** [comment]
Unfortunately this crops up time to time. Nothing much that can be done
from iocage a side, we try to forcefully stop and do it. Short of rebooting
your host, I haven’t seen much success outside of that.

I’d try stopping the jails and using fstab to see if anything is holding
onto these mounts first though
