### ISSUE TITLE
iocage console crash 

### ISSUE THREAD

**Issue by agshekeloh** [iocage/iocage#692]
OS updated yesterday, iocage updated today:

storm~;iocage --version
Version 1.0 RC 2018/11
storm~;uname -a
FreeBSD storm 13.0-CURRENT FreeBSD 13.0-CURRENT r340648 GENERIC  amd64

Can get console using base system:
storm;jexec -l 9 login -f root
Last login: Thu Sep 27 15:49:43 on pts/2
FreeBSD 12.0-ALPHA6  r338724

Welcome to FreeBSD!

Release Notes, Errata: https://www.FreeBSD.org/releases/
Security Advisories:   https://www.FreeBSD.org/security/
FreeBSD Handbook:      https://www.FreeBSD.org/handbook/
FreeBSD FAQ:           https://www.FreeBSD.org/faq/
Questions List: https://lists.FreeBSD.org/mailman/listinfo/freebsd-questions/
FreeBSD Forums:        https://forums.FreeBSD.org/

Documents installed with the system are in the /usr/local/share/doc/freebsd/
directory, or can be installed later with:  pkg install en-freebsd-doc
For other languages, replace "en" with a language code like de or fr.

Show the version of FreeBSD installed:  freebsd-version ; uname -a
Please include that output and any error messages when posting questions.
Introduction to manual pages:  man man
FreeBSD directory layout:      man hier

Edit /etc/motd to change this login announcement.
root@dns4:~ #

But using iocage:

storm~;iocage console dns4
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/console.py", line 41, in cli
    silent=True).exec("", console=True)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 774, in exec
    exec_clean = self.get('exec_clean')
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 1154, in get
    return ioc_json.IOCJson(path).json_get_value(prop)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 630, in json_get_value
    return conf[prop]
TypeError: tuple indices must be integers or slices, not str

**Comment by skarekrow** [comment]
Fixed by https://github.com/iocage/iocage/commit/3b986ef540205c35b09a8953e0323c8740c801aa
