### ISSUE TITLE
fetch non-functional on i386

### ISSUE THREAD

**Issue by sidju** [iocage/iocage#693]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
- [x] Supply the commands used, along with any steps to recreate it.
- [x] Provide the output from the command you issued.
- [x] Supply what you expected the result or output to be
- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Versions:**
iocage version: Version	0.9.10 2017/12/22
uname -r: (FreeBSD) 11.2-RELEASE-p4
system: i386 with 2 GB of RAM

**How to recreate:**
Base install
```
iocage activate zroot
iocage fetch
```
Select default.

**Result:**
```
Fetching: 11.2-RELEASE

Extracting: base.txz... 
lib32.txz missing, will try to redownload!
doc.txz missing, will try to redownload!
src.txz missing, will try to redownload!
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 166, in cli
    ioc.IOCage(exit_on_error=True).fetch(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 993, in fetch
    silent=self.silent, **kwargs).fetch_release()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 234, in fetch_release
    rel = self.fetch_http_release(eol, _list=_list)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 519, in fetch_http_release
    self.fetch_download(missing, missing=True)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 720, in fetch_download
    r.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://download.freebsd.org/ftp/releases/i386/11.2-RELEASE/lib32.txz
```
404 error on lib32.txz
This because the i386 release doesn't have a lib32.txz file

**Expected result:**
Fetching the release and enabling me to create a jail.

**Comment by skarekrow** [comment]
iocage only supports amd64. Even if this fetched from the mirror it would be incorrect binaries for you. You can use the -F switch, and roll your own ftp server and use —server. I suggest reading fetches —help as you can probably cobble a workaround together, but main iocage won’t support it.
