### ISSUE TITLE
Multiple errors in `iocage fstab` command

### ISSUE THREAD

**Issue by bartekrutkowski** [iocage/iocage#702]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`

Version	0.9.10 2017/12/22 on FreeBSD 11.2-RELEASE

- [x] Supply the commands used, along with any steps to recreate it.

Listed below.

- [x] Provide the output from the command you issued.

1. Error when creating broken fstab entries (mountpoint non existing):

```python-traceback
root@freebsd:~ # iocage fstab -a somejail /nonexisting /someotherpath nullfs ro 0 0
Successfully added mount to somejail's fstab
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fstab.py", line 126, in cli
    add_path=add_path, header=header)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 1061, in fstab
    exit_on_error=self.exit_on_error)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fstab.py", line 65, in __init__
    self.__fstab_parse__()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fstab.py", line 75, in __fstab_parse__
    self.__fstab_mount__()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fstab.py", line 165, in __fstab_mount__
    raise RuntimeError(f"{stderr_data.decode('utf-8')}")
RuntimeError: mount_nullfs: /nonexisting: No such file or directory
```

2. Error when adding correcting repeating fstab entries:

```python-traceback
root@freebsd:~ # iocage fstab -a somejail /somepath /someotherpath nullfs ro 0 0
Successfully added mount to somejail's fstab
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fstab.py", line 126, in cli
    add_path=add_path, header=header)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 1061, in fstab
    exit_on_error=self.exit_on_error)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fstab.py", line 65, in __init__
    self.__fstab_parse__()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fstab.py", line 75, in __fstab_parse__
    self.__fstab_mount__()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fstab.py", line 165, in __fstab_mount__
    raise RuntimeError(f"{stderr_data.decode('utf-8')}")
RuntimeError: mount_nullfs: /iocage/jails/somejail/root/somepath: Resource deadlock avoided
```

3. Error deleting broken fstab entries (mountpoint non existing):

```python-traceback
root@freebsd:~ # iocage fstab somejail -r 4
Successfully removed mount from somejail's fstab
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fstab.py", line 126, in cli
    add_path=add_path, header=header)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 1061, in fstab
    exit_on_error=self.exit_on_error)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fstab.py", line 65, in __init__
    self.__fstab_parse__()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fstab.py", line 78, in __fstab_parse__
    self.__fstab_umount__(dest)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fstab.py", line 182, in __fstab_umount__
    raise RuntimeError(f"{stderr_data.decode('utf-8')}")
RuntimeError: umount: /iocage/jails/somejail/root/somepath: not a file system root directory
```

4. Error when deleting nonexisting fstab entry (somejail has only 0-3 fstab entries):

```python-traceback
root@freebsd:~ # iocage fstab somejail -r 4
No matching fstab entry.
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fstab.py", line 126, in cli
    add_path=add_path, header=header)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 1061, in fstab
    exit_on_error=self.exit_on_error)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fstab.py", line 65, in __init__
    self.__fstab_parse__()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fstab.py", line 78, in __fstab_parse__
    self.__fstab_umount__(dest)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fstab.py", line 178, in __fstab_umount__
    proc = su.Popen(["umount", "-f", dest], stdout=su.PIPE, stderr=su.PIPE)
  File "/usr/local/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.6/subprocess.py", line 1275, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

- [x] Supply what you expected the result or output to be

All these use cases should verify the user supplied data before acting on it, and then act accordingly instead of crashing. Also, the errors should be handled in Python to catch exceptions instead of crashing.

- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

No.

**Comment by skarekrow** [comment]
None of these issues exist in master, hence that checkbox :)

```
root@freenas[~]# iocage create -n foo -r 11.2-RELEASE
foo successfully created!
root@freenas[~]# iocage fstab -a foo /nonexisting /someotherpath nullfs ro 0 0
Successfully added mount to foo's fstab
root@freenas[~]# iocage fstab -a foo /root/iocage /newpath nullfs ro 0 0
Successfully added mount to foo's fstab
root@freenas[~]# iocage fstab -a foo /root/iocage /newpath nullfs ro 0 0
Successfully added mount to foo's fstab
root@freenas[~]# iocage fstab foo -r 4
No matching fstab entry.
root@freenas[~]# ls /nonexisting
ls: /nonexisting: No such file or directory
root@freenas[~]# cat /mnt/foo/iocage/jails/foo/fstab
/nonexisting    /mnt/foo/iocage/jails/foo/root/someotherpath    nullfs  ro      0       0 # Added by iocage on 2018-11-21 17:50:17
/root/iocage    /mnt/foo/iocage/jails/foo/root/newpath  nullfs  ro      0       0 # Added by iocage on 2018-11-21 17:51:01
/root/iocage    /mnt/foo/iocage/jails/foo/root/newpath  nullfs  ro      0       0 # Added by iocage on 2018-11-21 17:51:02
```

**Comment by bartekrutkowski** [comment]
@skarekrow the problem is that master doesn't exist as a package, so the issue is real for stable, packaged version available to typical user. Any chance for getting a new tag, so that I could update the iocage port so that new packages could be built?

**Comment by skarekrow** [comment]
@bartekrutkowski There is a port, iocage-devel. I agree a stable release is *long* overdue, and we're making good headway that direction for one. Also nice to see you again!

**Comment by skarekrow** [comment]
These actually all trigger if the jail is running

**Comment by bartekrutkowski** [comment]
@skarekrow the iocage-devel port is over a month old as well, so again not something from master branch and my comments are still valid.

**Comment by skarekrow** [comment]
@bartekrutkowski The port is from this week. He typo'd the month in the title of the package.

```
iocage-devel FreeBSD jail manager written in Python3
1.0.0.20181026,1 sysutils search for ports that depend on this port Find issues related to this port Report an issue related to this port
Maintainer: wg@FreeBSD.org search for ports maintained by this maintainer
Last commit date: 2018-11-27 16:19:25
```

**Comment by bartekrutkowski** [comment]
@skarekrow I don't think he did, the distinfo uses month old sources:
```
SHA256 (iocage-iocage-1.0.0.20181026-c4016ac_GH0.tar.gz) = df96aa350274198e257d6d392cc6f280b8719bdafe3a382f40268f654817a371
```

**Comment by skarekrow** [comment]
@william-gr So which is it :D

**Comment by bartekrutkowski** [comment]
@skarekrow the commit is from 2 days ago, but it updated the port to a month old sources. The port version number and distinfo src version are coherent and seem valid.

**Comment by william-gr** [comment]
The name doesnt matter, the hash does, which is c4016ac

**Comment by william-gr** [comment]
And thats from 3 days ago.

**Comment by bartekrutkowski** [comment]
@william-gr can you correct the port's version then?

**Comment by william-gr** [comment]
sure
