### ISSUE TITLE
RELEASE not found

### ISSUE THREAD

**Issue by dBitech** [iocage/iocage#707]
Unable to create jail, iocage states RELEASE does not exist.

root@quad:/usr/jails # iocage --version
Version 0.9.10 2017/12/22
root@quad:/usr/jails # uname -ro
FreeBSD 11.2-RELEASE-p5
root@quad:/usr/jails # iocage list -r
+---------------+
| Bases fetched |
+===============+
| 9.3-RELEASE   |
+---------------+
| 10.4-RELEASE  |
+---------------+
| 11.2-RELEASE  |
+---------------+
root@quad:/usr/jails # iocage create -n temp_104 -r 10.4-RELEASE
temp successfully created!
root@quad:/usr/jails # iocage create -n temp_112 -r 11.2-RELEASE
RELEASE: 11.2-RELEASE not found!
root@quad:/usr/jails # iocage list
+-----+----------+-------+--------------+---------------+
| JID |   NAME   | STATE |   RELEASE    |      IP4      |
+=====+==========+=======+==============+===============+
| 1   | getlost  | up    | 11.2-RELEASE | 192.168.1.237 |
+-----+----------+-------+--------------+---------------+
| -   | kafka    | down  | 11.2-RELEASE | 192.168.1.238 |
+-----+----------+-------+--------------+---------------+
| 3   | mqtt     | up    | 11.2-RELEASE | 192.168.1.235 |
+-----+----------+-------+--------------+---------------+
| -   | temp     | down  | 10.4-RELEASE | -             |
+-----+----------+-------+--------------+---------------+

**Comment by skarekrow** [comment]
Hmm this section had a lot of work done since then. Does `zfs list -r quad/iocage/releases` show the release existing?

If you don't mind testing the latest RC, the iocage-devel port should get you running. I cannot reproduce this on master currently.

**Comment by dBitech** [comment]
root@quad:/usr/jails # zfs list -r zvol0/iocage/releases
NAME                                      USED  AVAIL  REFER  MOUNTPOINT
zvol0/iocage/releases                    2.76G   378G    23K  /iocage/releases
zvol0/iocage/releases/10.4-RELEASE        640M   378G    23K  /iocage/releases/10.4-RELEASE
zvol0/iocage/releases/10.4-RELEASE/root   640M   378G   640M  /iocage/releases/10.4-RELEASE/root
zvol0/iocage/releases/11.2-RELEASE       1.47G   378G    23K  /iocage/releases/11.2-RELEASE
zvol0/iocage/releases/11.2-RELEASE/root  1.47G   378G   753M  /iocage/releases/11.2-RELEASE/root
zvol0/iocage/releases/9.3-RELEASE         677M   378G    23K  /iocage/releases/9.3-RELEASE
zvol0/iocage/releases/9.3-RELEASE/root    677M   378G   677M  /iocage/releases/9.3-RELEASE/root

What is strange (as you can see) I was able to spin up several cages with 11.2 then all of a sudden it stopped.  I can certainly try the devel port.

**Comment by skarekrow** [comment]
It is very strange, I suspect it's the name you're supplying and it's causing issues internally with the sorting. But that code is so old, I can only guess. A loooot of churn has happened there. Please make backups of your jails config.json's first though, that way you can go backwards.

**Comment by dBitech** [comment]
root@quad:/usr/jails # iocage create -r 11.2-RELEASE -n temp
RELEASE: 11.2-RELEASE not found!
root@quad:/usr/jails # iocage --version
Version 1.0 RC 2018/11
root@quad:/usr/jails # iocage create -r LATEST

Host: 11.2-RELEASE is not greater than target: 12.0-RELEASE
This is unsupported.
root@quad:/usr/jails # iocage fetch
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/fetch.py", line 129, in cli
    ioc.IOCage().fetch(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 1039, in fetch
    **kwargs).fetch_release()
TypeError: __init__() got an unexpected keyword argument 'thickconfig'
root@quad:/usr/jails # iocage list -r
+---------------+
| Bases fetched |
+===============+
| 10.4-RELEASE  |
+---------------+
| 11.2-RELEASE  |
+---------------+
| 9.3-RELEASE   |
+---------------+

**Comment by skarekrow** [comment]
The fetch bug is fixed, sorry about that. Port must be a little old. This is a bizarre bug, 

```
root@freenas[~]# iocage create -n temp -r 11.2-RELEASE
temp successfully created!
root@freenas[~]# iocage list -r
+---------------+
| Bases fetched |
+===============+
| 11.1-RELEASE  |
+---------------+
| 11.2-RELEASE  |
+---------------+
```
It works for me, what does your `locale` look like?

**Comment by dBitech** [comment]
root@quad:/usr/jails # locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_ALL=

**Comment by skarekrow** [comment]
Hmm nothing sticks out there, can you supply `iocage debug`?

**Comment by skarekrow** [comment]
It will be in iocage's mountpoint/debug, make sure to zip it up and attach it here. If you feel it's too personal you can email me the archive at brandon (at) ixsystems.com

**Comment by dBitech** [comment]
the output of iocage debug was emailed;

Also, it would appear that ever since upgrading, there are a bunch of other commands that result in dumps:
```
root@quad:~ # iocage list
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_list.py", line 168, in list_all
    'all'
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 1093, in json_get_value
    return self.get_full_config()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 754, in get_full_config
    conf, write = self.json_load()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 1066, in json_load
    conf = self.check_config(conf)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 326, in check_config
    jail_conf = self.check_jail_config(conf)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 423, in check_jail_config
    if not freebsd_version.is_file():
AttributeError: 'str' object has no attribute 'is_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/list.py", line 83, in cli
    dataset_type, header, _long, _sort, plugin=plugins, quick=quick)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 1247, in list
    quick=quick
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_list.py", line 75, in list_datasets
    _all = self.list_all(ds)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_list.py", line 177, in list_all
    default=True
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 1081, in json_get_value
    conf = self.default_config
AttributeError: 'IOCJson' object has no attribute 'default_config'
```
or
```
root@quad:~ # iocage console getlost
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/console.py", line 41, in cli
    silent=True).exec("", console=True)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 766, in exec
    exec_clean = self.get('exec_clean')
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 1155, in get
    return ioc_json.IOCJson(path).json_get_value(prop)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 1095, in json_get_value
    conf, write = self.json_load()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 1066, in json_load
    conf = self.check_config(conf)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 326, in check_config
    jail_conf = self.check_jail_config(conf)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 423, in check_jail_config
    if not freebsd_version.is_file():
AttributeError: 'str' object has no attribute 'is_file'
```
I also updated my local port to follow a more recent version out of git, ``` bbc971fffd ```
```
root@quad:~ # pkg info | grep iocage
py36-iocage-devel-1.0.0.20181205,1 FreeBSD jail manager written in Python3
root@quad:~ # file /usr/ports/distfiles/iocage-iocage-1.0.0.20181205-bbc971fffd_GH0.tar.gz
/usr/ports/distfiles/iocage-iocage-1.0.0.20181205-bbc971fffd_GH0.tar.gz: gzip compressed data, from Unix
```
Is it possible that there is an "upgrade" type command I need to run ?

**Comment by skarekrow** [comment]
No those are actually two bugs, I just fixed now in https://github.com/iocage/iocage/commit/964bd34f2b589718ad131b305902c645369b5105 and https://github.com/iocage/iocage/commit/704b5c273d903f1d6ff850f9e770cbeec98abf4f

Good finds!  I haven't received the debug yet, but will look when it arrives. Perhaps gmail isn't liking the attachment?

**Comment by dBitech** [comment]
[iocage-debug.tar.gz](https://github.com/iocage/iocage/files/2658378/iocage-debug.tar.gz)

**Comment by skarekrow** [comment]
I think I see the problem @dBitech, try `zfs mount -a`

**Comment by dBitech** [comment]
both list and console work now at patch level [```704b5c2```](https://github.com/iocage/iocage/commit/704b5c273d903f1d6ff850f9e770cbeec98abf4f)
and ```zfs mount -a``` looks to have solved the problem, though this does lead me to wonder how it got into the sate of needing this command to correct....

Thanks a lot.

**Comment by skarekrow** [comment]
Fantastic! Yes, it's very odd as they should be mounted when tried to be used. I couldn't repro it on my box here, so I'll close this out unless someone finds a solid reproduction case. Thanks for the good report!
