### ISSUE TITLE
"iocage fetch" of FreeBSD 12 fails downloading

### ISSUE THREAD

**Issue by pos42** [iocage/iocage#728]
On all mirrors I found, there is no longer a doc.txz. On the FreeBSD 12.0-RELEASE it is named doc.txz.empty_archive ( http://ftp.freebsd.org/pub/FreeBSD/releases/amd64/12.0-RELEASE/ ) which causes the error below.

23:03:00 huey:~ # iocage fetch
[0] 9.3-RELEASE (EOL)
[1] 10.1-RELEASE (EOL)
[2] 10.2-RELEASE (EOL)
[3] 10.3-RELEASE (EOL)
[4] 10.4-RELEASE (EOL)
[5] 11.0-RELEASE (EOL)
[6] 11.1-RELEASE (EOL)
[7] 11.2-RELEASE
[8] 12.0-RELEASE

Type the number of the desired RELEASE
Press [Enter] to fetch the default selection: (12.0)
Type EXIT to quit: 8
Fetching: 12.0-RELEASE

Extracting: base.txz... 
Extracting: lib32.txz... 
doc.txz missing, will try to redownload!
src.txz missing, will try to redownload!
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 166, in cli
    ioc.IOCage(exit_on_error=True).fetch(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 993, in fetch
    silent=self.silent, **kwargs).fetch_release()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 234, in fetch_release
    rel = self.fetch_http_release(eol, _list=_list)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 519, in fetch_http_release
    self.fetch_download(missing, missing=True)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 720, in fetch_download
    r.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://download.freebsd.org/ftp/releases/amd64/12.0-RELEASE/doc.txz
23:04:43 huey:~ # 
23:07:40 huey:~ # 
23:07:40 huey:~ # pkg info|grep ioc
py36-iocage-0.9.10             FreeBSD jail manager written in Python3
23:07:47 huey:~ # 

23:50:04 huey:~ # cat /iocage/download/12.0-RELEASE/MANIFEST |awk '{print $1}'
base-dbg.txz
base.txz
kernel-dbg.txz
kernel.txz
lib32-dbg.txz
lib32.txz
ports.txz
src.txz
tests.txz
23:50:12 huey:~ # 

Note that there is no longer a doc.txz, but even so, the iocage doesn't care.

Am I missing something here?

**Comment by skarekrow** [comment]
Anyone finding this issue in the meantime, please follow my advice here: #472 (comment)

iocage-devel will have these changes ASAP, and a new tagged release for iocage stable is incoming shortly!
