### ISSUE TITLE
Fails during fetch on arm64 due to missing lib32.txz

### ISSUE THREAD

**Issue by voutilad** [iocage/iocage#75]
I'm using iocage installed from master on an rpi3 running a build of 12.0-CURRENT. My `uname -a` output looks like: `FreeBSD rpi3 12.0-CURRENT FreeBSD 12.0-CURRENT #0 r313109M: Thu Feb  2 16:16:39 MST 2017     raspberry@hive.raspbsd.org:/usr/home/brd/rpi3/crochet/work/obj/arm64.aarch64/usr/src/sys/GENERIC  arm64` and `iocage --version` reports `Version	0.9.7 2017/03/08`

It looks like since `lib32.txz` is hardcoded in `iocage/lib/ioc_fetch.py` and it's not part of the 11.0-RELEASE for aarch64 it's simply failing during the fetch:

```bash
[root@rpi3 ~ ] iocage fetch -r 11.0-RELEASE
Fetching: 11.0-RELEASE

Extracting: base.txz...
Extracting: lib32.txz...
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/iocage/main.py", line 94, in main
    cli(obj=MODULES)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 88, in fetch_cmd
    eol=eol).fetch_release()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 185, in fetch_release
    self.fetch_ftp_release(eol, _list=_list)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 347, in fetch_ftp_release
    missing = self.__fetch_check__(ftp_list, ftp=True)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 459, in __fetch_check__
    self.fetch_extract(f)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 566, in fetch_extract
    with tarfile.open(src) as f:
  File "/usr/local/lib/python3.6/tarfile.py", line 1564, in open
    return func(name, "r", fileobj, **kwargs)
  File "/usr/local/lib/python3.6/tarfile.py", line 1629, in gzopen
    fileobj = gzip.GzipFile(name, mode + "b", compresslevel, fileobj)
  File "/usr/local/lib/python3.6/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/iocage/download/11.0-RELEASE/lib32.txz'
```

I'm not sure you're planning on supporting arm releases yet, but I did simply remove it from the tuple in my local branch ('aarch64') of iocage, reinstalled via pip, and am off and running with jail running 11.0-RELEASE:

```diff
dave@rpi3 /usr/src/iocage (aarch64*) $ git diff
diff --git a/iocage/lib/ioc_fetch.py b/iocage/lib/ioc_fetch.py
index 2fac209..7238bc1 100644
--- a/iocage/lib/ioc_fetch.py
+++ b/iocage/lib/ioc_fetch.py
@@ -51,7 +51,8 @@ class IOCFetch(object):
         self._file = _file
         self.verify = verify
         self.hardened = hardened
-        self.files = ("MANIFEST", "base.txz", "lib32.txz", "doc.txz")
+        #self.files = ("MANIFEST", "base.txz", "lib32.txz", "doc.txz")
+        self.files = ("MANIFEST", "base.txz", "doc.txz")
         self.update = update
         self.eol = eol
```

**Comment by skarekrow** [comment]
I do not personally have any arm machines to test, but I'm going to push some support here and see if I can fix this for others :)

**Comment by skarekrow** [comment]
So this was both a bug and an enhancement, you should now be able to fetch without having to touch anything. Test and let me know 👍

**Comment by dgeo** [comment]
M'y (own) preferred way of fixing this would be to never install lib32.txz by default (as it's not needed for most usages). Currently I'm overriding default to install only base.txz.

**Comment by skarekrow** [comment]
Well both `doc.txz` and `lib32.txz` are quite small so I fetch them by default so the users don't have to go scramble on the off chance something doesn't work.

In your case @dgeo you can now just supply `iocage fetch -r RELEASE -F base.txz` and be off to the races!

**Comment by dgeo** [comment]
I'm OK with current behaviour, just tried :)
