### ISSUE TITLE
Unable to upgrade jails - AttributeError: 'IOCUpgrade' object has no attribute 'zfs_get_dataset_name'

### ISSUE THREAD

**Issue by cwross** [iocage/iocage#760]
Hi, I am running FreeBSD 12.0-RELEASE-p1 with iocage installed from pkg. I have several jails running 11.2-RELEASE that I am attempting to upgrade to 12.0. I have already fetched 12.0-RELEASE using the `iocage fetch --release 12.0-RELEASE` command.

My `iocage --version` reports `Version 1.0 RELEASE 2018/12`

When I run `iocage upgrade <jailname> -r 12.0-RELEASE`, it fails with the following output:

> Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/upgrade.py", line 40, in cli
    ioc.IOCage(jail=jail, skip_jails=skip_jails).upgrade(release)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 1975, in upgrade
    callback=self.callback
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_upgrade.py", line 82, in upgrade_jail
    tmp_dataset = self.zfs_get_dataset_name('/tmp')
AttributeError: 'IOCUpgrade' object has no attribute 'zfs_get_dataset_name'

I did not see any similar bugs reported that have been fixed in master, but if I missed something, please forgive me.

**Comment by skarekrow** [comment]
Closed by https://github.com/iocage/iocage/pull/762

**Comment by ghost** [comment]
> Closed by #762

Manually applying the changes works for me on FreeBSD 12.0-RELEASE when trying to upgrade a 11.2-RELEASE jail imported from a different system to 12.0-RELEASE. Thanks

**Comment by gerritche** [comment]
The changes worked for me as well. When will it make it to the ports and the binary?
Thank you!

**Comment by skarekrow** [comment]
I pinged @araujobsd when I tagged. He usually gets it done in a couple days :)
