### ISSUE TITLE
iocage fetch fails on 12.0-RELEASE

### ISSUE THREAD

**Issue by dbalan** [iocage/iocage#761]
The problem is probabaly not in iocage per say, the docs.txz file is missing from 12.0-RELEASE ftp. Not sure if the release process is broken or 12.0 changed how it handler docs.

- [x] Supply `iocage --version`
```
iocage --version
Version	0.9.10 2017/12/22
```
- [x] Supply the commands used, along with any steps to recreate it.
```
iocage fetch
```

- [x] Provide the output from the command you issued.
Password:
[0] 9.3-RELEASE (EOL)
[1] 10.1-RELEASE (EOL)
[2] 10.2-RELEASE (EOL)
[3] 10.3-RELEASE (EOL)
[4] 10.4-RELEASE (EOL)
[5] 11.0-RELEASE (EOL)
[6] 11.1-RELEASE (EOL)
[7] 11.2-RELEASE
[8] 12.0-RELEASE

Type the number of the desired RELEASE
Press [Enter] to fetch the default selection: (Not a RELEASE)
Type EXIT to quit: 8
Fetching: 12.0-RELEASE

Downloading : MANIFEST [####################] 100% 0Mbit/s
Downloading : base.txz [####################] 100%  17.01Mbit/s
Downloading : lib32.txz [####################] 100%  14.54Mbit/s
 14.54Mbit/sTraceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 166, in cli
    ioc.IOCage(exit_on_error=True).fetch(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 993, in fetch
    silent=self.silent, **kwargs).fetch_release()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 234, in fetch_release
    rel = self.fetch_http_release(eol, _list=_list)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 515, in fetch_http_release
    self.fetch_download(self.files)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 720, in fetch_download
    r.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://download.freebsd.org/ftp/releases/amd64/12.0-RELEASE/doc.txz

- [] Supply what you expected the result or output to be
should have fetched the release.

- [ ] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by patrickmalsom** [comment]
I just ran into this problem as well (FreeBSD-12.0 with `py37-iocage` installed from `pkg`). FreeBSD is no longer supplying the doc.txz file. It seems that the master branch already has the fix: c2a72f3367978ccd57f749f287175e5f7aab097b

`iocage-fetch` completed after editing the files in `/usr/local/lib/python3.6/site-packages/iocage/lib`.

**Comment by kpfleming** [comment]
That doesn't seem like the right fix, since older FreeBSD releases still supply those files. A better fix would be to pull down the MANIFEST file first, parse it, and then remove anything from ```files``` which is not listed in MANIFEST. That way if the FreeBSD release doesn't include ```doc.txz``` iocage won't try to retrieve it, but it will still be retrieved for releases that provide it.

**Comment by skarekrow** [comment]
As @patrickmalsom noted, that's the only fix as upstream deprecated those dists. iocage has a new version (1.0) that solves this issue as well, I encourage you to upgrade :)
