### ISSUE TITLE
iocage explodes when a jail was not cleanly created

### ISSUE THREAD

**Issue by Licenser** [iocage/iocage#80]
Right now I'm investigating as of why the creation failed (report pending;) but that aside it feels like this could be handled more gracefully.

the `root/data` was not created that seems to be where everything falls apart.

```
[root@fifo-bsd ~/iocage]# iocage list
cannot open 'zroot/iocage/jails/0577a3fe-4786-41ee-a962-97db79861ac9/root/data': dataset does not exist
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 113, in json_load
    with open(self.location + "/config.json", "r") as conf:
FileNotFoundError: [Errno 2] No such file or directory: '/iocage/jails/0577a3fe-4786-41ee-a962-97db79861ac9/config.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/iocage/main.py", line 94, in main
    cli(obj=MODULES)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/list.py", line 47, in list_cmd
    _list = IOCList(dataset_type, header, _long).list_datasets()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_list.py", line 58, in list_datasets
    _all = self.list_all(datasets)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_list.py", line 119, in list_all
    conf = IOCJson(jail).json_load()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 193, in json_load
    self.json_convert_from_zfs(uuid, skip=skip)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 92, in json_convert_from_zfs
    "{}/root/data".format(dataset)])
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_common.py", line 191, in checkoutput
    out = check_output(*args, **kwargs).decode("utf-8")
  File "/usr/local/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['zfs', 'set', 'jailed=off', 'zroot/iocage/jails/0577a3fe-4786-41ee-a962-97db79861ac9/root/data']' returned non-zero exit status 1.
```

and zfs list

```
NAME                                                           USED  AVAIL  REFER  MOUNTPOINT
zroot                                                         8.11G   438G    96K  /zroot
zroot/ROOT                                                    5.83G   438G    96K  none
zroot/ROOT/default                                            5.83G   438G  5.83G  /
zroot/iocage                                                   467M   438G   104K  /iocage
zroot/iocage/download                                          112M   438G    96K  /iocage/download
zroot/iocage/download/11.0-RELEASE                             112M   438G   112M  /iocage/download/11.0-RELEASE
zroot/iocage/images                                             96K   438G    96K  /iocage/images
zroot/iocage/jails                                             200K   438G    96K  /iocage/jails
zroot/iocage/jails/0577a3fe-4786-41ee-a962-97db79861ac9        104K   438G    96K  /iocage/jails/0577a3fe-4786-41ee-a962-97db79861ac9
zroot/iocage/jails/0577a3fe-4786-41ee-a962-97db79861ac9/root     8K   438G   355M  /iocage/jails/0577a3fe-4786-41ee-a962-97db79861ac9/root
zroot/iocage/log                                               136K   438G   136K  /iocage/log
zroot/iocage/releases                                          355M   438G    96K  /iocage/releases
zroot/iocage/releases/11.0-RELEASE                             355M   438G    96K  /iocage/releases/11.0-RELEASE
zroot/iocage/releases/11.0-RELEASE/root                        355M   438G   355M  /iocage/releases/11.0-RELEASE/root
zroot/iocage/templates                                          96K   438G    96K  /iocage/templates
zroot/tmp                                                     42.9M   438G  42.9M  /tmp
zroot/usr                                                     1.78G   438G    96K  /usr
zroot/usr/home                                                  96K   438G    96K  /usr/home
zroot/usr/ports                                                624M   438G   624M  /usr/ports
zroot/usr/src                                                 1.17G   438G  1.17G  /usr/src
zroot/var                                                     2.59M   438G    96K  /var
zroot/var/audit                                                 96K   438G    96K  /var/audit
zroot/var/crash                                                 96K   438G    96K  /var/crash
zroot/var/log                                                 1.36M   438G  1.36M  /var/log
zroot/var/mail                                                 124K   438G   124K  /var/mail
zroot/var/tmp                                                  844K   438G   844K  /var/tmp
```

**Comment by skarekrow** [comment]
Yeah that's a red herring since it's using the exception to think it's migrating an old style jail. We should have one more check there :D

**Comment by skarekrow** [comment]
Closing as the latest commits should make this a moot point. Will revisit if they don't.
