### ISSUE TITLE
Fresh install from Ports on FreeBSD 12-RELEASE

### ISSUE THREAD

**Issue by andros-ua** [iocage/iocage#828]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
Version 1.0 RELEASE 2018/12     from FreeBSD Ports
- [x] Supply the commands used, along with any steps to recreate it.
`iocage fetch -r LATEST` first time after installation

To recreate errors:
`zfs destroy -r zroot/iocage`
`iocage fetch -r LATEST`

- [x] Provide the output from the command you issued.
Setting up zpool [zroot] for iocage usage
If you wish to change please use "iocage activate"
********************************************************************************
fdescfs(5) is not mounted, performance may suffer. Please run:
mount -t fdescfs null /dev/fd
You can also permanently mount it in /etc/fstab with the following entry:
fdescfs /dev/fd  fdescfs  rw  0  0
********************************************************************************

Creating zroot/iocage
Creating zroot/iocage/download
Creating zroot/iocage/images
Creating zroot/iocage/jails
Creating zroot/iocage/log
Creating zroot/iocage/releases
Creating zroot/iocage/templates
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/fetch.py", line 129, in cli
    ioc.IOCage().fetch(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 113, in __init__
    self.pool = PoolAndDataset().get_pool()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 54, in __init__
    self.pool = ioc_json.IOCJson().json_get_value("pool")
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 841, in __init__
    super().__init__(location, checking_datasets, silent, callback)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 169, in __init__
    self.pool, self.iocroot = self.get_pool_and_iocroot()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 317, in get_pool_and_iocroot
    return pool, get_iocroot()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 315, in get_iocroot
    raise RuntimeError(f"Please set a mountpoint on {loc}")
RuntimeError: Please set a mountpoint on zroot/iocage

- [x] Supply what you expected the result or output to be
Fetched the latest RELEASE
- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by skarekrow** [comment]
Read the error :)

You must be using legacy mountpoints, set a mountpoint on `zroot/iocage`

**Comment by andros-ua** [comment]
I saw the error message.
Not using legacy mount points.
I followed the documentation at https://iocage.readthedocs.io/en/latest/basic-use.html
> Once iocage is ready with an active zpool, users are able to immediately begin downloading FreeBSD releases for jail creation.

There is nothing about mount points. I assumed they must be created automatically.
And a lot of code errors that are not user friendly.
After `zfs set mountpoint=/iocage zroot/iocage` it runs normally.
