### ISSUE TITLE
Unable to rename jail

### ISSUE THREAD

**Issue by djmixman** [iocage/iocage#925]
- [X] Supply `iocage --version`
- [X] Supply the commands used, along with any steps to recreate it.
- [X] Provide the output from the command you issued.
- [X] Supply what you expected the result or output to be
- [ ] Checked that the problem has not already been fixed on `master` if using
 a stable release.

`iocage --version : Version 1.2 BETA && Version 1.1 RELEASE 2019/01`
`Freebsd Version: 11.2-RELEASE`

```
iocage activate n1a1
export IOCAGE_COLOR=TRUE
iocage fetch
iocage list
iocage create -r 11.2-RELEASE
iocage list
iocage set notes="This is a test jail." ffadbf73
iocage get notes ffadbf73
iocage get all ffadbf73
iocage rename ffadbf73 TESTJAIL
```

```
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/rename.py", line 39, in cli
    ioc.IOCage(jail=jail).rename(new_name)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 1420, in rename
    for release_snap, rel_path in self.release_snapshots.items():
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 534, in release_snapshots
    for snap in rel_dir.glob('**/root/.zfs/snapshot/*'):
  File "/usr/local/lib/python3.6/pathlib.py", line 1100, in glob
    for p in selector.select_from(self):
  File "/usr/local/lib/python3.6/pathlib.py", line 559, in _select_from
    for starting_point in self._iterate_directories(parent_path, is_dir, scandir):
  File "/usr/local/lib/python3.6/pathlib.py", line 549, in _iterate_directories
    for p in self._iterate_directories(path, is_dir, scandir):
  File "/usr/local/lib/python3.6/pathlib.py", line 545, in _iterate_directories
    entries = list(scandir(parent_path))
OSError: [Errno 22] Invalid argument: '/n1a1/iocage/releases/.zfs'
```
Expected: Jail to be renamed

**Comment by sonicaj** [comment]
@djmixman can you please verify if this is still an issue for you ?
```
root@freenas[~]# iocage list
Creating vol1/iocage/jails
+-----+------+-------+---------+-----+
| JID | NAME | STATE | RELEASE | IP4 |
+=====+======+=======+=========+=====+
+-----+------+-------+---------+-----+
root@freenas[~]# iocage create -r 11.2-RELEASE
13f5179f-57e8-4a88-9b13-31d25853008e successfully created!
root@freenas[~]# iocage list
+-----+----------+-------+--------------+-----+
| JID |   NAME   | STATE |   RELEASE    | IP4 |
+=====+==========+=======+==============+=====+
| -   | 13f5179f | down  | 11.2-RELEASE | -   |
+-----+----------+-------+--------------+-----+
root@freenas[~]# iocage set notes="This is a test jail." 13f5179f
notes: none -> This is a test jail.
root@freenas[~]# iocage get notes 13f5179f
This is a test jail.
root@freenas[~]# iocage rename 13f5179f TESTJAIL
Jail: 13f5179f-57e8-4a88-9b13-31d25853008e renamed to TESTJAIL
root@freenas[~]# iocage list
+-----+----------+-------+--------------+-----+
| JID |   NAME   | STATE |   RELEASE    | IP4 |
+=====+==========+=======+==============+=====+
| -   | TESTJAIL | down  | 11.2-RELEASE | -   |
+-----+----------+-------+--------------+-----+
root@freenas[~]#
```
This is from latest master.

**Comment by djmixman** [comment]
I just wiped out my test setup yesterday. I'll set it all back up this weekend and get back to you.

**Comment by sonicaj** [comment]
Perfect, thank you

**Comment by djmixman** [comment]
Ok sorry for the delay..

I've reinstalled FreeBSD and have moved to 12.0-RELEASE. I tested with the ports again to verify I still would get the same error.

It turns out that the cause of the error is the snapshot directory ".zfs" within the zfs volume. If you set the property "snapdir=hidden" on the volume it fixes the error on renaming the jails. If "snapdir=visible" then you will receive the error.

```
SVR01:~ # zfs set snapdir=hidden s1a1/iocage

SVR01:~ # iocage rename bfaa786c TESTJAIL
Jail: bfaa786c-bcfd-41b2-906b-56930d8bfc33 renamed to TESTJAIL

SVR01:~ # zfs set snapdir=visible s1a1/iocage

SVR01:~ # iocage rename TESTJAIL TESTJAIL2
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/rename.py", line 39, in cli
    ioc.IOCage(jail=jail).rename(new_name)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 1340, in rename
    for release_snap, rel_path in self.release_snapshots.items():
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 273, in release_snapshots
    for snap in rel_dir.glob('**/root/.zfs/snapshot/*'):
  File "/usr/local/lib/python3.6/pathlib.py", line 1100, in glob
    for p in selector.select_from(self):
  File "/usr/local/lib/python3.6/pathlib.py", line 559, in _select_from
    for starting_point in self._iterate_directories(parent_path, is_dir, scandir):
  File "/usr/local/lib/python3.6/pathlib.py", line 549, in _iterate_directories
    for p in self._iterate_directories(path, is_dir, scandir):
  File "/usr/local/lib/python3.6/pathlib.py", line 545, in _iterate_directories
    entries = list(scandir(parent_path))
OSError: [Errno 22] Invalid argument: '/s1a1/iocage/releases/.zfs'
```

**Comment by gutiersa** [comment]
Hello:
I am using FreeBSD 12.1-RELEASE-p3 and IOCAGE version 1.2_5 (installed from ports). After renaming a jail I am getting syslog errors:

> "hostname syslogd /zroot/iocage/jails/oldjailname/root/var/log/nginx/access.log: No such file or directory"

If this has already been addressed elsewhere I apologize in advance and would appreciate to be pointed to the solution. 

Thanks

**Comment by rob4226** [comment]
@djmixman Thanks! `zfs set snapdir=hidden zroot/iocage` before the rename stopped the error!
