### ISSUE TITLE
iocage get -a gives an error when we don't have any jails configured.

### ISSUE THREAD

**Issue by yerrysherry** [iocage/iocage#966]
Make sure to follow and check these boxes before submitting an issue! Thank you.

# iocage --version
Version	1.2 RC

I don't have any jails yet?
# iocage list
+-----+------+-------+---------+-----+
| JID | NAME | STATE | RELEASE | IP4 |
+=====+======+=======+=========+=====+
+-----+------+-------+---------+-----+

# iocage get -p
jails

root@jail1:~ # iocage get
You must specify a jail!

root@jail1:~ # iocage get -a
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 1622, in json_load
    f"{self.pool}/iocage/{jail_type}/{jail_uuid}")
  File "libzfs.pyx", line 604, in libzfs.ZFS.get_dataset
libzfs.ZFSException: Dataset jails/iocage/jails/ not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/get.py", line 114, in cli
    props = ioc.IOCage(jail=jail, skip_jails=True).get(prop)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 1303, in get
    props = ioc_json.IOCJson(path).json_get_value(prop)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 1871, in json_get_value
    return self.get_full_config()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 1503, in get_full_config
    conf, write = self.json_load()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 1644, in json_load
    f'{jail_type.rstrip("s").capitalize()}:'
iocage_lib.ioc_exceptions.JailMissingConfiguration: Jail:  has a missing configuration, please check that the dataset is mounted.

root@jail1:/jails/iocage/jails # ls -l
total 0

**Comment by yerrysherry** [comment]
Also when there are jails configured we get this bug

root@jail1:~ # iocage list -h
4	dns4	up	11.2-RELEASE	192.168.59.61
3	www1	up	11.2-RELEASE	192.168.59.60
root@jail1:~ #
root@jail1:~ # iocage get -a
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 1626, in json_load
    f"{self.pool}/iocage/{jail_type}/{jail_uuid}")
  File "libzfs.pyx", line 604, in libzfs.ZFS.get_dataset
libzfs.ZFSException: Dataset jails/iocage/jails/ not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/get.py", line 114, in cli
    props = ioc.IOCage(jail=jail, skip_jails=True).get(prop)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 1303, in get
    props = ioc_json.IOCJson(path).json_get_value(prop)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 1875, in json_get_value
    return self.get_full_config()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 1507, in get_full_config
    conf, write = self.json_load()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 1648, in json_load
    f'{jail_type.rstrip("s").capitalize()}:'
iocage_lib.ioc_exceptions.JailMissingConfiguration: Jail:  has a missing configuration, please check that the dataset is mounted.

**Comment by sonicaj** [comment]
@yerrysherry a jail name is required for which all props should be listed for with `-a` flag. However we can certainly improve this by it being an error message instead of a traceback.
