### ISSUE TITLE
Upgrade error

### ISSUE THREAD

**Issue by pos42** [iocage/iocage#977]
Hi

18:49:00 huey:/usr/ports # iocage -v
Version	1.1 RELEASE 2019/01

18:49:59 huey:/usr/ports # freebsd-version 
12.0-RELEASE-p6

I have run iocage fetch --update and haver updated both 12.0 and 11.2 locally...

Now...
Trying to run "iocage upgrade WEB -r 12.0-RELEASE"

After it is done it refers to a script to run in /tmp/ . A script that does not work. 

The jail is after this says it has 12.0p6 instead of 11.2. But it is not working as expected. pkg for example says there is an ssl error. And trying "iocage update WEB" in the host says I have to run a script it points out in /tmp with a -install flag. A script if run that says I have to run the same script with -fetch first. After that it says there is nothing to install.

Going over to the jail itself trying to upgrade there, I see...

18:47:20 WEB:~ # freebsd-update upgrade -r 12.0-RELEASE
src component not installed, skipped
freebsd-update: Cannot upgrade from 12.0-RELEASE to itself
18:47:30 WEB:~ # 

So I cannot upgrade jail from within the jail and not from the host with iocage. I had to rollback and import the earlier version to 11.2.....

An iocage bug? Or what have I missed?

/Peo

**Comment by sonicaj** [comment]
Hello @pos42, i am sorry i haven't followed you on this one. Can you please state your objective first, like what you are trying to achieve ? That would be saying i want to update 11.2 jail to 12.0 for example. Once done with that, please share the steps you used to achieve that objective and then the end result and how it differs from your expectations.

**Comment by pos42** [comment]
Well... The subject is "upgrade". But sorry if not totally clear...

I am trying to upgrade jails from 11.2 to 12.0. I.e to the same version as the host.

**Comment by sonicaj** [comment]
Please correct me if i got this wrong, but your issue is that the upgrade was succuessful but now you can't use pkg ?
```
But it is not working as expected. pkg for example says there is an ssl error. 
```

**Comment by pos42** [comment]
@sonicaj  The first upgrade command "iocage upgrade WEB -r 12.0-RELEASE" was successful yes, but requires running a post script in the /tmp which does not work as stated in the output from the "iocage upgrade WEB -r 12.0-RELEASE" command. So the complete upgrade of the jail OS from 11.2 to 12.0 was *not* a success. See initial post...

The jail OS is not working as expected as the OS upgrade from 11.2 to 12.0 is half done. This due to what I write in the initial post. The pkg command was just a test in the jail OS. I could have skipped that test. So do not focus on the pkg command...

Trying "iocage update WEB" as a test afterwards and it fails and says I should run a script in /tmp that it refers to (that is not working). I guess, because of the upgrade was never finished and iocage sees that. Just half done.

**Comment by sonicaj** [comment]
@pos42 can you please share the complete execution of upgrade command ? I am sorry i can't help you more until i know what steps were taken and where/how it failed. Please try another upgrade and copy the text here. There are many things which can go wrong on upgrades and it is very possible that this has nothing to do with iocage at all but not making any assumptions just right now :). ( Also please use github's formatting to share it, for the command it would be three backticks at the start and then three at the end. Also you can use preview option where you type the comment to see how it will actually look after the formatting ). 
Looking forward to hearing from you, thank you!

**Comment by pos42** [comment]
I guess there was a problem with the pkg upgrade after the OS upgrade.

See further down...

```
12:09:39 huey:~ # iocage destroy --recursive WEB
12:15:41 huey:~ # iocage import WEB_2019-06-29
12:18:13 huey:~ # iocage start WEB
* Starting WEB
  + Started OK
  + Using devfs_ruleset: 7
  + Starting services OK
  + Executing poststart OK
12:18:27 huey:~ # 
12:22:08 huey:~ # freebsd-version 
12.0-RELEASE-p6

12:22:15 huey:~ # iocage list|grep WEB
| 24  | WEB  | up    | 11.2-RELEASE | MY_IP_GOES_HERE |


12:22:23 huey:~ # 

12:23:24 huey:~ # df -h|grep releases
zroot/iocage/releases                      4.2G     88K    4.2G     0%    /iocage/releases
zroot/iocage/releases/11.2-RELEASE         4.2G     88K    4.2G     0%    /iocage/releases/11.2-RELEASE
zroot/iocage/releases/11.2-RELEASE/root    5.3G    1.0G    4.2G    20%    /iocage/releases/11.2-RELEASE/root
zroot/iocage/releases/12.0-RELEASE         4.2G     88K    4.2G     0%    /iocage/releases/12.0-RELEASE
zroot/iocage/releases/12.0-RELEASE/root    5.5G    1.3G    4.2G    23%    /iocage/releases/12.0-RELEASE/root
12:23:32 huey:~ # 

12:23:49 huey:~ # iocage upgrade WEB -r 12.0-RELEASE
Looking up update.FreeBSD.org mirrors... 3 mirrors found.
Fetching metadata signature for 11.2-RELEASE from update1.freebsd.org... done.
Fetching metadata index... done.
Fetching 1 metadata files... done.
Inspecting system... done.

The following components of FreeBSD seem to be installed:
world/base world/doc world/lib32

The following components of FreeBSD do not seem to be installed:
src/src world/base-dbg world/lib32-dbg

Does this look reasonable (y/n)? y

Fetching metadata signature for 12.0-RELEASE from update1.freebsd.org... done.
Fetching metadata index... done.
Fetching 1 metadata patches. done.
Applying metadata patches... done.
Fetching 1 metadata files... done.
Inspecting system... done.
Fetching files from 11.2-RELEASE for merging... done.
Preparing to download files... 
Fetching 7900 patches....10....20....
--CUT--
CUT OUT PATH FETCH OUTPUT
--CUT--
....7880....7890....7900 done.
Applying patches...  done.
Fetching 1116 files... done.
Attempting to automatically merge changes in files... done.

The following changes, which occurred between FreeBSD 11.2-RELEASE and
--CUT--
MERGING OF FOUR FILES
--CUT--


The following files are affected by updates, but no changes have
been downloaded because the files have been modified locally:
/var/db/locate.database

The following files will be removed as part of updating to 12.0-RELEASE-p6:
--CUT--
CUT OUT FILES OUTPUT
--CUT--

To install the downloaded upgrades, run "/tmp/tmp0az6c09s install".
Installing updates...
Kernel updates have been installed.  Please reboot and run
"/tmp/tmp0az6c09s install" again to finish installing updates.
Installing updates...
Completing this upgrade requires removing old shared object files.
Please rebuild all installed 3rd party software (e.g., programs
installed from the ports tree) and then run "/tmp/tmp0az6c09s install"
again to finish installing updates.
Installing updates...rmdir: /iocage/jails/WEB/root//var/db/etcupdate/current/usr/share/openssl/man/en.ISO8859-1: Directory not empty
rmdir: /iocage/jails/WEB/root//var/db/etcupdate/current/usr/share/openssl/man: Directory not empty
rmdir: /iocage/jails/WEB/root//var/db/etcupdate/current/usr/share/openssl: Directory not empty
rmdir: /iocage/jails/WEB/root//var/db/etcupdate/current/usr/share/man/en.UTF-8: Directory not empty
rmdir: /iocage/jails/WEB/root//var/db/etcupdate/current/usr/share/man/en.ISO8859-1: Directory not empty
rmdir: /iocage/jails/WEB/root//var/db/etcupdate/current/usr/share/man: Directory not empty
 done.

WEB successfully upgraded from 11.2-RELEASE-p10 to 12.0-RELEASE-p6!
13:30:35 huey:~ # 

13:34:41 huey:~ # iocage list |grep WEB
| 24  | WEB  | up    | 12.0-RELEASE | MY_IP_GOES_HERE |
13:34:46 huey:~ # 


######## IN THE JAIL....
root@WEB:~ # pkg info
ld-elf.so.1: Shared object "libssl.so.8" not found, required by "pkg"
root@WEB:~ # 


######## IN THE HOST AGAIN...

13:36:32 huey:~ # iocage pkg WEB upgrade
Updating FreeBSD repository catalogue...
Updating FreeBSD repository catalogue...
[WEB] Fetching meta.txz: . done
[WEB] Fetching packagesite.txz: .......... done
Processing entries: .......... done
FreeBSD repository update completed. 31777 packages processed.
All repositories are up to date.
Checking for upgrades (32 candidates): .......... done
Processing candidates (32 candidates): .......... done
The following 32 package(s) will be affected (of 0 checked):

Installed packages to be REINSTALLED:
	pkg-1.10.5_5 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	wget-1.20.3 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	sudo-1.8.27_1 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	readline-7.0.5 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	python27-2.7.16 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	perl5-5.28.1_1 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	pcre-8.43 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	p5-Socket6-0.29 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	p5-Net-SSLeay-1.85 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	p5-Mozilla-CA-20180117 (ABI changed: 'freebsd:11:*' -> 'freebsd:12:*')
	p5-IO-Socket-SSL-2.060 (ABI changed: 'freebsd:11:*' -> 'freebsd:12:*')
	p5-IO-Socket-INET6-2.72_1 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	p5-HTML-Tagset-3.20_1 (ABI changed: 'freebsd:11:*' -> 'freebsd:12:*')
	p5-HTML-Parser-3.72 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	p5-GSSAPI-0.28_1 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	p5-Error-0.17027 (ABI changed: 'freebsd:11:*' -> 'freebsd:12:*')
	p5-Digest-HMAC-1.03_1 (ABI changed: 'freebsd:11:*' -> 'freebsd:12:*')
	p5-CGI-4.42 (ABI changed: 'freebsd:11:*' -> 'freebsd:12:*')
	p5-Authen-SASL-2.16_1 (ABI changed: 'freebsd:11:*' -> 'freebsd:12:*')
	nginx-1.14.2_13,2 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	libunistring-0.9.10_1 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	libnghttp2-1.37.0 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	libidn2-2.1.1 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	libffi-3.2.1_3 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	indexinfo-0.3.1 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	git-2.21.0 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	gettext-runtime-0.19.8.1_2 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	expat-2.2.6_1 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	cvsps-2.1_2 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	curl-7.65.0_2 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	ca_root_nss-3.44.1 (ABI changed: 'freebsd:11:*' -> 'freebsd:12:*')
	bash-5.0.3 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')

Number of packages to be reinstalled: 32

The process will require 2 MiB more space.
41 MiB to be downloaded.


I GOT NO OUTPUT HERE AND IT FAILED.... I COULD SEE I DID NOT GET ANY Y/N QUESTION...

NOW.... 
I have used "setenv IOCAGE_COLOR TRUE" in my shell config. Could that matter???


SO I RUN THE SAME PKG UPGRADE COMMAND AGAIN BUT SAID "y" WITHOUT SEEING ANY QUESTION... 
I SAW THE QUESTION AFTER I ANSWERED "y". 
AND NOW IT STARTED TO UPGRADE THE PACKAGES....

13:49:41 huey:~ # iocage pkg WEB upgrade
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
Checking for upgrades (32 candidates): .......... done
Processing candidates (32 candidates): .......... done
The following 32 package(s) will be affected (of 0 checked):

Installed packages to be REINSTALLED:
	pkg-1.10.5_5 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	wget-1.20.3 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	sudo-1.8.27_1 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	readline-7.0.5 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	python27-2.7.16 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	perl5-5.28.1_1 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	pcre-8.43 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	p5-Socket6-0.29 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	p5-Net-SSLeay-1.85 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	p5-Mozilla-CA-20180117 (ABI changed: 'freebsd:11:*' -> 'freebsd:12:*')
	p5-IO-Socket-SSL-2.060 (ABI changed: 'freebsd:11:*' -> 'freebsd:12:*')
	p5-IO-Socket-INET6-2.72_1 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	p5-HTML-Tagset-3.20_1 (ABI changed: 'freebsd:11:*' -> 'freebsd:12:*')
	p5-HTML-Parser-3.72 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	p5-GSSAPI-0.28_1 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	p5-Error-0.17027 (ABI changed: 'freebsd:11:*' -> 'freebsd:12:*')
	p5-Digest-HMAC-1.03_1 (ABI changed: 'freebsd:11:*' -> 'freebsd:12:*')
	p5-CGI-4.42 (ABI changed: 'freebsd:11:*' -> 'freebsd:12:*')
	p5-Authen-SASL-2.16_1 (ABI changed: 'freebsd:11:*' -> 'freebsd:12:*')
	nginx-1.14.2_13,2 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	libunistring-0.9.10_1 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	libnghttp2-1.37.0 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	libidn2-2.1.1 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	libffi-3.2.1_3 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	indexinfo-0.3.1 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	git-2.21.0 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	gettext-runtime-0.19.8.1_2 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	expat-2.2.6_1 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	cvsps-2.1_2 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	curl-7.65.0_2 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')
	ca_root_nss-3.44.1 (ABI changed: 'freebsd:11:*' -> 'freebsd:12:*')
	bash-5.0.3 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:12:x86:64')

Number of packages to be reinstalled: 32

The process will require 2 MiB more space.
41 MiB to be downloaded.
y

Proceed with this action? [y/N]: [WEB] [1/32] Fetching pkg-1.10.5_5.txz: .......... done
[WEB] [2/32] Fetching wget-1.20.3.txz: .......... done
[WEB] [3/32] Fetching sudo-1.8.27_1.txz: .......... done
[WEB] [4/32] Fetching readline-7.0.5.txz: .......... done
[WEB] [5/32] Fetching python27-2.7.16.txz: .......... done
[WEB] [6/32] Fetching perl5-5.28.1_1.txz: .......... done


AND THIS NOW WENT ON AND WORKED....

```

**Comment by pos42** [comment]
It seems WEB jail works. But something is not working.... So the upgrade seems not 100% ok yet.

A bug or I am missing something obvious...


```

14:10:16 huey:~ # iocage update WEB

* Updating WEB to the latest patch level... 
You have a partially completed upgrade pending
Run '/tmp/tmp_7gfcjot install' first.
Run '/tmp/tmp_7gfcjot fetch -F' to proceed anyway.
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/update.py", line 39, in cli
    ioc.IOCage(jail=jail, skip_jails=skip_jails).update()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 1894, in update
    ).fetch_update(True, uuid)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_fetch.py", line 911, in fetch_update
    _exec, callback=self.callback)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_common.py", line 873, in consume_and_log
    for stdout, _ in exec_gen:
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_exec.py", line 260, in exec_jail
    list(stderr_queue)
iocage_lib.ioc_exceptions.CommandFailed: [b'']
14:10:26 huey:~ # /tmp/tmp_7gfcjot install
No updates are available to install.
Run '/tmp/tmp_7gfcjot fetch' first.
14:11:53 huey:~ # /tmp/tmp_7gfcjot fetch
Looking up update.FreeBSD.org mirrors... 3 mirrors found.
Fetching metadata signature for 12.0-RELEASE from update2.freebsd.org... done.
Fetching metadata index... done.
Inspecting system... done.
Preparing to download files... done.

No updates needed to update system to 12.0-RELEASE-p6.
14:12:27 huey:~ # 
14:12:30 huey:~ # /tmp/tmp_7gfcjot install
No updates are available to install.
Run '/tmp/tmp_7gfcjot fetch' first.
14:12:32 huey:~ # 
14:12:36 huey:~ # 
14:12:36 huey:~ # iocage update WEB

* Updating WEB to the latest patch level... 
You have a partially completed upgrade pending
Run '/tmp/tmpwsps71u9 install' first.
Run '/tmp/tmpwsps71u9 fetch -F' to proceed anyway.
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/update.py", line 39, in cli
    ioc.IOCage(jail=jail, skip_jails=skip_jails).update()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 1894, in update
    ).fetch_update(True, uuid)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_fetch.py", line 911, in fetch_update
    _exec, callback=self.callback)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_common.py", line 873, in consume_and_log
    for stdout, _ in exec_gen:
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_exec.py", line 260, in exec_jail
    list(stderr_queue)
iocage_lib.ioc_exceptions.CommandFailed: [b'', b'', b'', b'', b'', b'', b'', b'', b'', b'', b'', b'', b'', b'', b'', b'', b'', b'', b'', b'', b'']
14:12:42 huey:~ # 
14:12:50 huey:~ # /tmp/tmpwsps71u9 install
No updates are available to install.
Run '/tmp/tmpwsps71u9 fetch' first.
14:12:57 huey:~ # /tmp/tmpwsps71u9 fetch
Looking up update.FreeBSD.org mirrors... 3 mirrors found.
Fetching metadata signature for 12.0-RELEASE from update2.freebsd.org... done.
Fetching metadata index... done.
Inspecting system... done.
Preparing to download files... done.

No updates needed to update system to 12.0-RELEASE-p6.
14:13:20 huey:~ # 
14:13:22 huey:~ # iocage update WEB

* Updating WEB to the latest patch level... 
You have a partially completed upgrade pending
Run '/tmp/tmp3mqonqk6 install' first.
Run '/tmp/tmp3mqonqk6 fetch -F' to proceed anyway.
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/update.py", line 39, in cli
    ioc.IOCage(jail=jail, skip_jails=skip_jails).update()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 1894, in update
    ).fetch_update(True, uuid)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_fetch.py", line 911, in fetch_update
    _exec, callback=self.callback)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_common.py", line 873, in consume_and_log
    for stdout, _ in exec_gen:
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_exec.py", line 260, in exec_jail
    list(stderr_queue)
iocage_lib.ioc_exceptions.CommandFailed: [b'', b'']
14:13:30 huey:~ # 


```

**Comment by pos42** [comment]
I can see similar problems in other posts since 3-4 weeks back. So I guess this might be a know problem.

For now I have run "iocage set securelevel=0 WEB" in the host and double checked the system is ok updated from inside the WEB jail and then set back "iocage set securelevel=2 WEB".

So this WEB jail is upgraded to 12.0-RELEASE-p6 and seems ok with my also upgraded packages. But I will wait with my other jails to see how this thread and the other with similar problems falls out. I want to if possible handle all jails and their upgrades+updates with the iocage cli...

**Comment by vendion** [comment]
I also see similar issues trying to update a jail to a newer patch level

```
[/u/h/vendion]─> doas iocage list
+-----+------+-------+--------------+-------------+
| JID | NAME | STATE |   RELEASE    |     IP4     |
+=====+======+=======+==============+=============+
| -   | hugo | down  | 12.0-RELEASE | 192.168.0.2 |
+-----+------+-------+--------------+-------------+
[/u/h/vendion]─> doas iocage update hugo

* Updating hugo to the latest patch level... 
You have a partially completed upgrade pending
Run '/tmp/tmpbptczik1 install' first.
Run '/tmp/tmpbptczik1 fetch -F' to proceed anyway.
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/update.py", line 39, in cli
    ioc.IOCage(jail=jail, skip_jails=skip_jails).update()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 1894, in update
    ).fetch_update(True, uuid)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_fetch.py", line 911, in fetch_update
    _exec, callback=self.callback)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_common.py", line 873, in consume_and_log
    for stdout, _ in exec_gen:
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_exec.py", line 260, in exec_jail
    list(stderr_queue)
iocage_lib.ioc_exceptions.CommandFailed: [b'']
```

That is the result from trying to update a jail from FreeBSD 12.0-RELEASE-p8 -> 12.0-RELEASE-p9.  Setting the `securelevel` property to 0 and doing the update within the jail does seem to work though.
