### ISSUE TITLE
"iocage fetch --plugins" broken?

### ISSUE THREAD

**Issue by jsegaert** [iocage/iocage#995]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
- [x] Supply the commands used, along with any steps to recreate it.
- [x] Provide the output from the command you issued.
- [x] Supply what you expected the result or output to be
- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

Installing plugins no longer seems to work.  I'm running master, latest commit a0621af4d974ae097366368c37979e9abaff8075 on vanilla FreeBSD 12.0

```
sudo iocage fetch --plugins -P mineos ip4_addr="wlan0|192.168.0.210/24" vnet=off
```
This results in the following output:
```
Plugin: mineos
  Official Plugin: False
  Using RELEASE: 11.2-RELEASE
  Using Branch: 12.0-RELEASE
  Post-install Artifact: https://github.com/jsegaert/iocage-plugin-mineos.git
  These pkgs will be installed:
    - sysutils/rdiff-backup
    - sysutils/screen
    - net/rsync
    - devel/gmake
    - devel/git-lite
    - lang/python2
    - www/node8
    - www/npm-node8
    - java/openjdk8-jre
    - ftp/wget
    - shells/bash

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 1609, in json_load
    f"{self.pool}/iocage/{jail_type}/{jail_uuid}")
  File "libzfs.pyx", line 604, in libzfs.ZFS.get_dataset
libzfs.ZFSException: Dataset zroot/iocage/jails/None not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_plugin.py", line 271, in fetch_plugin
    jaildir, _conf, repo_dir = self.__fetch_plugin_create__(props)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_plugin.py", line 492, in __fetch_plugin_create__
    _conf = iocage_lib.ioc_json.IOCJson(jaildir).json_get_value('all')
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 1858, in json_get_value
    return self.get_full_config()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 1490, in get_full_config
    conf, write = self.json_load()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 1631, in json_load
    f'{jail_type.rstrip("s").capitalize()}:'
iocage_lib.ioc_exceptions.JailMissingConfiguration: Jail: None has a missing configuration, please check that the dataset is mounted.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 1609, in json_load
    f"{self.pool}/iocage/{jail_type}/{jail_uuid}")
  File "libzfs.pyx", line 604, in libzfs.ZFS.get_dataset
libzfs.ZFSException: Dataset zroot/iocage/jails/None not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/fetch.py", line 181, in cli
    ioc.IOCage().fetch(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 1105, in fetch
    props, accept_license=accept, official=official)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_plugin.py", line 902, in fetch_plugin_index
    self.fetch_plugin(props, 0, accept_license)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_plugin.py", line 282, in fetch_plugin
    iocage_lib.ioc_destroy.IOCDestroy().destroy_jail(location)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_destroy.py", line 271, in destroy_jail
    iocage_lib.ioc_stop.IOCStop(uuid, path, silent=True)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_stop.py", line 62, in __init__
    raise e
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_stop.py", line 55, in __init__
    path, suppress_log=True).json_get_value('all')
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 1858, in json_get_value
    return self.get_full_config()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 1490, in get_full_config
    conf, write = self.json_load()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 1631, in json_load
    f'{jail_type.rstrip("s").capitalize()}:'
iocage_lib.ioc_exceptions.JailMissingConfiguration: Jail: None has a missing configuration, please check that the dataset is mounted.
```
That same traceback also occurs when the plugin is not specified, but the corresponding number is picked from the list after issuing e.g. this command:
```
sudo iocage fetch --plugins ip4_addr="wlan0|192.168.0.210/24" vnet=off
```
or when explicitly providing a jailname using this command:
```
sudo iocage fetch --plugins -P mineos -n minecraftjail ip4_addr="wlan0|192.168.0.210/24" vnet=off
```
This issue also exists in the FreeNAS nightlies.
Am I missing something?

**Comment by sonicaj** [comment]
Hello @jsegaert, so you can fetch plugin this way now
```
iocage fetch -P plugin_name -n jail_name vnet=1 nat=1
````
Extra `--plugins` should not be added. I'll see if we can improve the error handling here, though it is low priority right now.
Please let me know if there are still issues. Thank you!

**Comment by sonicaj** [comment]
Closing this in favor of #996

**Comment by jsegaert** [comment]
I did some more elaborate testing on this and do believe some issues are present.  I documented my findings and expectations below.

## 1. Old syntax:  (-P -> -plugin-file)
The below commands all work fine in older releases, i.e. all 3 scenarios resulted in a pluginjail called **plex**.
This was tested in FreeNAS 11.2, 

### 1.1 Install plugin from list of available plugins from plugin repo:
`iocage fetch --plugins dhcp=on vnet=on bpf=yes allow_raw_sockets=1`

### 1.2 Install from plugin repository w/o selection:
`iocage fetch --plugins -n plexmediaserver dhcp=on vnet=on bpf=yes allow_raw_sockets=1`

### 1.3 Install plugin from local manifest file:
`iocage fetch --plugin-file -n /mnt/tank/iocage/.plugin_index/plexmediaserver.json dhcp=on vnet=on bpf=yes allow_raw_sockets=1`

## 2. Current syntax:  (-P -> --plugin-name)
This below tests were executed using iocage master.
### 2.1 Install plugin from list of available plugins from plugin repo:
`iocage fetch --plugins dhcp=on vnet=on bpf=yes allow_raw_sockets=1`

This doesn't work, i.e. it results in the traceback as listed in the original post above.
### 2.2a Install from plugin repository w/o selection, default jailname:
`iocage fetch --plugin-name plexmediaserver dhcp=on vnet=on bpf=yes allow_raw_sockets=1`

This creates a jail called **plexmediaserver**.  I expected the jailname to be just **plex**, the default jailname as specified in the manifest.
### 2.2b Install from plugin repository w/o selection, specify own jailname:
`iocage fetch --plugin-name plexmediaserver -n myplexjail dhcp=on vnet=on bpf=yes allow_raw_sockets=1` 

This creates a pluginjail called myplexjail, as expected.  Note that this functionality was not supported in the old syntax. 
### 2.3a Install plugin from local manifest file, default jailname:
`iocage fetch --plugin-name /zroot/iocage/.plugins/github_com_freenas_iocage-ix-plugins_git/plexmediaserver.json dhcp=on vnet=on bpf=yes allow_raw_sockets=1`

This ends with an exception, as it doesn't seem to like that an absolute path is specified.  
Copying the manifest file to the working directory, and try again:

`iocage fetch --plugin-name plexmediaserver.json dhcp=on vnet=on bpf=yes allow_raw_sockets=1`

This creates a jail called **plexmediaserver.json**.  I expected the jailname to be just **plex**, the default jailname as specified in the manifest.

### 2.3b Install plugin from local manifest file, specify own jailname:
`iocage fetch --plugin-name plexmediaserver.json -n myplexjail dhcp=on vnet=on bpf=yes allow_raw_sockets=1`

This creates a pluginjail called myplexjail, as expected.  Note that this functionality was not supported in the old syntax.

**Comment by sonicaj** [comment]
@jsegaert we have a regression. I'll have it covered, thank you for the elaborate comment ;)

**Comment by sonicaj** [comment]
@jsegaert why are you expecting iocage to create a jail named `plex` and not `plexmediaserver` in 2.2a ?

**Comment by sonicaj** [comment]
Ah i see, you mention `name` as specified in json file. This is interesting as this is clearly not happening. @skarekrow please confirm if `name` in plugin manifest points to jail name ?

**Comment by skarekrow** [comment]
It does :)

**Comment by jsegaert** [comment]
> Ah i see, you mention `name` as specified in json file.

Correct; I expected the default jail name to be the "name" property from the manifest file, plexmediaserver.json  That's how it used to work.

**Comment by jsegaert** [comment]
Thank you for your quick response.  I reran the tests from my post above.  The plugin jails now get created in all cases, but there's some oddness with the jail names.

2.1 Install plugin from list of available plugins from plugin repo:
```
iocage fetch --plugins dhcp=on vnet=on bpf=yes allow_raw_sockets=1
```
:warning: Creates a jail named **plexmediaserver_5c2d**; I expected the jail to be named **plex**

Full output below:
```
(iocage-env) ➜  ~ sudo iocage fetch --plugins dhcp=on vnet=on bpf=yes allow_raw_sockets=1
Creating zroot/iocage/jails
[0] BackupPC - BackupPC is a high-performance, enterprise-grade system for backing up Linux, WinXX and MacOSX PCs and laptops to a s                                  erver's disk. (backuppc)
[1] Bacula-server - programs to manage backup, recovery, and verification of computer data across a network of computers of differen                                  t kinds (bacula-server)
[2] BRU Server - BRU Server™ Backup and Recovery Software by TOLIS Group, Inc. (bru-server)
[3] ClamAV - ClamAV® is an open source antivirus engine for detecting trojans, viruses, malware & other malicious threats. (clamav)
[4] CouchPotato - CouchPotato is an automatic NZB and torrent downloader. (couchpotato)
[5] Deluge - Bittorrent client using Python, and libtorrent-rasterbar (deluge)
[6] Dnsmasq - Dnsmasq provides network infrastructure for small networks: DNS, DHCP, router advertisement and network boot. (dnsmasq                                  )
[7] Emby - Home media server built using mono and other open source technologies (emby)
[8] GitLab - Powerful features for modern software development (gitlab)
[9] GitLab Runner - CI/CD runner powered by gitlab (gitlab-runner)
[10] Homebridge - Homebridge is a lightweight NodeJS server emulates the iOS HomeKit API and enables you to add not offically suppor                                  ted devices to HomeKit. (homebridge)
[11] irssi - Irssi is a modular IRC client that currently has only text mode user interface, but 80-90% of the code isn't text mode                                   specific, so other UIs could be created pretty easily. (irssi)
[12] Jenkins - Jenkins CI (jenkins)
[13] Jenkins (LTS) - Jenkins CI (Long Term Support Version) (jenkins-lts)
[14] MadSonic - Open-source web-based media streamer and jukebox. (madsonic)
[15] MineOS - MineOS is a web interface to set up and manage Minecraft servers with a few mouse clicks. (mineos)
[16] Nextcloud - Access, share and protect your files, calendars, contacts, communication & more at home and in your enterprise. (ne                                  xtcloud)
[17] OpenVPN Server - OpenVPN server (openvpn)
[18] Plex Media Server - The Plex media server system (plexmediaserver)
[19] Plex Media Server (PlexPass) - The Plex media server system (plexmediaserver-plexpass)
[20] qbittorrent - qBittorrent is the open source bittorrent client in C++/Qt that uses libtorrent-rasterbar. (qbittorrent)
[21] Quasselcore - Quassel Core is a daemon/headless IRC client, part of Quassel, that supports 24/7 connectivity. Quassel Client ca                                  n be attached to it to. (quasselcore)
[22] radarr - Radarr is a fork of Sonarr to work with movies in the style of Couchpotato. (radarr)
[23] Redmine - Redmine Bugtracker (redmine)
[24] Resilio Sync - Resilient, fast and scalable file sync software for enterprises and individuals. (rslsync)
[25] SickChill - Automatic Video Library Manager for TV Shows (sickchill)
[26] SickRage - Automatic Video Library Manager for TV Shows (sickrage)
[27] Sonarr - PVR for Usenet and BitTorrent users (sonarr)
[28] SubSonic - Open-source web-based media streamer and jukebox. (subsonic)
[29] Syncthing - Personal cloud sync (syncthing)
[30] Tarsnap - Online encrypted backup service (client) (tarsnap)
[31] Tautulli - A python based web application (formerly known as PlexPy) for monitoring, analytics and notifications for Plex Media                                   Server. (tautulli)
[32] Transmission - Fast and lightweight daemon BitTorrent client (transmission)
[33] unificontroller - The UniFi Software-Defined Networking (SDN) platform is an end-to-end system of network devices across differ                                  ent locations. (unificontroller)
[34] unificontroller-lts - The UniFi Software-Defined Networking (SDN) platform is an end-to-end system of network devices across di                                  fferent locations. (Long term support version) (unificontroller-lts)
[35] weechat - WeeChat (Wee Enhanced Environment for Chat) is a fast and light IRC client. (weechat)
[36] XMRig - XMRig is a high performance Monero (XMR) CPU miner written in C++. (xmrig)
[37] Zoneminder - ZoneMinder is a free, open source Closed-circuit television software application developed for Linux which support                                  s IP, USB and Analog cameras. (zoneminder)

Type the number of the desired plugin
Press [Enter] or type EXIT to quit: 18
Plugin: Plex
  Official Plugin: True
  Using RELEASE: 11.2-RELEASE
  Using Branch: 12.0-RELEASE
  Post-install Artifact: https://github.com/freenas/iocage-plugin-plexmediaserver.git
  These pkgs will be installed:
    - plexmediaserver
    - ffmpeg

Testing Host DNS response to pkg.cdn.trueos.org
Testing plexmediaserver_5c2d's SRV response to pkg.cdn.trueos.org
Testing plexmediaserver_5c2d's DNSSEC response to pkg.cdn.trueos.org

Installing plugin packages:
  - plexmediaserver...
  - ffmpeg...

Fetching artifact...

Branch 12.0-RELEASE does not exist at https://github.com/freenas/iocage-plugin-plexmediaserver.git!
Using "master" branch for plugin, this may not work with your RELEASE

Running post_install.sh
plexmediaserver_enable:  -> YES
plexmediaserver_support_path:  -> /
Starting plexmediaserver.

Admin Portal:
http://192.168.0.137:32400/web
(iocage-env) ➜  ~ iocage list
+-----+----------------------+-------+--------------+------+
| JID |         NAME         | STATE |   RELEASE    | IP4  |
+=====+======================+=======+==============+======+
| 12  | plexmediaserver_5c2d | up    | 11.2-RELEASE | DHCP |
+-----+----------------------+-------+--------------+------+
```

2.2a Install from plugin repository w/o selection, default jailname:
```
iocage fetch --plugin-name plexmediaserver dhcp=on vnet=on bpf=yes allow_raw_sockets=1
```
The jail is called **Plex** (note the proper case), exactly as on the manifest.  
:warning: Note that the old syntax always converted to lower case **plex**, so even though this works _more correct_ than before, I'm not sure that this is intentional so I wanted to point it out.

2.2b Install from plugin repository w/o selection, specify own jailname:
```
iocage fetch --plugin-name plexmediaserver -n myplexjail dhcp=on vnet=on bpf=yes allow_raw_sockets=1
```
Works as expected!
2.3a Install plugin from local manifest file, default jailname:
```
iocage fetch --plugin-name /zroot/iocage/.plugins/github_com_freenas_iocage-ix-plugins_git/plexmediaserver.json dhcp=on vnet=on bpf=yes allow_raw_sockets=1
```
Works as expected with absolute path!  
:warning: Same remark on the name **Plex** versus **plex** lower case.

2.3b Install plugin from local manifest file, specify own jailname:
```
iocage fetch --plugin-name /zroot/iocage/.plugins/github_com_freenas_iocage-ix-plugins_git/plexmediaserver.json -n myplexjail dhcp=on vnet=on bpf=yes allow_raw_sockets=1
```
Works as expected!

**Comment by sonicaj** [comment]
@jsegaert that is intentional. It is to ensure uniqueness of a jail name. We don't have another efficient way to make that fix so i introduced uuid's for now. But we are looking to refactor a lot of this code in the future, rest assured, this won't be the case then ;)
I believe all other cases are as desired, if you believe no ( apart from 2.1 ), please let me know. Thanks !
